### ISSUE TITLE
CI: reduce log dump size when errors are found

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1000]
Currently when an error is found in the logs in the [teardown script](https://github.com/kata-containers/tests/blob/master/.ci/teardown.sh#L232-L261), it does a fancy sed trick to pull out the error line and the following likely trail of messages - but, quite often that results in us having huge log files (Mb's - for instance in a local test from a real CI run, for two errors, I got 28715 lines in a 5.5Mb file...).
I suspect that means at the moment:
 - as we normally see the tail of the log in Jenkins, we only ever see a tail of log lines that mean very little out of context
 - few of us dare click the 'download the 48Mb full console log link`
 - and even if we do, we scroll back up over all the log stuff back to the real CI error

Let's reduce the log output to just the critical lines that the sed/searc/grep located. The full logs are attached as artifacts to the build run anyway, so if somebody does need to go look at the logs for real, then they can.

**Comment by grahamwhaley** [comment]
ooh, Issue **1000** :-) Do I get a prize?

**Comment by jodh-intel** [comment]
@grahamwhaley - here ya go.... :champagne: :wine_glass: :chocolate_bar: :cake: :ice_cream: :1st_place_medal: ! :smile:
