### ISSUE TITLE
Remove losetup EBUSY errors

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#101]
Taken from (successful build for #98):

- http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-tests-ubuntu-16-04-PR/59/console

```
Running command '/sbin/losetup [losetup -P /dev/loop0 /tmp/dd284653835]'
command failed error 'exit status 1'
[losetup -P /dev/loop0 /tmp/dd284653835]
Timeout: 60 seconds
Exit Code: 1
Stdout: 
Stderr: losetup: /tmp/dd284653835: failed to set up loop device: Device or resource busy
```

The code seems to be looping trying to find a free loop device. However, the errors are a bit scary ;)

I think we can change the test to do the equivalent of this:

```
# Find a free loop device and use it
sudo losetup -fP "$file"

# Get the full path to the loop device that was chosen
sudo losetup -j "$file" | cut -d: -f1 | sort -k1,1 | tail -1
```

**Comment by jodh-intel** [comment]
Do you guys have any thoughts on when you'll be able to look at this? Every time I look at the logs to find why a test failed, this catches me out as it is currently "expected behaviour" (but very confusing imho).

**Comment by chavafg** [comment]
sorry for the delay, I forgot about the issue, opened #145 to address this.
