### ISSUE TITLE
Soak test failing in Debian 9

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#1029]
The soak test is failing with Debian 9 http://jenkins.katacontainers.io/job/kata-containers-tests-debian-9-master/5/console. The main reason is that is looking for the process of `ksm-throttler` and Debian does not have it.
```
$ echo ' --pgrep ksm-throttler--'
$ pgrep -a ksm-throttler
echo 'ERROR: Got 1 errors, quitting'
```
```
$ systemctl start vc-throttler
Failed to start vc-throttler.service: Unit vc-throttler.service not found.
```
/cc @jodh-intel @grahamwhaley 

Should we skip the verification of this process in Debian?

**Comment by GabyCT** [comment]
/cc @chavafg @grahamwhaley @jodh-intel 
If we install and enable `kata-ksm-throttler` at the `soak-test` and then we start running the test, we got errors like 
```
Error response from daemon: Could not kill running container b035f4b8f4c6c9ec83e9ecaebaf2ed2a6e6b689fba5263df0d19ee34f6292b1b, cannot remove - Cannot kill container b035f4b8f4c6c9ec83e9ecaebaf2ed2a6e6b689fba5263df0d19ee34f6292b1b: unknown error after kill: /usr/local/bin/kata-runtime did not terminate sucessfully
```
See: http://jenkins.katacontainers.io/job/kata-containers-tests-debian-9-PR/3/console
I did reproduce this locally in a VM and I see the same error.

**Comment by GabyCT** [comment]
If we run the `soak-test` without installing or starting `kata-ksm-throttler`, the `soak-test` does not run properly as we got errors like
```
docker: Error response from daemon: OCI runtime start failed: rpc error: code = Unavailable desc = transport is closing: unknown.
```
From what I can see is that not all the containers are running properly (some of them stays in `created` mode)
```
Wrong number of proxys running (15 containers, 14 proxys) - stopping
Wrong number of shims running (15 != 14) - stopping
Wrong number of qemus running (15 != 14) - stopping
Wrong number of netmons running (15 != 14) - stopping
Wrong number of 'runtime list' containers running (15 != 14) - stopping
Wrong number of pods in /var/lib/vc/sbs (15 != 14) - stopping)
Showing system state:
 --Docker ps--
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
2ab15fdf1bb3        nginx:1.14          "nginx -g 'daemon of…"   54 seconds ago       Created             80/tcp              fervent_ritchie
f640eecda677        nginx:1.14          "nginx -g 'daemon of…"   About a minute ago   Up 55 seconds       80/tcp              stoic_noyce
3fca9e3408ab        nginx:1.14          "nginx -g 'daemon of…"   About a minute ago   Up About a minute   80/tcp              boring_albattani
cef1a130767b        nginx:1.14          "nginx -g 'daemon of…"   2 minutes ago        Up 2 minutes        80/tcp              lucid_feynman
```

**Comment by GabyCT** [comment]
Should I skipped the `soak-test` in Debian (in order to enable the jenkins job) and open an issue to see how to fixed the failures?

**Comment by grahamwhaley** [comment]
Heh, I would say that is maybe not so much a problem with the soak test, and more likely the uncovering of a potential real issue. The test did its job, and spotted a runtime anomaly... It probably needs debugging via the kata logs to work out why one of the containers failed to start - looks like that `rpc` error you noted..

**Comment by GabyCT** [comment]
@grahamwhaley looking the `soak test` in details, I do not know if we need to run it using `firecracker`. The main reason is that when we run a container using `firecracker` only `kata-shim` and `firecracker` are seen as a process (https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support). The `soak test` is looking for `kata-runtime`, `kata-proxy`, `qemu`, `ksm-throttler`, if pod information is left (/var/lib/vc/sbs) and `kata-netmon`, all of these are not available using `firecracker`.
/cc @chavafg

**Comment by GabyCT** [comment]
Closing this issue as the CI is running debian 10
