### ISSUE TITLE
Revert Debian-only test behaviour

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1077]
https://github.com/kata-containers/tests/pull/1073 added Debian-specific test behaviour. I'm not clear why, so please can we either revert this or document why Debian needs to be different.

**Comment by GabyCT** [comment]
@jodh-intel, the name of the package in Debian is `kata-ksm-throttler` and in the other distros the name is `ksm-throttler`.

**Comment by GabyCT** [comment]
Before this change, the test of `soak-test.sh` was looking for the process of `ksm-throttler` in distros like Ubuntu, CentOS, and Fedora. However, in Debian `ksm-throttler` does not exist so we need it to install the package and then look for that process but instead of `ksm-throttler` the name is `kata-ksm-throttler`.

**Comment by jodh-intel** [comment]
@GabyCT - I'm confused. afaik, the package is called `kata-ksm-throttler` on all distros (OBS confirms this). The binary and service names also use that name.

**Comment by GabyCT** [comment]
@jodh-intel , :S now I am confused, so what is `ksm-throttler`, why we are checking this (before this PR) in all the distros and in Debian does not exist?

**Comment by jodh-intel** [comment]
It looks like @grahamwhaley added that check on #414 so he might recall. It could just be a partial but unique-ish string to search for that process, or possibly a hangover from clearcontainers?

**Comment by grahamwhaley** [comment]
que? what? - in the original `soak_parallel_rm.sh` commit - actually in the `lib/common.bash` - I added a system state dump function - and that tries to get the state of the `kata-ksm-throttler` iirc.... I think there are a few things we need to figure out then...

- if that system dump routine fails to find something like the ksm-throttler installed or running - it should probably print an error, but not error out?
- can we verify that the ksm-throttler
  - is meant to be installed on all distros
  - is being installed on all distros for users?
  - the name of the binary and service on all the distros
  - is or is not being installed on the CIs (and probably **not** installed on the metrics CI **or** confirm the metrics CI locates and disables it (it has to to get stable non-KSM results))

/cc @chavafg

**Comment by jodh-intel** [comment]
@grahamwhaley - see https://github.com/kata-containers/tests/pull/414/files#diff-8c333de75ec3e0069ccf425dbff435d6R266

But maybe that was moved from somewhere else?

- Packages and service names are always `kata-ksm-throttler` (https://github.com/kata-containers/tests/issues/1077#issuecomment-456862504) - see https://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/ for example.
- Installing the runtime installs the throttler:
  - https://github.com/kata-containers/packaging/blob/master/obs-packaging/runtime/kata-runtime.dsc-template#L18
  - https://github.com/kata-containers/packaging/blob/master/obs-packaging/runtime/kata-runtime.dsc-template#L18
- The `kata-ksm-throttler` service is masked by default so that it is not enabled and not started:
  ```sh
  $ sudo systemctl status kata-ksm-throttler
  ● kata-ksm-throttler.service
     Loaded: masked (/dev/null; bad)
     Active: inactive (dead)
  ```
- We should be running tests without and with the throttler imho. But that could be handled by simply running the metrics CI twice: once with and once without the throttler?
- CI currently does not test with the throttler enabled: https://github.com/kata-containers/tests/issues/735.

**Comment by grahamwhaley** [comment]
> @grahamwhaley - see https://github.com/kata-containers/tests/pull/414/files#diff-8c333de75ec3e0069ccf425dbff435d6R266

Yep - as I said - this is just a 'show system state' function - it should not baulk if it cannot find one of the services - it should print out a 'not found' or similar and carry on - thus, adding the `ksm-throttler` in there is not an error, and should handle all distros with the throttler either running or not.
It probably needs a (tiny) patch.

> * We should be running tests without and with the throttler imho. But that could be handled by simply running the metrics CI twice: once with and once without the throttler?

QA CI I suspect yes, both with and without the throttler.
Metrics CI maybe not - the metrics CI controls KSM itself to ensure it can get figures both with and without KSM running - so it does not want the throttler in the mix...

> * CI currently does not test with the throttler enabled: #735.
Yeah, that feels like a bug we need to understand...

**Comment by GabyCT** [comment]
@jodh-intel this change is at https://github.com/kata-containers/tests/pull/1122

**Comment by GabyCT** [comment]
This is already closed
