### ISSUE TITLE
kata env extraction in test scripts does not understand static release binaries

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1112]
We have a hard wired `kata-runtime` in the test script libraries that tries to use `kata-env` to extract useful information:
https://github.com/kata-containers/tests/blob/master/lib/common.bash#L32

but, in the static tar balls the binaries are called `kata-qemu` and `kata-fc`. I suspect this is not the only place in the scripts we have that is hard wired. We probably need to be smarter about our checking of `${RUNTIME}`, and determining if we can make kata specific calls to it etc.

**Comment by grahamwhaley** [comment]
Ooh, ooh - at last I've figured out how to get docker to give us the paths to the runtimes I think!

```
 docker info --format "{{json .Runtimes}}"
{"kata-fc":{"path":"/opt/kata/bin/kata-fc"},"kata-qemu":{"path":"/opt/kata/bin/kata-qemu"},"runc":{"path":"docker-runc"}}
```

which unwound looks like:

```json
{
  "kata-fc":
    {"path":"/opt/kata/bin/kata-fc"},
  "kata-qemu":
    {"path":"/opt/kata/bin/kata-qemu"},
  "runc":
    {"path":"docker-runc"}
}
```

Yay, I think we can now be smarter with our runtime detection and info extraction @GabyCT ! :-)

**Comment by grahamwhaley** [comment]
We can also slam a `${RUNTIME}` in there, except when it has a `-` in its name - I'll have to go learn some json go syntax hacking..

```bash
$ export RUNTIME=runc
$ docker info --format "{{json .Runtimes.${RUNTIME}}}"
{"path":"docker-runc"}
$ export RUNTIME=kata-fc
$ docker info --format "{{json .Runtimes.${RUNTIME}}}"
Template parsing error: template: :1: bad character U+002D '-'
```

**Comment by GabyCT** [comment]
@grahamwhaley , yes getting the static binaries from the release is a special case as not only the runtime names are change but also you will have different names for the configuration.toml. For the CI, we are not running using a static binary from a release as we are building the kata components to test a specific PR.

**Comment by GabyCT** [comment]
@grahamwhaley, I do not know yet how are we going to apply this :S

**Comment by grahamwhaley** [comment]
:-) np @GabyCT - I have a branch nearly ready to PR that utilises this and some other changes to allow the metrics to run for all our variants of kata and also 'runc'. I need to wrap up and test a few more things, but hope to PR this in the next day or two.
