### ISSUE TITLE
metrics: fc: extract fc version information for json results

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1118]
The metrics code does not know how to get the firecracker version, so it does not currently get stored in the json data - add that ability
(it looks like you have to run `/opt/kata/bin/firecracker -V` as root to extract the info, as that binary is root owned and not other-executable, on my system at least.

**Comment by GabyCT** [comment]
@grahamwhaley is this issue fixed or is still happening?

**Comment by grahamwhaley** [comment]
afaik, I didn't add any fc specifics to the code. But, nobody else is complaining, so let's close for now.
