### ISSUE TITLE
Request: need to add two test case for supporting k8s probing function by using http/tcpsocket

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/tests#1127]
Currently, there is a test case to cover k8s liveness and readiness probing function by using "exec" here:
https://github.com/kata-containers/tests/blob/master/integration/kubernetes/k8s-liveness-probes.bats

Can we add two cases for covering k8s liveness and readiness probing function by using "http/tcpsocket" respectively?
Thanks a lot!

**Comment by zhiminghufighting** [comment]
@chavafg @jcvenegas

**Comment by GabyCT** [comment]
Closing this issue as this test has been added.
