### ISSUE TITLE
Add explicit hugepages test

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1128]
fwics, we don't currently have any tests that exercise `enable_hugepages=true` in `configuration.toml`.

This has come to light as we appear to have broken hugepage support - see https://github.com/kata-containers/runtime/issues/1210.

/cc @mcastelino.

**Comment by GabyCT** [comment]
@jodh-intel one question about this test, I see at the `configuration.toml` that if you enable it it allocates VM RAM, this can be tested using kubernetes and creating a pod and allocating memory greater than the value that we currently handle?

**Comment by jodh-intel** [comment]
I think we need @mcastelino to comment on what form this test should take.

**Comment by GabyCT** [comment]
@amshinde do you have an idea of how we can exercise this?

**Comment by GabyCT** [comment]
Closing this issue as a hugepages test with kubernetes has been submitted
