### ISSUE TITLE
metrics: report: 'in container' memory test needs to understand hotplug

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1145]
The 'in container' memory test (https://github.com/kata-containers/tests/blob/master/metrics/density/memory_usage_inside_container.sh), as used in the report generator (https://github.com/kata-containers/tests/blob/master/metrics/report/report_dockerfile/mem-in-cont.R) doesn't understand (work correctly) now that we have memory hotplug and pod memory handling in place.
(currently it presumes when you ask for '2G' of memory, that is what you should get inside the container, which no longer holds, as we add some overhead for the 'pod' or 'VM overhead').

It needs rework - probably mostly at the report generator side.

Whilst there, it doesn't understand `runc` either - so maybe we can make it use cgroup/constraint information to extract some useful information.

**Comment by GabyCT** [comment]
@grahamwhaley is this issue still open?

**Comment by grahamwhaley** [comment]
afaik, it's still a valid item - that is, it still does not work as intended as it still doesn't understand how memory is allocated/plugged inside the Kata VM.
But, I also don't think anybody is actively going to look at it, or is using/complaining about it. I'll close it for now, and at least somebody can re-open it if they run into the issue and find this item by a github search etc.

**Comment by HongfeiYin** [comment]
@GabyCT I encountered this issue these days. When create a container, the total memory is memory_used_by_VM + memory_used_by_container in current kata runtime. While in memory_usage_inside_container.sh, the _memrequest_ is only memory_used_by_container, the _memtotal_ is memory_used_by_VM + memory_used_by_container , so the results _memrequest_ - _memtotal_ is negatvie.
I think we include memory used by VM in _memrequest_.
Another thought, when use '_docker -m 2G_' to limit container memory usage, I think it is suppose to limit the total memory used by VM and the container, not the container alone in kata.
