### ISSUE TITLE
metrics: docker_mem_usage: sometimes shows syntax error

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1147]
Occasionally, when running the report generator with `RUNTIME=runc` at least, I see a shell math syntax error come out from what I think is the PSS measurements:

```bash
density/docker_memory_usage.sh: line 72: ((: 632
37738 > 0 : syntax error in expression (error token is "37738 > 0 ")
```

and, I don't know why. It definitely does not happen all the time. Needs some debug (`bash -x ...`). Probably a relatively simple thing to do with the output of `smem` at my best guess.

**Comment by jodh-intel** [comment]
It looks like this line:

- https://github.com/kata-containers/tests/blob/master/metrics/density/docker_memory_usage.sh#L67

... is returning multiple pids so you end up with two numbers (`632` and `37738`) rather than the expected one?

**Comment by grahamwhaley** [comment]
hmm, which would imply multiple shims active or similar... thx @jodh-intel - that should make it easier to track (and, probably add a sanity check maybe to ensure we are getting the number of children we expect)

**Comment by grahamwhaley** [comment]
This is now bugging me a bit. I can't reproduce it every time. I have a feeling it involves me running the `runc` tests after I've run either the `kata-fc` or `kata-qemu` tests - maybe something is dying and leaving an extra shim around is my current best theory. I will continue to try and reproduce, as it is hindering me doing some measure/compares :-)

**Comment by grahamwhaley** [comment]
ah. ah ah... how about....

```bash
 child_mem=$(sudo "$SMEM_BIN" -c "pid pss" | \
                                grep "$child_pid" | awk '{print $2}')
```

*if*, one PID is a subset of another PID (like you have valid PIDs 123 and 1234), then I reckon just now and again the grep | awk will give you a double answer....
