### ISSUE TITLE
CI: Sanity check fails after the CI run ends. 

### ISSUE THREAD

**Issue by nitkon** [kata-containers/tests#1157]
```
21:34:43 Ran 214 of 234 Specs in 1886.406 seconds
21:34:43 SUCCESS! -- 214 Passed | 0 Failed | 0 Pending | 20 Skipped PASS
21:34:43 
21:34:43 Ginkgo ran 1 suite in 40m6.048808247s
21:34:43 Test Suite Passed
21:34:43 bash sanity/check_sanity.sh
21:34:44 ERROR: 4 pods left and found at /var/lib/vc/sbs
21:34:44 make: *** [Makefile:51: docker] Error 1
21:34:44 Build step 'Execute shell' marked build as failure
21:34:44 Performing Post build task...
21:34:44 Match found for :.* : True
21:34:44 Logical operation result is TRUE
21:34:44 Running script  : #!/bin/bash
```
Context: https://github.com/kata-containers/proxy/pull/141#issuecomment-461093056

On the Jenkins Slave I could find:

```
jenkins@kata1:~$ sudo ls -lrt /var/lib/vc/sbs
total 16
drwxr-x--- 3 root root 4096 Feb  6 21:06 0863fbd4febc35edcdccb3923ba5e95479865765d60edbf44d98df482ff64733
drwxr-x--- 3 root root 4096 Feb  6 21:11 8a17f2c890d363ac98839389588dad7bb071bf720510b8a79ab382da81ef8d9c
drwxr-x--- 3 root root 4096 Feb  6 21:11 e3bc0a6de9e1db3739ef400540360313d4abc7bf797f871343f18538075b49a7
drwxr-x--- 3 root root 4096 Feb  6 21:25 1a862a76df0752154f26bf8cd97d047685885971adec70b91769d6d1b39f8ca0
``` 

From the CI Logs, some of these seem to be originating from tests:  cc @GabyCT 
```
docker run --cidfile /tmp/cid715320257/IWHOTNSj36wMY6ES2X9AMESZY30fN6 --runtime kata-runtime --name IWHOTNSj36wMY6ES2X9AMESZY30fN6 -dt busybox sh -c trap "exit 29" 29; echo TRAP_RUNNING; while :; do sleep 1; done
```

Side note: When I ran the test locally, I could not send a kill signal to it `kill -s` as it had already exited. However it did not leave any files in `/var/lib/vc/sbs` after exiting. 

I am opening this issue to document my findings and as I am not sure how to stop leaky pods in the CI runs.

**Comment by GabyCT** [comment]
@nitkon , did you try to run all the tests like the CI? because the `check sanity` test what it does is to check that no pods or processes are present but it is not going to remove them as they should be terminated before. I see that that issue is only happening at Power 8 infrastructure which I do not know why.

**Comment by GabyCT** [comment]
These are the tests that are leaving pod information (from the jenkins logs)
1. docker run --cidfile /tmp/cid715320257/JCfqP7Gf2Az3Vv1zyVEy7yc5TAhquX --runtime kata-runtime --name JCfqP7Gf2Az3Vv1zyVEy7yc5TAhquX -d -v /tmp/hello604339774:/volume_file busybox top
2. docker run --cidfile /tmp/cid715320257/IWHOTNSj36wMY6ES2X9AMESZY30fN6 --runtime kata-runtime --name IWHOTNSj36wMY6ES2X9AMESZY30fN6 -dt busybox sh -c trap "exit 29" 29; echo TRAP_RUNNING; while :; do sleep 1; done

However, I can not find two container ids that you listed so it seems like it is not a fresh VM?

**Comment by nitkon** [comment]
Hi @GabyCT, We are running bare metal and before every CI runs we run a cleanup [script](https://github.com/kata-containers/tests/blob/4b89bae8e25cbe6c6c0dffc76eb4734616d1c231/.ci/lib.sh#L238) which should have cleared `/var/lib/vc` so I suspect the container ids are due to the CI.

We can run the CI one more time to check if the issue is seen again.

**Comment by GabyCT** [comment]
@nitkon , I see from the logs this:
```
09:12:33 INFO: Remove installed kata packages
09:12:33 ERROR: packages not installed
```
which is from https://github.com/kata-containers/tests/blob/c714d29a98ac004835105cfdf222c9b06b2b6e8c/cmd/kata-manager/kata-manager.sh#L374, @jodh-intel is that expected?

**Comment by jodh-intel** [comment]
Hi @GabyCT - I'm confused. Which log file is that from? Kata manager will indeed display that error if you ask it to remove the kata packages, but they are not installed. I'm unclear what this has to do with the sanity check failing...?

**Comment by grahamwhaley** [comment]
@nitkon - OK, let's spin the CI once more (I'll go do an individual kick via jenkins) - but, just because it passes this time does not mean there is not a sporadic issue ;-)  Also, I'm not sure this is just a ppc issue ...

**Comment by nitkon** [comment]
@grahamwhaley : From the CI Logs debain container update test is failing due to 60sec timeout (sporadic)? rerun? 
```
16:01:59 Summarizing 1 Failure:
16:01:59 
16:01:59 [Fail] package manager update test check apt-get update [It] should not fail 
16:01:59 /home/jenkins/workspace/kata-containers-proxy-Power8-16.04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:41
16:01:59 
16:01:59 Ran 214 of 234 Specs in 1922.759 seconds
16:01:59 FAIL! -- 213 Passed | 1 Failed | 0 Pending | 20 Skipped --- FAIL: TestIntegration (2437.45s)
16:01:59 FAIL
```

@jodh-intel : @GabyCT was talking about Power CI logs from the test PR on proxy repo.

**Comment by grahamwhaley** [comment]
@nitkon the Debian one looks to me (without digging), like maybe a package repo access (apt etc.) timed out - which made the test fail (sadly, some things outside our control sometimes knobble us...). Yes, we can re-fire the Debian job. Err, which job/PR is that on - I had a quick look at https://github.com/kata-containers/proxy/pull/141 and didn't immediately see a Debian job??

**Comment by grahamwhaley** [comment]
ah, I see, not a Debian job per se - it was a fail on the Power8 job.... yes, let's re-trigger that.
Now, @nitkon - I believe I gate you re-trigger rights on that job. Hmm, maybe they don't apply at the Jenkins ui level - can you check for me - if you go and log into Jenkins and go to the power8 job, do you get a 'rebuild' action on the lhs menu? If not, maybe @chavafg and I can look at the github priv/security matrix and see if we can enable you for just the power jobs...

**Comment by nitkon** [comment]
@grahamwhaley : Also from the Jenkins slave I see the following: 
```
jenkins@kata1:~$ sudo ls -lrt /var/lib/vc/sbs
total 4
drwxr-x--- 3 root root 4096 Feb  8 15:45 5aa8c8e98cb7fd24355c09e247fba2b49d43ae4c0f418b5e1319fa440c76f87e
jenkins@kata1:~$ sudo ls -lrt /var/lib/vc/sbs/5aa8c8e98cb7fd24355c09e247fba2b49d43ae4c0f418b5e1319fa440c76f87e
total 60
-rw-r--r-- 1 root root 53270 Feb  8 15:45 config.json
drwxr-x--- 2 root root  4096 Feb  8 15:45 5aa8c8e98cb7fd24355c09e247fba2b49d43ae4c0f418b5e1319fa440c76f87e
jenkins@kata1:~$ sudo ls -lrt /var/lib/vc/sbs/5aa8c8e98cb7fd24355c09e247fba2b49d43ae4c0f418b5e1319fa440c76f87e/5aa8c8e98cb7fd24355c09e247fba2b49d43ae4c0f418b5e1319fa440c76f87e
total 28
-rw-r--r-- 1 root root 28004 Feb  8 15:45 config.json
```

But in the CI Logs I do not find anything when I grep for "5aa8c8e98cb7fd24355c09e247fba2b49d43ae4c0f418b5e1319fa440c76f87e"

PS: Yes I can retrigger the build. I ask you so that we are on the same page when we check the CI Logs. :-)

**Comment by grahamwhaley** [comment]
Right, np. Heh, when searching the logs you might have to do some deeper investigation... that UUID in the sbs dir is probably not the container or pod ID - but, if you go and look inside that directory/folder/file maybe you will find something like the `.json` file, and inside that it might reference the container or pod UUID, and then you can track it in the logs. Or, maybe you can look in the Jenkins attached fragments, which I think will container the full debug logs from `journald`, and thus they might give you say the qemu cmdline that does use that sbs UUID, and thus you can relate that back to which test was running. I know, slightly more complex and some digging, but, I think it is the only way (as we do not print sbs UUIDs in the stdout logs etc.)

**Comment by grahamwhaley** [comment]
/me thinks @nitkon will need a 🔍 here ;-)

**Comment by nitkon** [comment]
@grahamwhaley : I see the CI green. I shall re-nudge it again to take a second look at how the CI goes.

**Comment by GabyCT** [comment]
> Hi @GabyCT - I'm confused. Which log file is that from? Kata manager will indeed display that error if you ask it to remove the kata packages, but they are not installed. I'm unclear what this has to do with the sanity check failing...?

@jodh-intel , I saw it here http://jenkins.katacontainers.io/job/kata-containers-proxy-Power8-16.04-PR-initrd/40/consoleFull

**Comment by nitkon** [comment]
Thanks, Graham for the inputs!
After running the CI on Power8 multiple times today I realized that the `leaky pods` issue comes up in 3 out of 5 CI runs.
However, when I trace back to the test that caused it and run it individually on the Jenkins slave machine I do not see any leaks as such. So I can conclude that it's not caused by the same test over and over again. 
Now I am trying to understand what causes a Kata pod to leak and as it is been seen on other archs as well, what could be the possible generic reason & how to prevent it. 

cc @grahamwhaley @jodh-intel

**Comment by nitkon** [comment]
It seems that this [code](https://github.com/kata-containers/runtime/blob/d07297c197225fe9e32cc9e810cbf941c46d8fa2/virtcontainers/store/filesystem_backend.go#L189) is responsible to clear the contents of `/var/lib/vc/sbs` when we are exiting Kata Containers.

However if the files still stay on the host("leaky pods"), is it because `os.RemoveAll(f.path)` is failing to do so and not even reporting errors? @sameo have you by any chance seen this behaviour before? 
Or is it possible that this function `delete()` gets skipped due to some reason and files persist on the host system in `/var/lib/vc/sbs`.

**Comment by nitkon** [comment]
**Observation:**

After the CI runs, we see that 3 pods are left behind:

**From The jenkins Slave:**

```
jenkins@kata1:~$ sudo ls -lrt --full-time /var/lib/vc/sbs
total 12
drwxr-x--- 4 root root 4096 2019-02-14 00:18:30.920521050 +0530 6aaa6b2c258f2c54b92bde9a1698a43c53e7bcac92bfa2b09926e4a62634d993
drwxr-x--- 4 root root 4096 2019-02-14 00:19:51.841512358 +0530 0962601231fc2e1bf499d4d67c920e48460154903c2fea25dd43de111b447a44
drwxr-x--- 4 root root 4096 2019-02-14 00:33:01.243895993 +0530 f48da0a22768e8d89f8f0f125d2e37956521a31f1a82be55fb9ea3efdf610a40
```

When we check the journalctl logs we see the logs to create these files but no log messages to delete those files

```
jenkins@kata1:~$ sudo journalctl | grep "level=debug msg=\"Creating root directory\" backend=filesystem path=/var/lib/vc/sbs/6aaa6b2c258f2c54b92bde9a1698a43c53e7bcac92bfa2b09926e4a62634d993"
Feb 14 00:18:26 kata1 kata-runtime[63321]: time="2019-02-14T00:18:26.686038844+05:30" level=debug msg="Creating root directory" backend=filesystem path=/var/lib/vc/sbs/6aaa6b2c258f2c54b92bde9a1698a43c53e7bcac92bfa2b09926e4a62634d993 source=virtcontainers/store subsystem=store
Feb 14 00:18:30 kata1 kata-runtime[63321]: time="2019-02-14T00:18:30.847787164+05:30" level=debug msg="Creating root directory" backend=filesystem path=/var/lib/vc/sbs/6aaa6b2c258f2c54b92bde9a1698a43c53e7bcac92bfa2b09926e4a62634d993/6aaa6b2c258f2c54b92bde9a1698a43c53e7bcac92bfa2b09926e4a62634d993 source=virtcontainers/store subsystem=store
jenkins@kata1:~$ sudo journalctl | grep "level=debug msg=\"Deleting files\" backend=filesystem path=/var/lib/vc/sbs/6aaa6b2c258f2c54b92bde9a1698a43c53e7bcac92bfa2b09926e4a62634d993"

```

```
jenkins@kata1:~$ sudo journalctl | grep "level=debug msg=\"Creating root directory\" backend=filesystem path=/var/lib/vc/sbs/0962601231fc2e1bf499d4d67c920e48460154903c2fea25dd43de111b447a44"
Feb 14 00:19:47 kata1 kata-runtime[67176]: time="2019-02-14T00:19:47.626201124+05:30" level=debug msg="Creating root directory" backend=filesystem path=/var/lib/vc/sbs/0962601231fc2e1bf499d4d67c920e48460154903c2fea25dd43de111b447a44 source=virtcontainers/store subsystem=store
Feb 14 00:19:51 kata1 kata-runtime[67176]: time="2019-02-14T00:19:51.758670211+05:30" level=debug msg="Creating root directory" backend=filesystem path=/var/lib/vc/sbs/0962601231fc2e1bf499d4d67c920e48460154903c2fea25dd43de111b447a44/0962601231fc2e1bf499d4d67c920e48460154903c2fea25dd43de111b447a44 source=virtcontainers/store subsystem=store
jenkins@kata1:~$ sudo journalctl | grep "level=debug msg=\"Deleting files\" backend=filesystem path=/var/lib/vc/sbs/0962601231fc2e1bf499d4d67c920e48460154903c2fea25dd43de111b447a44"

```

```
jenkins@kata1:~$ sudo journalctl | grep "level=debug msg=\"Creating root directory\" backend=filesystem path=/var/lib/vc/sbs/f48da0a22768e8d89f8f0f125d2e37956521a31f1a82be55fb9ea3efdf610a40"
Feb 14 00:32:57 kata1 kata-runtime[25693]: time="2019-02-14T00:32:57.029486429+05:30" level=debug msg="Creating root directory" backend=filesystem path=/var/lib/vc/sbs/f48da0a22768e8d89f8f0f125d2e37956521a31f1a82be55fb9ea3efdf610a40 source=virtcontainers/store subsystem=store
Feb 14 00:33:01 kata1 kata-runtime[25693]: time="2019-02-14T00:33:01.165047454+05:30" level=debug msg="Creating root directory" backend=filesystem path=/var/lib/vc/sbs/f48da0a22768e8d89f8f0f125d2e37956521a31f1a82be55fb9ea3efdf610a40/f48da0a22768e8d89f8f0f125d2e37956521a31f1a82be55fb9ea3efdf610a40 source=virtcontainers/store subsystem=store
jenkins@kata1:~$ sudo journalctl | grep "level=debug msg=\"Deleting files\" backend=filesystem path=/var/lib/vc/sbs/f48da0a22768e8d89f8f0f125d2e37956521a31f1a82be55fb9ea3efdf610a40"

```


Now we need to figure out why the  `return os.RemoveAll(f.path)` does not get called.

**Comment by nitkon** [comment]
So when a `qmp` command fails do we not clean up the virtcontainers store files like the ones stored in `/var/lib/vc/sbs` ? @devimc @sameo Do we/Should we/ Should we not?
Any inputs appreciated ...

I have seen that if the CI sanity check fails due to X number of leaky pods in `/var/lib/vc/sbs` then there are X number of `exitting QMP loop, command cancelled` errors in the journalctl logs as well.

```
jenkins@kata1:~$ sudo journalctl | grep "exitting QMP loop, command cancelled"

Feb 14 21:32:34 kata1 kata-runtime[62963]: time="2019-02-14T21:32:34.344216632+05:30" level=error msg="Fail to execute qmp QUIT" arch=ppc64le command=kill container=09d6c1c7a04f6aaf9081d578d3cda585bdd6c2af38ec561dc0555ac89732680a error="exitting QMP loop, command cancelled" name=kata-runtime pid=62963 sandbox=09d6c1c7a04f6aaf9081d578d3cda585bdd6c2af38ec561dc0555ac89732680a source=virtcontainers subsystem=qemu

Feb 14 21:32:34 kata1 kata-runtime[62963]: time="2019-02-14T21:32:34.344396403+05:30" level=error msg="exitting QMP loop, command cancelled" arch=ppc64le command=kill container=09d6c1c7a04f6aaf9081d578d3cda585bdd6c2af38ec561dc0555ac89732680a name=kata-runtime pid=62963 sandbox=09d6c1c7a04f6aaf9081d578d3cda585bdd6c2af38ec561dc0555ac89732680a source=runtime

Feb 14 21:35:55 kata1 kata-runtime[73113]: time="2019-02-14T21:35:55.692228286+05:30" level=error msg="Failed to negoatiate QMP capabilities" arch=ppc64le command=kill container=75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728 error="exitting QMP loop, command cancelled" name=kata-runtime pid=73113 sandbox=75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728 source=virtcontainers subsystem=qemu

Feb 14 21:35:55 kata1 kata-runtime[73113]: time="2019-02-14T21:35:55.692478855+05:30" level=error msg="exitting QMP loop, command cancelled" arch=ppc64le command=kill container=75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728 name=kata-runtime pid=73113 sandbox=75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728 source=runtime

Feb 14 21:35:55 kata1 dockerd[26835]: time="2019-02-14T21:35:55+05:30" level=error msg="failed to kill init's children" error="OCI runtime killall failed: exitting QMP loop, command cancelled" id=75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728 namespace=moby path="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728" pid=72987

```

```
jenkins@kata1:~$ sudo ls -lrt --full-time /var/lib/vc/sbs
total 8
drwxr-x--- 4 root root 4096 2019-02-14 21:32:32.323815084 +0530 09d6c1c7a04f6aaf9081d578d3cda585bdd6c2af38ec561dc0555ac89732680a
drwxr-x--- 4 root root 4096 2019-02-14 21:35:55.026011228 +0530 75cc8a498e83c5ab92efcf81c34eecf77ab6350e4c2ab41ad5a43dd5092ce728

```

**Comment by nitkon** [comment]
`Leaky pods` are occurring due to failure in [VM clean up](https://github.com/kata-containers/runtime/blob/816ea42840af7e4391a555c4b6072bdd1a203c76/virtcontainers/qemu.go#L658) when `Stop Sandbox` fails in setting up qmp / running qemu capabilities/executing `kill` command/ sock files closed/not exists etc

Hints from journalctl logs

```
level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37/kata.sock : use of closed network connection" name=kata-proxy
```

```
level=error msg="Failed to negoatiate QMP capabilities" arch=ppc64le command=kill container=57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37 error="exitting QMP loop, command cancelled" name=kata-runtime source=virtcontainers subsystem=qemu
```

```
level=error msg="exitting QMP loop, command cancelled" arch=ppc64le command=kill container=57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37 name=kata-runtime pid=71566 sandbox=57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37 source=runtime
```

```
level=error msg="Failed to connect to QEMU instance" arch=ppc64le command=kill container=57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37 error="dial unix /run/vc/vm/57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37/qmp.sock: connect: no such file or directory"
```

```
level=error msg="dial unix /run/vc/vm/57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37/qmp.sock: connect: no such file or directory" arch=ppc64le command=kill container=57b832292e3eb1acf9e07ab79293a2dbd3963339779a8dfeecb1e78919b69e37
```

The last 2 logs `Failed to connect to QEMU instance` & `qmp.sock no such file..` are logged thrice since I guess its tries multiple times b4 the actual failure.

So when there is a failure to stop a sandbox due to failure at qmp/qemu level, cleaning up of VM files on the host system gets skipped. Probably, we need to clean them irrspective of `Stop Sandbox` failure/success?

@jodh-intel @grahamwhaley @bergwolf @devimc

**Comment by bergwolf** [comment]
@nitkon Yes, I agree with you. If there is no vm to stop (aka, failing to establish qmp connections) in `stopSandbox`, we should go ahead and clean up the rest of sandbox artifacts on the host. It can happen if e.g., qemu process crashed etc and we should clean things up properly in such cases.

**Comment by GabyCT** [comment]
Closing this issue as sanity checks run after each test
