### ISSUE TITLE
metrics: launch times, network bringup time?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1166]
Investigate if we can measure how long it took to 'bring up the network' in a boot. If so, consider adding that data to the [launch time tests](https://github.com/kata-containers/tests/blob/master/metrics/time/launch_times.sh) and then into the [metrics report generator](https://github.com/kata-containers/tests/tree/master/metrics/report)

**Comment by GabyCT** [comment]
@grahamwhaley is this still open?

**Comment by grahamwhaley** [comment]
I don't believe we ever implemented it. Nobody asking/looking though, so will close for now.
