### ISSUE TITLE
metrics: check for entropy before running tests

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1167]
If the system is short on entropy, the kernel inside the VM may stall/wait for enough entropy before carrying on. This can add a large artificial overhead/delay into tests such as the launch times test.
We could probably do something a little smart and have the tests wait on the host side until they know enough entropy is present to launch a container - and, have a sensible timeout so they die if entropy does not become available.

**Comment by GabyCT** [comment]
@grahamwhaley one question about this, so we need to check the entropy at the host with `cat /proc/sys/kernel/random/entropy_avail`  and if the value is less than `1000` do not launch the tests, is that correct?

**Comment by grahamwhaley** [comment]
Hi @GabyCT - approximately, yes I think so.
Presuming that is the correct path on the host.
You probably want to locate the code in the linux kernel that does the 'wait for enough entropy' and figure out what it thinks 'enough' is - I don't know if that is 1000 for instance. It might change depending on the number of vCPUs assigned to the container for instance (but, if we are doing cpu hotplug then that may always be 1 vCPU for kata ??).
