### ISSUE TITLE
containerd: run test-cri for containerd for other archs

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#1211]
Hi,

I'm currently working on the containerd testsuite for cri and I'd like to make that working for Kata. Up to now, I've been working to make the `test-cri` from https://github.com/containerd/cri working on s390x. The testsuite is working fine except for 3 tests cases. They fail because they use 2 images that are not multi-arch:
- gcr.io/cri-tools/hostnet-nginx:latest
- gcr.io/google_containers/nonewprivs:1.2
For the image gcr.io/cri-tools/hostnet-nginx:latest there is the image also for `s390x`, `ppc64le` and `arm64`. However in the test suite the image name is hardcoded (https://github.com/kubernetes-sigs/cri-tools/blob/c06001ff65b2de51c7bb8160ee902f46a3e0858d/pkg/validate/networking.go#L38) and it should use the image `gcr.io/cri-tools/hostnet-nginx-$(ARCH):latest`.
For the image `gcr.io/google_containers/nonewprivs:1.2` I was not able to find it for other architecture.
This could be interesting also for @nitkon  and @Pennyzct . Have you already tried for your arch?

A possible workaround would be to skip those tests.

Any suggestions?

**Comment by lubinsz** [comment]
@alicefr 
Hi,
For the image nonewprivs, it  supports different architectures: amd64/arm/arm64/ppc64le.
The source code is in kubernetes.
Please use following command to check it:
manifest-tool inspect gcr.io/kubernetes-e2e-test-images/nonewprivs:1.0

**Comment by alicefr** [comment]
@lubinsz ok thanks! There isn't the `s390x` so I need to build it from scratch. However, also the image `* gcr.io/google_containers/nonewprivs:1.2` is (see hardcoded https://github.com/kubernetes-sigs/cri-tools/blob/c06001ff65b2de51c7bb8160ee902f46a3e0858d/pkg/validate/security_context.go#L40) and to properly run the test suite you need to modify the cri-tools
