### ISSUE TITLE
ci: Install image name with out hour date.

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#1223]
Instead of time of image creation just use
date, to make easier image cache on CI

a >8 mes------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

Creating an issue for kata-containers/tests

Write a message for this issue. The first block of
text is the title and the rest is the description.

**Comment by GabyCT** [comment]
@jcvenegas is this something that we still need to implement? or can we close this issue?
