### ISSUE TITLE
metrics: Failing ci for stable-1.4

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/tests#1231]
The metrics CI fails quickly on every PR submitted to the stable-1.4 branch since it looks for an OBS path that doesn't exist anymore.
Here is the fix that has been merged for the regular CI: https://github.com/kata-containers/tests/pull/1230

/cc @grahamwhaley @chavafg

**Comment by GabyCT** [comment]
Closing this issue as we are not supporting this branch anymore
