### ISSUE TITLE
log-parser: is being handed all 0 length files an error?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1248]
I was looking to maybe clean up our noisy CI logs a bit to make finding the actual failure points easier. I spotted something that raises a couple of questions....

On http://jenkins.katacontainers.io/job/kata-containers-tests-fedora-PR/1164/console (which will rot), at the end of the log we have:

```
04:52:45 install kata-log-parser /tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/bin/kata-log-parser
04:52:45 make[1]: Leaving directory '/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/cmd/log-parser'
04:52:45 time="2019-02-26T04:52:45.970382648Z" level=debug msg="ignoring empty file \"/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/kata-ksm-throttler.log\"\n" commit=e3aa004ea2eea93b1f00a0d93d4c65a68dbb94be name=kata-log-parser pid=84262 source=log-parser version=0.0.1
04:52:45 time="2019-02-26T04:52:45.970476848Z" level=debug msg="ignoring empty file \"/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/kata-proxy.log\"\n" commit=e3aa004ea2eea93b1f00a0d93d4c65a68dbb94be name=kata-log-parser pid=84262 source=log-parser version=0.0.1
04:52:45 time="2019-02-26T04:52:45.970516948Z" level=debug msg="ignoring empty file \"/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/kata-runtime.log\"\n" commit=e3aa004ea2eea93b1f00a0d93d4c65a68dbb94be name=kata-log-parser pid=84262 source=log-parser version=0.0.1
04:52:45 time="2019-02-26T04:52:45.970548047Z" level=debug msg="ignoring empty file \"/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/kata-shim.log\"\n" commit=e3aa004ea2eea93b1f00a0d93d4c65a68dbb94be name=kata-log-parser pid=84262 source=log-parser version=0.0.1
04:52:45 time="2019-02-26T04:52:45.970575147Z" level=debug msg="ignoring empty file \"/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/kata-vc-throttler.log\"\n" commit=e3aa004ea2eea93b1f00a0d93d4c65a68dbb94be name=kata-log-parser pid=84262 source=log-parser version=0.0.1
04:52:45 ERROR: kata-log-parser: no log records to process
```

I tracked down the `ERROR` to https://github.com/kata-containers/tests/blob/master/cmd/log-parser/main.go#L129, which matches the lines in the log - all the log files it was passed were of 0 length, so it error'd out. My questions then:

1) Should it be an error? the log parser was handed files that existed, they just didn't have anything in them. Maybe we change the code to make it an error to be handed no files at all, but a warning to be handed only empty files?

2) and the, why did we get handed a bunch of empty files? I suspect what has happened is the CI error'd before we even got to install/run any of the kata components. So, maybe that is not really an issue.

**Comment by jodh-intel** [comment]
There are already two options in the log parser to handle various scenarios:

```
   --error-if-file-empty  error if any files are empty
   --error-if-no-records  error if all logfiles are empty
```

We run the log parser in the CI with `-error-if-no-records` because that should be an impossible scenario - we would never expect all the logs to collectively provide zero log entries.

**Comment by grahamwhaley** [comment]
right, I found those args just after I put this Issue up :-) So, what about the scenario above - we bombed out on 'no GOPATH' or similar, so very early on I think. Maybe we can write it off as the 'very rare case', and close this then?

**Comment by jodh-intel** [comment]
wfm. As I say, unless something goes catastrophically wrong in a CI run, we would always expect some log records (even with debug disabled). I guess you could tweak the teardown script to not run the log parser if it detects said catastrophic scenario but by showing the error we can know that none of the Kata components wrote to the journal. That info might be useful as it indicates the error occurred before the CI attempted to create any containers.

**Comment by grahamwhaley** [comment]
I'll close this then - as now we know what and why it happens, and we have a paper trail here for is somebody does see it and try to figure out why the error is coming out... thx
