### ISSUE TITLE
Run docker tests in parallel

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#1256]
Use ginkgo `-p` to parallelize as much as docker tests possible to reduce execution time.

**Comment by grahamwhaley** [comment]
This could be fun... I suspect we are trading speed against stability here... but, having said that, if running things in parallel shows up more problems, then maybe that is a good thing (even if those problems are then going to be much harder to debug)

**Comment by chavafg** [comment]
I've run them locally and seems pretty stable. Hopefully under the CI systems too.
