### ISSUE TITLE
Need test for vmcache function

### ISSUE THREAD

**Issue by teawater** [kata-containers/tests#1259]
https://github.com/kata-containers/runtime/pull/1166

**Comment by GabyCT** [comment]
@teawater any approach that we need to take to do this test? I see that we need to enable `enable_vm_cache` to true and then the `kata-runtime cache`, however, then we need to run a container and what is what we are going to see that is working?

**Comment by GabyCT** [comment]
anyupdate with this @teawater

**Comment by teawater** [comment]
> @teawater any approach that we need to take to do this test? I see that we need to enable `enable_vm_cache` to true and then the `kata-runtime cache`, however, then we need to run a container and what is what we are going to see that is working?

@GabyCT I think this test is similar to vm_templating_test.sh.  And more introduction of vmcahe is in https://github.com/kata-containers/documentation/blob/master/how-to/what-is-vm-cache-and-how-do-I-use-it.md
