### ISSUE TITLE
metrics makereport doesn't specify runtime

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1286]
See https://github.com/kata-containers/tests/issues/1266#issuecomment-471748429.

**Comment by grahamwhaley** [comment]
This one is not an issue - this is a host side action used to generate the metrics report using data gathered from the tests. It might be run on a machine that does not have kata, and is never run inside the CI (yet), so there may be no notion of `RUNTIME` where it is run.
Closing this one.
