### ISSUE TITLE
integration: cri-o: Skip 'ctr stats'

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/tests#1311]
With the recent fix of the bats from CRI-O https://github.com/kubernetes-sigs/cri-o/pull/2054, the test `ctr stats` does not work with Kata Containers. This is actually an expected behavior since we know stats don't work with Kata v1. Once we get to Kata v2, this will be solved, but for now, we have to skip this test.

**Comment by chavafg** [comment]
reopened as test name is `ctr stats output` and we need to have the complete name of the test in the skipped list.
