### ISSUE TITLE
Add codecov to jenkins script

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#132]
We need to update the CI script to allow us to move away from Travis.

See: https://github.com/kata-containers/tests/pull/103#issuecomment-369625173

Related: #104.

**Comment by chavafg** [comment]
@jodh-intel, The tokens will be stored in the `credentials.xml` and currently we are ignoring that file, so it won't be added to the CI repo.

In addition the credentials.xml entries are encrypted with a key that is located in the `secrets` directory, which we also do not add the CI repo.

I have added a token, which can be retrieved with `CODECOV_TOKEN` envar.
want to try it in your PR?
