### ISSUE TITLE
`.ci/install_go.sh` broken

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#1324]
`.ci/install_go.sh` is broken since it sources `.ci/lib.sh` and this requires `go` to already be installed.

**Comment by grahamwhaley** [comment]
@chavafg - Ah, is that because one of the `lib.sh` exports is `GOPATH`, which it tries to find, if not set, by invoking `go env` ? :-)

**Comment by chavafg** [comment]
@grahamwhaley yes, opened #1325 to fix it, although not sure if there could be a better way...
