### ISSUE TITLE
Use the HEAD or last version of software introduced too much issues

### ISSUE THREAD

**Issue by teawater** [kata-containers/tests#1349]
https://github.com/kata-containers/tests/issues/1345
https://github.com/kata-containers/tests/issues/1343
https://github.com/kata-containers/tests/issues/1344

The root causes of them use the HEAD or last version of some software that will output different test result or cannot work at all.
Because the HEAD of software means that maybe it can work but actually I am not sure.  It just for the developer of this software.
And the behavior of the last version of a software is always different from the previous version even if the Linux kernel.

So I think we should use a special version or commit of the software.  If someone wants to change the version, post a PR for it.

**Comment by jodh-intel** [comment]
Hi @teawater - I'm not quite clear what you are saying here. Do you mean we should be using something like the last/previous releases of `yq` and the linters to ensure they work on the `HEAD` of the Kata repos? If so, we could do that by adding details for those external tools to either the main versions database:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml

... or the additional tests one:

- https://github.com/kata-containers/tests/blob/master/versions.yaml

In fact, looking at the main one @ganeshmaharaj, it still mentions `gometalinter`:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml#L212..L218

Any chance you could raise a PR to zap that and maybe replace with details for the new linter?
