### ISSUE TITLE
dmesg docker integration test fails randomly on RHEL

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#1443]
While running the docker integration test to check the dmesg, we have the following error
```
04:21:38 [3] check dmesg logs errors
04:21:38 [3] /tmp/jenkins/workspace/kata-containers-tests-rhel-7-master/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:263
04:21:38 [3]   Run to check dmesg log errors
04:21:38 [3]   /tmp/jenkins/workspace/kata-containers-tests-rhel-7-master/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:280
04:21:38 [3]     should be empty [It]
04:21:38 [3]     /tmp/jenkins/workspace/kata-containers-tests-rhel-7-master/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:281
04:21:38 [3] 
04:21:38 [3]     Expected
04:21:38 [3]         <string>: [    2.157496] Spectre V2 : Spectre mitigation: kernel not compiled with retpoline; no mitigation available!
04:21:38 [3]     to be empty
```

**Comment by grahamwhaley** [comment]
@GabyCT - do we have an example of what the dmesg does look like? If not, maybe we can enhance the test to dump the dmesg that did not container the string(s) we were looking for to make it easier to debug in the future??

**Comment by GabyCT** [comment]
@grahamwhaley this error is only visible while running jenkins, I can not reproduce it locally, and I think the output says something like <string>: [    2.157496] Spectre V2 : Spectre mitigation: kernel not compiled with retpoline; no mitigation available!
