### ISSUE TITLE
ci: scripts: installer sudo missing PATH env

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1497]
In the .ci/lib.sh we have the function:

```bash
function build_and_install() {
	github_project="$1"
	make_target="$2"
	test_not_gopath_set="$3"

	build "${github_project}" "${make_target}"
	pushd "${GOPATH}/src/${github_project}"
	if [ "$test_not_gopath_set" = "true" ]; then
		info "Installing ${github_project} in No GO command or GOPATH not set mode"
		sudo -E KATA_RUNTIME="${KATA_RUNTIME}" make install
		[ $? -ne 0 ] && die "Fail to install ${github_project} in No GO command or GOPATH not set mode"
	fi
	info "Installing ${github_project}"
	sudo -E PATH="$PATH" KATA_RUNTIME="${KATA_RUNTIME}" make install
	popd
}
```

The `test_not_gopath_set` `sudo -E` is missing the `PATH=$PATH` entry, which for our CIs is not normally an issue, but on Zuul, where we can have two golangs installed and the default one is the too-old system one, it can cause a failure with 'golang version too old'.

Add the `PATH=$PATH` into the `sudo` line...

**Comment by GabyCT** [comment]
Closing this issue as it is already done https://github.com/kata-containers/tests/blob/4bebe311ed348f61455bea53b52afb376cc9eb0d/.ci/lib.sh#L104
