### ISSUE TITLE
ci: kernel: should force overwrite of symlinks

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#150]
At https://github.com/kata-containers/tests/blob/master/.ci/install_kata_kernel.sh#L91-L92
we do:
```
sudo ln -s /usr/share/clear-containers/vmlinux.container /usr/share/kata-containers/
sudo ln -s /usr/share/clear-containers/vmlinuz.container /usr/share/kata-containers/
```

which fails if the files are already there, as they can be on a bare-metal machine. We don't see an issue with the CI at present as it always runs on a clean installed cloud instance.

Change to `ln -sf` to force the over-write.

**Comment by grahamwhaley** [comment]
@chavafg @jodh-intel wdyt?

**Comment by chavafg** [comment]
Agree. Also, image creation has the same issue. 

https://github.com/kata-containers/tests/blob/master/.ci/install_kata_image.sh#L38

**Comment by grahamwhaley** [comment]
right, I'll PR those (as I think they are impacting my ci testing right now ;-) )

**Comment by jodh-intel** [comment]
I guess so. It worries me slightly that we have "stuff" left over on baremetal system as we can't be assured (easily) that we have a fully vanilla environment.

**Comment by grahamwhaley** [comment]
Well, 'left over' is more 'we have stuff installed from a previous run'.
The only ways to ensure we don't would be:
- completely re-install the system each time (for each build) - not very practical
- have a script that removes all evidence that any previous kata was installed or ever ran - that is potentially quite a bit of cleanup
- figure out how to run docker in some sort of sandbox (a bit like [dind](https://github.com/jpetazzo/dind) and --priv --net=host) - but, if we then nest our storage or nework on other underlying layers, that will affect our results.

We do need to find a solution mid-term, and I suspect it might be the 'write a script to clean up the environment' - but, we are not there yet...

**Comment by grahamwhaley** [comment]
@chavafg - the one in the image install does a force remove (`rm -f`) just before the `ln`, so I think that one is safe? (doing a forced `rm` is also an option in the kernel script - but `ln -sf` I guess saves an extra command). Maybe I'll change the crio one to remove the `rm` and add the `-f`...

What do you think about the one in https://github.com/kata-containers/tests/blob/master/.ci/install_crio.sh#L27 as well?

**Comment by grahamwhaley** [comment]
proposed code [here](https://github.com/grahamwhaley/kata-containers-tests/commit/eef5c33de8557ddfa9e4bca3d9b2fb9a6d8ed48e)
