### ISSUE TITLE
tests: document how to run subsets of tests

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1515]
We document how to run the CI tests
https://github.com/kata-containers/tests#run-the-tests
and the Makefile supports ginkgo `FOCUS` and `SKIP` arguments by using the ENV vars
https://github.com/kata-containers/tests/blob/master/Makefile#L60
https://onsi.github.io/ginkgo/#focused-specs

but, afaik, we don't document that link, or show an example of how to run a single or subset of tests.
This can be very useful/handy when trying to track down and debug a single test failure for instance.

**Comment by grahamwhaley** [comment]
@chavafg @devimc wdty

**Comment by chavafg** [comment]
agree, this is needed in the README

**Comment by devimc** [comment]
yes I agree, we should mention that :smiley:

**Comment by grahamwhaley** [comment]
I see 'we' never added this then? well, I need to use a `FOCUS` right now, so I guess whilst I figure it out again I may as well see if I can side it in the docs...

**Comment by jodh-intel** [comment]
Thanks @grahamwhaley - assigning...
