### ISSUE TITLE
openshift tests blocked

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#1522]
All Fedora jobs will be failing due to an openshift issue we have.
Kubernetes is removing all images from `docker.io` [1] and for some reason the `kubernetes/pause` image in the docker registry is being used by openshift. 
I am not sure if there is a way to configure openshift and get the image from another registry, but in the meantime you may see failures. 

btw, I have tried to look for this image at `gcr.io` and couldn't find it.

[1] https://github.com/kubernetes/k8s.io/issues/237

**Comment by spiffxp** [comment]
Should be using `k8s.gcr.io/pause` instead ref: https://github.com/kubernetes/kubernetes/pull/69631

**Comment by chavafg** [comment]
Thanks @spiffxp, 
I opened #1526 that changes our `cri-o` configuration to use `k8s.gcr.io/pause` image.
