### ISSUE TITLE
entropy/randomness: tests need improving

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1543]
Enabling the kernel `CONFIG_RANDOM_TRUST_CPU` option over in
https://github.com/kata-containers/packaging/pull/482
has highlighted that when we added the [entropy test](https://github.com/kata-containers/tests/pull/887) to the CI, maybe it is not quite testing what we thought, and maybe we really now need to test the availability of random data, not just the amount of entropy available?

Maybe we can do something along the lines of:

```bash
$ dd if=/dev/random of=/dev/null bs=4b count=1000000
```

and time it - and ensure it finishes in 'a reasonable time' ?
I have also wondered if we can run something like the openssl benchmarks, maybe they consume randomness?

**Comment by GabyCT** [comment]
@grahamwhaley, in order to get this `reasonable time` should we need to perform this operation several times and get the `maximum` and `minimum` in order to set a time limit? or do we have an idea of this `reasonable time`?

**Comment by GabyCT** [comment]
@grahamwhaley also what do you think if I add this test as part of PnP metrics?

**Comment by grahamwhaley** [comment]
@GabyCT I don't have specific numbers in mind - we are going to have to do a bit of experimentation and thought to figure out what feels 'good' and where that becomes 'bad'.
The only number I have right now is that 1000000 /dev/random reads inside a kata on my local NUC took ~35s iirc. I want to look around to see if maybe we can find an off the shelf test that eats randomness as well to see if that will be useful.
I think, yes, maybe we will have to do re-runs and average if we find there is variation in the results. But, I think we should maybe move away from measuring the entropy value, and shift towards the availability of randomness - as I think that is ultimately what a real container workload would care about.

**Comment by grahamwhaley** [comment]
oh, and wrt adding to the pnp metrics - let's get some numbers first and see how it looks - it is possible, but we need to see how good and stable the tests we come up with are first.
