### ISSUE TITLE
s390x: update list of tests passed

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#1548]
Hi,

the tests:
 - network
  - ramdisk
  - docker-compose
  - docker-stability
  - entropy
  - cri-containerd
are passing in our internal CI

**Comment by alicefr** [comment]
@grahamwhaley do you want that I update the table in https://github.com/kata-containers/ci/blob/master/README.md or do you prefer we wait for your CI to be ready for s390x?
/cc @tuan-hoang1

**Comment by grahamwhaley** [comment]
Hi @alicefr - it would be good to see the CI pass here on github/jenkins with the change in place - but, you can go ahead and update the table - with the caveat that you might have to undo it if it all falls apart :-)

We should start tying to push the s390 CI slave job onto more repos eh?

**Comment by alicefr** [comment]
hi @grahamwhaley yes I'd like. How do we do that?

**Comment by grahamwhaley** [comment]
@alicefr - (as we discussed on slack :-) ), if you get your internal signoff reasonably soon to access the kata Jenkins master, then we'll add you as admins and guide you through how to set up/clone jobs etc. If not, we can set them up for you.
/cc @chavafg
