### ISSUE TITLE
docker: docker images latest version available

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#1556]
Hi,

it happens sometime for s390x that the `latest` version of a docker image is not correctly update for a couple of days. We're monitoring that but it causes the `docker` testsuite failing because it's trying to pull an image that has not been correctly update. The error I get is:
```
no matching manifest for unknown in the manifest list entries
```
this issue breaks the kata CI. If we plan to run the kata CI for every project and ideally fo each PR, we should solve the issue.

A possible work-around is to refer to the architecture image. In this case, we avoid the broken reference of the multi-arch image. WDYT?

@Pennyzct @nitkon I'm wondering if you face a similar issue for ARM and Power.

**Comment by jodh-intel** [comment]
Hi @alicefr - ooi, is this one particular image (busybox maybe?) or a variety?

**Comment by alicefr** [comment]
@jodh-intel  no a variety. This morning was postgres, but it already happened with httpd, alpine and busybox too.

**Comment by jodh-intel** [comment]
That almost sounds like a bug with docker hub, not giving you the latest "known working" and tested version of an image for s390x in this case presumably?

**Comment by alicefr** [comment]
I guess more than a bug is a race condition. The s390x building server is not very fast and docker pushes the images when the amd64 image is ready. If you want an example, you can have a look at https://github.com/docker-library/httpd/issues/129 . The detailed explanation at https://github.com/docker-library/official-images/issues/3835

**Comment by jodh-intel** [comment]
Errr, so they update `:latest` *for all architectures* only when a single architectures build passes...? Ouch!

**Comment by alicefr** [comment]
yes, until Tianon finds a better solution

**Comment by alicefr** [comment]
I've a patch let me pull it and then you can have a look if it sounds reasonable for you

**Comment by jodh-intel** [comment]
Wow. Well, surely until they can make `:latest` change independently for each architecture, why can't they just make `:latest` change when the slowest build system completes? :)

**Comment by alicefr** [comment]
@jodh-intel my proposal https://github.com/kata-containers/tests/pull/1557

**Comment by jodh-intel** [comment]
Seems pretty harsh to potentially break all other arches though :(

**Comment by tianon** [comment]
I commented on https://github.com/docker-library/official-images/issues/3835 (https://github.com/docker-library/official-images/issues/3835#issuecomment-491108329, https://github.com/docker-library/official-images/pull/5897), but we are hoping to have this one solved upstream by the end of this week. :smile:

(Noticed the issue link while checking on my own comment this morning. :sweat_smile:)

**Comment by jodh-intel** [comment]
Great - thanks @tianon !
