### ISSUE TITLE
CI always failed on docker test case 

### ISSUE THREAD

**Issue by lifupan** [kata-containers/tests#1561]
------------------------------
[Serial Test] package manager update test check apt-get update and upgrade 
  should not fail
  /tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:55
Running command '/usr/bin/docker [docker run --cidfile /tmp/cid444864546/dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 --runtime kata-runtime -td --name dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 debian sh]'
[docker run --cidfile /tmp/cid444864546/dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 --runtime kata-runtime -td --name dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 debian sh]
Timeout: 120 seconds
Exit Code: 0
Stdout: d73253240b1ea21a792afed1b6943b9fc5c9b0959c092b70c94aa4257adcd86e

Stderr: 
Running command '/usr/bin/docker [docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]'
command failed error 'exit status 100'
[docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]
Timeout: 900 seconds
Exit Code: 100
Stdout: Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [487 kB]
Get:7 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages [209 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages [25.9 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [31.7 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Reading package lists...

Stderr: E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
W: Conflicting distribution: http://security-cdn.debian.org/debian-security stretch/updates InRelease (expected stretch/updates but got )
E: Unable to determine file size for fd 15 - fstat (2: No such file or directory)
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' provides only weak security information.
W: Conflicting distribution: http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease (expected stretch-updates but got )
E: Unable to determine file size for fd 4 - fstat (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

Running command '/usr/bin/docker [docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]'
command failed error 'exit status 100'
[docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]
Timeout: 900 seconds
Exit Code: 100
Stdout: Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:2 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:3 http://cdn-fastly.deb.debian.org/debian stretch Release
Get:4 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Hit:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:5 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:5 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:5 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:6 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:5 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:5 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:6 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Hit:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:8 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:8 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:9 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:9 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:8 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:9 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:8 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:9 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:8 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:9 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Reading package lists...

Stderr: E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' provides only weak security information.
W: Conflicting distribution: http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease (expected stretch-updates but got )
E: Unable to determine file size for fd 15 - fstat (2: No such file or directory)
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
W: Conflicting distribution: http://security-cdn.debian.org/debian-security stretch/updates InRelease (expected stretch/updates but got )
E: Unable to determine file size for fd 4 - fstat (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

Running command '/usr/bin/docker [docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]'
command failed error 'exit status 100'
[docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]
Timeout: 900 seconds
Exit Code: 100
Stdout: Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
Hit:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Reading package lists...

Stderr: E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
W: Conflicting distribution: http://security-cdn.debian.org/debian-security stretch/updates InRelease (expected stretch/updates but got )
E: Unable to determine file size for fd 15 - fstat (2: No such file or directory)
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' provides only weak security information.
W: Conflicting distribution: http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease (expected stretch-updates but got )
E: Unable to determine file size for fd 4 - fstat (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

Running command '/usr/bin/docker [docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]'
command failed error 'exit status 100'
[docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]
Timeout: 900 seconds
Exit Code: 100
Stdout: Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
Hit:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:6 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:6 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Reading package lists...

Stderr: E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
W: Conflicting distribution: http://security-cdn.debian.org/debian-security stretch/updates InRelease (expected stretch/updates but got )
E: Unable to determine file size for fd 15 - fstat (2: No such file or directory)
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' provides only weak security information.
W: Conflicting distribution: http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease (expected stretch-updates but got )
E: Unable to determine file size for fd 4 - fstat (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

Running command '/usr/bin/docker [docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]'
command failed error 'exit status 100'
[docker exec dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 apt-get -y update]
Timeout: 900 seconds
Exit Code: 100
Stdout: Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
Hit:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:5 http://security-cdn.debian.org/debian-security stretch/updates/main all Packages
Hit:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:7 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main all Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Reading package lists...

Stderr: E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
W: Conflicting distribution: http://security-cdn.debian.org/debian-security stretch/updates InRelease (expected stretch/updates but got )
E: Unable to determine file size for fd 15 - fstat (2: No such file or directory)
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' provides only weak security information.
W: Conflicting distribution: http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease (expected stretch-updates but got )
E: Unable to determine file size for fd 4 - fstat (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

Running command '/usr/bin/docker [docker ps -a -f name=dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 --format {{.Status}}]'
[docker ps -a -f name=dGRSSQEQEtjcRDevJ90ecXvb5mWHH1 --format {{.Status}}]
Timeout: 120 seconds
Exit Code: 0
Stdout: Up 29 seconds

Stderr: 

• Failure [31.669 seconds]
[Serial Test] package manager update test
/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:32
  check apt-get update and upgrade
  /tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:54
    should not fail [It]
    /tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:55

    Expected
        <int>: 100
    to be zero-valued

    /tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:61
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] [Serial Test] package manager update test check apt-get update and upgrade [It] should not fail 
/tmp/jenkins/workspace/kata-containers-tests-fedora-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:61

Ran 18 of 249 Specs in 121.056 seconds
FAIL! -- 17 Passed | 1 Failed | 0 Pending | 231 Skipped --- FAIL: TestIntegration (121.06s)
FAIL

Ginkgo ran 1 suite in 2m2.285104113s
Test Suite Failed
make: *** [Makefile:78: docker] Error 1
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash

**Comment by grahamwhaley** [comment]
Thanks @lifupan - can you tell from that if this is an upstream debian repo timeout issue, or maybe a kata issue?
The bit that makes me twitch I see is:

```
Stderr: E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
```

which smells very similar to the 9p `unlink-ref` bug. Hmm, did we maybe change our QEMU or some other item very recently - but, then I think the CI would have picked that up and blocked the merge?
/cc @chavafg

**Comment by devimc** [comment]
@lifupan you need a 9p patch in the kernel https://github.com/kata-containers/packaging/blob/master/kernel/patches/4.19.x/0003-NO-UPSTREAM-9P-always-use-cached-inode-to-fill-in-v9.patch

**Comment by jodh-intel** [comment]
This looks like a real Kata bug - I can recreate the problem trivially with `1.7.0~rc1`, but not with `1.6.3`:

```sh
$ docker run --runtime kata-runtime -ti debian apt update
Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease             
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]             
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Reading package lists... Done                                                                                                                                                                 
E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
E: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' provides only weak security information.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Unable to determine file size for fd 13 - fstat (2: No such file or directory)
E: The repository 'http://deb.debian.org/debian stretch-updates InRelease' provides only weak security information.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$ 
```

**Comment by jodh-intel** [comment]
@devimc is correct - the `1.7.0~rc`` kernel appears to be broken`:

- `1.6.3` + `1.7.0~rc1`'s `kata-containers.img`: OK
- `1.6.3` + `1.7.0~rc1`'s `kata-containers.img` + `1.7.0~rc1`'s `vmlinuz.container` : **FAIL**
- `1.6.3` + `1.7.0~rc1`'s `vmlinuz.container` : **FAIL**

**Comment by devimc** [comment]
@jodh-intel thanks for confirming it

**Comment by grahamwhaley** [comment]
It would be frustrating if we suddenly find that 9p patch is silently failing to apply as we updated the kernel version.... should fail the build if that were so.

**Comment by chavafg** [comment]
so it seems that we still have gaps when testing the kernel changes in the packaging repo :(

**Comment by chavafg** [comment]
another question is why it only fails on some of the jobs...
I see that sles, opensuse and centos jobs are passing

**Comment by chavafg** [comment]
closing this one as newest build includes all required patches. 
A PR[1] in packaging for newer builds has also been merged to avoid this situation. 

[1] https://github.com/kata-containers/packaging/pull/509
