### ISSUE TITLE
crio: create a temporal loop device if the lvm device doesn't exist

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#1575]
create a loop device if the default lvm device doesn't exist, that way, testing crio+devicemapper in system without an extra block device will be easier

**Comment by grahamwhaley** [comment]
In some ways, this sounds good to me (as normally I don't have a block based graph driver installed etc. ;-) ), but, I would like to make sure we don't obscure anything by doing this automatically - is there some CI env settings for instance that will trigger this?

**Comment by devimc** [comment]
@grahamwhaley good question,   @chavafg any thoughts?

**Comment by chavafg** [comment]
changing `LVM_DEVICE` value at the beginning of the script to something else should be enough
