### ISSUE TITLE
test: firecracker: docker: [Fail] Hot plug CPUs [BeforeEach] container with CPU period and quota should have 2 CPUs 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#1577]
```
08:37:41 • Failure in Spec Setup (BeforeEach) [0.001 seconds]
08:37:41 Hot plug CPUs
08:37:41 /tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR-firecracker/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:54
08:37:41   container with CPU period and quota [BeforeEach]
08:37:41   /tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR-firecracker/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
08:37:41     should have 2 CPUs
08:37:41     /tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR-firecracker/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
08:37:41 
08:37:41     Expected
08:37:41         <int>: 0
08:37:41     to be >
08:37:41         <int>: 0
08:37:41 
08:37:41     /tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR-firecracker/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:72
```

```
08:37:41 Summarizing 1 Failure:
08:37:41 
08:37:41 [Fail] Hot plug CPUs [BeforeEach] container with CPU period and quota should have 2 CPUs 
08:37:41 /tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR-firecracker/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:72
08:37:41 
08:37:41 Ran 20 of 249 Specs in 324.386 seconds
08:37:41 FAIL! -- 19 Passed | 1 Failed | 0 Pending | 229 Skipped --- FAIL: TestIntegration (324.39s)
```

**Comment by grahamwhaley** [comment]
Hmm, might be something we can improve with that test as well - right now to me that reads as `0 != 1 ... fail` ??? I guess it is not logging one of the values (either the one it captured, or the one it compared against?)

**Comment by grahamwhaley** [comment]
(edited - `0 != 0`)

**Comment by jcvenegas** [comment]
@grahamwhaley yep not really clear the log. 

The complete logs in http://jenkins.katacontainers.io/job/kata-containers-tests-centos-7-4-PR-firecracker/565/console

**Comment by grahamwhaley** [comment]
Ah, I see - it is actually saying (after reading the [code](https://github.com/kata-containers/tests/blob/master/integration/docker/cpu_test.go#L72)...

`0 should be larger than 0` - `0 > 0` - the `>` is sort of buried amongst the rest of the `<>`'s in the ginkgo output though! ;-)

**Comment by jcvenegas** [comment]
this error was found in https://github.com/kata-containers/tests/pull/1571/files the change does not look very clear but taking with @GabyCT  this test should not run in fc so it is result of the refactor for the PR.

**Comment by GabyCT** [comment]
@jcvenegas this is the list of tests that do not run on FC
https://github.com/kata-containers/tests/blob/master/.ci/hypervisors/firecracker/configuration_firecracker.yaml
