### ISSUE TITLE
Error while running static checks on RHEL

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#1591]
We have the following error in RHEL while running the static checks script
```
12:41:38 INFO: Checking vendored code is pristine
12:41:38 INFO: Checking vendoring metadata
12:42:50 Solving failure: 
12:42:50 	(1) failed to list versions for https://go.googlesource.com/crypto: fatal: unable to access 'https://go.googlesource.com/crypto/': The requested URL returned error: 502
12:42:50 : exit status 128
```
This is making to the RHEL CI to fail.

http://jenkins.katacontainers.io/job/kata-containers-tests-rhel-7-PR/110/console

/cc @jodh-intel

**Comment by GabyCT** [comment]
This a random fail

**Comment by jodh-intel** [comment]
Yep - sounds like a transitory network issue.

**Comment by GabyCT** [comment]
Closing this issue as is not happening anymore
