### ISSUE TITLE
Save trace spans for CI artifact collector

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1593]
The [tracing test](https://github.com/kata-containers/tests/blob/master/tracing/tracing-test.sh) performs lots of checks on the collected Jaeger trace spans. However, if the test fails in the CI, it is almost impossible to debug.

Save the trace spans to allow the CI to attach them to a Jenkins job as artifacts.

**Comment by jodh-intel** [comment]
Hi @chavafg - any thoughts on where I should write the trace spans to? Maybe one of...?:

```
/tmp/traces/${jaeger_service}.log
/var/log/kata-tests/jaeger-tracing/${jaeger_service}.log
```

Once we've decided, I'll write the logs to that location and then update `.ci/teardown.sh` to save them.

(I could update `.ci/teardown.sh` to extract the trace spans from Jaeger directly but I'd rather not do that as we'd have duplicate logic in the teardown script and the tracing test).

**Comment by chavafg** [comment]
I think we can use `/var/log/kata-tests/...`. Maybe later we will need to save other logs and we can use that same location.

**Comment by jodh-intel** [comment]
Thanks @chavafg - #1594 raised.
