### ISSUE TITLE
Add CI for testing virtio-block

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#1603]
Now that we know people are interested in using virtio-block, we should have CI for testing this out.

**Comment by amshinde** [comment]
cc @egernst 
cc @chavafg @GabyCT

**Comment by chavafg** [comment]
We had a PR opened time ago that ended closed. I remember that the issue was that we needed to use qemu 2.7, should this work now with the current qemu version that we use?

**Comment by amshinde** [comment]
@chavafg Lets reopen that PR and see if we run into any failures.

**Comment by GabyCT** [comment]
@amshinde should this be enabled in all the distributions or should we enable it in a particular one and the other run with virtio-scsi?

**Comment by amshinde** [comment]
@GabyCT Lets enable this on a single distribution first.
