### ISSUE TITLE
Use qemu 2.11 vanilla for CI 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#163]
We have been using qemu-lite from CC project to run Kata Containers. We need to use qemu 2.11.

**Comment by jodh-intel** [comment]
List of files to update potentially when we switch:

```
cd $GOPATH/src/github.com/kata-containers
grep -lr qemu-lite
tests/.ci/setup_env_fedora.sh
tests/.ci/lib.sh
tests/.ci/setup_env_ubuntu.sh
tests/.ci/install_qemu_lite.sh
documentation/Developer-Guide.md
runtime/data/kata-collect-data.sh
runtime/cli/config/configuration.toml
runtime/arch/amd64-options.mk
runtime/kata-runtime
runtime/virtcontainers/documentation/api/1.0/api.md
runtime/virtcontainers/api_test.go
runtime/virtcontainers/qemu_amd64.go
runtime/virtcontainers/qemu_arch_base_test.go
runtime/virtcontainers/example_pod_run_test.go

```

**Comment by bergwolf** [comment]
Is the intention to drop qemu-lite support?

**Comment by sboeuf** [comment]
For now, yes. We want a common basis for Kata with Qemu, instead of relying on a custom version that some of our users might not be able to use.

**Comment by bergwolf** [comment]
+1

**Comment by devimc** [comment]
let's move kata to QEMU 2.11, this version introduces two new features to reduce memory footprint
* disable-tcg
* memory flatview optimization

also, last month 2.11 was tagged as stable

**Comment by sboeuf** [comment]
@devimc Do we need to enable those features from the code (the command line invocation) ?

**Comment by devimc** [comment]
@sboeuf nop, `flatview` was a redesign in the memory management and  `disable-tcg` is a configure option (./configure --disable-tcg)

**Comment by sboeuf** [comment]
@devimc Ok cool. Have you run the full testing to make sure no regression were introduced between 2.10 and 2.11 ?

**Comment by devimc** [comment]
@sboeuf yes, all seems good

**Comment by sboeuf** [comment]
@devimc sounds good then. I am all for 2.11 if it's stable and better than 2.10.
If @mcastelino @egernst @grahamwhaley agree, I think @chavafg can go ahead and move to 2.11 instead of 2.10.

**Comment by chavafg** [comment]
so if there are no regressions, I agree to move to qemu 2.11

**Comment by grahamwhaley** [comment]
Given all QA and metrics checks are no worse than 2.10 (and that we have not actually moved to 2.10 yet...), then yes, this sounds like the right thing to do.

**Comment by egernst** [comment]
agreed!  Thanks guys.

**Comment by sboeuf** [comment]
I think that you're good to move to 2.11 @chavafg  :smiley:
