### ISSUE TITLE
Explain $CI behaviour if *not* running under a CI

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1649]
We need to update the following section to explain how tests should detect they are **not** running under a CI by stating what value `$CI` should be set to (if it should even be set...):

- https://github.com/kata-containers/tests/#detecting-a-ci-system

It's clear that if `$CI == true` we're running under a CI. But what is not clear atm is what `$CI` should be set to if we are not running under a CI. There seem to be three possibilities:

- `$CI` not set
- `$CI` set to empty string (`""`)
- `$CI` set to `false`

We do need to document two things:

- The expected value of `$CI`.
- How to test for "not running under a CI".

For the second bullet, should it be (which assumes `$CI` will be unset if not running under a CI):

```sh
if [ -z "$CI" ]; then
    echo "Not running under CI"
fi
```

Or should it be the following (which assumes will always be set to `CI=false` if not running under a CI):

```sh
if "$CI"; then
    echo "Not running under CI"
fi
```

I think the best option is for us to assume that the `CI` variable is **not** set if not running under a CI since that provides the least surprising and safest behaviour.

**Comment by jodh-intel** [comment]
Whatever we decide, we need to apply the logic consistently across all repos to avoid any surprises.

**Comment by chavafg** [comment]
I've always taken `$CI = true` as the only valid comparison to know if we are running under the CI and considered all other options for **not** running under a CI, but I see that some of our scripts behave differently. 
I would say that comparing to `true` will be the safest and will let us have a more standardized way to compare. If we accept different options, we might end having different comparisons in the scripts as we do now.

**Comment by jodh-intel** [comment]
@chavafg - that's definitely the best solution! And https://github.com/kata-containers/tests#detecting-a-ci-system is already saying that too :)

In which case, if you're happy let's close this issue and @ganeshmaharaj - could you update https://github.com/kata-containers/packaging/pull/538 to reflect this?
