### ISSUE TITLE
Error while running static checks

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#1652]
While running the `static checks`, the CI is failing with the following error
```
5:42:56 INFO: Checking local branch for changed documents only
15:42:56 INFO: No documentation to check
15:42:56 INFO: Skipping check_files: see https://github.com/kata-containers/tests/issues/469
15:42:56 INFO: Checking vendored code is pristine
15:42:56 INFO: Checking vendoring metadata
15:43:02 The following errors occurred while deducing packages:
15:43:02   * "code.cloudfoundry.org/bytefmt": unable to deduce repository and source type for "code.cloudfoundry.org/bytefmt": unable to read metadata: go-import metadata not found
15:43:02 
15:43:02 validateParams: could not deduce external imports' project roots
```

This is the error that we are getting in all the PRs and for all the OS distributions
http://jenkins.katacontainers.io/job/kata-containers-tests-fedora-PR/1794/console

/cc @jodh-intel

**Comment by GabyCT** [comment]
@jodh-intel the issue is also happening on travis
````
The following errors occurred while deducing packages:
  * "code.cloudfoundry.org/bytefmt": unable to deduce repository and source type for "code.cloudfoundry.org/bytefmt": unable to read metadata: go-import metadata not found
validateParams: could not deduce external imports' project roots
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 1.
```

**Comment by jodh-intel** [comment]
Hi @GabyCT - it looks like this might be caused by a transitory network error. The test runs the following:

```sh
dep ensure -no-vendor -dry-run
```

I've just run this locally a few times on an up-to-date `tests` checkout and it works fine:

```sh
$ go get -v -u github.com/golang/dep/cmd/dep
$ dep ensure -no-vendor -dry-run
Would have written Gopkg.lock.
Would have updated the following projects in the vendor directory:

(0/25) Would have written github.com/beorn7/perks@v1.0.0: new project
(0/25) Would have written github.com/json-iterator/go@v1.1.6: new project
(0/25) Would have written github.com/slok/kubewebhook@v0.2.0: new project
(0/25) Would have written github.com/google/gofuzz@v1.0.0: new project
(0/25) Would have written k8s.io/klog@v0.3.2: new project
(0/25) Would have written github.com/shurcooL/sanitized_anchor_name@v1.0.0: new project
(0/25) Would have written github.com/gogo/protobuf@v1.2.1: new project
(0/25) Would have written github.com/golang/protobuf@v1.3.1: new project
(0/25) Would have written k8s.io/api@master: new project
(0/25) Would have written k8s.io/apimachinery@master: new project
(0/25) Would have written github.com/matttproud/golang_protobuf_extensions@v1.0.1: new project
(0/25) Would have written gopkg.in/russross/blackfriday.v2@v2.0.1: new project
(0/25) Would have written sigs.k8s.io/yaml@v1.1.0: new project
(0/25) Would have written github.com/opentracing/opentracing-go@v1.1.0: new project
(0/25) Would have written github.com/appscode/jsonpatch@1.0.0: new project
(0/25) Would have written github.com/prometheus/client_model@master: new project
(0/25) Would have written github.com/onsi/ginkgo@v1.3.1: hash of vendored tree didn't match digest in Gopkg.lock
(0/25) Would have written github.com/prometheus/client_golang@v0.9.3: new project
(0/25) Would have written github.com/modern-go/concurrent@1.0.3: new project
(0/25) Would have written github.com/prometheus/common@v0.4.1: new project
(0/25) Would have written gopkg.in/inf.v0@v0.9.1: new project
(0/25) Would have written golang.org/x/text@v0.3.2: new project
(0/25) Would have written github.com/modern-go/reflect2@1.0.1: new project
(0/25) Would have written github.com/prometheus/procfs@master: new project
(0/25) Would have written golang.org/x/net@master: new project
$ echo $?
0
```

**Comment by GabyCT** [comment]
@jodh-intel , yes it looks like the other one was a network issue, now we have a new one (which is happening now)
```
09:20:33 (0/25) Would have written sigs.k8s.io/yaml@v1.1.0: new project
09:20:33 INFO: Cannot check labels as yamllint not available
09:20:33 rm: cannot remove '/tmp/tmp.P8WvhgGlvB': Is a directory
```

**Comment by GabyCT** [comment]
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/694/console

**Comment by jodh-intel** [comment]
@chavafg - I think this might be because we're now (?) running the static checks before running `setup_env_*.sh`?

**Comment by chavafg** [comment]
yeah, I think so... should that `INFO:` be an  `ERROR:` instead?

**Comment by jodh-intel** [comment]
It probably should be tbh. I made it a warning to handle SLES, but we could special case that distro I guess:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L294

**Comment by chavafg** [comment]
also, I think that probably we want to manage that dependency in the `static-checks.sh` script in case it is not installed, so we don't need to run the whole `setup_env*.sh` before running static checks

**Comment by jodh-intel** [comment]
@chavafg - it's tricky to know how best to handle this. We either add all the `apt`/`dnf`/`yum`/`zypper` calls into the static check script to install this package or we just install `pip` if not already installed and then `pip install --user yamllint` or something. I did wonder about `go get`-ing a yaml lint tool but cannot find a golang one.

Alternatively, how about we change the `setup.sh` script so that the static-check script can call something like `setup.sh minimal`. That will call the appropriate `setup_env_${distro}.sh` script to install the minimal set of package (`yamllint` ;). That way, we keep all the distro-specific packaging logic out of the static checks script.

I'll be EOD very soon so can tal on Monday but you might want to pick this up as it's blocking the CIs?

**Comment by chavafg** [comment]
I'll try to fix it, I think the `pip` options sounds really good as it wont required too many modifications. I'll try it locally and if everything works right, open a PR

**Comment by jodh-intel** [comment]
Thanks @chavafg!

**Comment by chavafg** [comment]
Actually the CI fails because it cannot delete a  temporary directory:
```
09:20:33 rm: cannot remove '/tmp/tmp.P8WvhgGlvB': Is a directory
```
I've opened #1659 to work on the `yamllint` issue and opened #1660 to this issue.
