### ISSUE TITLE
CI: k8s shared volume test might be optimisable

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1680]
Staring at the CI logs, looking for potential time improvements, I noticed that the [k8s shared volume test](https://github.com/kata-containers/tests/blob/master/integration/kubernetes/k8s-shared-volume.bats) I think is taking some time (~2m33s or so?)

From timestamped logs of a nemu agent CI run](http://jenkins.katacontainers.io/job/kata-containers-agent-ubuntu-nemu/98/consoleFull):

```
01:50:38.197 ok 1 Containers with shared volume
01:51:01.584 ok 2 initContainer with shared volume
01:51:01.622 1..1
01:53:34.115 ok 1 Expose IP Address
```

I think that time gap is coming from the test, and I suspect it is as the test is based on these two containers:

```
first_container_name="nginx-container"
second_container_name="debian-container"
```

both of those are quite large and will be pulled seperately. I wonder if we can re-write the test to maybe use two busybox or alpine container/pods and just cat/echo across the volume between them? This might save us a lot of time and space.

@GabyCT @amshinde - can you think of any reason we should not switch to a simpler test? I know it will not be quite as 'real world' as linking nginx with a full distro, but, for our testing, will it matter?

I'd be interested at least if you can test/time a run (on a machine where all the images are not present), and see if that test is consuming minutes.

thx!

**Comment by amshinde** [comment]
@grahamwhaley I took a look at the test code, we can move to a leaner image if the nginx image takes a long time to get downloaded. There is no reason for us to use nginx here in particular.

**Comment by chavafg** [comment]
@grahamwhaley isn't the `Expose IP Address` test the one that is taking more than 2 min?

**Comment by grahamwhaley** [comment]
@chavafg - ah, you might be right. I just checked the logs (as, my current script seems to have a bit of a +/-1 error sometimes, I suspect maybe to do with blank log lines...).
Let me try that `Expose IP Address` test locally and see how it looks here - probably another candidate to scrutinise :-)
