### ISSUE TITLE
kata-manager.sh fails with gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by davidthewatson** [kata-containers/tests#1691]
# Description of problem

1. Install ubuntu 19.04 server
1. sudo apt update
1. sudo apt upgrade
1. sudo reboot
1. bash -c "$(curl -fsSL https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh) install-docker-system"
[
# Expected result

Script completes without error.

# Actual result

Cloning into '/root/go/src/github.com/kata-containers/documentation'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1487 (delta 1), reused 7 (delta 0), pack-reused 1471
Receiving objects: 100% (1487/1487), 1.83 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (867/867), done.
Cloning into '/root/go/src/github.com/kata-containers/tests'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 10169 (delta 0), reused 0 (delta 0), pack-reused 10165
Receiving objects: 100% (10169/10169), 6.67 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (5930/5930), done.
gpg: no valid OpenPGP data found.

**Comment by marcov** [comment]
@davidthewatson  thanks for reporting this.

That happens because we don't provide builds for Ubuntu 19.04 yet. But, why not add them. WDYT @jcvenegas?

It may also be worth adding to kata-manager a more self-explaining error message.

**Comment by davidthewatson** [comment]
For my use case, I can back down to whatever version is supported. It might make sense to just hyperlink the version compatibility doc in the error or the like. Thanks!

**Comment by marcov** [comment]
@davidthewatson I agree with that, let's leave this issue open to keep track of this enhancement.

**Comment by jodh-intel** [comment]
The original PR had problems so it's being reverted on https://github.com/kata-containers/tests/pull/1882. Re-opening this issue as a result.

**Comment by GabyCT** [comment]
Closing this issue as it is already merged

**Comment by gvancuts** [comment]
I am hitting this issue on Ubuntu 20.04. Would this be the same root-cause as mentionned above (i.e. no builds yet for Ubuntu 20.04)? If true, should this be tracked in https://github.com/kata-containers/ci/issues/277?

**Comment by jcvenegas** [comment]
I think it is a good place to track. As alternative you can also install Kata in without host version limitation using snap, https://snapcraft.io/kata-containers

**Comment by gvancuts** [comment]
> I think it is a good place to track. As alternative you can also install Kata in without host version limitation using snap, https://snapcraft.io/kata-containers

This is what I tried but the installation is not working correctly for me. My set-up is probably not the most common though as I use [ACRN](https://projectacrn.org/). Aside from a number of paths that are not correct (which I have fixed manually) is the fact that the snap provides a `kata-containers-initrd.img` but not a `kata-containers.img` file... I know I can create one manually but I have not gotten around to doing it just yet :-)
