### ISSUE TITLE
ci: integration: k8s: expose IP test needs improvements and fixes

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1692]
# Description of problem

the [k8s expose IP test](https://github.com/kata-containers/tests/blob/master/integration/kubernetes/k8s-expose-ip.bats) has some improvements and fixes it could do with:

- It currently uses the google `node-hello` image. first, that is huge (650Mb+), and is also marked as (afaict) deprecated in the upstream. Replace that with the [hello-app](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/hello-app/main.go), which is more like 10Mb...  The only change is the string we look for will move to 'hello, World!'
- It current [tests against the pod IPs](https://github.com/kata-containers/tests/blob/master/integration/kubernetes/k8s-expose-ip.bats#L54-L59), whereas we probably actually want to test against the service (loadbalancer) IP and the localhost exposed IP to check IP exposure is really happening.
- there are a bunch of extraneous commands executed through the test that may not be necessary as part of the test, and were inherited from the [k8s example page](https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/) that afaict the test was derived from.

Overall goals then are to:
- reduce the time and footprint to execute the test
- correct/improve the test whilst we are there.

**Comment by egernst** [comment]
Is this a bug or enhancement?

**Comment by grahamwhaley** [comment]
well, indeed. Given I think the test was actually testing the wrong thing, probably a `bug` ?
