### ISSUE TITLE
frequent failing test: nginx.bats

### ISSUE THREAD

**Issue by egernst** [kata-containers/tests#1697]
# Description of problem

This test frequently fails:
https://github.com/kata-containers/tests/blob/master/integration/kubernetes/nginx.bats

Example: 
http://jenkins.katacontainers.io/job/kata-containers-runtime-vsocks-PR/929/console

**Comment by GabyCT** [comment]
related https://github.com/kata-containers/tests/pull/1694

**Comment by egernst** [comment]
Several instances.  Example: http://jenkins.katacontainers.io/job/kata-containers-tests-vsocks-PR/1648/

**Comment by GabyCT** [comment]
Closing this issue as the PR is already merged
