### ISSUE TITLE
integration: crio: Evaluate ctr.bats tests

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/tests#171]
I have run CRI-O bats `ctr.bats` with `overlay` and `devicemapper` storage drivers and here is the result:

- Passing tests:
  - `ctr log max`
  - `ctr partial line logging`
  - `ctrs status for a pod`
  - `ctr stop idempotent`
  - `ctr caps drop`
  - `ctr with image with Config.Volumes`
  - `ctr /etc/resolv.conf rw/ro mode`
  - `ctr correctly setup working directory`
  - `ctr execsync conflicting with conmon env`

- Failing tests:
  - `ctr hostname env`: Needs a patch on `kata-containers/runtime` to support executing a process on a container `CREATED` but not yet `STARTED`/`RUNNING`.
  - `ctr oom`: OOM never happened, needs further investigations.
  - `ctr create with non-existent command`: `cleanup_test` failed because we need to properly unmount what we have previously mounted, even in case of failure (which is the case of this test).
  - `ctr create with non-existent command [tty]`: Same reason than `ctr create with non-existent command`
  - `ctr update resources`: We don't have the support of `kata-runtime update` yet.
  - `ctr resources`: We don't have the support of `cpuset`.

**Comment by sboeuf** [comment]
/cc @chavafg 
I think we should enable the passing ones ASAP to make sure we can catch any regression while enabling more tests.

**Comment by chavafg** [comment]
Agree, will open a PR to enable them.

**Comment by sboeuf** [comment]
Thanks @chavafg
