### ISSUE TITLE
k8s v1.14.0.x failed with AArch64 kernel 5.0.x

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#1726]
**This issue acts as warning for running kata-containers with k8s on AArch64. it's not working proprely.**  
Lately, I'm trying include k8s integration tests on Arm kata-containers CI
However, the suggested k8s version `v1.14.0` failed on kernel `5.0.x`.
When you `kubeadm init` to initialize a Kubernetes control-plane node. The error is as follows:
```
Jun 18 10:32:41 entos-thunderx2-desktop kubelet[223169]: F0618 10:32:41.223415  223169
kubelet.go:1359] Failed to start ContainerManager failed to initialize top level QOS containers: 
failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for
cgroup [kubepods burstable]: Failed to set config for supported subsystems : failed to write
4611686018427387904 to hugetlb.64kB.limit_in_bytes: open
/sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64kB.limit_in_bytes: permission denied
```
That's because when `kubelet` wants to set up hugepagetlb cgroup, they use `kB` instead of `KB`(emmmmmmm, 😓😰), which conflicts the formal usage in kernel.

specific code lies in `pkg/kubelet/cm/cgroup_manager_linux.go`:
```
// hugePageSizeList is useful for converting to the hugetlb canonical unit 
// which is what is expected when interacting with libcontainer 
var hugePageSizeList = []string{"B", "kB", "MB", "GB", "TB", "PB"}

```
All above means that `kubelet` try to open `/sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64kB.limit_in_bytes`, but what kernel provides is that `/sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64KB.limit_in_bytes`.

This error won't bother `x86_64`, since the smallest hugepage for `x86_64` will be `2M`.
But for AArch64 using 4kb page size, they could support four different hugepage sizes, `64K`, `2M`, `32M`, `1G`.  So bad luck, AArch64. 😭

people already raised a fixed PR in kubernetes community, you can find more detailed info in this [kubernetes/kubernetes/78495](https://github.com/kubernetes/kubernetes/pull/78495). It is still under review. I, and my fellow will follow the latest and try our best to cherry pick to `1.14.x`.

BTW, same typo error also existed in runc, but it already got fixed [opencontainers/runc#2065](https://github.com/opencontainers/runc/pull/2065). 

IIRC, ci environment only supports k8s installed by `apt` command.
Do we need to provide ways to build kubelet/kubeadm/kubectl binary from scratch? @grahamwhaley @chavafg

**Comment by grahamwhaley** [comment]
/cc @egernst @ganeshmaharaj for domain input.
nice, but sad, find @Pennyzct 😜

**Comment by jodh-intel** [comment]
@Pennyzct - To cheer you up, I'm going to award you the :1st_place_medal: for "Best use of Emojis" :wink: :tada: :rainbow: :sun_with_face:

**Comment by Pennyzct** [comment]
I maybe need to change my github status from coding to "Best use of Emojis" in kata-containers Community. 😎

**Comment by jodh-intel** [comment]
Go for it - you earned it! :laughing:

**Comment by chavafg** [comment]
@Pennyzct yeah, we use `apt` for installing all kubernetes stuff... do you want to have the option to build it so as soon as the k8s fix lands, we can build and add k8s to the aarch64 CI?
If so, yeah, I think it would be a good option. 
BTW, k8s provide the packages for arm architecture when every time they make a release:
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/InRelease

**Comment by Pennyzct** [comment]
@chavafg yes, thanks to the k8s community, we could download the packages like other archs.
I definitely like to use `apt` for installing all kubernetes stuffs on ARM, but once in a while, awkward things like this, happened only on ARM(emmmmmmm,🤬😡), so maybe another option for building from scratch is one way to walk around, which really costs time. 
I definitely will urge my folks to cherry pick this PR back to 1.14.x asap!!!!!!!

**Comment by Pennyzct** [comment]
Hi guys
Finally, k8s community has finally cherry picked related patch back into releases/1.15, see PR [kubernetes/kubernetes#79671](https://github.com/kubernetes/kubernetes/pull/79671).🎉🎊
They said that 

> We've begun merging content for 1.15.3 with a target of 2019-08-19.

So we may have functioning-well k8s cluster v1.15.3 on AArch64 at least the end of Aug, FWIT.
I'm gone closing this issue, thanks again. ;)

**Comment by chavafg** [comment]
great news, thanks @Pennyzct 😃
