### ISSUE TITLE
CI failure: no tracing span status

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#1735]
# Description of problem

Saw at http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-PR/2276/console
```
15:02:59 INFO: Enabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
15:02:59 INFO: Checking runtime spans
15:03:04 ERROR: no span status
15:03:05 jaeger
15:03:05 jaeger
15:03:05 INFO: Disabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
15:03:06 make: *** [Makefile:150: tracing] Error 1
15:03:06 Build step 'Execute shell' marked build as failure
15:03:13 Performing Post build task...
15:03:13 Match found for :.* : True
15:03:13 Logical operation result is TRUE
15:03:13 Running script  : #!/bin/bash
```

Is it because jaeger not configured? /cc @jodh-intel

**Comment by jodh-intel** [comment]
Hi @bergwolf - difficult to tell as we're not yet capturing the logfile from the tracing test (see https://github.com/kata-containers/ci/issues/182).. I'll try to recreate locally but I suspect this might be a transitory issue.

**Comment by GabyCT** [comment]
Closing this issue as this https://github.com/kata-containers/tests/commit/39d862c32085ae9f407e0ebf66d10dc6dfed1aad is already merged
