### ISSUE TITLE
CI: Remove librbd1 repo for Debian setup

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1740]
See: https://github.com/kata-containers/tests/pull/1730/files#r294866374.

If we (can) do this, we also need to update the Debian installation guide which also tells user to install `librbd1`:

- https://github.com/kata-containers/documentation/blob/master/install/debian-installation-guide.md

**Comment by GabyCT** [comment]
Why we want to remove it?

**Comment by jodh-intel** [comment]
We don't want to install unnecessary packages. However, fwics we *do* still need this. `librdb1` is used for CEPH's RADOS block device support:

- http://docs.ceph.com/docs/master/rbd/

... and we compile QEMU to require that when building dynamically:

- https://github.com/kata-containers/packaging/blob/master/scripts/configure-hypervisor.sh#L357..L358

The situation may change when we switch to QEMU 4.0:

- https://github.com/kata-containers/packaging/pull/580
