### ISSUE TITLE
Resolve KSM throttler build strategy for CI

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1741]
See: https://github.com/kata-containers/tests/pull/1730/files#r294867576.

This affects the following distro-specific setup scripts:

```
.ci/setup_env_centos.sh
.ci/setup_env_debian.sh
.ci/setup_env_fedora.sh
.ci/setup_env_rhel.sh
.ci/setup_env_ubuntu.sh
```

It looks like @GabyCT wrote that code so she might have thoughts on this.

**Comment by GabyCT** [comment]
Closing this issue as this is running at the CI
