### ISSUE TITLE
CI build failure: /rootfs/etc/chrony.conf: No such file or directory

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#1744]
# Description of problem

Saw at http://jenkins.katacontainers.io/job/kata-containers-agent-centos-7-4-PR-firecracker/171/

```
INFO: Create symlink to /tmp in /var to create private temporal directories with systemd
INFO: Configure chrony file /rootfs/etc/chrony.conf
/osbuilder/rootfs.sh: line 398: /rootfs/etc/chrony.conf: No such file or directory
Failed at 116: sudo -E AGENT_INIT="${AGENT_INIT}" AGENT_VERSION="${agent_commit}" GOPATH="$GOPATH" USE_DOCKER=true OS_VERSION=${os_version} ./rootfs-builder/rootfs.sh "${distro}"
Failed at 18: "${cidir}/install_kata_image.sh"
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

**Comment by GabyCT** [comment]
This is related with https://github.com/kata-containers/osbuilder/commit/3df19ff984b2e9c937434dbaaedbbda3b70895aa#diff-263ae4105d99e0786c940f7229085c31
/cc @amshinde

**Comment by amshinde** [comment]
@GabyCT Just taking a look at this.
Is this a sporadic failure or can this be easily reproduced in our CI?
I dont see why this should fail, as the file `/rootfs/etc/chrony.conf` should be created if it is not present, unless `/etc` itself is not present on the rootfs.
I'll try to reproduce this locally if you provide more details, is this failing just for the agent CI, just for firecracker?

**Comment by GabyCT** [comment]
@amshinde yes it is a sporadic failure and always happen in the CentOS CI (I do not recall seen it on firecracker).

**Comment by amshinde** [comment]
@bergwolf @GabyCT We havent seen this in a while. Closing this.
