### ISSUE TITLE
Upgrade firecracker to 0.17.0

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/tests#1756]
Firecracker 0.17.0 changed the location of the binaries. As we upgrade firecracker to 0.17.0 switch to the new location.

**Comment by mcastelino** [comment]
Note: The changes between the runtime versions file and this file are co-dependent. So this change many need to be force merged.

**Comment by chavafg** [comment]
@mcastelino Please add a `Depends-on: github.com/kata-containers/runtime#1813` to your commit body
