### ISSUE TITLE
metrics: report: network: test/report seems broken

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1771]
# Description of problem

I ran a [metrics report](https://github.com/kata-containers/tests/blob/master/metrics/report/report_dockerfile/network-cpu.R) over kata and runc, and found the network report page didn't display and showed the following:

```
## Warning in eval(ei, envir): Skipping non-existent file: /inputdir/runc/cpu-
## information.json
## Warning in eval(ei, envir): NAs introduced by coercion
## Warning in eval(ei, envir): NAs introduced by coercion
## Warning in eval(ei, envir): NAs introduced by coercion
## Error in rbind_2(gc, g, "max"): ncol(x) == ncol(y) is not TRUE
```

Looks like we have a regression/breakage somewhere there - investigate, fix etc.

**Comment by grahamwhaley** [comment]
@GabyCT - any chance you can have a peek at this sometime soon?

**Comment by grahamwhaley** [comment]
side note - I think this failed when there were probably *no* results in any of the subdirs for that test. That happened as I don't think I have `perf` installed on my test system right now. Still, we should make the rmarkdown code fail more gracefully I think.

**Comment by GabyCT** [comment]
@grahamwhaley is this issue fixed or still happening?

**Comment by grahamwhaley** [comment]
I think it will still happen with a poorly configured system (no `perf`), but we can close as 'not a critical bug'.
