### ISSUE TITLE
metrics: report: runc path/name has changed - need to adapt

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1796]
# Description of problem

We hard code some `runc` names and paths into some of the metrics code, in order to take measurements or extract information from it. It seems the `runc` process has changed binary name and/or path, and the checks are no longer working, meaning we miss some metrics data such as the PSS footprint when testing with `RUNTIME=runc`.

e.g., when running the memory footprint test:
```
tests/metrics/lib/json.bash: line 96: docker-runc: command not found
...
ERROR: Runc process not found
```

# Expected result

Correctly find `runc`, or fail more gracefully

At https://github.com/kata-containers/tests/blob/master/metrics/lib/json.bash#L96 we open code `runc` as `docker-runc`, which seems to no longer exist. I can see a `/usr/sbin/runc` though.

And in https://github.com/kata-containers/tests/blob/master/metrics/density/docker_memory_usage.sh#L86 we open code some runc measurements, which are failing, which is why we get the `ERROR` line in the output.

**Comment by Galansary** [comment]
Hi @grahamwhaley any update on this issue? I'm facing the same when trying to run the test with runc

**Comment by grahamwhaley** [comment]
Hi @Galansary - nobody working on fixes afaik (but, PR's most welcome ;-).
A quick workaround would be to hard-code the paths referenced above to the paths on your actual system.
A longer term real fix would be to:
- use maybe `which` or `whereis` to try and dynamically locate the binaries
- have a list of known places, and search them in order
- see if we can ask `docker info` to tell us where the components are ?

**Comment by GabyCT** [comment]
@grahamwhaley is this still an issue?

**Comment by grahamwhaley** [comment]
afaik, yes.

**Comment by GabyCT** [comment]
@grahamwhaley , I ran the memory test `bash density/docker_memory_usage.sh 20 5`  and I just did `export RUNTIME=runc` and then I see the json results and I can see the individual runc results, so I am not quite sure which part is failing (about the issue that you open)... thanks
```
{
        "@timestamp" : 1588885114034,
        "env" : {
                "RuntimeVersion": "0.0.0",
                "RuntimeCommit": "unknown",
                "RuntimeConfig": "/usr/share/defaults/kata-containers/configuration.toml",
                "Hypervisor": "/usr/bin/qemu-system-x86_64",
                "HypervisorVersion": "0.0.0",
                "Proxy": "/usr/libexec/kata-containers/kata-proxy",
                "ProxyVersion": "0.0.0",
                "Shim": "/usr/libexec/kata-containers/kata-shim",
                "ShimVersion": "0.0.0",
                "machinename": "gabyfoot"
        },
        "date" : {
                "ns": 1588885114042502520,
                "Date": "2020-05-07T20:58:34.049"
        },
        "test" : {
                "runtime": "runc",
                "testname": "memory footprint"
        },
        "runc-env" :
        {
                "Version": {
                        "Semver": "1.0.0-rc5+dev.docker-18.06",
                        "Commit": "a592beb5bc4c4092b1b1bac971afed27687340c5"
                }
        },
"memory-footprint" : {
        "Config": [
                        {
                "containers": 20,
                "ksm": 0,
                "auto": "",
                "waittime": 5,
                "image": "busybox",
                "command": "sh"
        }
        ],
        "Results": [
                        {
                "average": {
                        "Result": 80.95,
                        "Units" : "KB"
                },
                "runc": {
                        "Result": 80.95,
                        "Units" : "KB"
                }
        }
        ],
        "Raw results": [
                        {
                "runc individual results": [
                        86,
                        83,
                        83,
                        79,
                        83,
                        79,
                        79,
                        79,
                        79,
                        79,
                        79,
                        79,
                        79,
                        83,
                        83,
                        83,
                        79,
                        83,
                        83,
                        79

                ]
        }
        ]
        }
}
```

**Comment by grahamwhaley** [comment]
Hi @GabyCT . I just tried it here, and it failed. It could be that my system is possibly out of date - or, that your system has some old components installed.

The crucial part is linked at the top of this report - where the json code is [trying to extract the version info using the `docker-runc` binary](https://github.com/kata-containers/tests/blob/master/metrics/lib/json.bash#L96). It relies on a hard wired call to `docker-runc`, which on my system does not exist, and is not just called `runc`.
I got no JSON results - but, I see in your results above that your runtime version is 0.0.0 for instance - what I'd expect in there is an actual `runc` version number.

Here is what I got - which two errors in it - one near the top, and one at the bottom:

```bash
# RUNTIME=runc bash ./density/docker_memory_usage.sh 20 5
===== starting test [memory footprint ksm] =====
command: docker: yes
INFO: Runtime environment not found - setting defaults
command: smem: yes
command: bc: yes
docker pull'ing: busybox
Using default tag: latest
latest: Pulling from library/busybox
Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Image is up to date for busybox:latest
docker pull'd: busybox
/home/gwhaley/go/src/github.com/kata-containers/tests/metrics/lib/json.bash: line 96: docker-runc: command not found
2d64ee7ca198f16ebcb1c0a504092a3d7da5e23589e6ec9131420a2372a630b0
8d68d9431deb7ea6f09562d998bce842faa4c8fac6b8976faaefdb1c9f9398bd
998791dde325780d137823807328141c0c156f148b19b122d816db812d9485f8
44648cf31aac3d7f15cb5e9d674ace03cef4372a64483ff70958e54f7606eb59
ebd23ce5539063cf16df6f3c128929570c6fb29bd73d8caad5641accaa2be232
bad686e602672b1b7a3932a58e73321c4ecf7bed4157c3e3f3774e205feff215
052c1986cea948d8ef093d0c9851d4b1599204271a83f322f375914ec41bdc2e
fefc6367969692974ff8d6bec0f5914e30a8309c3e4cd54e982dfee2389c9f37
bb8f5d32d1960d66c984b03cbac24988d36af1fbedad9ebb2ce2e68146c87c56
9263c5cea6790d0a52eb602c200b68ce1a4d199c6fb3dd2854e4f1a41c867e85
3d9a6704d8c63f5938b9a94ff6c309d2e308a7d3639c8eecda0f64d3b9176172
436c213a2f9d327caf934570a90950ed33fcd3cb385231dafc1f7b7fe87e88a8
2a88a27f2c2a7e10af75e00dc284409931c59b2103a5165fc5e38cb804b21a5b
ecfa60e4400b60932f4942658afdad49f65bf305f17ac810153831b3aacd25d6
6cbeb01a070624799c6dbb2f6c55f91fb4644be5003d0274380334d34322c738
98180a09c794d4da227d41800b23b703cd0c6b209b21b621e3992b1b5d816027
73d2d400f856cece8869c958e6f159a2d3a6004ee07066506190ba2a6bf4a55e
5785ae0da0deaa7e08c12fc1b28c5d5fb34f29844d009721a2699be965874a42
c770b95c3f721e889330f767becc90f6cd88901cec7e321ad7baab729e9e74bc
332db5418ac7b508e1f59b527d5edd6c2a6c65b6afbc0f56ebaffd6a910f0fe4
napping 5 s
kata-VVkhA5
kata-c5SJUo
kata-bHvLgw
kata-htkak6
kata-nxcyyj
kata-HwbWT8
kata-RP7TrI
kata-KUujRM
kata-U5lYxQ
kata-TRplzr
kata-FbPPn6
kata-DHYuvK
kata-ULpQ8d
kata-S8ds8v
kata-MdhPh5
kata-cMil5z
kata-pK1lhc
kata-UCv8g9
kata-pm48lc
kata-EhvgK0
ERROR: Runc process not found
```

Can you check if your system has `docker-runc` installed, and if so, where from? This is no doubt dependant on which version of docker is installed, and potentially if any parts of a previous installation may still be on the system.

You could also try running:

```bash
sudo docker info --format "{{json .Runtimes}}"
```

which should give you the names/paths that docker thinks it is using, which might also help. (I stole that piece of magic from our own [library code that searches for the kata path being used](https://github.com/kata-containers/tests/blob/master/lib/common.bash#L75) - we may be able to use a similar snippet to locate the name/path of the `$RUNTIME` that has been requested and thus fix this issue...

**Comment by GabyCT** [comment]
@grahamwhaley 
```
$ sudo docker info --format "{{json .Runtimes}}"
{"kata-runtime":{"path":"/usr/bin/kata-runtime"},"runc":{"path":"runc"}}
```
```
 $ docker-runc --version
runc version 1.0.0-rc10
spec: 1.0.1-dev
```

**Comment by grahamwhaley** [comment]
Right, so your docker installation thinks it is using the binary `runc`, which is probably in `/usr/sbin/runc`. In which case, the json script should have failed, like it did for me, as it should not have been able to find the binary `docker-runc`... maybe you still have `docker-runc` on your system from an older installation, which is why you didn't see the issue.

Anyhow, the issue still stands that afaik, the scripts are hard wired to look for `docker-runc`, but the actual docker runc binary is now called `runc`, so the scripts are broken for 'modern' installations. They should probably use that `.Runtimes` json trick above to find the name of the binary associated with the `runc` runtime, and use that, instead of hard wiring it. This is of course only all an issue if anybody wants to run the tests against `runc`, and not `kata`.
