### ISSUE TITLE
metrics: report: PSS footprint Rmd does not handle missing files well

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1797]
# Description of problem

With issue #1796 , we had no 'pss' memory footprint results for `runc`. The report generator spotted this issue, but instead of just skipping that set of data, fell over on it like:

```
## Warning in eval(ei, envir): Skipping non-existent file: /inputdir/runc/
## memory-footprint-ksm.json
## Error in cbind(rstats_names, rstats): number of rows of matrices must match (see arg 2)
```

# Expected result

It should gracefully skip any missing data, and still generate the report from the data it did find.

**Comment by GabyCT** [comment]
@grahamwhaley is this is fixed or still happening?

**Comment by grahamwhaley** [comment]
This is probably still there in the code, but it seems nobody is tripping over it. closing.
