### ISSUE TITLE
metrics: system memory: elastic not working with runc correctly

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#1798]
# Description of problem

It looks like the elasticsearch based memory footprint test is not functioning correctly with `runc`. I suspect the container is terminating early. In this picture:

![image](https://user-images.githubusercontent.com/4761717/60972620-8491ba00-a31e-11e9-88c0-c593fb553a8a.png)

the 'blue line with square dots' should be a linear downtrend line, normally somewhere approximately near the other blue lines. Here we see it is oscillating up and down, which makes me think containers are running for a short time and then stalling or exiting.

# Expected result

I'd expect to see a linear-ish decrease in available system memory - run a `runc` elasticsearch by hand under the same circumstances and check the stdout/logs to ensure they are running as expected (and running in a comparable fashion to the kata ones).

**Comment by GabyCT** [comment]
@grahamwhaley is this still an issue?

**Comment by grahamwhaley** [comment]
afaik, but nobody working on it. closing.
