### ISSUE TITLE
Check if yamllint is installed

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#180]
https://github.com/kata-containers/tests/pull/164 added a requirements for `yamllint`. That PR installs it for the Jenkins CI, but not for Travis, which is now failing. For example, see:

https://github.com/kata-containers/runtime/pull/112

Since we want to move away from Travis, just add a check to only call `yamllint` if available.

**Comment by chavafg** [comment]
The `[ -n "$(command -v $cmd)" ]` condition fails and makes `.ci/static-checks.sh` fail.
