### ISSUE TITLE
Soak tests: Soak tests assume hypervisors run with the full path

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/tests#1802]
# Description of problem

Soak tests: Soak tests assume hypervisors run with the full path.
https://github.com/kata-containers/tests/blob/5c6b6efe9f599483d54397cd5b5dfd890ad9dff8/lib/common.bash#L137

https://github.com/kata-containers/tests/blob/master/integration/stability/soak_parallel_rm.sh#L109

However when running a hypervisor with jailer the path is relative to the jail and hence the check should only look for the process.

For example when running firecracker with jailer the process will be

```
 /firecracker --id=5af26fcea8dbf413067e90026fd9845515d5a1f300d61f66427760a27ef114c2 --seccomp-level=2 --start-time-us=1562786230593253 --start-time-cpu-us=223 --api-sock=/api.socket
```

where /firecracker is relative to the jailed location.

**Comment by GabyCT** [comment]
Closing this issue as it is already solved
