### ISSUE TITLE
clean-up: do extra clean up for k8s integration on bare-metal CI

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#1811]
When running `kubeadm reset` to delete stale resource derived from k8s integration tests, we often get following suggestion:
```
The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually.
For example:
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
```
Especially for cleaning up iptables, if you don't clean it up, it may lead to `cni0` interface not being set up in master node next time.
They all exist in bare-metal environment. ;)
related PR is on the way~

**Comment by grahamwhaley** [comment]
Cool. I've seen the message before, but was running on local transient test machines, so ignored it ;-)
/cc @krsna1729  @mcastelino who may be interested or have input.
