### ISSUE TITLE
Unit test advice contains an error

### ISSUE THREAD

**Issue by marcov** [kata-containers/tests#1837]
This:
https://github.com/kata-containers/tests/blob/093143be0c361b9fa4578946840ea9167cb56c36/Unit-Test-Advice.md#L68

should be:
```
if d.expectError {
```

**Comment by jodh-intel** [comment]
Good catch @marcov! I can't fix this atm but if someone wants to pick it up, it would be a great (and very small, but very useful) PR ;)
