### ISSUE TITLE
nemu CI failure: vhost_dev_init failed: Operation not permitted: unknown.

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#1844]
# Description of problem
Saw at http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-nemu/668/consoleFull

> 11:35:00 [4] Running command '/usr/bin/docker [docker run --cidfile /tmp/cid382916938/0yJpbbBAmnRhI8WpOm74tnmDDQvRo4 --runtime kata-runtime --name 0yJpbbBAmnRhI8WpOm74tnmDDQvRo4 --rm -i debian /usr/bin/perl -e exit -1]'
11:35:00 [1] command failed error 'exit status 125'
11:35:00 [1] [docker run --cidfile /tmp/cid554230307/mVezJ1XJRIaCJiDfxPVN0B5egqlV91 --runtime kata-runtime --name mVezJ1XJRIaCJiDfxPVN0B5egqlV91 --rm debian /usr/bin/perl -e exit 1]
11:35:00 [1] Timeout: 120 seconds
11:35:00 [1] Exit Code: 125
11:35:00 [1] Stdout: 
11:35:00 [1] Stderr: docker: Error response from daemon: OCI runtime create failed: nemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-c802a37dd0ab28da,tag=kataShared,cache-size=1024M: Failed to read msg header. Read -1 instead of 12. Original request 1.
11:35:00 [1] nemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-c802a37dd0ab28da,tag=kataShared,cache-size=1024M: vhost_dev_init failed: Operation not permitted: unknown.
11:35:00 [1] 
11:35:00 [1] Running command '/usr/bin/docker [docker ps -a -f name=mVezJ1XJRIaCJiDfxPVN0B5egqlV91 --format {{.Status}}]'
11:35:01 [1] [docker ps -a -f name=mVezJ1XJRIaCJiDfxPVN0B5egqlV91 --format {{.Status}}]
11:35:01 [1] Timeout: 120 seconds
11:35:01 [1] Exit Code: 0
11:35:01 [1] Stdout: 
11:35:01 [1] Stderr: 
11:35:01 [1] 
11:35:01 [1] • Failure [4.852 seconds]
11:35:01 [1] docker exit code
11:35:01 [1] /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-nemu/go/src/github.com/kata-containers/tests/integration/docker/exitcode_test.go:20
11:35:01 [1]   check exit codes
11:35:01 [1]   /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-nemu/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
11:35:01 [1]     with exit code '1' when interactive mode is: 'false', it should exit '1' [It]
11:35:01 [1]     /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-nemu/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
11:35:01 [1] 
11:35:01 [1]     Expected
11:35:01 [1]         <int>: 125
11:35:01 [1]     to equal
11:35:01 [1]         <int>: 1
11:35:01 [1] 
11:35:01 [1]     /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-nemu/go/src/github.com/kata-containers/tests/integration/docker/exitcode_test.go:42

# Expected result

It should pass.

# Actual result

It failed.

**Comment by yuntongjin** [comment]
any update ?

**Comment by GabyCT** [comment]
Closing this issue as we no longer support nemu
