### ISSUE TITLE
firecracker is not tested here

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#1846]
# Description of problem

Firecracker ci is not enabled here and as a result, PR #1839 breaks it without showing any failure in the PR's CI.

# Expected result

Firecracker CI should also be enabled.

**Comment by bergwolf** [comment]
@jcvenegas @grahamwhaley How are we configuring fc ci right now? I'm seeing

```
Makefile:112: recipe for target 'docker-stability' failed
make: *** [docker-stability] Error 1
Failed at 29: sudo -E PATH="$PATH" bash -c "make docker-stability"
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

And it is because `HYPERVISOR_PATH` is not getting set https://github.com/kata-containers/tests/blob/master/integration/stability/hypervisor_stability_kill_test.sh#L32 by reading kata config.

**Comment by grahamwhaley** [comment]
@bergwolf - I think @GabyCT and @mcastelino were looking at this last week - I thought things got fixed.... let's see what they say.

**Comment by bergwolf** [comment]
@grahamwhaley Thanks for the hint. I looked for @GabyCT's commit log and found the problem. Let's see if #1847 fixes it.

**Comment by GabyCT** [comment]
@bergwolf the fc is being triggered https://github.com/kata-containers/tests/pull/1847
