### ISSUE TITLE
filter: build filter frame for k8s intergration tests on aarch64

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#1888]
Hi guys. 
Recent days, I have been focusing on including k8s integration tests on ARM CI. 
The last majority work may be building up k8s filter frame, just like what I did for docker integration tests.
Since for now, a few advanced feature hasn't been fully supported on aarch64, like cpu hotplug, we need to skip a few k8s intergration tests involving these features.

**Comment by Pennyzct** [comment]
I have just brought the filter scheme online. ;). see [tests/#1889](https://github.com/kata-containers/tests/pull/1889).
Since I'm going to use arm_slave_02 for test, it's better bring it down, how could i do the trick??? 🤓

**Comment by Pennyzct** [comment]
@kalyxin02

**Comment by grahamwhaley** [comment]
@Pennyzct - how do you take the jenkins node offline? - go to the Jenkins UI, go to the node in question, and there is a 'take node offline' button. Add an explanation in the dialog box of why it is going offline.....  and then, in the past I saw nodes still getting used (but, I **did** have quite a stange node launch setup at the time). So I **also** tend to change the labels on the node as well, normally by appending `_XXX` to one. So, if you have a label on the node for `aarch64` for instance, change that to `aarch64_XXX`, which will ensure no job match that node, and so will not get scheduled on it....

and then wait for any jobs running on that node to finish, and then the node should be free to use :-)

**Comment by Pennyzct** [comment]
Hi @grahamwhaley 
I'm not sure if I have the authority to do the trick. 😭
This is How I look in Jenkins UI.
![image](https://user-images.githubusercontent.com/31910522/62436792-5bc0e100-b773-11e9-8942-342cf5ef4a43.png)
If I went to the arm02_slave node, i couldn't find `take node offline` button.
![image](https://user-images.githubusercontent.com/31910522/62436924-c1ad6880-b773-11e9-8584-7bf59684827d.png)

**Comment by grahamwhaley** [comment]
@Pennyzct - ah, looks like you don't have 'the power' - or you would see a 'Configure' item in the menu for the slave.
I have take `arm02_slave` offline, and appened `_XXX` to its labels - you should be able to see that in your view now...
When you need it back online, ping myself or @chavafg

**Comment by Pennyzct** [comment]
thanks!!!! @grahamwhaley
