### ISSUE TITLE
Jenkins: enable initrd test

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#190]
Now that we have merge #173, we should integrate this in the Jenkins with following environment setups:
```
- AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine
- AGENT_INIT=no TEST_INITRD=no OSBUILDER_DISTRO=clearlinux
```
They can be used to create parallel jobs or sub-jobs.

**Comment by sboeuf** [comment]
Looks good !
This should be running as a separate job(Azure VM) from the CI.

**Comment by GabyCT** [comment]
This is being blocked by https://github.com/kata-containers/osbuilder/issues/82

**Comment by GabyCT** [comment]
Closing this issue as currently the ci is running for initrd https://github.com/kata-containers/ci/pull/48
