### ISSUE TITLE
cri_containerd: missing CNI plugin binary

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#1907]
# Description of problem
Hi guys
FWIT, if I want to test k8s cluster with `containerd-cri`, I need to set `$CI_JOB` as `CRI_CONTAINERD_K8S`. 
And when I go with that, cni plugins will be not installed, which means no binary installed under `/opt/cni/bin`, see code [here](https://github.com/kata-containers/tests/blob/master/.ci/install_cni_plugins.sh#L10).
That confuses me, with no cni plugin binary, `coredns` pod will stuck in `ContainerCreating`
```
NAMESPACE     NAME                                              READY   STATUS              RESTARTS   AGE
kube-system   coredns-5c98db65d4-mj6c4                          0/1     ContainerCreating   0          101s
kube-system   coredns-5c98db65d4-n7hjb                          0/1     ContainerCreating   0          101s
```
error log:
```
kubelet[178216]: E0807 16:18:12.239805  178216 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "coredns-5c98db65d4-mj6c4_kube-system(433c44f7-8c6d-46de-815b-dda22d690cac)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "5ae332bf5a5ab788948422356efc74b40b437c1f6741622f8abed7448f66721a": failed to find plugin "loopback" in path [/opt/cni/bin]
```
I'm wondering if I misunderstand somewhere, since CI with running k8s integration tests with `containerd-cri` is working well long time. 
But I really couldn't figure out by myself, could anyone lend a hand here, plz😭😭
@jodh-intel @grahamwhaley @chavafg

**Comment by chavafg** [comment]
Hi @Pennyzct,

taking a look at the logs, I see that the cni plugins are being installed when running `containerd/cri` integration tests, which run before k8s, see: 
https://github.com/kata-containers/tests/blob/master/integration/containerd/cri/integration-tests.sh#L73-L75.
