### ISSUE TITLE
Add test to check if a block device passed as a volume is passed to VM using a block driver instead of 9p.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#191]
Test needs to be added after https://github.com/kata-containers/runtime/pull/138 lands.

**Comment by GabyCT** [comment]
@amshinde so what I understand is that we need to add a test with $ docker run -v .... is that correct?

**Comment by amshinde** [comment]
@GabyCT Yes thats correct. You can create an image first and loop mount it.(I think we have tests that do that currently) You can then pass the /dev/loop directory where the image is mounted to the container and check if that can be mounted

```
sudo docker run -v /dev/loop2:/dev/loop2 debian bash -c "mount /dev/loop2 /mnt"
```

Also, can you add another test, which  creates a text file under /dev and pass that to a container, and pass check if contents are the same.

```
$ sudo bash -c "echo 'hello'> /dev/foo"
$ sudo docker run -v /dev/foo:/dev/foo debian bash -c "cat /dev/foo"
#Verify output of above command = "hello"
```

**Comment by GabyCT** [comment]
@amshinde thanks for the information

**Comment by GabyCT** [comment]
@amshinde , while doing
$ docker run  -v /dev/loop2:/dev/loop2 debian bash -c "mount /dev/loop2 /mnt"
I am getting
`mount: permission denied`

I am using the following configuration
kata-runtime  : 0.0.1
commit   : 7bb4e0470c3236c9c0df3cd59196576752610bc2
OCI specs: 1.0.1
kata-shim version 0.0.1-2bdea2e41109b6b71c600899e1bf5794b125200d
kata-proxy version 0.0.1-de18929631091cb1f079b2e6e1caa3e4625f4930

**Comment by grahamwhaley** [comment]
I think that is because we have locked down the (/me forgets the correct phrase...) system capabilities inside the container - so you cannot use `mount` there by default any more. But, I also think you can re-enable that SYSCAP on the docker command line... (have to leave that as an exercise for the user to find the right command though - I don't have it to hand I'm afraid).

**Comment by sboeuf** [comment]
@GabyCT you need capabilities to be able to mount.

**Comment by GabyCT** [comment]
@sboeuf and @grahamwhaley for the answer :) I will try with capabilities

**Comment by amshinde** [comment]
@GabyCT yeah, you will need to pass additional capabilities on the command line `--cap-add=SYS_ADMIN`
