### ISSUE TITLE
firecracker-ci should only test vsock

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#1927]
# Description of problem
Constantly seen in firecracker CI failures like (e.g., http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-1804-PR-firecracker/971/consoleFull):

```
Stderr: docker: Error response from daemon: OCI runtime create failed: dial unix: missing address: unknown.
```
It means kata-runtime is trying to connect to agent via a unix domain socket, which is only possible for serial port connections. However, for firecrakcer, we only support vsock connection. So not sure why test is trying to connect via serial port.

**Comment by jodh-intel** [comment]
FC is using a unix socket it seems:

- https://github.com/kata-containers/runtime/blob/master/virtcontainers/fc.go#L254

However, why the address is unset is not clear to me.

/cc @mcastelino.

**Comment by chavafg** [comment]
From CI perspective, we haven't changed anything. As you can see in the log, we are using vsocks when running with firecracker:
```
[Hypervisor]
  MachineType = ""
  Version = "firecracker 0.17.0"
  Path = "/usr/bin/firecracker"
  BlockDeviceDriver = "virtio-mmio"
  EntropySource = "/dev/urandom"
  Msize9p = 0
  MemorySlots = 10
  Debug = true
  UseVSock = true
  SharedFS = ""
```

**Comment by lifupan** [comment]
@chavafg @bergwolf 
Let me have a debug.

**Comment by chavafg** [comment]
this was fixed on https://github.com/kata-containers/runtime/pull/1990, closing.
