### ISSUE TITLE
ci: add backward compatibility test

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#2134]
add a simple backward compatibility test

**Comment by bergwolf** [comment]
Can we please have a compatibility plan first? E.g., what kind of compatibility we want to maintain.

afaics, shimv2 and kata-runtime cli have different compatibility requirements. shimv2 only needs to be able to cleanup a running sandbox upon errors after the shimv2 binary is updated. Whereas the kata-runtime cli need compatibility amongst every operation.

/cc @kata-containers/architecture-committee

**Comment by grahamwhaley** [comment]
afaik, the only place we talk about backwards compatibility and versions and releases is in the [vc experimental docs](https://github.com/kata-containers/runtime/tree/master/virtcontainers/experimental) - we could/should start with that, and make it more formal for the whole project maybe.
