### ISSUE TITLE
ci: travis: depends-on is ignored

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2145]
# Description of problem

In jenkins kata dependecies are resolved and updated using `depends-on` in a commit
but this is not enabled in travis.

All travis repos will run `.ci/setup.sh` as inital step but this does check for depends-on,
this is not usually a blocker because only static checks are done in travis but when a static
check is updated on tests repository and needed in a PR this is an issue.

# Expected result

depends-on  works in all travis repos, ideally  just need to modify the script in this repo to avoid
go in all of them and create PRs.

# Actual result

depends-on does not work

**Comment by GabyCT** [comment]
Closing this as we not longer support travis
