### ISSUE TITLE
ci: check system is 'clean' after each test

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#215]
We should check the system is in a 'clean and expected' state after each test - this should pick up any issues where parts of the runtime are left behind, including any VM/proxy/vc files/mounts/net connections/etc.

See https://github.com/clearcontainers/tests/issues/826
Also see the related #195 - where you can find the code to check many such items

**Comment by grahamwhaley** [comment]
Hi @GabyCT 
This is the Issue I was thinking you might look at.
It basically involves lifting the 'system sanity checks' out of the [rm soak test](https://github.com/kata-containers/tests/blob/master/integration/stability/soak_parallel_rm.sh), adding them to a top level library somewhere/somehow, and then running those checks after every test.

Now, the tricky bit I think is really that we have a number of different types of test - `go test`, ginkgo, bats etc. I don't think we'll manage to add this sanity checking to all of those in one go, in which case maybe a first step is to make a github markdown ticklist here with all the sub-types of tests we have and then we can try to add the sanity test to the subsets one at a time. I do expect each subset of tests may require a different approach to implement/wrapping.

Shout if you need more input, guidance, idea review, RFC etc.

**Comment by GabyCT** [comment]
@grahamwhaley ok :) I'll take a look

**Comment by GabyCT** [comment]
This is a PR related with that https://github.com/kata-containers/tests/pull/726

**Comment by GabyCT** [comment]
This issue has been solved with PRs https://github.com/kata-containers/tests/pull/801 , https://github.com/kata-containers/tests/pull/732, https://github.com/kata-containers/tests/pull/726
