### ISSUE TITLE
 Footprint-busybox.json results in "KB" should be in "B"

### ISSUE THREAD

**Issue by Galansary** [kata-containers/tests#2169]
**Which feature do you think can be improved?**
Metrics reporting, footprint-busybox.json
**Specify the feature you think could be made better**
memory unit reporting in the result should be in "Bytes", not in "KB"
**How can it be improved?**
change the scripts 
![image](https://user-images.githubusercontent.com/36736397/70797638-cc6caf80-1d9c-11ea-8a87-fd12115e415b.png)

Describe how specifically you think it could be improved.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by grahamwhaley** [comment]
Good spot @Galansary - indeed, that looks like it needs fixing.
If you have not already, you could verify by looking at the [code that generates those results](https://github.com/kata-containers/tests/blob/master/metrics/density/footprint_data.sh), and confirming which tools (maybe `smem` or `/proc/meminfo` iirc) that are used to get that data. I think maybe some of the results (from `/proc/meminfo` ?) are in Kb, but others may be in bytes...

If you are going to submit a PR, and have not done so already, please have a read of https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md to get the right format of the PR so it will pass the CI ;-)

thanks!

**Comment by GabyCT** [comment]
@grahamwhaley , I tried to reproduce this issue and I noticed the following
We are getting the memory free https://github.com/kata-containers/tests/blob/master/metrics/density/footprint_data.sh#L284,
by using `smem` (which if I am not in an error the result is given in bytes) `sudo smem -w | head -6 | tail -1 | awk '{print $4}'` and I get a result like `mem_free=15435476`, however, I see that that result is multiplied by 1024 https://github.com/kata-containers/tests/blob/master/metrics/density/footprint_data.sh#L285,
which gave us `15805927424` which is reflected at the report in `KB`. My question is should this result not be divided instead of multiplied it?

**Comment by grahamwhaley** [comment]
Hi @GabyCT . `smem` by default gives results in Kb I believe - a little annoyingly, not documented either....
If we try that command, and then add the `-k` to get it to add the units in, we can see (on my system):

```bash
$ smem -w -k
Area                           Used      Cache   Noncache
firmware/hardware                 0          0          0
kernel image                      0          0          0
kernel dynamic memory          4.0G       3.7G     222.4M
userspace memory               2.9G     751.9M       2.2G
free memory                   24.4G      24.4G          0
$
$ smem -w
Area                           Used      Cache   Noncache
firmware/hardware                 0          0          0
kernel image                      0          0          0
kernel dynamic memory       4147996    3920200     227796
userspace memory            3056596     770092    2286504
free memory                25623500   25623500          0
```

I think the only thing wrong is the output of the JSON, that says `KB` for the data we've derived from `smem`, but as we have multiplied by 1024, it should be `B`. But, we should probably check each entry to make sure it is indeed correct (not all of them are derived from `smem` iirc).
