### ISSUE TITLE
CI does not catch static check failure on runtime master

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#2196]
# Description of problem

Running `make check` in runtime repo master tip, I got following error:
```
/home/vagrant/workplace/golang/src/github.com/kata-containers/runtime/virtcontainers/utils
cli/kata-check.go:446:20: SA4003: no value of type uintptr is less than 0 (staticcheck)
                if errno != 0 || ret <= 0 {
                                 ^
```

I'm using `v1.15.0` of `golangci-lint` as required by runtime versions.yaml.

Any reason CI is not catching it?

**Comment by bergwolf** [comment]
Same is true for `make test`. CI seems to ignore `make test` failures as well?

see https://github.com/kata-containers/runtime/pull/2371

**Comment by bergwolf** [comment]
@jcvenegas @grahamwhaley @jodh-intel

**Comment by grahamwhaley** [comment]
Is this understood/fixed now @bergwolf ?
