### ISSUE TITLE
Clean: clean up stale files under /tmp

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#2210]
# Description of problem
Stale dir `/tmp/virtc/ocibundle/` has caused recent ARM CI failure.
http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/1414/ 
Related PR: kata-containers/runtime#2387
BTW,  almost ten thousand😖 stale file/dir have been accumulated on ARM CI.
We need to clean up `/tmp` on all baremetal CI. ;)
PR is on the way~~~

**Comment by ariel-adam** [comment]
https://github.com/kata-containers/tests/pull/2236

**Comment by ariel-adam** [comment]
Closing this issue since there is a merged PR
