### ISSUE TITLE
firecracker ci cannot be pass most of time

### ISSUE THREAD

**Issue by teawater** [kata-containers/tests#2216]
http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-1804-PR-firecracker/
There are 28 records and only 1 pass.

**Comment by GabyCT** [comment]
@teawater what I see from the records is that is not passing in particular PRs , here it is the list
* Suppport systemd cgroups and cgroupsv2 failed - 2
* Update qemu failed - 2
* Land experimental newstore failed - 4
* Update firecracker version failed - 8
Looking other repositories the CI looks more stable so it seems that these changes have an impact on the FC functionality

**Comment by GabyCT** [comment]
@teawater or maybe something was landed that has affected the stability of FC

**Comment by GabyCT** [comment]
Closing this issue as https://github.com/kata-containers/runtime/issues/2397 is related with this
