### ISSUE TITLE
ci-fast-return.sh skips the CI when only changing vendor directory

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#2241]
# Description of problem

If only `vendor` directory is modified, `ci-fast-return.sh` skips the CI. 
See: https://github.com/kata-containers/runtime/pull/2403#issuecomment-576381479

We are currently kind of safe since we also need to modify the `Gopkg.toml/lock` when we are revendoring, but still a bug.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by GabyCT** [comment]
@chavafg , I think this issue has been fixed, can we close this?

**Comment by chavafg** [comment]
@GabyCT I'll check today and will close if this is already solved.
