### ISSUE TITLE
check-markdown: generates broken toc in corner case

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#2249]
# Description of problem

In a specific corner(ish) case of what appears to be valid github markdown, it looks like `check-markdown toc` generates a partly broken toc.

# Description

Given this raw markdown:

````markdown
#  One

* point
```bash
```

# Two

blah

# Three

foo
````

with `check-markdown toc`, we get the toc output of:

```markdown
* [One](#one)
* [](#two)
* [](#three)
```

# Workaround

It seems the lack of space between the `*` and the ` ``` ` code block is what is upsetting the parsing or whatever. If we modify the test to:

````markdown
#  One

* point

```bash
```

# Two

blah

# Three

foo
````

we get the correct toc output of:

```markdown
* [One](#one)
* [Two](#two)
* [Three](#three)
```

# Notes

I ran into this whilst modifying some existing markdown docs on github, that seem to render just fine - but, the toc generator was fumbling.

**Comment by jodh-intel** [comment]
I was aware of this issue, but alas there isn't a clean fix for it fwics; the toc generator uses the blackfriday package which is problematic (to be fair *all* the golang md parsers I considered at the time were too, but blackfriday was the least ;)

See: https://github.com/kata-containers/tests/blob/master/cmd/check-markdown/hack.go#L15..L19

The solution is to space the document elements out as you've found. Maybe it's time to investigate a rewrite in rust... :smile:

**Comment by ariel-adam** [comment]
Given that we have a workaround and the effort in trying to fix this is large we will close this as wont fix.
