### ISSUE TITLE
Add docker test for testing ipv6

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#2270]
Once the ipv6 PRs for runtime and agent are merged, we need a integration tests for this.
We can start with a simple test with docker to check if containers with ipv6 can ping each other.

Docker needs to be started with ipv6 enabled by adding the following configuration in the `/etc/docker/daemon.json`
```
$ cat /etc/docker/daemon.json
{
“ipv6”: true,
“fixed-cidr-v6”: “2001:db8:1::/64”
}
```

Start 2 containers:
$ sudo docker run -name test1 --runtime kata-runtime debian tail -f /dev/null
$ sudo docker run -name test2 --runtime kata-runtime debian tail -f /dev/null

Find out the ipv6 address of the containers:
```
$ sudo docker inspect --format='{{range .NetworkSettings.Networks}}{{.GlobalIPv6Address}}{{end}}' test2
2001:db8:1::242:ac11:3
```

Ping test2 from test1
```
$ sudo sudo docker exec test1 ping -6 2001:db8:1::242:ac11:3
PING 2001:db8:1::242:ac11:2(2001:db8:1::242:ac11:2) 56 data bytes
64 bytes from 2001:db8:1::242:ac11:2: icmp_seq=1 ttl=64 time=0.095 ms
```
Container should be able to ping the other container.

**Comment by amshinde** [comment]
@GabyCT Do you think you can take a look at this.
We also need to add a test for kubernetes, have to test that on my side. Will open a separate issue for that.

**Comment by GabyCT** [comment]
@amshinde yes, I will do this
