### ISSUE TITLE
CRI-O tests: outdated conmon version

### ISSUE THREAD

**Issue by haircommander** [kata-containers/tests#2271]
# Description of problem
in CRI-O, our kata integration tests have been failing in release-1.16 for a while. it turns out we merged a commit that broke backwards compatibility with conmon, and the conmon version used in the kata test is now out of date.

# Expected result
kata tests to pass

# Actual result
```
12:21:05 # conmon: option parsing failed: Unknown option --persist-dir
```

I would submit a PR, but it seems the kata version is managed as an [external version](https://github.com/kata-containers/tests/blob/76c759651a21b1626c5f3d3c1cb789f608e7daf2/.ci/install_crio.sh#L35). Where is this variable defined and can we update it to (at minimum) 2.0.7?

**Comment by haircommander** [comment]
@chavafg PTAL

**Comment by chavafg** [comment]
We manage the conmon version here: https://github.com/kata-containers/runtime/blob/master/versions.yaml#L183-L186

we recently got issues with latest version. so we currently stick to v2.0.1. I am not sure if Kata needs to add/change something to support latest version.
/cc @amshinde 

For reference:
https://github.com/kata-containers/tests/commit/b145f4ca07e4acdaa8d6d308a942ed05f9181f2e#diff-bf1835c7dd8eb40baff2fda278134cc2

https://github.com/kata-containers/runtime/issues/2352#issuecomment-565642204

**Comment by haircommander** [comment]
okay, I'm going to open a PR to update the version, and see if I can look into the breakages
