### ISSUE TITLE
ci: new `yq` version is not expanding default values

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#2274]
# Description of problem

Using`yq` 2.4.1:
```
$ yq r runtime/versions.yaml 'assets.initrd.architecture.x86_64.name'
alpine
```

Using`yq` 3.0.1:
```
$ yq r runtime/versions.yaml 'assets.initrd.architecture.x86_64.name'
*default-initrd-name
```

**Comment by jodh-intel** [comment]
I've raised https://github.com/mikefarah/yq/issues/340. Note that adding `-j` works around the issue (albeit resulting in JSON output ;)
