### ISSUE TITLE
CI: do not checkout to crio version from versions.yaml when running jobs from cri-o repo

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#230]
Right now, the CI scripts install the cri-o version from versions.yaml [1]. But now that we are adding a CI job to check the PRs opened on `kubernetes-incubator/cri-o` [2] repository, we need to check if the change being tested is from the cri-o repository, and if so, do not use `versions.yaml` but instead checkout to the commit ID of the PR. 

[1] https://github.com/kata-containers/runtime/blob/master/versions.yaml
[2] https://github.com/kubernetes-incubator/cri-o

**Comment by sboeuf** [comment]
Yes, we definitely need to be able to test something else from the crio jenkins job. And priority is master I'd say.
