### ISSUE TITLE
metrics: density: store finer details into JSON results

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#232]
As per the `FIXME` comment in #217 in file metrics/density/docker_memory_usage.sh, we currently collect and process a bunch of data (such as PSS data) for a number of containers, but only presently store the result of that processing in the JSON file.
It would be great from a long term validation/repeatability/preservation pov if we stored the raw data in the JSON as well.

**Comment by GabyCT** [comment]
@grahamwhaley, I see from the `docker_memory_usage.sh`, you are measuring PSS with `smem`, when you say that you want to save the stored raw data you mean to save all the results that `smem` generates not only PSS but RSS etc?

**Comment by grahamwhaley** [comment]
Hiya.
 The initial idea was we should store the PSS for each individual container, and not just the average of them all. the [get_pss_memory()](https://github.com/kata-containers/tests/blob/master/metrics/density/docker_memory_usage.sh#L93) you see does a bunch of math and returns the average, but throws the raw data away. I think we should store the raw data as well, why not, seeing as we have it.

And then, yes, if you are there fixing that, we should probably store all of PSS/RSS/VSS, and not just PSS like we do at present.

I'll leave it to you to decide if we still store the averages as well as the individual container data. If you do drop the averages, you may have to fix some other bits in the repo (possibly reportgen if that is using this test, and maybe the metrics CI - but, that may need me to modify the config files on the jenkins slave machines). Hmm, that might get complex actually - so, if it is not too hard, I vote we leave the averages in there as well as the raw data.
thx for looking at this.

**Comment by GabyCT** [comment]
Related https://github.com/kata-containers/tests/pull/687

**Comment by GabyCT** [comment]
Closing this issue as #687 is already merged
