### ISSUE TITLE
ci: static markdown doc check is checking vendor files

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#2338]
# Description of problem

Occasionally we see the CI static check markdown doc checker kicking out an error on an un-referenced markdown file, that is actually in the `vendor` tree. The code looks like it filters out `vendor` files, but obviously somewhere, somehow, it is failing.

```
INFO[0000] Checking file                                 commit=4dc5d23e8a997dc4a3aef2299b765be5bd13048e file=vendor/github.com/docker/docker/project/CONTRIBUTORS.md name=kata-check-markdown pid=25802 source=check-markdown version=0.0.1
FATA[0000] open vendor/github.com/docker/docker/project/CONTRIBUTORS.md: no such file or directory  commit=4dc5d23e8a997dc4a3aef2299b765be5bd13048e name=kata-check-markdown pid=25802 source=check-markdown version=0.0.1
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

# Expected result

`vendor` files should noit be checked!

**Comment by chavafg** [comment]
reopening as it seems that this is still happening

**Comment by awprice** [comment]
Thanks for investigating @chavafg I noticed this still happening too.

**Comment by grahamwhaley** [comment]
If you get stuck, and we have a PR where we can see it happening, post a link and I can try to re-produce and have another look...
