### ISSUE TITLE
.ci/ci-fast-return.shCI not working properly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#2365]
From https://github.com/kata-containers/tests/pull/2335, we can see that the fastpast script did not run.

The error that we have is
```
12:15:38 INFO: Checking for any changed files that will prevent CI fastpath return
12:15:38 INFO: Skip patterns: [-e ^CODEOWNERS$ -e ^LICENSE$ -e .*\.md -e *\.travis\.yml -e .*\.txt -e ^VERSION$ ]
12:15:38 INFO: Check patterns: []
12:15:38 INFO: No force CI check patterns
12:15:38 INFO: No force check files found
12:15:38 INFO: No files to check in CI.
12:15:38 INFO: Fastpath short circuit returning from CI.
12:15:38 INFO: Files skipped are:
12:15:38 
12:15:38 cmd/check-spelling/README.md
12:15:38 
12:15:38 INFO: Checking labels for PR kata-containers/tests/2335
12:15:38 debconf: unable to initialize frontend: Dialog
12:15:38 debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
12:15:38 debconf: falling back to frontend: Readline
12:15:38 debconf: unable to initialize frontend: Readline
12:15:38 debconf: (This frontend requires a controlling tty.)
12:15:38 debconf: falling back to frontend: Teletype
12:15:38 dpkg-preconfigure: unable to re-open stdin: 
12:15:41 INFO: No forcing label found
12:15:41 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/.ci/ci-fast-return.sh: line 447: exit: Reading: numeric argument required
```
See http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/1393/consoleFull

/cc @grahamwhaley

**Comment by grahamwhaley** [comment]
hmm, that looks like a dpkg problem, and not specifically to do with the fast path... looks like one of those cases where something is requiring a real tty, and we don't have those on the CI machines...
@chavafg - can you think of anything we landed recently that might have added such a dep?
I'll have a stare at the scripts around where the lable checks are performed to see if there is anything obvious...

**Comment by grahamwhaley** [comment]
@GabyCT - I'm not sure that it actually errored. I think that is just `apt-get` whining that it does not have an interactive terminal... and then I suspect it did install the packages, and did run the check OK.
The root place of interest is the [call to `install_jq`](https://github.com/kata-containers/tests/blob/master/.ci/ci-fast-return.sh#L262), which ends up doing a
 [`sudo apt-get -y install jq`](https://github.com/kata-containers/tests/blob/master/.ci/ci-fast-return.sh#L87). It is that `apt-get` that is complaining.

What we probably should do is set `export DEBIAN_FRONTEND=noninteractive` [like we do in the debian setup script](https://github.com/kata-containers/tests/blob/master/.ci/setup_env_debian.sh#L13). The questions then are:

- why did this setting not already propagate into the fast path check
- where is the best place to globally set this for the Debian based CIs in general.

I think it's a slightly bigger thing to consider than just the fast-path script iyswim.

/cc @chavafg

**Comment by grahamwhaley** [comment]
but, good spot in the logs btw ;-)

**Comment by chavafg** [comment]
> What we probably should do is set export DEBIAN_FRONTEND=noninteractive like we do in the debian setup script.

agree. 

> where is the best place to globally set this for the Debian based CIs in general.

We have two options: 
- best one I think is to set it on the `.ci/jenkins_job_build.sh` for debian/ubuntu distros or
- we can set it on each debian/ubuntu job, which will require more work. 

anyway the script in addition failed on:
```
.ci/ci-fast-return.sh: line 447: exit: Reading: numeric argument required
```

which I think is because `check_force_label` function is now returning a non-numeric (contaminated) value.

**Comment by grahamwhaley** [comment]
> anyway the script in addition failed on:
> 
> ```
> .ci/ci-fast-return.sh: line 447: exit: Reading: numeric argument required
> ```
> 
> which I think is because `check_force_label` function is now returning a non-numeric (contaminated) value.

Ah, right - I'd missed that. Looking at the code, given how `main()` relies on the answer from `check_force_label()` to be numeric, and that failed due to what is a catastrophic failure, I'm not sure there is a nice fix here. If we re-directed the output from `install_jq` to `/dev/null` for instance, then we would have had a silent fail maybe, which is probably worse.

So, I'm not sure there is anything to really fix here, is there?

**Comment by jodh-intel** [comment]
Anyone interested in some shell + YAML coding / debugging?
