### ISSUE TITLE
AArch64: enable FC tests on ARM CI

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#2375]
Hi~ guys
I've been trying to enable FC tests on ARM CI lately. 
All tests work well in my local machine and I may need to do a few twist on upstream existing configuration. 
@grahamwhaley @chavafg  
Could you please teach me where to build a new jenkins job for running fc tests on ARM CI? just like the one `kata-containers-tests-ubuntu-1804-PR-firecracker` for `x86_64`😊

**Comment by grahamwhaley** [comment]
Sure @Pennyzct . There are some old-ish docs over at https://github.com/kata-containers/ci/blob/master/Jenkins_setup.md that give an overview.
Fundamentally, you will want to go to the Kata Jenkins master UI,log in, and presumin gyou have enough rights, make a new 'freestyle project' (iirc), and copy an existing similar job as it's template ( such as http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/).

Then you tweak that new job. In your case, setting the appropriate env settings to use FC rather than QEMU - I would check the x86 FC job to find what those settings are. @chavafg might have better/more guidance...

**Comment by chavafg** [comment]
Hi @Pennyzct, as @grahamwhaley commented, the easiest would be to copy the existing ARM job to a new one. You should have enough perms to do that. 
On the main jenkins page, go to `New Item`, then add a name for your new job, then on the `Copy from` textbox write the name of the existing job (e.g: `kata-containers-tests-ARM-18.04-PR`). 
I think adding a job for the tests repo first and once we know it is stable, we can add more jobs for the other repos. 

The specific env vars for FC are:
```
export KATA_HYPERVISOR="firecracker"
export CI_JOB="FIRECRACKER"
```

**Comment by Pennyzct** [comment]
Hi~ @grahamwhaley @chavafg 
Sorry for the delayed response. thanks for the detailed instruction!!!
I've set up the jenkins job [kata-containers-tests-ARM-18.04-PR-firecracker](http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR-firecracker/) and raised a PR to do the trial~~~

**Comment by Pennyzct** [comment]
Hi~ guys @grahamwhaley @chavafg 
Sorry to bother~ could you please tell me how to add this jenkins job [kata-containers-tests-ARM-18.04-PR-firecracker](http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR-firecracker/) to tags /test and /test-fc. Then we could use /test and /test-fc to trigger them~~~

**Comment by grahamwhaley** [comment]
Hi @Pennyzct - sure - it's in the job config dialog, under the 'advanced' button of the 'build triggers'. You will find a dialog 'trigger phrase' - that job current has `.*(\n|^|\s)/(re)?test(-arm)?(\n|$|\s)+.*` in that box, probably inherited when you did the job clone. So, it looks to me that it is already set up with the phrase.....
What happens right now if we issue a /test-arm on a PR on the tests repo ... does the new job appear?

Just for ref as well, ultimately the trigger phrase gets stored in the job xml, which we back up into the ci repo, like [here](https://github.com/kata-containers/ci/blob/master/jenkins/jobs/kata-containers-proxy-ARM-18.04-PR/config.xml#L74)

**Comment by grahamwhaley** [comment]
Oh, I see - you want to add 'fc' as well - heh, you'll have to figure out the correct regex. ...

**Comment by chavafg** [comment]
`.*(\n|^|\s)/(re)?test(-fc)?(\n|$|\s)+.*` should work. 

@Pennyzct just changed it and tried it. 

I also changed the `Commit Status Context` Label under `Trigger Setup` to: _jenkins-ci-ARM-ubuntu-18-04-firecracker_. 
This is the text shown in the github build checks. It was overwriting the _jenkins-ci-ARM-ubuntu-18-04_ build.

**Comment by grahamwhaley** [comment]
Good catch on the trigger phrase over-write @chavafg - we forgot to mention, and I forgot to check, that....

**Comment by Pennyzct** [comment]
> I also changed the Commit Status Context Label under Trigger Setup to: jenkins-ci-ARM-ubuntu-18-04-firecracker.
> This is the text shown in the github build checks. It was overwriting the jenkins-ci-ARM-ubuntu-18-04 build.

I was going to ask you guys how to give this new job a new name~~~ thanks thousand times. ;)
