### ISSUE TITLE
jenkins-ci-ubuntu-16-04 failure

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#238]
Saw at http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-ubuntu-16-04-PR/241/

Looks like something with pip missing resource:

>HTTP error 404 while getting https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl#sha256=74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd (from https://pypi.org/simple/jinja2/)
> Could not install requirement Jinja2>=2.4 from https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl#sha256=74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd (from flask->-r requirements.txt (line 5)) because of error 404 Client Error: Not Found for url: https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
> Could not install requirement Jinja2>=2.4 from https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl#sha256=74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd (from flask->-r requirements.txt (line 5)) because of HTTP error 404 Client Error: Not Found for url: https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl for URL https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl#sha256=74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd (from https://pypi.org/simple/jinja2/)

**Comment by GabyCT** [comment]
Closing this issue as it is not seen anymore in the CI http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-16-04-PR/
