### ISSUE TITLE
ci: clh: List of skipped integration tests for both docker and k8s

### ISSUE THREAD

**Issue by likebreath** [kata-containers/tests#2399]
This issue tracks the integration tests that are being skipped in Kata's CI with cloud-hypervisor (`CLH`). We plan to bring them back as many as possible, so that we have comparable confidence when using `CLH` and `QEMU` in Kata.

* Skipped integration tests on Docker (based on yaml file defined [here](https://github.com/kata-containers/tests/blob/master/.ci/hypervisors/clh/configuration_clh.yaml)):

Test keyword                             | Status                                                                                                               
-----------------------------------|----------------                                                                                                        
`check yum update` | Work-in-progress (#2418 #2008)

* All integration Tests on k8s (based on script [here](https://github.com/kata-containers/tests/blob/master/integration/kubernetes/run_kubernetes_tests.sh#L76-L77)) are enabled and passing (the same as qemu).

- [Skipped test for end-to-end Kubernetes testing](https://github.com/kata-containers/tests/issues/2572)

| Test regex 	| Status 	|
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|--------	|
| [Daemon set \[Serial\] should rollback without unnecessary restart 	|  	|
| [sig-storage\] Secrets optional updates should be reflected in volume \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-storage\] Projected secret optional updates should be reflected in volume \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-storage\] Projected downwardAPI should update labels on modification \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-scheduling\] SchedulerPredicates \[Serial\] validates that there exists conflict between pods with same hostPort and protocol but one using 0.0.0.0 hostIP \[Conformance\] 	|  	|
| [sig-storage\] Projected downwardAPI should update annotations on modification \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-storage\] Projected configMap updates should be reflected in volume \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-storage\] Downward API volume should update labels on modification \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-storage\] Projected configMap optional updates should be reflected in volume \[NodeConformance\] \[Conformance\ 	|  	|
| [sig-storage\] ConfigMap optional updates should be reflected in volume \[NodeConformance\] \[Conformance\] 	|  	|
| [sig-storage\] ConfigMap updates should be reflected in volume \[NodeConformance\] \[Conformance\] 	|  	|

- containerd tests:

https://github.com/kata-containers/tests/issues/2329

**Comment by likebreath** [comment]
With the PR #2363 being merged, we are passing `104/250` docker tests in the CI now (increased from `53/250`).

**Comment by jcvenegas** [comment]
@amshinde  could you give us some priority for `k8s-sysctls.bats`  it is skip today

**Comment by amshinde** [comment]
@jcvenegas What is the reason for skipping this today..is it not passing? This is a basic test that should pass and is more of a agent functionality, should not have any dependence on the hypervisor used.

**Comment by likebreath** [comment]
Let me try the all the k8s tests locally. Any pointers on how to run them on my own dev machine?
@amshinde @jcvenegas @GabyCT

**Comment by jcvenegas** [comment]
@amshinde  I dont have a cause, it was skip as part of the intial CI enabling, @likebreath thanks you should be able to get it running if you export variables from https://github.com/kata-containers/tests/issues/2399#issuecomment-606166061 and then run `./ci/setup.sh` and the `make kuberentes`

**Comment by likebreath** [comment]
With PR #2412 being merged, we are passing `228/250` docker tests in the CI now, and most of the rest are working-in-progress.

**Comment by likebreath** [comment]
@jcvenegas Thanks for enabling the `memory hotplug` tests and debugging the `package manager` tests. With that we have 230/250 docker tests running and passing in the CI (log [here](http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/166/consoleFull)).

One observation: Before PR #2429 on enabling `package manager` tests, we had `232/250` (two more) tests passing (CI log [here](http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/163/console)). Any thoughts about it?

**Comment by jcvenegas** [comment]
@likebreath thanks for spot that I can take a look
