### ISSUE TITLE
Random failures on clh CPU test

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#2416]
I've seen some random failures at the clh CI
```
12:39:57 • Failure [9.004 seconds]
12:39:57 Update CPU constraints
12:39:57 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:390
12:39:57   Update CPU set
12:39:57   /tmp/jenkins/workspace/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
12:39:57     cpuset should be equal to 0 [It]
12:39:57     /tmp/jenkins/workspace/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
12:39:57 
12:39:57     Expected
12:39:57         <int>: 125
12:39:57     to be zero-valued
12:39:57 
12:39:57     /tmp/jenkins/workspace/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:449
12:39:57 ------------------------------
12:39:57 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
12:39:57 
12:39:57 Summarizing 1 Failure:
12:39:57 
12:39:57 [Fail] Update CPU constraints Update CPU set [It] cpuset should be equal to 0 
```
see http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-1804-PR-cloud-hypeprvisor/141/console
/cc @jcvenegas @likebreath

**Comment by likebreath** [comment]
This is a known issue that is being fixed by https://github.com/kata-containers/runtime/pull/2552.  @jcvenegas and I didn’t expect that PR took this much time to be merged. Sorry for the confusion.

**Comment by likebreath** [comment]
@GabyCT The pending PR  https://github.com/kata-containers/runtime/pull/2552 has been merged, and the error should be fixed. I was trying to restart the CLH CI where you got this specific failure, but it looks like your PR https://github.com/kata-containers/tests/pull/2408 was merged. 

Please let me know if you are still experiencing failures on CLH CI. Thanks!

**Comment by GabyCT** [comment]
Thanks @likebreath , I will close this issue
