### ISSUE TITLE
metrics: scaling: Parallel launch of Kata's needs to be analysed

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#2440]
Launching multiple Kata pods in parallel (say via a deployment launch, like in the test at https://github.com/clearlinux/cloud-native-setup/blob/master/metrics/scaling/k8s_parallel.sh) does not appear to scale well.

Results are likely hardware dependent, specifically I would guess related to the number of processors in the system.

My theory is that launching pods in parallel makes the VMs 'race', and take long enough for k8s to time out and and kill them - at which point the deployment may try to re-launch them, and we end up in a death roll of kill/retry...

There are a couple of tracks we can follow here and investigate:

- Should the k8s timeouts be settable/scalable with the runtime being used?
- Are there improvements we could make in the kernel (KVM) and/or QEMU to improve the parallel VM launch ability (generic Linux item)?
- Could/can/should Kata time out and die more gracefully?

The issue needs some more digging into and further analysis. The k8s scaling code over at https://github.com/clearlinux/cloud-native-setup/tree/master/metrics may be of use as they are set up to do parallel launches via deployments etc. The [metrics code in this repo](https://github.com/kata-containers/tests/blob/master/metrics/) have little knowledge of how to run or measure parallel launches - there is just a fraction of code in the [fast footprint test](https://github.com/kata-containers/tests/blob/master/metrics/density/fast_footprint.sh#L42).

**Comment by GabyCT** [comment]
@grahamwhaley , I ran the ./k8s_scale_parallel.sh and I think that the issue that you raised is the thing that I am seeing (I just want to confirm). The script runs however, when it is testing it stucks and does not finishes completely. For me it got stuck by testing parallel replicas 9 of 20 and what I see is that it gets stuck by performing the cleaning up as I got an error of
```
kllierror: timed out waiting for the condition
INFO: Cleaning up
deployment.apps "busybox" deleted                                              
INFO: Not all pods died
cleaning up kubectl proxy
```

**Comment by grahamwhaley** [comment]
correct, that is the problem iirc. And if you plot (preferably via the report tool) the graph, I think you find the boot time is pretty non-linear with the parallelism.
It may be instructive to also look at how other runtimes appear, for reference.

**Comment by GabyCT** [comment]
@grahamwhaley is there a way to run them with runc for example, I tried to run them with RUNTIME=runc but it did not work, and I only see kata, kata-qemu, and kata-fc

**Comment by grahamwhaley** [comment]
Yes. If you [look at the code](https://github.com/clearlinux/cloud-native-setup/blob/master/metrics/scaling/k8s_parallel.sh#L55-L60), you will find snippets such as:

```bash
	local runtime_command
	if [ -n "$RUNTIME" ]; then
			runtime_command="s|@RUNTIMECLASS@|${RUNTIME}|g"
	else
			runtime_command="/@RUNTIMECLASS@/d"
	fi
```

If you do not set `RUNTIME`, then the tests will delete the `RuntimeClass` from the yaml/json deployment files, and the tests will run with whatever the default runtime is on the node(s) - which, most commonly, is `runc`.

**Comment by GabyCT** [comment]
@grahamwhaley I ran this test with runc and I see that all the test was finished completely without hanging so it seems a kata issue

**Comment by grahamwhaley** [comment]
ack - Kata parallel launch scales differently than `runc`, and needs some analysis as to:
- why?
- Is it a real issue?

**Comment by GabyCT** [comment]
@grahamwhaley , I ran again the test on the same hardware and I see that the test finishes completely, so maybe this is a random issue
![image](https://user-images.githubusercontent.com/20359065/82569974-94854780-9b46-11ea-91c9-5b6047458e5a.png)

These results were generated with `kata-qemu` , my only question is in the delete graphs what does it mean the downfall that we see? thanks

**Comment by grahamwhaley** [comment]
@GabyCT - indeed, that looks much more linear. So linear in fact I feel I should say check that it was using `kata-qemu` - you might be able to check that in the json results files for instance. If something looks to good to be true, then sometimes it is ;-)

As to why do we get the up/down/up blips in the delete times - I don't know. It might be something to do with internal timings of k8s for instance. iirc, we [use a deployment and measure the time it takes](https://github.com/clearlinux/cloud-native-setup/blob/master/metrics/scaling/k8s_parallel.sh#L202-L205) [for the list of pods to be 0](https://github.com/clearlinux/cloud-native-setup/blob/master/metrics/scaling/k8s_parallel.sh#L34) - because I think k8s does not provide a convenient way to wait for a deployment destroy to complete. So, I don't know, but that is the sort of anomaly that is 'interesting' - and you should check if that is also visible for other runtimes, or just `kata-qemu` for instance.

**Comment by GabyCT** [comment]
@grahamwhaley , yes I reviewed the json results from `k8s-parallel.json` and it seems that is using `kata-qemu`
```
"katacontainers.io/kata-runtime": "true",
"runtime": "kata-qemu",
```

**Comment by grahamwhaley** [comment]
OK, thanks @GabyCT . I guess we should maybe consider what changed - I'm going to guess you ran this test on a different system than from the previous test where you did see the slowdown?
If it is a much bigger system, maybe try changing the maximum number of pods from 20 to say 100 (that might be a bit optimistic), and also comparing how the `kata-qemu` results look vs other runtimes - that might still give some insight to scalability etc.

**Comment by GabyCT** [comment]
@grahamwhaley no I used the same vm, it is a clearlinux vm so maybe it changed between the versions, now as I far I understand `kata-qemu` and `kata` are the same so maybe I can take a look with `kata-fc` to see how it behaves
