### ISSUE TITLE
metrics: scaling: Kata 'delete' times feel 'too fast'....

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#2441]
Running k8s scaling tests from [this k8s scaling test code](https://github.com/clearlinux/cloud-native-setup/blob/master/metrics/scaling/k8s_scale.sh), it looks like the kata pod/deployment deletion times are somewhat 'faster' than one might expect.

My suspicion is maybe Kata is reporting the pod deletion has completed before everything has actually been cleaned up. We should understand if this is true, and if we are OK with that (that is, is it safe or not). We need to also check this does not interfere with k8s metrics and node load balancing.

**Comment by GabyCT** [comment]
@grahamwhaley what do you mean with is faster than one expect? I ran the k8s test and I got at the report something like this
![image](https://user-images.githubusercontent.com/20359065/81206380-a507c080-8f91-11ea-8617-8731e0031766.png)
![image](https://user-images.githubusercontent.com/20359065/81206400-ac2ece80-8f91-11ea-8ed8-e75d6d14d77e.png)


![image](https://user-images.githubusercontent.com/20359065/81206450-c10b6200-8f91-11ea-85de-415d676451fa.png)

![image](https://user-images.githubusercontent.com/20359065/81206519-d7b1b900-8f91-11ea-89d9-b32f83e6e3d5.png)

![image](https://user-images.githubusercontent.com/20359065/81206570-eb5d1f80-8f91-11ea-9c34-463615bc2e0f.png)
![image](https://user-images.githubusercontent.com/20359065/81206580-f2842d80-8f91-11ea-84bb-9b8ab1ae4ed7.png)


![image](https://user-images.githubusercontent.com/20359065/81206623-016ae000-8f92-11ea-85a6-5895afb0123e.png)
![image](https://user-images.githubusercontent.com/20359065/81206647-092a8480-8f92-11ea-8588-8e2bcd3cd329.png)

**Comment by GabyCT** [comment]
@grahamwhaley , I ran again the test and I see that at the second results we got negative results (this is looked at the json files)
```
                        "memory": {
                                "consumed": {
                                        "Result": -548228,
                                        "Units": "Kb"
                                },
                                "pods_per_gb": {
                                        "Result": -28.170000
                                }
                        }
```
The negative results I do not know if it has an impact that we got something like this
![image](https://user-images.githubusercontent.com/20359065/81215828-89a3b200-8f9f-11ea-8dce-5b8ca3a7a111.png)

![image](https://user-images.githubusercontent.com/20359065/81215855-92948380-8f9f-11ea-88e9-be0f208c4e0d.png)

Now I see a lot of negative results
```
        "launched_pods": [
                                                {
                                        "pod_name": "busybox-57dd88fb54-75mnv",
                                        "node": "gabymetrics"
                                }
        ],
                        "memory": {
                                "consumed": {
                                        "Result": -2753124,
                                        "Units": "Kb"
                                },
                                "pods_per_gb": {
                                        "Result": -537.710000
                                }
                        }
```
Are those negative results related with kata deleting too fast? or why we have them?

**Comment by grahamwhaley** [comment]
I think there are two separate things here - let's do them one at a time....

1) This issue is to do with the time it takes to delete a container. The code that generates the data is at https://github.com/clearlinux/cloud-native-setup/blob/master/metrics/scaling/k8s_scale_rapid.sh#L172-L178 I think, and looks like:

    ```bash
	info "Delete Took $total_milliseconds ms ($end_time - $start_time)"

	local json="$(cat << EOF
	"Delete": {
		"Result": ${total_milliseconds},
		"Units" : "ms"
	}
    ```
    Having a quick look at the report code, I don't think these results are processed into the report/graphs at all - they are results you'll have to either examine directly in the results json files, or add to the reports.
    The fundamental thing that leapt out iirc was that it looked quicker to delete a kata container than a `runc` one, which just doesn't feel right or is not easy to explain, so needs more investigation.

2) On the memory consumption and the negative values. Looking at your graphs, it looks like your system ran out of memory after 12 pods or so - if you look at the graph, you can see a nice linear decline in available memory until you pretty much hit 0 available, and then the line bounces around near 0 - which may be the system killing and re-spawning pods due to resource starvation. Now, that is *not* what this Issue is about - so, if you are looking at that, we should do it on a different Issue. I seem to remember we did have quite a dive into 'how to measure system memory' at the time when we wrote that test - and, it's not quite trivial. In this specific case, I think you need a system with more memory available to run a 20 pod test, if that is your goal.
