### ISSUE TITLE
random failure in entropy test in sles

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#2493]
I have seen random failures in the entropy test in sles http://jenkins.katacontainers.io/job/kata-containers-runtime-sles-15-PR/347/console
```
bats integration/entropy/entropy_time.bats
1..1
not ok 1 measured time for /dev/random
# (in test file integration/entropy/entropy_time.bats, line 32)
#   `[ "$measured_time" -le "$expected_time" ]' failed
# 
# 
make: *** [Makefile:283: entropy] Error 1
Failed at 86: sudo -E PATH="$PATH" bash -c "make test"
```
This is related with the test https://github.com/kata-containers/tests/blob/981e49f315d4c296af3c2a33aeb29ca1b11f809e/integration/entropy/entropy_time.bats#L21 so I am not quite sure if this test should be skipped or what is the best approach to this? any ideas @jcvenegas @rhafer

**Comment by grahamwhaley** [comment]
I see we have [`haveged`](https://github.com/kata-containers/tests/blob/master/.ci/setup_env_sles.sh#L58) in the sles package install list - that should 'take care' of the entropy...

So, something I pointed out iirc when we wrote that test, which is basically a failing of BATS I think, is I don't think it shows us the values when the test fails, which is less than useful :-(... it would be good if we could see the actual results - did we fail with 999<1000 or 0<1000 for instance...

**Comment by GabyCT** [comment]
I tried to reproduce this issue locally but I could not do it
