### ISSUE TITLE
Not stable CI setup using chronic

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2494]
# Description of problem

Recently CI setup jobs has started to fail randomly running with the following log data:
```
00:16:54.724 Disable systemd-journald rate limit
00:16:55.026 Drop caches
00:17:04.673 /tmp/jenkins/workspace/kata-containers-runtime-clh-docker-ubuntu-master/go/src/github.com/kata-containers/runtime
00:17:04.673 Setup virtcontainers environment
00:17:04.705 .ci/setup.sh: /usr/bin/chronic: /usr/bin/perl: bad interpreter: Bad message
00:17:04.870 Build step 'Execute shell' marked build as failure
00:17:12.146 Performing Post build task...
00:17:12.146 Match found for :.* : True
00:17:12.146 Logical operation result is TRUE
00:17:12.146 Running script  : #!/bin/bash
```

# Expected result

Setup not fails randomly

**Comment by GabyCT** [comment]
@jcvenegas I tried to reproduce this issue locally by setting up ubuntu for clh and ubuntu ci, however, I did not face this issue

**Comment by jcvenegas** [comment]
@GabyCT  thanks for the quick check seems that is random let's see how reproducible in CI.dash

We have this mini dashboard to keep tracking how stable it is.

**Comment by grahamwhaley** [comment]
I re-visited my similar local ClearLinux issue, but it was subtly different, and cured with an extra bundle install:

```
Can't locate IPC/Run.pm in @INC (you may need to install the IPC::Run module) (@INC contains: /usr/local/lib/perl5/site_perl/5.30.2/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.30.2 /usr/lib/perl5/vendor_perl/5.30.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.30.2 /usr/lib/perl5/5.30.2/x86_64-linux-thread-multi /usr/lib/perl5/5.30.2 /usr/local/lib/perl5/site_perl /usr/lib/perl5/vendor_perl) at /usr/bin/chronic line 57.
BEGIN failed--compilation aborted at /usr/bin/chronic line 57.

$ sudo swupd bundle-add perl-extras
```

I had a read through the logs on that failed clh Jenkins run, and nothing else related leapt out at me. Yeah, possibly spurious. Maybe we should re-start that failed clh Jenkins job again and see if it reproducible on that PR (which does seem wholly unrelated to the issue).
```

**Comment by chavafg** [comment]
I have just seen this on other jobs, it also happens when running `kata-runtime kata-env`.
```
15:02:43 /usr/local/bin/kata-runtime
15:02:43 Logging kata-env information:
15:02:43 .ci/jenkins_job_build.sh: line 188: /usr/local/bin/kata-runtime: Bad message
15:02:43 Build step 'Execute shell' marked build as failure
```

btw, I have just seen this issue in jobs that run under ubuntu 18.04. I think they recently changed their image as they now are using kernel 5.3. At the beginning of last week they were still using 5.0 iirc. So maybe this change could be related, but as @GabyCT says, I cannot reproduce locally.

The other guilty could be jenkins? I saw that there was an update available, so ran the update... Let's see if that helps.

**Comment by GabyCT** [comment]
@jcvenegas I modify the version of the image that we were using in ubuntu that instead of using the latest (sku) uses another one and it seems that the errors are gone

**Comment by jcvenegas** [comment]
Let me try

**Comment by jcvenegas** [comment]
I see that two PRs that were failing a lot now passed, I will close and re-open if needed.
@GabyCT  thanks for your help  :)

**Comment by jcvenegas** [comment]
@GabyCT  do you have the sku ID that now it is used would be nice to document it there for any reference in the future. Also that new sku has an old kernel ? I ask because current effort from @devimc  to move to qemu  5.0

**Comment by GabyCT** [comment]
@jcvenegas the version that I am using is 18.04.202001291, instead of latest, and I do not know if it has the latest kernel as I can't run a particular version in the azure web ui
