### ISSUE TITLE
Failures on libpod tests | podman run - uidmapping has no /sys/kernel mounts

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#2502]
This is one of the issues raised due to the failures running libpod "system tests" using kata as runtime.

This specific test is part of https://github.com/containers/libpod/blob/master/test/system/030-run.bats and fails due to:
```
 ✗ podman run - uidmapping has no /sys/kernel mounts
   (from function `die' in file /usr/share/podman/test/system/helpers.bash, line 274,
    from function `run_podman' in file /usr/share/podman/test/system/helpers.bash, line 164,
    in test file /usr/share/podman/test/system/030-run.bats, line 67)
     `run_podman run --rm --uidmap 0:100:10000 $IMAGE mount' failed with status 126
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime rm --all --force
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   quay.io/libpod/alpine_labels:latest   4fab981df737
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime run --rm --uidmap 0:100:10000 quay.io/libpod/alpine_labels:latest mount
   Error: rpc error: code = Unknown desc = User namespaces enabled, but no user mapping found.: OCI runtime error
   [ rc=126 (** EXPECTED 0 **) ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: exit code is 126; expected 0
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime pod rm --all --force
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime rm --all --force
```

I understand the test is not part of the list of tests run (as in https://github.com/kata-containers/tests/blob/master/.ci/podman/configuration_podman.yaml), but there's also no mention about uidmapping limitations in the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md).

Note: Maybe this is not the best place for this issue, but I'd like to have it opened somwhere in order to either have documented what's the reason of the failure (if it's expected), or to have it investigated (in case it's not expected).

**Comment by c3d** [comment]
Probably a documentation problem, since I see no sensible way to do UID mapping in Kata.

**Comment by c3d** [comment]
Another option would be to do the UID remapping in `virtiofsd`.
