### ISSUE TITLE
Failures on libpod tests | podman container storage is not accessible by unprivileged users

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#2509]
This is one of the issues raised due to the failures running libpod "system tests" using kata as runtime.

This specific test is part of https://github.com/containers/libpod/blob/master/test/system/400-unprivileged-access.bats and fails due to:

```
 ✗ podman container storage is not accessible by unprivileged users
   (from function `die' in file /usr/share/podman/test/system/helpers.bash, line 274,
    from function `run_podman' in file /usr/share/podman/test/system/helpers.bash, line 164,
    in test file /usr/share/podman/test/system/400-unprivileged-access.bats, line 12)
     `run_podman run --name c_uidmap   --uidmap 0:10000:10000 $IMAGE true' failed with status 126
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime rm --all --force
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   quay.io/libpod/alpine_labels:latest   4fab981df737
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime run --name c_uidmap --uidmap 0:10000:10000 quay.io/libpod/alpine_labels:latest true
   Error: rpc error: code = Unknown desc = User namespaces enabled, but no user mapping found.: OCI runtime error
   [ rc=126 (** EXPECTED 0 **) ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: exit code is 126; expected 0
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime pod rm --all --force
   $ /usr/bin/podman --runtime=/usr/bin/kata-runtime rm --all --force
   4ca1691a4dd838c8af30f0c29002821c21ccececf3d394f3e5f21eb560026baf
```
I understand the test is not part of the list of tests run (as in https://github.com/kata-containers/tests/blob/master/.ci/podman/configuration_podman.yaml), but there's also no mention about user mappings limitations in the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)

Note: Maybe this is not the best place for this issue, but I'd like to have it opened somewhere in order to either have documented what's the reason of the failure (if it's expected), or to have it investigated (in case it's not expected).

**Comment by fidencio** [comment]
This one may just be duplicated of https://github.com/kata-containers/tests/issues/2502

**Comment by c3d** [comment]
Since this is a podman issue and podman is not supported with 2.0, flagging this as "area/podman" so that we keep track of it, but no plan to work on it in the short term.
