### ISSUE TITLE
stable-1.11: kata-env fails in CI wihtout any information

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2519]
# Description of problem

In runtime repository (seems that only in bump PR, it does not make sense :S ) the CI fails with the next trace.

```
00:24:18.617 Logging kata-env information:
00:24:19.181 Build step 'Execute shell' marked build as failure
00:24:26.260 Performing Post build task...
```

I have tried to debug by:
- Adding printfs to kata-env.
https://github.com/kata-containers/runtime/pull/2666 but is not reproducible
- Add strace 
https://github.com/kata-containers/tests/pull/2518
and do depends on PR that fails, but needs to be merged before because depends-on not work as jenkins script and seems that the one from runtime master is used
https://github.com/kata-containers/runtime/pull/2669
```
tests_repo="github.com/kata-containers/tests"
tests_repo_dir="${GOPATH}/src/${tests_repo}"
mkdir -p "${tests_repo_dir}"

git clone "https://${tests_repo}.git" "${tests_repo_dir}"
cd "${tests_repo_dir}"

.ci/jenkins_job_build.sh "github.com/kata-containers/runtime"
```

Aditional notes:
In the release process other jobs run for other repositories like : 
https://github.com/kata-containers/tests/pull/2514

Or even backports in runtime were merged before an none of them has show any error like that.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by GabyCT** [comment]
@jcvenegas , I think this was fixed, can we close this?

**Comment by jcvenegas** [comment]
yes!
