### ISSUE TITLE
Run e2e tests on openshift-ci

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#2527]
== The context and goal ==

The Openshift 4.x project provides an CI infra (openshift-ci) where integration tests can be executed in a fully operational cluster (api.ci.openshift.org). If a component wants to use the CI facilities it should be prepared and request to get onboard.

If kata-containers gets onboard then we could use openshift-ci for e2e integration tests. 

So this issue is created to track to work required and being done to get kata-containers onboard the openshift-ci.

== The openshift-ci onboard process ==
In a nutshell, to onboard a component on openshift-ci one need to:
  1. Configure the component repository to:
    1.1  Deliver webhooks events to the CI System
    1.2 Allow openshift-ci robot to interact in the PRs. This will make the robot to comment on PRs, do automatic merges, be triggered by commands...etc.
  2. Configure the ci-operator on openshift/release repository
    2.1 Create an entry for kata-containers on https://github.com/openshift/release/ci-operator that describes the CI pipeline. CI Jobs are automatically generated from the configuration. See more information at https://github.com/openshift/release/blob/master/README.md#ci-workflow-configuration

== What it need to change on kata-containers side? ==

The logic to install kata-containers in the openshift-ci  test cluster is:
 1. Build kata-containers components and install them under a well-known path (let's call it DESTDIR)
 2. Install the dependencies (QEMU, Kernel and Image) as well as configuration files in DESTDIR
 3. Update the `machine-os-content` container image with the files from DESTDIR. This image is used to build the test cluster nodes, i.e., it is how we can install kata-containers without using an operator/installer.  
 
So there are needed scripts and dockerfiles on the repositories to implement the above workflow.

To be confirmed: it needs test script(s) which should trigger the e2e and conformance tests.

== Required changes on openshift-ci ==
As pointed above, it needs to create the kata-containers configuration and jobs at openshift ci-operator. This work is being carried out on https://github.com/openshift/release/pull/9009

**Comment by GabyCT** [comment]
@wainersm please let me know if you need help as I am familiar with the CI of kata

**Comment by wainersm** [comment]
> @wainersm please let me know if you need help as I am familiar with the CI of kata

Hello @GabyCT , I will do, thanks for the offer.
