### ISSUE TITLE
add no systemd image installation helper

### ISSUE THREAD

**Issue by jongwu** [kata-containers/tests#2544]
**Which feature do you think can be improved?**

no systemd image installer

**How can it be improved?**

using no systemd image will largely improve performance for startup time of kata

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by grahamwhaley** [comment]
Can you give us a few more details @jongwu - I presume you mean remove systemd from the guest VM rootfs image? I'm not sure if we already have a build that does that when we use the kata agent as the init process. /cc @devimc @jcvenegas for input and thoughts.

**Comment by jongwu** [comment]
@grahamwhaley , yeah, as systemd consume lots of time when startup of kata and also systemd is not the essential part for kata, so if we remove systemd in kata image we can get lots of benefit. maybe it's time to think about it.
for now, alpine is the best choose for us to use as the no systemd image. I have tested it in Arm and get considerable performance improvement (bootup time) compared to ubuntu image. 
maybe we can try other distro like ubuntu which use systemd as its default init process, but I have not done that.

**Comment by devimc** [comment]
@jongwu what about just adding `init=/usr/bin/kata-agent` to `kernel_params` ? I think it's the same

**Comment by jongwu** [comment]
@devimc , I think there is a little different. take ubuntu as an example, if just set init=/usr/bin/kata-agent, it means that we must abandon all of the service offered by systemd and if we want to add those service in other ways, the image should be touched. so I think it will be better to offer a different image against those normal ones.
