### ISSUE TITLE
clh: Enable crio testing

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2546]
**Which feature do you think can be improved?**

Enable crio testing for cloud hypervisor. Now that block [device is enabled ](https://github.com/kata-containers/runtime/pull/2681) we can use crio testing to exercise that code path

**How can it be improved?**
- [ ] Add a new job for crio and k8s
 

 \cc @likebreath

**Comment by likebreath** [comment]
We decide to focus on enabling the cri-o in kata 2.0, where we will resume the work when the k8s+crio CI for qemu is stabilized in 2.0. Changing it medium-priority.
