### ISSUE TITLE
2.0: some k8s tests failing

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#2574]
# Description of problem
Trying to execute our k8s integration tests, I saw three tests failing:
```
"Copy file in a pod"
"Empty dir volumes"
"Check PID namespaces"
```

This was using rust agent and shimv2, so may be related to any of these functionalities.

Needs further investigation. 

## Known additional skipped k8s tests in `2.0-dev` branch
Both `containerd` and `CRI-O`
- [x] integration/kubernetes/k8s-copy-file.bats
- [x] integration/kubernetes/k8s-cpu-ns.bats
- [x] integration/kubernetes/k8s-empty-dirs.bats
- [x] integration/kubernetes/k8s-sysctls.bats

`CRI-O` specific:
- [x] integration/kubernetes/k8s-block-volume.bats
- [x] integration/kubernetes/k8s-liveness-probes.bats
- [x] integration/kubernetes/k8s-oom.bats
- [x] integration/kubernetes/nginx.bats

**Comment by bergwolf** [comment]
/cc @lifupan 
looks like some feature gaps between rust and go agent.

**Comment by GabyCT** [comment]
Currently the list of k8s tests that are failing are:
integration/kubernetes/k8s-qos-pods.bats
integration/kubernetes/k8s-hugepages.bats
integration/kubernetes/k8s-sysctls.bats
integration/kubernetes/k8s-memory.bats
integration/kubernetes/k8s-footloose.bats
integration/kubernetes/k8s-replication.bats
integration/kubernetes/k8s-port-forward.bats
integration/kubernetes/k8s-pid-ns.bats

**Comment by GabyCT** [comment]
here it is the list ^ of k8s tests that are failing @amshinde @jodh-intel @chavafg @bergwolf

**Comment by GabyCT** [comment]
@bergwolf most of them are not working with CRI-O, some of them with both, this is for kata 2.0. When you go to the tests, you will see in the skip if it is for CRI-O job or containerd job or if it is for both of them

**Comment by bergwolf** [comment]
Thanks @GabyCT ! I compared `master` and `2.0-dev` branch, and found these additional skipped tests in `2.0-dev`:

Both `containerd` and `CRI-O`
```
integration/kubernetes/k8s-copy-file.bats
integration/kubernetes/k8s-cpu-ns.bats
integration/kubernetes/k8s-empty-dirs.bats
integration/kubernetes/k8s-sysctls.bats
```

`CRI-O` specific:
```
integration/kubernetes/k8s-block-volume.bats
integration/kubernetes/k8s-liveness-probes.bats
integration/kubernetes/nginx.bats
```

Let's track them here to make sure they are fixed.

**Comment by bergwolf** [comment]
https://github.com/kata-containers/tests/pull/2866 should close two of the CRIO test failures (`integration/kubernetes/k8s-block-volume.bats` and `integration/kubernetes/nginx.bats`). Then we only have one k8s integration test failure left (`integration/kubernetes/k8s-liveness-probes.bats`).

**Comment by fidencio** [comment]
Now the only missing bit is `k8s-oom.bats`, which is being taken care of here:
- [ ] Backporting to release-1.18 CRI-O branch: https://github.com/cri-o/cri-o/pull/4356
- [ ] Bump CRI-O version on `kata-runtime/kata-runtime` to include the patch backported to the release-1.18: https://github.com/kata-containers/kata-containers/issues/1116
- [ ] Enabling `k8s-oom.bats` for CRI-O: https://github.com/kata-containers/tests/issues/2859 and https://github.com/kata-containers/tests/pull/3060

**Comment by fidencio** [comment]
We've know reached parity on k8s bats tests between CRI-O and containerd. \o/

I'm closing this issue.
