### ISSUE TITLE
CI on tests PRs

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#258]
The tests repo changes are special. Instead of just running its own tests, we should also make sure a new change does not break existing CIs. So CI in this repo should also pass CIs in other kata repos. The kata runtime repo is currently the most extensively changed one. We can start from there, by cloning the kata-runtime master, and running the kata-runtime CI with any change in the test repo's pull request.

**Comment by sboeuf** [comment]
@bergwolf the issue introduced by Go 1.10 was not introduced through this repo. If you didn't notice, there is the whole CI triggered everytime a PR is submitted to this repo, meaning any test change is being tested.

**Comment by bergwolf** [comment]
Fair enough. Looks like I was over worried. sorry for the noise ;)
