### ISSUE TITLE
CI logs flooded with  find: ‘/tmp/...: Permission denied when running teardown script

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#2580]
# Description of problem

Power and ARM job logs are flooded with:

```
14:21:17 find: ‘/tmp/cid346779482’: Permission denied
14:21:17 find: ‘/tmp/kata-shim-265456015’: Permission denied
14:21:17 find: ‘/tmp/tmpxu6jbkiv’: Permission denied
14:21:17 find: ‘/tmp/190704275’: Permission denied
14:21:17 find: ‘/tmp/tmp53gw_yu_’: Permission denied
14:21:17 find: ‘/tmp/tmp.bgqPtthpus’: Permission denied
14:21:17 find: ‘/tmp/cid991369235’: Permission denied
14:21:17 find: ‘/tmp/cid646937627’: Permission denied
14:21:17 find: ‘/tmp/215738445’: Permission denied
14:21:17 find: ‘/tmp/267160445’: Permission denied
14:21:17 find: ‘/tmp/tmp.FSyQMeWEDy’: Permission denied
14:21:17 find: ‘/tmp/tmp.hroSmKnUbe’: Permission denied
14:21:17 find: ‘/tmp/shimV2-551741441’: Permission denied
```
e.g.:

http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR/1555/console
http://jenkins.katacontainers.io/job/kata-containers-tests-Power8-ubuntu-18-04-PR-initrd/710/console

I think changes in https://github.com/kata-containers/tests/commit/9878c4c2fa75b19e107cef932896438d37667239 are the reason of this. 
/cc @jcvenegas 

I see some kata related directories under /tmp/ that we may want to delete after each execution.
/cc @Pennyzct @bpradipt

**Comment by Pennyzct** [comment]
Hi @chavafg 
thanks for the heads-up. ;) I've been trying to fix it on https://github.com/kata-containers/tests/pull/2585, Plz take a look.
