### ISSUE TITLE
arm ci is broken: Job for docker.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#2591]
Saw at http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/1673/console 

```
11:50:44 Install os-tree
11:50:46 Job for docker.service failed because the control process exited with error code.
11:50:46 See "systemctl status docker.service" and "journalctl -xe" for details.
11:50:46 Build step 'Execute shell' marked build as failure
```

**Comment by Pennyzct** [comment]
Hi @bergwolf @jodh-intel 
just logging into arm ci, found conflict and duplicate dockerd configuration, `/etc/systemd/system/docker.service.d/kata-containers.conf` and `/etc/docker/daemon.json`, not sure which pr created and used this `/etc/docker/daemon.json` to configure kata in docker. 😓
I'll manually delete it and see if the error is reproducible.

**Comment by jodh-intel** [comment]
Thanks @Pennyzct !

**Comment by bergwolf** [comment]
It's working now. Thanks @Pennyzct
