### ISSUE TITLE
ci/install_runtime: check if vhost_vsock module need to be loaded manually

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#2614]
On commit 907c0cd07ddd96 the `.ci/install_runtime.sh` was changed to support kata+vsock tests and then it does explicitly modprobe vhost_vsock. For QEMU I don't think it is needed, perhaps for Firecracker?

So if it is bogus code then can we remove it?

**Comment by chavafg** [comment]
Although kata also works without the vsock implementation using Qemu, we currently have a CI job where Kata runs along with [vsock+qemu](http://jenkins.katacontainers.io/job/kata-containers-runtime-vsocks-PR/). That is why we make use of the `USE_VSOCK`, which is set in the jenkins job configuration. And we load the vhost_vsock module as on the Azure images, it is not loaded by default.

**Comment by wainersm** [comment]
@chavafg Thanks for the explanation.

I will need to disable this module load on openshift-ci. Perhaps the same `OPENSHIFT_CI` environment variable as we talked in #2600 ?

**Comment by chavafg** [comment]
> I will need to disable this module load on openshift-ci. Perhaps the same OPENSHIFT_CI environment variable as we talked in #2600 ?

yeah, it could be an option, although the default value is `USE_VSOCK=no`, so it shouldn't be loaded as default.
