### ISSUE TITLE
Flaky tests  package manager update test check yum update [It] should not fail 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#264]
The following test is being failing randomly in the CI:

[Fail] package manager update test check yum update [It] should not fail 
/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:68

Ran 92 of 162 Specs in 573.015 seconds
FAIL! -- 91 Passed | 1 Failed | 0 Pending | 70 Skipped --- FAIL: TestIntegration (605.89s)
FAIL

**Comment by GabyCT** [comment]
@jcvenegas I will take a look in this
