### ISSUE TITLE
AArch64: Enable ARM CI for kata 2.0

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#2668]
Hi guys

I've tried to enable ARM CI for kata 2.0.  ;) 🎉🎊
For importing new features like rust-agent, shimv2 as default, I need to enable containerd-cri integration tests on ARM CI.
I will follow http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-PR/ to create jenkins job for arm ci.

**Comment by amshinde** [comment]
Fixed with https://github.com/kata-containers/tests/pull/2669
