### ISSUE TITLE
ci: VFIO test failed on qemu-virtiofs  

### ISSUE THREAD

**Issue by likebreath** [kata-containers/tests#2677]
# Description of problem

As a part of debugging the VFIO test failure on clh, we found that VFIO test is also failing on qemu-virtiofs.

# Expected result

The VFIO test should pass when "configuration-qemu-virtiofs.toml" is selected.

# Actual result

From the CI log(http://jenkins.katacontainers.io/job/kata-containers-tests-vfio-PR/197/console), we have the following error message:
```
+ sudo kata-runtime --kata-config /tmp/tmp.RYi9mmRvxb/configuration.toml run --detach -b /tmp/tmp.RYi9mmRvxb/bundle --pid-file=/tmp/tmp.RYi9mmRvxb/pid vfiotest
QMP command failed: vfio 0000:00:03.0: failed to setup container for group 3: memory listener initialization failed for container: Bad address
++ handle_error 86
++ local exit_code=1
Failed at 86: sudo kata-runtime --kata-config "${CONFIG_FILE}" run --detach -b "${bundle_dir}" --pid-file="${tmp_data_dir}/pid" "${container_id}"
++ local line_number=86
++ echo 'Failed at 86: sudo kata-runtime --kata-config "${CONFIG_FILE}" run --detach -b "${bundle_dir}" --pid-file="${tmp_data_dir}/pid" "${container_id}"'
++ exit 1
+ cleanup
+ sudo kata-runtime --kata-config /tmp/tmp.RYi9mmRvxb/configuration.toml kill vfiotest
```

/cc @devimc @cmaf @jcvenegas

**Comment by jcvenegas** [comment]
@likebreath is this still an issue ? Is there a way to reproduce it, locally ?

**Comment by likebreath** [comment]
@jcvenegas I am not sure about that. I encountered the error when I was debugging clh VFIO on the CI machine.  AFAIK, we are not running qemu-virtiofs in our VFIO CI (in kata 1.x as shown [here](https://github.com/kata-containers/tests/blob/master/Makefile#L343)). So we will need to run it manually on the VFIO CI machine to see whether we still have the issue. We will need help from @devimc to setup a L1 VM that is ready for VFIO CI test on the VFIO CI machine. Please let me know whether you want to do that. Thanks.

**Comment by jcvenegas** [comment]
@devimc @likebreath Thanks I wanted to know if is still an issue we want to keep in mind and probably to report for virtiofsd folks. In 2.0 qemu-virtiofs + vfio is running ? If yes what are the current changes make it work ? E.g Disable DAX?

**Comment by likebreath** [comment]
> Thanks I wanted to know if is still an issue we want to keep in mind and probably to report for virtiofsd folks. 

Makes sense.

> In 2.0 qemu-virtiofs + vfio is running ?

Yes, I think so, as virtiofs is default in 2.0. @devimc please correct me, if I am wrong.

>If yes what are the current changes make it work ? E.g Disable DAX?

I also had this question, but I don't have an answer for sure. I just opened a PR to enable the VFIO CI w/ qemu-virtiofs, and let's see how it works (https://github.com/kata-containers/tests/pull/3030).

**Comment by devimc** [comment]
> Yes, I think so, as virtiofs is default in 2.0. @devimc please correct me, if I am wrong.

yes, in 2.0 the default sharefs is virtio-fs

https://github.com/kata-containers/kata-containers/blob/259589ad896a82b543194ce0385d71f83e3a5b32/src/runtime/cli/config/configuration-qemu.toml.in#L125

> I also had this question, but I don't have an answer for sure. I just opened a PR to enable the VFIO CI w/ qemu-virtiofs, and let's see how it works (#3030).

qemu-virtiofs is a different version of qemu ?  this doesn't make sense to me :thinking:
