### ISSUE TITLE
Sometimes launch qemu failed

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#2699]
Sometimes starting qemu may failed:

```
Message: "failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: error: failed to set MSR 0x48b to 0x1582e00000000\nqemu-system-x86_64: /root/qemu/target/i386/kvm.c:2695: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.\n: unknown",

```

Here is a full log: http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR/73/consoleFull

I'm sorry that I have no azure machines, so I can't verify that, but I hope these links will be helpful:

- https://github.com/GNS3/gns3-server/issues/1774#issuecomment-639396742
- https://www.mail-archive.com/qemu-devel@nongnu.org/msg665051.html
- https://bugzilla.redhat.com/show_bug.cgi?id=1822682

**Comment by liubin** [comment]
Also found this https://github.com/kata-containers/runtime/pull/2355#issuecomment-572132900

**Comment by devimc** [comment]
uhmm why 2.0-dev is using QEMU 5 when the version in the `versions.yaml` is 4.1.1  https://github.com/kata-containers/kata-containers/blob/2.0-dev/versions.yaml#L91 ?  anyway https://github.com/kata-containers/tests/pull/2694 will fix this

cc @chavafg @GabyCT

**Comment by chavafg** [comment]
hmmm, this is weird, will check CI scripts that install qemu

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
