### ISSUE TITLE
skip k8s tests that fail randomly in kata 2.0

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#2711]

**Comment by bergwolf** [comment]
@GabyCT Could you please list skipped tests that are supposed to work for kata 2.0 in this issue? Just so that we know which one is skipped on purpose and can work on fixing and re-enabling them. Thanks!

**Comment by jodh-intel** [comment]
@GabyCT ^^

**Comment by GabyCT** [comment]
Closing this issue as it is replicated in https://github.com/kata-containers/tests/issues/2574
