### ISSUE TITLE
2.0: ARM CI is blocked

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#2745]
Many ci builds are failed with the same error:

```
=== RUN   TestContainerStats
    TestContainerStats: container_stats_test.go:32: Create a pod config and run sandbox container
E0727 02:38:16.354371   25508 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to reserve sandbox name "sandbox1_stats-81855ad8681d0d86d1e91e00167939cb6694d2c422acd208a0072939487f6999_52fdfc072182654f163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649_0": name "sandbox1_stats-81855ad8681d0d86d1e91e00167939cb6694d2c422acd208a0072939487f6999_52fdfc072182654f163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649_0" is reserved for "aa2fa8f316736ec203e517b9597536f62cd850031f424b93325ec379a424c217"
    TestContainerStats: container_stats_test.go:35: 
        	Error Trace:	container_stats_test.go:35
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = failed to reserve sandbox name "sandbox1_stats-81855ad8681d0d86d1e91e00167939cb6694d2c422acd208a0072939487f6999_52fdfc072182654f163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649_0": name "sandbox1_stats-81855ad8681d0d86d1e91e00167939cb6694d2c422acd208a0072939487f6999_52fdfc072182654f163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649_0" is reserved for "aa2fa8f316736ec203e517b9597536f62cd850031f424b93325ec379a424c217"
        	Test:       	TestContainerStats
-
```

http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/101/console

**Comment by bergwolf** [comment]
```
E0727 03:01:03.698852    8120 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to reserve sandbox name "sandbox1_stats-81855ad8681d0d86d1e91e00167939cb6694d2c422acd208a0072939487f6999_52fdfc072182654f163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649_0": name "sandbox1_stats-81855ad8681d0d86d1e91e00167939cb6694d2c422acd208a0072939487f6999_52fdfc072182654f163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649_0" is reserved for "aa2fa8f316736ec203e517b9597536f62cd850031f424b93325ec379a424c217"
```

**Comment by GabyCT** [comment]
@Jianyong Wu could you please take a look

**Comment by GabyCT** [comment]
@jongwu here it is the ARM issue

**Comment by devimc** [comment]
ARM CI is istill failing but with a different error

http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/247/console

```
ERROR: LIBC type for ppc64le should be gnu
different error 
```

**Comment by jodh-intel** [comment]
@jongwu, @justin-he - please could you look at this ^^ :smile:

**Comment by jongwu** [comment]
Hi @devimc @jodh-intel , you mean the CI under https://github.com/kata-containers/kata-containers/pull/679? I think it's the PR issue not CI itself, see the same error in http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR/332/console.

**Comment by bergwolf** [comment]
@jongwu could you please take another look at the ARM CI? It seems that it has been failing for some time.

E.g.,
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/386/console

**Comment by jongwu** [comment]
Thanks @bergwolf - , ARM CI fail for more than one week. the main reason is for qemu and I'm working on that now. it's new for me of [http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/386/console](url), I will go to see it.

**Comment by bergwolf** [comment]
@jongwu It looks like somehow `install_aarch64_musl` is not called?

**Comment by jongwu** [comment]
@bergwolf - the failure of [ http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/386/console](url) may result from [https://github.com/kata-containers/kata-containers/pull/795](url). I will go further to see why that happend.

**Comment by chavafg** [comment]
should we close this one? I see stability in the arm jobs for the last couple of days:
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/buildTimeTrend

**Comment by jodh-intel** [comment]
@jongwu ^ :smile:

**Comment by jongwu** [comment]
@chavafg - yeah, close this. open it again if necessary.
