### ISSUE TITLE
Delete -i option of kubectl exec if there is no stdin

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#2770]
Some cases use `kubectl exec -i POD -- cat /etc/resolve.conf`, now this will leads https://github.com/kata-containers/kata-containers/pull/440 failed for CRI-O, so the solution may be:

- [x] delete `-i` option if there need not this option #2771 
- [x] merge https://github.com/kata-containers/kata-containers/pull/440
- [x] merge https://github.com/kata-containers/tests/pull/2766
- [x] wait https://github.com/cri-o/cri-o/issues/4046 to be fixed
- [x] update CRI-O to the latest version
- [ ] add case `kubectl exec -i POD -- cat /etc/resolve.conf` after CRI-O fixed the bug.

@lifupan how about this?

**Comment by lifupan** [comment]
> Some cases use `kubectl exec -i POD -- cat /etc/resolve.conf`, now this will leads [kata-containers/kata-containers#440](https://github.com/kata-containers/kata-containers/pull/440) failed for CRI-O, so the solution may be:
> 
> 1. delete `-i` option if there need not this option
> 2. merge [kata-containers/kata-containers#440](https://github.com/kata-containers/kata-containers/pull/440)
> 3. merge #2766
> 4. wait [cri-o/cri-o#4046](https://github.com/cri-o/cri-o/issues/4046) to be fixed
> 5. add case `kubectl exec -i POD -- cat /etc/resolve.conf` after CRI-O fixed the bug.
> 
> @lifupan how about this?

It's  look good to me.

**Comment by fidencio** [comment]
Adding a note here, this change in CRI-O introduced a regressison on `k8s-copy-file.bats`, and it's been tracked here:
https://github.com/kata-containers/kata-containers/issues/1080

**Comment by fidencio** [comment]
I also checked the box of update CRI-O to the "latest" version @GabyCT updated CRI-O to v1.18.4, which includes the fix in the following PR: https://github.com/kata-containers/kata-containers/pull/1037

**Comment by egernst** [comment]
Do we have the test merged here?

**Comment by ariel-adam** [comment]
Closing this issue since it was fixed.
