### ISSUE TITLE
Review GitHub labels

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#2778]
# TL;DR

We should review the GitHub labels once again.

# Background

Originally, each Kata repo had a very disparate set of labels - there was a lot of duplication, oddly-named labels and lots of labels without descriptions.

# Labels database

This led us to create a standard set of labels used in all the Kata repos. To try to keep control of them, we defined that list of standard labels in a YAML file here:

- https://github.com/kata-containers/tests/blob/master/cmd/github-labels/labels.yaml.in

Once standardised, we set the list of labels in each repo to match the contents of the YAML database.

See: #1463 for further details.

# Current situation

However, time has moved on and we now have the following to consider:

- Kata 2.x.
- Some labels have been manually added to repos.
- The fact that we have a *lot* of labels :smile:
- We're in the process of consolidating most of the repos into https://github.com/kata-containers/kata-containers for 2.x and all future work.

# Manually added labels

I've just reviewed the labels in all the repos and here are the changes to the master YAML database:

| repo | new labels |
|-|-|
| `agent` | `port-to-2.0` |
| `documentation` | `port-to-2.0` |
| `runtime` | `port-to-2.0` |
| `kata-containers` | `asoc2020`, `kata-2.0-features` |

As such, we should review the labels once again.

# Current standard labels

The table below was generated like this:

```sh
$ cd $GOPATH/src/github.com/kata-containers/tests/cmd/github-labels
$ make
$ ./kata-github-labels show labels --format md labels.yaml.in | cut -b1-139
```

|           NAME            |                                   DESCRIPTION                                    |         CATEGORY         |
|---------------------------|----------------------------------------------------------------------------------|--------------------------|
| `api-breakage`            | API was broken                                                                   | `api`                    |
| `api-change`              | API change                                                                       | `api`                    |
| `architecture-specific`   | Affects subset of architectures                                                  | `environment`            |
| `area/api`                | Application Programming Interface                                                | `area`                   |
| `area/cli`                | Command Line Interface (flags/options and arguments)                             | `area`                   |
| `area/comms`              | Communications (gRPC, Yamux, etc)                                                | `area`                   |
| `area/config`             | Configuration                                                                    | `area`                   |
| `area/logging`            | Logging                                                                          | `area`                   |
| `area/networking`         | Networking                                                                       | `area`                   |
| `area/storage`            | Storage                                                                          | `area`                   |
| `area/tracing`            | Tracing                                                                          | `area`                   |
| `backport`                | Code needs to be applied to older (stable) releases                              | `backport`               |
| `bug`                     | Incorrect behaviour                                                              | `type`                   |
| `cannot-reproduce`        | Issue cannot be recreated                                                        | `resolution`             |
| `cleanup`                 | General tidy-up                                                                  | `cleanup`                |
| `crash`                   | Causes part of the system to crash                                               | `behaviour`              |
| `customer`                | Relates to a customer                                                            | `customer`               |
| `data-loss`               | System loses information                                                         | `behaviour`              |
| `deprecate`               | Highlight a feature that will soon be removed                                    | `cleanup`                |
| `do-not-merge`            | PR has problems or depends on another                                            | `block`                  |
| `duplicate`               | Same issue as one already reported                                               | `resolution`             |
| `enhancement`             | Improvement to an existing feature                                               | `type`                   |
| `feature`                 | New functionality                                                                | `type`                   |
| `good-first-issue`        | Small and simple task for new contributors                                       | `new-contributor`        |
| `hang`                    | System appears to stop operating or freeze                                       | `behaviour`              |
| `high-priority`           | Very urgent issue (resolve quickly)                                              | `priority`               |
| `high-severity`           | Very important issue                                                             | `severity`               |
| `highest-priority`        | Critically urgent issue (must be resolved as soon as possible)                   | `priority`               |
| `highest-severity`        | Extremely important issue                                                        | `severity`               |
| `invalid`                 | Issue does not make sense                                                        | `resolution`             |
| `limitation`              | Issue cannot be resolved                                                         | `limitation`             |
| `medium-priority`         | Urgent issue (resolve before unprioritised issues)                               | `priority`               |
| `medium-severity`         | Important issue                                                                  | `severity`               |
| `needs-decision`          | Requires input from the Architecture Committee                                   | `architecture-committee` |
| `needs-design-doc`        | Needs a document explaining the design                                           | `design`                 |
| `needs-design-review`     | Needs a formal design review of the approach                                     | `design`                 |
| `needs-docs`              | Needs some new or updated documentation                                          | `documentation`          |
| `needs-help`              | Request for extra help (technical, resource, etc)                                | `help`                   |
| `needs-integration-tests` | Needs new system/integration tests to validate behaviour in the tests repository | `test`                   |
| `needs-more-info`         | Blocked until user or author provides further details                            | `detail`                 |
| `needs-new-label`         | New label required to categorise this issue                                      | `label-admin`            |
| `needs-rebase`            | PR contains conflicts which need resolving                                       | `rebase`                 |
| `needs-revendor`          | Needs imported code to be re-vendored                                            | `vendor`                 |
| `needs-review`            | Needs to be assessed by the team.                                                | `team`                   |
| `needs-unit-tests`        | Needs new unit tests to validate behaviour in this repository                    | `test`                   |
| `os-specific`             | Affects subset of operating system / distro versions                             | `environment`            |
| `performance`             | System runs too slowly                                                           | `behaviour`              |
| `question`                | Requires an answer                                                               | `question`               |
| `refactor`                | Remove duplication, improve organisation, etc                                    | `cleanup`                |
| `regression`              | Behaviour inadvertently reverted to older behaviour                              | `sub-type`               |
| `related/containerd`      | Containerd                                                                       | `related`                |
| `related/cri`             | CRI                                                                              | `related`                |
| `related/crio`            | CRIO                                                                             | `related`                |
| `related/docker`          | Docker                                                                           | `related`                |
| `related/firecracker`     | Firecracker                                                                      | `related`                |
| `related/k8s`             | Kubernetes                                                                       | `related`                |
| `related/qemu`            | QEMU                                                                             | `related`                |
| `related/runc`            | Runc                                                                             | `related`                |
| `release-gating`          | Release must wait for this to be resolved before release                         | `release`                |
| `resource-hog`            | System uses too many resources (such as memory)                                  | `behaviour`              |
| `resource-leak`           | System does not free resources (such as memory)                                  | `behaviour`              |
| `rfc`                     | Requires input from the team                                                     | `question`               |
| `security`                | Potential or actual security issue                                               | `security`               |
| `size/huge`               | Largest and most complex task (probably needs breaking into small pieces)        | `sizing`                 |
| `size/large`              | Task of significant size                                                         | `sizing`                 |
| `size/medium`             | Average sized task                                                               | `sizing`                 |
| `size/small`              | Small and simple task                                                            | `sizing`                 |
| `size/tiny`               | Smallest and simplest task                                                       | `sizing`                 |
| `stale`                   | Issue or PR was not updated in a timely fashion                                  | `resolution`             |
| `team/ci`                 | Need Continuous Integration Team input                                           | `team`                   |
| `team/developer`          | Need Developer Team input                                                        | `team`                   |
| `team/documentation`      | Need Documentation Team input                                                    | `team`                   |
| `team/kernel`             | Need Kernel Team input                                                           | `team`                   |
| `team/metrics`            | Need Metrics Team input                                                          | `team`                   |
| `team/packaging`          | Need Packaging Team input                                                        | `team`                   |
| `team/test`               | Need Test Team input                                                             | `team`                   |
| `unreliable`              | Part of the system is not stable                                                 | `behaviour`              |
| `wip`                     | Work in Progress (PR incomplete - needs more work or rework)                     | `block`                  |
| `wont-fix`                | Issue will not be fixed (not a good use of limited resources)                    | `resolution`             |
| `wrong-repo`              | Raised in incorrect repository                                                   | `resolution`             |

# Current standard categories

> **Note:** Categories don't exist as a concept in GitHub labels, however we introduced them in the YAML database
> to allow grouping (and understanding) of the list of available labels.

The table below was generated like this:

```sh
$ cd $GOPATH/src/github.com/kata-containers/tests/cmd/github-labels
$ make
$ ./kata-github-labels show categories --format md labels.yaml.in | cut -b1-148
```

|           NAME           |                                                      DESCRIPTION                                                      |
|--------------------------|-----------------------------------------------------------------------------------------------------------------------|
| `api`                    | Change related to an Application Programming Interface.                                                               |
| `architecture-committee` | Needs input from the Architecture Committee.                                                                          |
| `area`                   | Code component / general part of product affected.                                                                    |
| `backport`               | Code that needs to be applied to other branches, generally older stable ones.                                         |
| `behaviour`              | How the issue affect the operation of the system. A more precise version of regression.                               |
| `block`                  | Stop a PR from being merged.                                                                                          |
| `cleanup`                | Refactoring, restructuring or general tidy-up needed.                                                                 |
| `customer`               | Related to a customer.                                                                                                |
| `design`                 | Requires formal review on the approach to solving the problem.                                                        |
| `detail`                 | Need further information from the user or author.                                                                     |
| `documentation`          | Needs more documentation.                                                                                             |
| `environment`            | Related to particular system environment.                                                                             |
| `help`                   | Request for technical help / extra resource. Also used for assisted workflow.                                         |
| `label-admin`            | Relates to the administration of labels.                                                                              |
| `limitation`             | Issue cannot be resolved (too hard/impossible, would be too slow, insufficient resources, etc).                       |
| `new-contributor`        | Small, self-contained tasks suitable for newcomers.                                                                   |
| `priority`               | Relative urgency (time-critical).                                                                                     |
| `question`               | Needs input from the team.                                                                                            |
| `rebase`                 | Code conflicts need to be resolved.                                                                                   |
| `related`                | Related project. Base set can be generated from https://github.com/kata-containers/runtime/blob/master/versions.yaml. |
| `release`                | Related to production of new versions.                                                                                |
| `resolution`             | Issue is not (or no longer) valid for some reason. Label specifies reason for closing.                                |
| `security`               | Potential or actual vulnerability / CVE.                                                                              |
| `severity`               | Relative importance (mission-critical).                                                                               |
| `sizing`                 | Estimate of the complexity of the task (story points).                                                                |
| `sub-type`               | More specific detail on the type category.                                                                            |
| `team`                   | Team that needs to analyse the issue.                                                                                 |
| `test`                   | New tests needed.                                                                                                     |
| `type`                   | High-level summary of the issue.                                                                                      |
| `vendor`                 | Related to handling imported code.                                                                                    |

/cc @ariel-adam, @egernst, @amshinde, @gnawux.

**Comment by jodh-intel** [comment]
Some comparative statistics:

| Project | Label count |
|-|-|
| [containerd](https://github.com/containerd/containerd/labels) | 29 |
| [crio](https://github.com/cri-o/cri-o/labels) | 140 |
| [docker moby](https://github.com/moby/moby/labels) | 126 |
| [Kata](https://github.com/kata-containers/kata-containers/labels) | 83 |
| [k8s](https://github.com/kubernetes/kubernetes/labels) | 189 |
| [openshift](https://github.com/openshift/origin/labels) | 148 |
| [podman](https://github.com/containers/podman/labels) | 42 |
| [runc](https://github.com/opencontainers/runc/labels) | 28 |

**Comment by GabyCT** [comment]
@jodh-intel should we close this issue? I see that was created a long time ago not sure if this was fixed

**Comment by jodh-intel** [comment]
@GabyCT - agreed. We only have two repos now and the labels seem to be working (and are being used fwics ;), so let's close this one...
