### ISSUE TITLE
Codecov did not report tests for kata-containers/kata-containers

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#2781]
Codecov is not running tests for newly created kata-containers/kata-containers repo. This can be fixed by adding `make test` back into jenkins_job_build.sh, which was missing in the 2.0-dev branch. 

Related to [kata-containers/kata-containers issue #514](https://github.com/kata-containers/kata-containers/issues/514)
and [kata-containers/tests issue #2779 ](https://github.com/kata-containers/tests/issues/2779)

**Comment by GabyCT** [comment]
@cmaf can we close this issue? I see that two PRs were merged that are related with this issue

**Comment by cmaf** [comment]
@GabyCT yes, closing since we disabled codecov for now (see https://github.com/kata-containers/tests/pull/3437)
