### ISSUE TITLE
Metrics: Use same enviroment options for blogbench

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2795]
# Description of problem

To enable blogbench in metrics CI we disabled DAX only for that 
test[1]. As consequence the data generated by that test may not reflect the default behavior provided by kata on any release and also could the issue that caused to other users.

[1] https://github.com/kata-containers/tests/pull/2725

# Expected result
We have three options
1. Do not modify the kata flags in the test but for all kata if required
1. Disable DAX in kata gloablly 
1. Dont run the test until there is a proper fix in virtifosd.

**Comment by GabyCT** [comment]
@jcvenegas I believe this issue has been fixed by https://github.com/kata-containers/tests/commit/4744d857358650272ffff59c47f2d4cd313dc52d, but please feel to open it in case that is not
