### ISSUE TITLE
clh: Stablize CI jobs related to cloud-hypervisor for kata 2.0

### ISSUE THREAD

**Issue by likebreath** [kata-containers/tests#2813]
# Description of problem

We now have two CI jobs on cloud-hypervisor with kata 2.0,  namely [`jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/) and [`jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/). While the CI jobs are working most of the time (e.g. passing all k8s+containerd tests and the minimal k8s e2e tests),  we did see instability from those CI jobs. This issue is to track the (unexpected) failures of those CI jobs, from where we can locate the problem and stabilize them.

# Expected result

All CI jobs related to cloud-hypervisor in kata 2.0 are passing constantly.

# Actual result

Example failures we have from the `k8s-containerd` CI are job [13](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/13/console), and job [12](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/13/console).

The `k8s-minimal` CI jobs is not executed much and we need more date points.

**Comment by likebreath** [comment]
@jcvenegas @GabyCT I am assigning this issue to all of us, so that we can report, discuss, and debug all issues related to the CLH CI jobs here. 

Like what we did for kata 1.x in PR https://github.com/kata-containers/runtime/pull/2900, we want to separate the factor of `seccomp` from other factors that cause the instability of the CI. I will open a PR soon in kata 2.0 to disable the seccomp filter option temporarily. Let's see how the CI jobs go from there. Any other comments or advises, please don't hesitate to share. Thanks.

**Comment by likebreath** [comment]
Review of the stability of CI job  [`jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/), based on 30 CI executions (job 87 - 116) since Sept 30.

In total, three failures (~`10%`) are potential `periodic`/`random` failures that may indicate instability: Job [`92`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/92/console) with error `not ok 1 Check PID namespaces`,  Job [`98`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/98/console) with error `not ok 1 Credentials using secrets`, and Job [`#116`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/116/console) with error `ERROR: 1 pods left and found at /run/vc/sbs`.

The following failures are expected and does not indicate CI instability: 4 (expected) failures as a result of debugging https://github.com/kata-containers/tests/pull/2895 (job 87/91/94/102); 2 short runs under 1 minute (job 95/106). All the rest CI jobs were finishing successfully.

**Comment by likebreath** [comment]
Review of the stability of CI job [`jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/), based on 30 CI executions (job 90- 119) since Sept 30.

In total, one failure (~`10%`) is potential `periodic`/`random` failures that may indicate instability: Job [`119`](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/119/console) with error `e2e_result_dir: unbound variable` (as reported in issue https://github.com/kata-containers/kata-containers/issues/905).

Besides 2 short runs under 1 minute (job 98/102) and two failures because of debugging PR (job 116/117), all the rest CI jobs were finishing successfully.

**Comment by liubin** [comment]
Not checked all, these two days got many the same  error.
Checked one log, the console shows:

```
01:36:59 time="2020-12-03T17:36:59Z" level=error msg="error attempting to run sonobuoy: waiting for run to finish: failed to get status: failed to get namespace sonobuoy: etcdserver: request timed out"
```

and kubelet log  shows:

```

Dec 03 17:36:58 ubuntu1804-azure51fbb0 kubelet[6708]: E1203 17:36:58.927044    6708 controller.go:178] failed to update node lease, error: etcdserver: request timed out
Dec 03 17:36:58 ubuntu1804-azure51fbb0 kubelet[6708]: I1203 17:36:58.942654    6708 kubelet.go:1997] SyncLoop (housekeeping)
Dec 03 17:36:59 ubuntu1804-azure51fbb0 kubelet[6708]: E1203 17:36:59.032955    6708 event.go:260] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-ubuntu1804-azure51fbb0.164d456242981a7c", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"442", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-ubuntu1804-azure51fbb0", UID:"351df54872071fbd62ff6c94edb4400e", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Unhealthy", Message:"Liveness probe failed: HTTP probe failed with statuscode: 503", Source:v1.EventSource{Component:"kubelet", Host:"ubuntu1804-azure51fbb0"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63742613730, loc:(*time.Location)(0x7026560)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfea666c95e161d1, ext:105718076544, loc:(*time.Location)(0x7026560)}}, Count:2, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'etcdserver: request timed out' (will not retry!)

Dec 03 17:37:00 ubuntu1804-azure51fbb0 kubelet[6708]: E1203 17:37:00.039166    6708 controller.go:178] failed to update node lease, error: Operation cannot be fulfilled on leases.coordination.k8s.io "ubuntu1804-azure51fbb0": the object has been modified; please apply your changes to the latest version and try again


Dec 03 17:37:01 ubuntu1804-azure51fbb0 kubelet[6708]: I1203 17:37:01.339889    6708 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-ubuntu1804-azure51fbb0", UID:"4894662206e328e2f3412ea47157a2cb", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-scheduler}"}): type: 'Warning' reason: 'Unhealthy' Liveness probe failed: Get https://127.0.0.1:10259/healthz: dial tcp 127.0.0.1:10259: connect: connection refused
```
