### ISSUE TITLE
rust install fails on ppc64le

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/tests#2829]
Rust install fails since the script installs the toolchain based on musl implementation which is not supported on ppc64le.

**Comment by jodh-intel** [comment]
Thanks for raising @Amulyam24. @bpradipt - could you tal? This is relevant I think: https://github.com/kata-containers/kata-containers/issues/206.

**Comment by bpradipt** [comment]
@jodh-intel this is fixed via https://github.com/kata-containers/tests/pull/2831 . Somehow the issue didn't get closed automatically.

**Comment by bpradipt** [comment]
Closing the issue.

**Comment by jodh-intel** [comment]
Thanks @bpradipt!
