### ISSUE TITLE
crio: Add containerd-shim-kata-v2 runtime to the runtimes map

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#2841]
Currently we're only adding `kata-runtime` to the runtimes map, but as we intend to also test `containderd-shim-kata-v2` together with the VM runtime type, we should also add it to the runtimes map.

I do believe it'd be okay to only do this for CRI-O 1.18+, but I'd like to hear from the community about this.

**Comment by GabyCT** [comment]
@fidencio it seems that this issue has been solved, in case that is not please re open the issue
