### ISSUE TITLE
Enables OOM test for CRI-O

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#2859]
Now CRI-O not support OOM events with Kata containers yet, but test for containerd has been added (see #2854  ). 

Once :

- the [PR for CRI-O](https://github.com/cri-o/cri-o/pull/4204) have been merged
- and, updated to latest CRI-O

test for CRI-O should be enabled.

**Comment by fidencio** [comment]
Closed via: https://github.com/kata-containers/tests/pull/3060
