### ISSUE TITLE
clh: Failing on new k8s test "OOM events for pods" for cloud-hypervisor in kata 2.0

### ISSUE THREAD

**Issue by likebreath** [kata-containers/tests#2864]
As a part of fixing the regression of clh CI for kata 2.0 (PR https://github.com/kata-containers/tests/pull/2862), the failure on test `OOM events for pods` is observed (as reported in [here](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/29/console)):

```
22:21:16 1..1
22:21:48 not ok 1 Test OOM events for pods
22:21:48 # (in test file k8s-oom.bats, line 30)
22:21:48 #   `kubectl wait --for=condition=Ready pod "$pod_name"' failed
22:21:48 # INFO: k8s configured to use runtimeclass
22:21:48 # pod/pod-oom created
22:21:48 # error: timed out waiting for the condition on pods/pod-oom
22:21:48 # pod "pod-oom" deleted
22:21:48 Failed at 80: bats "${K8S_TEST_ENTRY}"
22:21:48 [reset] Reading configuration from the cluster...
22:21:48 [reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
```

As this is a new test (added today https://github.com/kata-containers/tests/pull/2854), it is advisable to debug on this in a separate PR, after bring CLH CI back online.

**Comment by fidencio** [comment]
I've seen this happening on debian, and CentOS as well.

**Comment by GabyCT** [comment]
Closing this issue as it has been solved by https://github.com/kata-containers/tests/pull/3499/files

**Comment by fidencio** [comment]
@GabyCT, sorry for re-opening this one, but I think we should only close this after re-enabling the test on clh:
https://github.com/kata-containers/tests/blob/899576a1411fb27c15c11cb2724302d5e23fbb40/integration/kubernetes/run_kubernetes_tests.sh#L56-L64

I've opened https://github.com/kata-containers/tests/pull/3574 to check that.
