### ISSUE TITLE
enable crio k8s tests

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#2865]
We can just enable `integration/kubernetes/k8s-block-volume.bats` and `integration/kubernetes/nginx.bats` as they both pass w/o issues on k8s+crio.

**Comment by bergwolf** [comment]
Turns out `k8s-block-volume.bats` is still failing randomly. Let's keep this open until that is fixed. 

See:
http://jenkins.katacontainers.io/job/kata-containers-2.0-debian-PR/292/console
http://jenkins.katacontainers.io/job/kata-containers-2.0-centos-PR/292/console

```
# (in test file k8s-block-volume.bats, line 52)
#   `kubectl exec "$pod_name" -- sh -c "apk add --no-cache e2fsprogs"' failed
# Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
# unsatisfiable constraints:
# I0929 09:27:41.195732  120111 log.go:172] (0xc000a6a160) Data frame received for 3
# I0929 09:27:41.195753  120111 log.go:172] (0xc00070a000) (3) Data frame handling
# I0929 09:27:41.195767  120111 log.go:172] (0xc00070a000) (3) Data frame sent
#   e2fsprogs (missing):
#     required by: world[e2fsprogs]
```

Might be some network issue. Maybe we should consider using ubuntu container image instead of alpine to do the test, since alpine CDN is more likely to go out of service from time to time.

**Comment by ariel-adam** [comment]
@bergwolf @fidencio is there still an issue with this?

**Comment by fidencio** [comment]
This one can be closed as nowadays we have the same parity between the tests running against CRI-O and containerd.
