### ISSUE TITLE
golang linter needs updating in 2.0-dev branch

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#2870]
The version of `golangci-lint` in `master` is `v1.18.0`, but only `v1.16.0` in `2.0-dev`. This is since https://github.com/kata-containers/tests/pull/2435 hasn't been ported to `2.0-dev`.

I don't *think* we need to port that entire PR to `2.0-dev` though since the Travis config for `master` is using Ubuntu 16.04, whereas `2.0-dev` is using Ubuntu 20.04.

But we do need to bump the linter version since version 1.16.0  passed the code on https://github.com/kata-containers/kata-containers/pull/735 (now landed), but version 1.18.0 caught a few code simplification issues on https://github.com/kata-containers/runtime/pull/2976.

**Comment by GabyCT** [comment]
is this still an issue @jodh-intel (we do not have anymore a 2.0-dev branch)?
