### ISSUE TITLE
Investigate updating golangci-lint to latest version

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#2872]
We're using `golangci-lint` [v1.18.0 currently](https://github.com/kata-containers/tests/blob/master/versions.yaml#L73). Investigate moving to the latest (https://github.com/golangci/golangci-lint/releases/tag/v1.31.0 currently) and see what impact that has across all the repos.

Any volunteers?

**Comment by Jakob-Naucke** [comment]
1.x is EOL, has been updated on 2.x. Closing.
