### ISSUE TITLE
TCP Json output should have packets sent / received information

### ISSUE THREAD

**Issue by Sharma78** [kata-containers/tests#2873]
**Which feature do you think can be improved?**

Specify the feature you think could be made better.

**How can it be improved?**

Describe how specifically you think it could be improved.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by ariel-adam** [comment]
@Sharma78 please provide the detailed mentioned above so we can decide how to progress with this issue.
For example what do you mean by "TCP JSON output", what information? when? what flows?

**Comment by GabyCT** [comment]
Closing this isssue as a lack of information
