### ISSUE TITLE
port most popular docker images tests to containerd / cri-o

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#2927]
We have dropped the OCI CLI for 2.0 in favour of the containerd shimv2 concept. This means that docker and podman are not currently supported as they lack shim v2 capabilities.

However, prior to releasing 2.0 it would be good to know if we can run the ["most popular docker image test"](https://github.com/kata-containers/tests/blob/2.0-dev/integration/popular_docker_hub_images/popular_docker_images.bats) using another container manager such as containerd or cri-o.

As such, we need to port that test to another container manager, run it and see what results we get.

@amshinde, @gnawux, @bergwolf, @egernst - do you think this should be `release-gating`?

Related: https://github.com/kata-containers/kata-containers/issues/722

**Comment by jodh-intel** [comment]
Anyone in the community able to look at the rework? The simplest approach would be to rework the docker bats file for containerd (`ctr`) I believe.

**Comment by fidencio** [comment]
Just for the record, @egernst started working on this (kudos, sincerely!).

**Comment by jodh-intel** [comment]
Thanks @egernst ! but ooi, why do we also need #2955?

**Comment by devimc** [comment]
Due to the [rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) imposed in Docker hub, I consider that fixing this bug won't be possible, I'm going to close it, please feel free to reopen it if you are going to work on it :smiley:
