### ISSUE TITLE
git error in CI logs

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#2959]
For this code(`.ci/install_crio.sh`):

```bash
# This commit contains changes regarding CRI-O’s default configuration files,
# so we have to use a new default config path from here.
# https://github.com/cri-o/cri-o/commit/0f1226b99685f95e83c94dc6668b6452df5056db
if git merge-base --is-ancestor 0f1226b99685f95e83c94dc6668b6452df5056db HEAD; then
    crio_config_file="/etc/crio/crio.conf.d/00-default.conf"
fi
```

Leads to this error:

```
fatal: Not a valid commit name 0f1226b99685f95e83c94dc6668b6452df5056db
```

**Comment by jodh-intel** [comment]
@liubin - Can you paste a link to the failing CI log? That commit is valid:

- https://github.com/cri-o/cri-o/commit/0f1226b99685f95e83c94dc6668b6452df5056db

and that command wfm locally.

**Comment by liubin** [comment]
@jodh-intel , almost all CI logs of `kata-containers-2.0-fedora-PR`, I think.

For example this one http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR/406/consoleFull

**Comment by jodh-intel** [comment]
Looking at the `install_crio.sh` script, I think the problem may be show by this highlight:

- https://github.com/kata-containers/tests/blob/2.0-dev/.ci/install_crio.sh#L83..L102

That block is run inside the crio checkout. But, the `git merge-base` call is made on line:

https://github.com/kata-containers/tests/blob/2.0-dev/.ci/install_crio.sh#L115

And that is outside the first block. In other words, the `git merge-base` is not run from within the crio checkout fwics. I think it's being run from the initial `pwd`, whatever that is?

/cc @chavafg, @GabyCT.
