### ISSUE TITLE
manage_ctr_mgr: Setup docker runtime via daemon.json

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2991]
**Which feature do you think can be improved?**

CI setup for docker using daemon.json

**How can it be improved?**

Instead of use dockerd cmdline via service modfiy the runtime config using daemon.json

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
