### ISSUE TITLE
2.0 CI: jenkins-ci-fedora-32-crio is stuck

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#3007]
Jenkins reports that no nodes labeled with `fedora32_azure` were found. But there is no other 2.0 CI jobs running at all at the moment.

![image](https://user-images.githubusercontent.com/88972/97099059-3ba27800-16bf-11eb-903d-261acbc12b75.png)

**Comment by GabyCT** [comment]
Closing this as the fedora CI job is working properly
