### ISSUE TITLE
2.0: depends-on label doesn't work for travis

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#3008]
E.g., if we add `Depends-on` label in a PR in the kata-containers repo to rely on a PR in the tests repo, it works for Jenkins CI but doesn't work for travis jobs.

I'm not familiar with how it is implemented. @GabyCT @chavafg could you please help to take a look?

**Comment by ariel-adam** [comment]
Travis is no longer used for CI thus we are closing this issue.
