### ISSUE TITLE
Understand and try to fix codecov issues

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#301]
The codecov report summary on https://github.com/kata-containers/runtime/pull/305 claims I modified a golang file. However, that PR only changed a single YAML file.

It seems that codecov is comparing each PR to the last report uploaded for `master`. However:

- Something seems to have gone wrong as `git diff` shows that file in question `multicast.go` has not been changed for a long time.
- For some reason, the CI is not uploading the codecov reports for all PRs:
  https://codecov.io/gh/kata-containers/runtime/pulls
  

See also: https://docs.codecov.io/docs/unexpected-coverage-changes

**Comment by devimc** [comment]
codecov is still active? can we close this?

**Comment by grahamwhaley** [comment]
That's a good point @devimc . I've either forgotten or did not notice what happened with codecov - it appears we don't have it active do we? @jodh-intel do you remember the state of play? Did we turn it off, did it stop working for us, did it just stop by itself etc.?
I'm not hearing anybody bemoan its absence... let's make a decision to resurrect or kill it off permanently.

**Comment by jodh-intel** [comment]
It looks like we've broken it. From https://github.com/kata-containers/runtime/pull/1247 ...


```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8a28df4


==> Jenkins CI detected.
    project root: .
--> token set from env
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
find: ‘./virtcontainers/utils/supportfiles/bundles/busybox/rootfs/root’: Permission denied
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./coverage.txt bytes=13
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
find: ‘./virtcontainers/utils/supportfiles/bundles/busybox/rootfs/root’: Permission denied
find: ‘./virtcontainers/utils/supportfiles/bundles/busybox/rootfs/root’: Permission denied
find: ‘./virtcontainers/utils/supportfiles/bundles/busybox/rootfs/root’: Permission denied

    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=leakyPods&commit=1610b9f23383ff2bcf0d4875e39651c86549c2cd&build=1556&build_url=http%3A%2F%2Fjenkins.katacontainers.io%2Fjob%2Fkata-containers-runtime-ubuntu-16-04-PR%2F1556%2F&name=&tag=&slug=kata-containers%2Fruntime&service=jenkins&flags=&pr=1247&job=
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=****&branch=leakyPods&commit=1610b9f23383ff2bcf0d4875e39651c86549c2cd&build=1556&build_url=http%3A%2F%2Fjenkins.katacontainers.io%2Fjob%2Fkata-containers-runtime-ubuntu-16-04-PR%2F1556%2F&name=&tag=&slug=kata-containers%2Fruntime&service=jenkins&flags=&pr=1247&job=
    -> Uploading
    -> View reports at https://codecov.io/github/kata-containers/runtime/commit/1c339864877b4853a0e7a73db7f56c5478fdf181
```

Two things to note:

- The `EPERM` issue which needs resolving.
- The coverage file is 13 bytes long, which happens to be the same size as the covage file header:

  - https://github.com/kata-containers/tests/blob/master/.ci/go-test.sh#L161

  So for some reason we're no longer recording the coverage details.
