### ISSUE TITLE
Skip running CI for spell check data file changes

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#3021]
Don't run the full CI for PRs that only change the spell check data files.

**Comment by GabyCT** [comment]
Closing this issue as this has been fixed https://github.com/kata-containers/tests/commit/71b7dec3331bd0b98db996b517bcbc4eb32d9ba0#diff-b51ed67c64dc3e8b823eea587f44e0ca527b0ffda24d1c3d1551829fe1e90306
