### ISSUE TITLE
Port tracing test to 2.0-dev branch

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#3024]
The [tracing test](https://github.com/kata-containers/tests/blob/master/tracing/tracing-test.sh) needs to be ported to the `2.0-dev` branch. It can still use docker for Jaeger server but will need to use `ctr` to invoke the Kata 2.0 shimv2 runtime.

Related:

- https://github.com/kata-containers/tests/pull/2129
- https://github.com/kata-containers/runtime/pull/2980 (which will also need porting to the [2.x runtime](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime))

**Comment by cmaf** [comment]
@jodh-intel see #3038
