### ISSUE TITLE
VFIO CI broken due to SRIOV upstream change

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#3056]
From: http://jenkins.katacontainers.io/job/kata-containers-2.0-vfio-PR/220/console (PR https://github.com/kata-containers/kata-containers/pull/1105):

```
10:37:53 + sriov_plugin_version=b7f6d3e0679796e907ecca88cfab0e32e326850d
10:37:53 + git clone --depth=1 https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin
10:37:53 Cloning into 'sriov-network-device-plugin'...
10:37:55 + pushd sriov-network-device-plugin
10:37:55 /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/tests/sriov-network-device-plugin /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/tests
10:37:55 + git checkout b7f6d3e0679796e907ecca88cfab0e32e326850d
10:37:55 fatal: reference is not a tree: b7f6d3e0679796e907ecca88cfab0e32e326850d
```

This is coming from https://github.com/kata-containers/tests/blob/2.0-dev/integration/kubernetes/vfio.sh#L157..L161.

The problem appears to relate to the latest upstream commit:

- https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/commit/12178c85648e6d769cf3e6e2ba1d80b023c7f307

Workarounds:

- `git clone` without specifying `--depth=`
- `git clone --depth=4 ...`

**Comment by fidencio** [comment]
@jodh-intel, please, take a look at https://github.com/kata-containers/tests/issues/3052 and  https://github.com/kata-containers/tests/pull/3053. Those are covering this very same issue.

**Comment by jodh-intel** [comment]
Closing as fixed by https://github.com/kata-containers/tests/pull/3053.
