### ISSUE TITLE
jenkins-ci-Power8-ubuntu-18-04-initrd CI is constantly failing.

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3064]
Here's one example of the a failed run:
http://jenkins.katacontainers.io/job/kata-containers-runtime-Power8-ubuntu-18-04-PR-initrd/1172/console

@kata-containers/tests, do we have someone explicitly assigned to help with issues on Power 8? If we do, who? If not, let's drop an email on kata-dev asking for help on this, as having access to Power 8 hardware to debug issues is not that easy.

**Comment by GabyCT** [comment]
This is already an issue https://github.com/kata-containers/ci/issues/351 
@bpradipt please take a look

**Comment by bpradipt** [comment]
Looks like docker daemon is crashing again on the Power CI system. This again seems like a repeat of https://github.com/kata-containers/ci/issues/351#issuecomment-717807142.
I have restarted the docker daemon and kick started the build again. Will continue investigating the root cause later on

**Comment by bpradipt** [comment]
Builds are running now. I'll keep observing.
@GabyCT @fidencio is there any provision of email or slack notification indicating failed jenkins builds ? It might help to proactively fix issues as they crop up.

**Comment by fidencio** [comment]
@bpradipt, @kata-containers/power group has been created for this cases.  I'm closing this issue for now.

Thanks for the help!
