### ISSUE TITLE
jenkins-ci-ubuntu-18-04-initrd CI is constantly failing.

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3065]
Here's in one example of a failed run:
http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-18-04-PR-initrd/3341/console

@kata-containers/tests, a few questions:
* Is this something worth the time to debug and check what may have caused the regression?
  - I think it is, but I'd like to be sure someone doesn't jump on this with the tests being covered by some other CI;
* Why is this CI not required?
* Considering the first item gets fixed, should this CI be required?

**Comment by GabyCT** [comment]
This is already an issue https://github.com/kata-containers/ci/issues/351.

**Comment by GabyCT** [comment]
This is already an issue https://github.com/kata-containers/tests/issues/3012
/cc @bergwolf @lifupan

**Comment by GabyCT** [comment]
I am assigning this issue to @lifupan as he introduced the set of tests

**Comment by GabyCT** [comment]
Closing this issue as it is not longer present
