### ISSUE TITLE
create-certs.sh does not work using MacOS

### ISSUE THREAD

**Issue by pruan-rht** [kata-containers/tests#3078]
# Description of problem
 the default macOS base64 implementation doesn't have the -w flag

# Expected result
successful cert creation

# Actual result
$ ./create-certs.sh
Generating RSA private key, 2048 bit long modulus
........................................................................+++
...................................................................................................................+++
e is 65537 (0x10001)
Signature ok
subject=/CN=pod-annotate-webhook.default.svc
Getting Private key
base64: invalid option -- w
Usage:	base64 [-hvDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)

# Further information
So, the flag is called -b in macOS, and it already defaults to 0, which means base64 in macOS has the same behaviour as base64 -w0 on Linux.

**Comment by GabyCT** [comment]
Closing this issue as it seems solved
