### ISSUE TITLE
Failing OpenShift test: "HostPath should give a volume the correct mode" for Kata 1.x

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#3090]
# Description of problem

The following OpenShift e2e conformance test is failing on the openshift-ci:

`[sig-storage] HostPath should give a volume the correct mode [LinuxOnly] [NodeConformance] [Skipped:ibmcloud] [Suite:openshift/conformance/parallel] [Suite:k8s]`

Logs from 2020-12-02: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kata-containers-runtime-master-kata-containers-e2e-periodic/1334030093642633216
Logs from 2020-12-01: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kata-containers-runtime-master-kata-containers-e2e-periodic/1333667694460801024

# Further information

The daily Kata Containers CI job on openshift-ci can be found at https://prow.ci.openshift.org/?job=periodic-ci-kata-containers-runtime-master-kata-containers-e2e-periodic

**Comment by wainersm** [comment]
@kata-containers/redhat Could someone do an initial triage?

**Comment by cpmeadors** [comment]
Do we care since it was removed from kubernetes conformance tests upstream?

https://github.com/kubernetes/kubernetes/issues/90860

**Comment by pmores** [comment]
On Wed, Dec 02, 2020 at 07:29:02AM -0800, Cameron Meadors wrote:
> Do we care since it was removed from kubernetes conformance tests upstream?
> 
> https://github.com/kubernetes/kubernetes/issues/90860

Good point - I personally can see no reason why our interests should diverge
from those of upstream Kubernetes as far as HostPath is concerned. (?)  Also
the reasoning in the issue description seems sound to me.

	pvl

**Comment by ariel-adam** [comment]
Closing this issue since it is no longer on the upstream
