### ISSUE TITLE
the kata-webhook/deploy/webhook-registration.yaml.tpl is using a deprecated apiVersion `v1beta1`

### ISSUE THREAD

**Issue by pruan-rht** [kata-containers/tests#3093]
# Description of problem
the kata-webhook/deploy/webhook-registration.yaml.tpl is using a deprecated apiVersion `v1beta1`

# Expected result
oc apply -f deploy should be successful w/o warnings

# Actual result
W1203 21:28:15.344945   28253 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W1203 21:28:15.431559   28253 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration

# Further information

simply replace `v1beta1` with `v1` should get rid of this warning.

**Comment by fidencio** [comment]
@pruan-rht,

Thanks for filing the issue.  Do you fancy working on a patch for this one?  If so, please, /cc me for reviewing the patch.

**Comment by pruan-rht** [comment]
@fidencio yeah, I was thinking about adding the fix into https://github.com/kata-containers/tests/pull/3079

**Comment by fidencio** [comment]
A new PR would be better, @pruan-rht.  The reason for that is because this issue is not dependent on the OS, as the other one. :-)

**Comment by pruan-rht** [comment]
@fidencio ok, will file a separate PR then.  thx for the feedback.

**Comment by pruan-rht** [comment]
@fidencio PTAL https://github.com/kata-containers/tests/pull/3095 when you have a moment...the fix is simple.

**Comment by GabyCT** [comment]
Closing this issue as it seems to be fixed
