### ISSUE TITLE
ci: Add dracut support for install_kata_image.sh

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#3097]
Allow to build and install a dracut-based initrd/image from the install_kata_image.sh

Given a limitation on the Openshift CI build pipeline it is not possible to build the osbuilder using the docker method. So this issue is about to allow to build and install a dracut-baed initrd/image from the `.ci/install_kata_image.sh` script instead.

**Comment by GabyCT** [comment]
Closing this issue as it seems to be fixed https://github.com/kata-containers/tests/commit/d25ba0c2885a8c984233e75bbaa0b0e58c4833ee, in case that is not please re-open it.
