### ISSUE TITLE
Make CentOS CI temporarily optional

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3098]
Although we do want to test on CentOS, right now due to the release of what's based on RHEL 8.3 their repo is not in a good state, at all.

We're seeing issues related to packages conflicting, we're seeing issues related to repositories being renamed, and all sort of things that block development on Kata Containers side.

Knowing that, I'd like to recommend we make the CentOS based CIs not mandatory, as running them right now is just costing us money and there's not much we can do from our side to improve the situation apart from waiting.

@kata-containers/tests, @kata-containers/architecture-committee, WDYT?

**Comment by jcvenegas** [comment]
Sounds good to me, what would be the trigger to reconsider that is stable to enable it?  The issues you see are for building Kata or other dependencies around tests?

**Comment by fidencio** [comment]
> Sounds good to me, what would be the trigger to reconsider that is stable to enable it? The issues you see are for building Kata or other dependencies around tests?

The issues we're facing now are mostly about having the basics functioning before even being able to install / run Kata. :-/
My idea is to, personally, keep an eye in the situation and try to trigger the CI once or twice per week.  Once the CI is a good shape (after at least one good run), we can reenable / reinforce it.

Does this sound reasonable?

**Comment by jcvenegas** [comment]
Yeah, make sense, because today is not mark as required in github checks , I think you mean stop using triggering with the prefix `/test`does it work change it to `/centos` for now ? .

Also related on how it got broken, I think the image we are using in azure got updated to the latest centos, is that correct?

**Comment by fidencio** [comment]
> Yeah, make sense, because today is not mark as required in github checks , I think you mean stop using triggering with the prefix `/test`does it work change it to `/centos` for now ? .

For 2.x I think centos is required.  So, we should make that not required there.
Anywhere else, switching the trigger specifically to `/centos`  may be the way to go for now.

> Also related on how it got broken, I think the image we are using in azure got updated to the latest centos, is that correct?
CentOS installations will have their repositories pointing to the latest, as CentOS 8 doesn't follow a "versioning" schema.  What happened is that a rebuild of RHEL 8.3 was done and it's been tagged as their current set of pacakges, and some conflicts are known to be happening because of that (something went wrong in the rebuild process),  It'd end up happening regardless of using a new or an old image, unfortunately. :-/

**Comment by GabyCT** [comment]
For me it sounds good to disable it for the moment.

**Comment by chavafg** [comment]
sounds good, I have removed the `Required` setting for the centos8 job and have disabled all centos jobs (instead of switching the trigger). We can enable them once the repos issue is fixed.

**Comment by bergwolf** [comment]
Looks like we are having centos repo issues again:
```
Error: No matching repo to modify: PowerTools.
Failed at 46: sudo yum-config-manager --enable PowerTools
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

**Comment by wainersm** [comment]
> Looks like we are having centos repo issues again:
> 
> ```
> Error: No matching repo to modify: PowerTools.
> Failed at 46: sudo yum-config-manager --enable PowerTools
> Build step 'Execute shell' marked build as failure
> Performing Post build task...
> Match found for :.* : True
> Logical operation result is TRUE
> Running script  : #!/bin/bash
> ```
Hi @bergwolf , that's weird because recently @fidencio has a fix merged for that problem: https://github.com/kata-containers/tests/pull/3117

**Comment by fidencio** [comment]
Let me close this one as it's been solved.
