### ISSUE TITLE
[ci-failure] not ok 2 initContainer with shared volume

### ISSUE THREAD

**Issue by cpmeadors** [kata-containers/tests#3099]
in jenkins-ci-ubuntu-18-04 and jenkins-ci-ubuntu-18.04-initrd jobs for kata-containers/test:

16:40:03 not ok 2 initContainer with shared volume
16:40:03 # (in test file k8s-shared-volume.bats, line 44)
16:40:03 #   `kubectl exec "$pod_name" -c "$last_container" -- sh -c "$cmd"' failed
16:40:03 # INFO: k8s configured to use runtimeclass
16:40:03 # pod/initcontainer-shared-volume created
16:40:03 # pod/initcontainer-shared-volume condition met
16:40:03 # I1208 15:39:48.313167   28868 log.go:172] (0xc00089a160) (0xc000454500) Create stream
16:40:03 # I1208 15:39:48.313210   28868 log.go:172] (0xc00089a160) (0xc000454500) Stream added, broadcasting: 1
16:40:03 # I1208 15:39:48.314201   28868 log.go:172] (0xc00089a160) Reply frame received for 1
16:40:03 # I1208 15:39:48.314231   28868 log.go:172] (0xc00089a160) (0xc000714000) Create stream
16:40:03 # I1208 15:39:48.314238   28868 log.go:172] (0xc00089a160) (0xc000714000) Stream added, broadcasting: 3
16:40:03 # I1208 15:39:48.314875   28868 log.go:172] (0xc00089a160) Reply frame received for 3
16:40:03 # I1208 15:39:48.314893   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Create stream
16:40:03 # I1208 15:39:48.314900   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Stream added, broadcasting: 5
16:40:03 # I1208 15:39:48.315440   28868 log.go:172] (0xc00089a160) Reply frame received for 5
16:40:03 # I1208 15:39:48.490489   28868 log.go:172] (0xc00089a160) Data frame received for 1
16:40:03 # I1208 15:39:48.490512   28868 log.go:172] (0xc000454500) (1) Data frame handling
16:40:03 # I1208 15:39:48.490523   28868 log.go:172] (0xc000454500) (1) Data frame sent
16:40:03 # I1208 15:39:48.490534   28868 log.go:172] (0xc00089a160) (0xc000454500) Stream removed, broadcasting: 1
16:40:03 # I1208 15:39:48.491022   28868 log.go:172] (0xc00089a160) (0xc000714000) Stream removed, broadcasting: 3
16:40:03 # I1208 15:39:48.491044   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Stream removed, broadcasting: 5
16:40:03 # I1208 15:39:48.491060   28868 log.go:172] (0xc00089a160) (0xc000454500) Stream removed, broadcasting: 1
16:40:03 # I1208 15:39:48.491069   28868 log.go:172] (0xc00089a160) (0xc000714000) Stream removed, broadcasting: 3
16:40:03 # I1208 15:39:48.491075   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Stream removed, broadcasting: 5
16:40:03 # command terminated with exit code 1
16:40:03 # pod "initcontainer-shared-volume" deleted
16:40:03 Failed at 82: bats "${K8S_TEST_ENTRY}"

**Comment by cpmeadors** [comment]
jenkins jobs:
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/1887/
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR-initrd/2753/

**Comment by GabyCT** [comment]
Closing this is issue as it is not longer present in kata 2.x as you can see
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/1971/consoleFull
