### ISSUE TITLE
[ci-failure] not ok 1 Check PID namespaces

### ISSUE THREAD

**Issue by cpmeadors** [kata-containers/tests#3100]
In jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd for kata-containers/test:

16:32:47 not ok 1 Check PID namespaces
16:32:47 # (in test file k8s-pid-ns.bats, line 28)
16:32:47 #   `kubectl wait --for=condition=Ready pod "$pod_name"' failed
16:32:47 # INFO: k8s configured to use runtimeclass
16:32:47 # pod/busybox created
16:32:47 # error: timed out waiting for the condition on pods/busybox
16:32:47 # pod "busybox" deleted
16:32:47 Failed at 82: bats "${K8S_TEST_ENTRY}"

**Comment by cpmeadors** [comment]
jenkins job: http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/95/

**Comment by c3d** [comment]
> In jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd for kata-containers/test:
> 16:32:47 not ok 1 Check PID namespaces
> 16:32:47 # (in test file k8s-pid-ns.bats, line 28)
> 16:32:47 # `kubectl wait --for=condition=Ready pod "$pod_name"' failed
> 16:32:47 # INFO: k8s configured to use runtimeclass
> 16:32:47 # pod/busybox created
> 16:32:47 # error: timed out waiting for the condition on pods/busybox
> 16:32:47 # pod "busybox" deleted
> 16:32:47 Failed at 82: bats "${K8S_TEST_ENTRY}"
> 
> 

PID namespaces are not expected to work on Kata, are they?

(We can't share PIDs with the host, since it's a different kernel)

I have some trouble following the link today, so I'm replying by mail. Is the test trying to setup a specific namespace for the container (which might be expected to work), or is it using the shared PID namespace option (which will never work)?

**Comment by GabyCT** [comment]
Closing this issue as it is not present anymore in kata 2.x as you can see at 
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/239/console
