### ISSUE TITLE
CRI-O CI broke yesterday

### ISSUE THREAD

**Issue by haircommander** [kata-containers/tests#3108]
# Description of problem

CRI-O CI broke sometime yesterday. It looks like it's failing on building one of the rust components:
http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16030/console

# Expected result
Kata tests on CRI-O CI passes

# Actual result
they fail :'(

**Comment by haircommander** [comment]
@fidencio @chavafg PTAL

**Comment by wainersm** [comment]
It failed to build the guest OS image. Since it might be a an intermittent fail, I re-triggered the job:
 
http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16038/

Let's see if it passes  now.

**Comment by wainersm** [comment]
Sorry, the correct job to watch (that I re-triggered) is  http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16040

**Comment by fidencio** [comment]
This job has changed at some point from Yesterday to Today.  It was running based on 1.x, and suddenly it's running based on 2.x and failing to build the rust agent.

**Comment by wainersm** [comment]
Good catch @fidencio ! But should we keep testing CRI-O with 1.x or bump properly to 2.x?

**Comment by fidencio** [comment]
Right now, we should test 1.x. and @fgiudici is working on 2.x, I believe.

**Comment by fidencio** [comment]
@jcvenegas, any idea on what may have caused the job to change?
