### ISSUE TITLE
CI: cache qemu, kernel, image for 2.x

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#3119]
The ci install scripts for 1.x look for built and cached qemu, kernel and image files in http://jenkins.katacontainers.io. In case of cache miss those artifacts are built on job time. 

For 2.x it doesn't have the jobs on jenkins to build and cache those artifacts, thus they are built for every CI job. This issue is about enabling such as caching mechanism to 2.x as well.

**Comment by wainersm** [comment]
@GabyCT @chavafg Fix if I am wrong but current cached artifacts can't be used with 2.x because their versions can diverge.

**Comment by wainersm** [comment]
Reopening because I still need to address qemu.

**Comment by wainersm** [comment]
I will leave it open until we don't have images (osbuilder) cached too.

**Comment by GabyCT** [comment]
I think we can close this issue, the images is still an issue as it is not easy to solve
