### ISSUE TITLE
CentOS CI is failing due to package conflicts

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3136]
Here's the error:

```
16:02:56 Error: 
16:02:56  Problem: package nss-3.53.1-11.el8_2.x86_64 requires /usr/bin/update-crypto-policies, but none of the providers can be installed
16:02:56   - cannot install both crypto-policies-20200713-1.git51d1222.el8.noarch and crypto-policies-20191128-2.git23e1bf1.el8.noarch
16:02:56   - package crypto-policies-20200713-1.git51d1222.el8.noarch obsoletes crypto-policies < 20200527-1.git0a29b28 provided by crypto-policies-20191128-2.git23e1bf1.el8.noarch
16:02:56   - cannot install the best update candidate for package nss-3.44.0-15.el8.x86_64
16:02:56   - cannot install the best update candidate for package crypto-policies-20191128-2.git23e1bf1.el8.noarch
16:02:56 (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
16:02:56 Failed at 41: sudo -E yum -y update
16:02:56 ++ handle_error 69
16:02:56 ++ local exit_code=1
16:02:56 ++ local line_number=69
16:02:56 ++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-2.0-centos-PR/ci_entry_point.sh +69: .ci/jenkins_job_build.sh "${repo_to_test}"'
16:02:56 Failed at /tmp/jenkins/workspace/kata-containers-2.0-centos-PR/ci_entry_point.sh +69: .ci/jenkins_job_build.sh "${repo_to_test}"
```

**Comment by fidencio** [comment]
I've tested this inside a container and I couldn't reproduce the issue.
@chavafg, what's the CentOS version / image we're using from Azure?

**Comment by fidencio** [comment]
Adding @kata-containers/redhat for triage and investigation as well.

**Comment by chavafg** [comment]
I see that we are using Centos 8, Image version: 8.2.2020062400

**Comment by chavafg** [comment]
In December, we agreed to disable Centos jobs because of this issue, and I thought I disabled all centos related jobs, but seems that I didn't disable a couple of them. I have disable them for now and until we know what is the problem with the azure image.

**Comment by fidencio** [comment]
@chavafg, yep, you disabled because of a different issue and I re-enabled then when the issue was solved (reference: https://github.com/kata-containers/tests/issues/3116).

This one is a different bug and may be specifically affecting the image on Azure due to some customization done on their side. I'll try to get access one of those images Tomorrow and work the issue around.

Thanks a lot for disabling the CentOS jobs again.

**Comment by wainersm** [comment]
Hi @fidencio @chavafg a bit off-topic... how can one get access to the images being used on CI? Is it publicly available?

**Comment by GabyCT** [comment]
I think we can close this issue as CentOS 8 CI is running , wdyt @fidencio ?

**Comment by GabyCT** [comment]
Closing this issue as the Centos 8 CI is running
