### ISSUE TITLE
.ci/lib.sh: pid match error lead to system corrup

### ISSUE THREAD

**Issue by jongwu** [kata-containers/tests#3141]
in kill_stale_process(), pids=$(pgrep -d ' ' -f "${stale_process}") will match all of the pids in the whole system when "stale_process" is NULL, then the "kill -9 pids" will kill all of the process in the system.
the bug lead to the ci failure of arm. see [2.0-arm-ci](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/298/consolel)

**Comment by ariel-adam** [comment]
Closing this issue since a PR was merged for it already.
