### ISSUE TITLE
Shouldn't need a forward porting tag on PRs against the 2.0-dev branch

### ISSUE THREAD

**Issue by dgibson** [kata-containers/tests#3180]
# Description of problem

The static-checks tests complain about a PR that does't have a forward porting tag (either `forward-port`, `needs-forward-port` or `no-forward-port-needed`).  `forward-port` has meaning in that context, but the others are pointless: this is the branch for current development, there's nowhere to forward port to.

# Expected result

Can submit a PR against 2.0-dev with no forward porting label, and not have it fail CI.

# Actual result

Fails CI, necessitating busy work fiddling with the labels.

**Comment by dgibson** [comment]
> I think that we can close this issue, as `2.0-dev` has been replaced to `main` and when we raise a PR in `main` no labels are needed like `needs-forward-port` etc

This does not appear to be the case.  I just filed the trivial PR https://github.com/kata-containers/kata-containers/issues/1505, and the CI whinged about a missing forward port label.

**Comment by GabyCT** [comment]
@jodh-intel , any idea of how we can solve this? thanks

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
