### ISSUE TITLE
ci: fix scripts for centos 8

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#3245]
# Description of problem

The are several small errors to allow the `jenkins_job_build.sh` running on Centos 8. One of the main problems is that the wanted docker version is `18.04`, and this version is not available on Centos 8. The available versions are:
```bash
yum --showduplicate list docker-ce
Last metadata expiration check: 0:08:42 ago on Tue 16 Feb 2021 06:13:14 AM EST.
Available Packages
docker-ce.x86_64                                           3:19.03.13-3.el8                                            docker-ce-stable
docker-ce.x86_64                                           3:19.03.14-3.el8                                            docker-ce-stable
docker-ce.x86_64                                           3:19.03.15-3.el8                                            docker-ce-stable
docker-ce.x86_64                                           3:20.10.0-3.el8                                             docker-ce-stable
docker-ce.x86_64                                           3:20.10.1-3.el8                                             docker-ce-stable
docker-ce.x86_64                                           3:20.10.2-3.el8                                             docker-ce-stable
docker-ce.x86_64                                           3:20.10.3-3.el8                               
```

For opensuse/sles the docker version is set to `19.03` ([here](https://github.com/kata-containers/tests/blob/f4b8a8de9515843473266c41fe2753b2d0f663c5/cmd/container-manager/manage_ctr_mgr.sh#L151)).

# Expected result
Running without errors the Ci scripts on Centos 8

**Comment by alicefr** [comment]
cc @fidencio

**Comment by fidencio** [comment]
@GabyCT, what do you think?  Shall we consider a switch to `19.03` everywhere else?

**Comment by GabyCT** [comment]
@fidencio for me it is better if we have one docker version across all the CI's in order to avoid random issues maybe caused for the different versions, wdyt @chavafg ? I believe that the only reason why we are using `18.04` is because it is supporting devicemapper so that is something that you need to take in consideration

**Comment by alicefr** [comment]
@GabyCT is devicemapper still relevant? Docker has deprecated devicemapper support and podman/crio don't support it.

**Comment by GabyCT** [comment]
@alicefr I believe it is, but maybe it is something that should be discussed on the AC meeting
/cc @chavafg

**Comment by chavafg** [comment]
My understanding is that cri-o supports devicemapper, we also use it as part of the integration with Firecracker, and in some cases it brings better performance in Kata. I think this is still relevant, but as @GabyCT says, we can discuss in AC meeting if needed.

**Comment by fidencio** [comment]
@chavafg, @GabyCT, is there some way to just have a docker binary being dropped to the distro, rather than using the distro packages then?

**Comment by fidencio** [comment]
+1 for discussing devicemapper importance in the next AC meeting.
/cc @kata-containers/architecture-committee

**Comment by fidencio** [comment]
@GabyCT, @chavafg, what are the tests we run that require device-mapper?  I wonder if we'd be able to perform those tests, or at least similar ones, using CRI-O or Firecracker themselves.

**Comment by chavafg** [comment]
Hi @fidencio
These are the tests/jobs that run with devicemapper:
- CI jobs that run with Firecracker as only block storage is supported in FC. 
- CRI-O tests running in ubuntu [1].

Found this old discussion about this: https://github.com/kata-containers/runtime/issues/943 

[1] https://github.com/kata-containers/tests/blob/main/integration/cri-o/cri-o.sh#L83

**Comment by fidencio** [comment]
I've opened https://github.com/kata-containers/tests/pull/3272, which should unblock this one, in case everything goes well there.
