### ISSUE TITLE
collect mode failing inside of crio container

### ISSUE THREAD

**Issue by haircommander** [kata-containers/tests#3273]
ref: http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16567/console
cri-o CI is hitting 
```
12:20:16 # time="2021-02-24T17:20:16Z" level=fatal msg="run pod sandbox failed: rpc error: code = Unknown desc = container create failed: time=\"2021-02-24T17:20:15Z\" level=warning msg=\"signal: killed\"\ntime=\"2021-02-24T17:20:15Z\" level=error msg=\"container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: Cannot set property CollectMode, or unknown property.\"\n"
```
could this be possible from the systemd version inside of the guest is not capable of handling collectmode?

we're hitting this 100% in cri-o CI, and it only started popping up yesterday

**Comment by fidencio** [comment]
@haircommander, what's the minimum systemd version required?  This job is running on an `ubuntu 16.04`, which seems to use `229-4ubuntu21.27 [security]: amd64 i386`, according to https://packages.ubuntu.com/search?keywords=systemd

**Comment by haircommander** [comment]
it's not totally clear, we used to include it if it was systemd version 218, but different distros name the versions differently.

One should be able to run `systemctl show -p CollectMode systemd` and have it succeed. That's the test we use now

**Comment by fidencio** [comment]
I've done a quick change, switching the base image to use `ubuntu 18.04`, and triggered a rebuild.

Let's see if it helps.

**Comment by fidencio** [comment]
@haircommander, it seems to be working as expected now. Please, take a look at the job I posted in my previous comment, and close the issue accordingly if you're satisfied with the results.

**Comment by haircommander** [comment]
thanks @fidencio !
