### ISSUE TITLE
CI failure due to wrong path to virtiofsd

### ISSUE THREAD

**Issue by pmores** [kata-containers/tests#3274]
From [failed test log](http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-18-04-virtiofs-PR/851/consoleFull) it looks like the failure is due to a path mismatch where `virtiofsd` is expected at `/usr/bin/virtiofsd` but is actually at `/usr/libexec/kata-qemu/virtiofsd`.

**Comment by Jakob-Naucke** [comment]
has this been seen lately?

**Comment by fidencio** [comment]
@pmores, I'm closing this one.  Please, feel free to re-open it in case you hit the issue again in the future.
