### ISSUE TITLE
Add test to check that PID namespace is shared between containers in a pod

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#336]
Pid namespace is not shared among containers in a pod by default. This can be enabled by means of configuration option. 
In crio, this can be done with setting `enable_shared_pid_namespace=true` in the crio config file (/etc/crio/crio.conf)
This can also be enabled in k8s with version > 1.10 by setting `shareProcessNamespace: true` in the pod yaml file. 
Once pid namespace sharing in enabled with https://github.com/kata-containers/agent/pull/233, add a test to check that the pid ns in indeed shared.
This can be done by launching a pod with two containers and execing into them to run `ps` to check that pid 1 is `pause` process as shown:
```
kubectl exec two-containers-kata -c alpine -i -t sh
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /pause
    8 root       0:00 nginx: master process nginx -g daemon off;
   12 101        0:00 nginx: worker process
   13 root       0:00 watch wget -qO- localhost
   31 root       0:00 sh
   36 root       0:00 ps
```

**Comment by sboeuf** [comment]
This `pause` being the container workload of the `infraContainer`, right ?
Then we don't even need 2 containers for this check I'd say.

Now another test that we could do would be to exec into each container (in case we actually run two containers), and check that from each one, we can see the other one.

**Comment by amshinde** [comment]
@GabyCT Can you take a look at this?

**Comment by GabyCT** [comment]
@amshinde , I will work on this

**Comment by amshinde** [comment]
thanks @GabyCT

**Comment by GabyCT** [comment]
@amshinde , I am checking this issue doing the following

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  shareProcessNamespace: true
  containers:
  - name: first-test-container
    image: busybox
    command:
        - sleep
        - "10"
  - name: second-test-container
    image: busybox
    command:
        - sleep
        - "10"
    stdin: true
    tty: true
```
```
$ sudo -E kubectl create -f pod.yaml
$ sudo -E kubectl exec busybox -c first_test_container ps
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 10
    5 root      0:00 ps
$ sudo -E kubectl exec busybox -c second_test_container ps 
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 10
    5 root      0:00 ps
```
However, I can not see that `pause` is `PID 1`. I am using the following configuration:
kata-runtime  : 1.0.0
commit   : 329f70463a0a6a5c02da61801987ca4247094424
OCI specs: 1.0.1
kata-shim version 1.0.0-087a5371680f069d45baed8544a09b4e6353c06e
kata-proxy version 1.0.0-a69326b63802952b14203ea9c1533d4edb8c1d64
kubectl v1.10.0

**Comment by amshinde** [comment]
@GabyCT Can you test with the crio config "enable_shared_pid_namespace=true" as well and let me know if you see the same behaviour.
I'll try to reproduce the above and see what the issue is.

**Comment by GabyCT** [comment]
@amshinde, I am seeing the same behaviour
```
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 10
    6 root      0:00 ps
```

I used this configuration at the /etc/crio/crio.conf
```
default_workload_trust = "trusted"
````

**Comment by GabyCT** [comment]
@amshinde , I also put the `enable_shared_pid_namespace=true` at /etc/crio/crio.conf and I am seeing the same behaviour

**Comment by amshinde** [comment]
@GabyCT With k8s 1.10, the cri-o config for sharing namespaces has been deprecated and no longer works. So the only way to configure this in 1.10 is through k8s config.

This is still an alpha feature in 1.10, and in addition to the pod yaml configuration, this needs changes in the `kubelet` config and `kube-apiserver` config. We need to add ` --feature-gates=PodShareProcessNamespace=true` to both.

So while installing kubernetes, we need to change this:
https://github.com/kata-containers/tests/blob/master/.ci/install_kubernetes.sh#L33
to 
`sudo sed -i '/KUBELET_AUTHZ_ARGS=/a Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --runtime-request-timeout=30m  --feature-gates=PodShareProcessNamespace=true"' "$k8s_systemd_file"`

I looked around how the kube-apiserver configuration can be changed. I think the best way is to change the `/etc/kubernetes/manifests/kube-apiserver.yaml` file after the `init` script has run. 
Here we need to append `--feature-gates=PodShareProcessNamespace=true` to  `command` as shown:
```
- command:
    - kube-apiserver
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --requestheader-username-headers=X-Remote-User
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --secure-port=6443
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    - --enable-bootstrap-token-auth=true
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-allowed-names=front-proxy-client
    - --advertise-address=10.1.0.4
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --insecure-port=0
    - --allow-privileged=true
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --authorization-mode=Node,RBAC
    - --etcd-servers=https://127.0.0.1:2379
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --feature-gates=PodShareProcessNamespace=true
```

After this, I restarted kubelet with `systemctl restart kubelet`.
With this configuration, containers in a pod  with `shareProcessNamespace: true` in the pod yaml config, will share the pid namespace.

**Comment by amshinde** [comment]
@GabyCT I have made the config changes on the azure instance you shared with me. You can take a look.

**Comment by GabyCT** [comment]
@amshinde , I can not reproduce it. For the installation of kubernetes, I added the following

```
$ sudo sed -i '/KUBELET_AUTHZ_ARGS=/a Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --runtime-request-timeout=30m --feature-gates=PodShareProcessNamespace=true"' "$k8s_systemd_file"
```
Then I ran the ./init.sh script and before running the test, I modified the `/etc/kubernetes/manifests/kube-apiserver.yaml` with the following commands
```
$ sudo -E sed -i '40 i\    - --feature-gates=PodShareProcessNamespace=true' /etc/kubernetes/manifests/kube-apiserver.yaml
$ sudo -E systemctl restart kubelet
$ sudo cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep "PodShareProcessNamespace"
    - --feature-gates=PodShareProcessNamespace=true
```
Then I have the following in the pod yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  shareProcessNamespace: true
  containers:
  - name: first-test-container
    image: busybox
    command:
        - sleep
        - "100"
  - name: second-test-container
    image: busybox
    command:
        - sleep
        - "100"
    stdin: true
    tty: true
```

And then I am running the containers but I am having as a result
```
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 100
    5 root      0:00 ps
```
As you can see , I do not have the `/pause` process
