### ISSUE TITLE
CI is short-circuiting and returning false positive results `kata-containers/kata-containers` branch

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3386]
See any of the recent PRs, such as https://github.com/kata-containers/kata-containers/pull/1607

You'll see the following output in the majority of the jobs, if not in all of them:
```
Complete!
+++ jq '.[].name'
++ local 'labels="needs-backport"
"no-forward-port-needed"'
++ for x in $labels
+++ sed 's/"//g'
++ y=needs-backport
++ '[' needs-backport == force-ci ']'
++ for x in $labels
+++ sed 's/"//g'
++ y=no-forward-port-needed
++ '[' no-forward-port-needed == force-ci ']'
++ local_info 'No forcing label found'
++ msg='No forcing label found'
++ info 'No forcing label found'
++ echo -e 'INFO: No forcing label found'
INFO: No forcing label found
++ echo 0
++ return 0
+ res=0
+ exit 0
Short circuit fast path skipping the rest of the CI.
```

**Comment by fidencio** [comment]
I've retriggered the tests on that specific PR, let's see if they'll run now.

**Comment by jcvenegas** [comment]
I remember there is some magic to detect changes that may affect the runs of the CI to save some time. I am not sure the change will a side effect.  So it will happen again unless modify the logic. I think is based in the kind of files that are modified.

**Comment by fidencio** [comment]
Okay, so I think we're good to go there as I see other jobs are running well.

Sorry for the noise, I freaked out a little bit. :-)

I'm closing this issue.
