### ISSUE TITLE
clh+k8s+containerd CI not working on stable-2.-0

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#3403]
The CI is not working properly on stable-2.0, I am getting this failure
```
16:32:21 INFO: Build agent
16:32:21 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/kata-containers/src/agent /tmp/jenkins/workspace/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/kata-containers/tools/osbuilder
16:32:21 INFO: checkout failed!
16:32:21 make[1]: Entering directory '/tmp/jenkins/workspace/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/kata-containers/src/agent'
16:32:21 make[1]: cargo: Command not found
16:32:21 Makefile:131: recipe for target 'clean' failed
```
You can see all the information at http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/212/console

**Comment by GabyCT** [comment]
Maybe a backport is missing?

**Comment by jcvenegas** [comment]
@GabyCT  main branch is working correctly, probably the question is why only this job, it is trying to build the agent, a setup setup seems that is a CI env setup more than a clh issue.

**Comment by jcvenegas** [comment]
@GabyCT seems that `main` branch is working correctly probably is missing a backport.
Because is failing to build the agent, it may be a CI setup issue, I see in the log cargo being installed, probably it is missing to add the path where it is installed? or refresh the profile ?

**Comment by GabyCT** [comment]
@jcvenegas yes I am not sure about the agent, the only thing that I see is that is the only CI where we are getting that failure

**Comment by GabyCT** [comment]
@jcvenegas also what is funny is that is failing randomly

**Comment by jcvenegas** [comment]
last merged PR has all passing, lets keep monitoring the CI. for stable versions.

https://github.com/kata-containers/tests/pull/3400

**Comment by wainersm** [comment]
It fails to checkout the repository with `git checkout $AGENT_VERSION` on `tools/osbuilder/rootfs-builder/rootfs.sh`.

**Comment by GabyCT** [comment]
I recently submitted some backports to stable-2.0 https://github.com/kata-containers/tests/commit/3545eff60ebd3dfc6021fc11f485d52a30002d73 that seems to be fixed this issue in case that is not I will re-open this issue
