### ISSUE TITLE
Recent memory foot-print increase observed from the metrics CI in kata 1.x

### ISSUE THREAD

**Issue by likebreath** [kata-containers/tests#3404]
As observed and patched in recent PRs on the metrics CI (https://github.com/kata-containers/tests/pull/3336 and https://github.com/kata-containers/tests/pull/3239/), we observed around 23% percent increase of the memory-footprint both the qemu (https://github.com/kata-containers/tests/issues/3335) and cloud-hypervisor (https://github.com/kata-containers/tests/issues/3379). For instance, the memory footprint was increased from `135767` to `165251` for qemu, and from `141664` to `173539` for cloud-hypervisor. Further investigation is needed to understand the root-causes of this increase.

**Comment by egernst** [comment]
We know approximate date? I made a complication flag adjustment to use PIE, which was not enabled in 1.x, but was in 2.x, if I recall correctly. This made a substations increase in footprint of the kata runtime itself.

**Comment by GabyCT** [comment]
I noticed around March 12 when somebody raised a PR

**Comment by egernst** [comment]
Okay -- confirm it wasn't PIE, as the BUILDFLAGS wasn't merged into 1.x: https://github.com/kata-containers/runtime/pull/3077

Will keep looking...

**Comment by egernst** [comment]
Is there a similar increase on 2.x,  or is this unique to 1.x?

**Comment by GabyCT** [comment]
Closing this issue as kata 1.x is EOL
