### ISSUE TITLE
debian-10 CI has been randomly failiing in the k8s tests

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3406]
Since this week I've noticed a whole bunch of debian 10 failures on the CI, always during the k8s tests, usually due to a timeout or because the job gets aborted.

It's hard to debug what's exactly the issue as the failures are not on the same tests.

/cc @chavafg @GabyCT @jcvenegas

**Comment by GabyCT** [comment]
@fidencio , I have seen those failures and as you said is hard to debug locally...so maybe we should disable the CI
/cc @chavafg

**Comment by fidencio** [comment]
I'd say we should make it non-blocker.  Keep it enabled but non blocking patches to be merged.
WDYT?

**Comment by GabyCT** [comment]
sounds good for me

**Comment by GabyCT** [comment]
Closing this issue as PRs has been merged in order to fix this
