### ISSUE TITLE
integration: Remove old OpenShift scripts

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3410]
We have integration tests for OpenShift 3.x, which are never ever run as part of the 2.x branch.  Moreover, we have Kata Containers onboard with OpenShift CI (thanks to @wainersm) and we ultimately rely on that.

With this is mind, we can simply drop the whole content of `integration/openshift`.

**Comment by wainersm** [comment]
@fidencio I've been thinking about that for a while now. I support that idea. If you wish you can even assign this task to me.

**Comment by fidencio** [comment]
> @fidencio I've been thinking about that for a while now. I support that idea. If you wish you can even assign this task to me.

@wainersm, I have a PR about to be opened with this change (and some other cleanups related to the integration).
