### ISSUE TITLE
Code coverage tools for 2.x 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#3436]
We mentioned on the AC meeting that we need a tool to report the code coverage we have in the 2.x branches. 
Preferably we would like a single tool compatible with `rust` and `golang` languages. 
For 1.x, we run the `codecov` tool, but currently it is not configured in the 2.x repositories and before we move forward, we want to discuss and evaluate different options.

/cc @fidencio @egernst @bergwolf @devimc @jodh-intel

**Comment by jodh-intel** [comment]
At the risk of "re-inventing the wheel" (but minimising attack vectors) we could potentially write a GitHub action that:

1. Runs the unit tests on the `main` branch and determines the code coverage percentage.
1. Runs the unit tests on the PR branch and determines the code coverage percentage.
1. Calculates the difference.
1. Compares the difference with a threshold value stored in https://github.com/kata-containers/tests/blob/main/versions.yaml.
1. Fail the action `if (difference > threshold)`.

I haven't looked for alternatives to the codecov service but `go test -cover...` and [`cargo tarpaulin`](https://crates.io/crates/cargo-tarpaulin) would cover most of the code.
