### ISSUE TITLE
kata-doc-to-script not removing all code blocks, removing non-code blocks

### ISSUE THREAD

**Issue by c3d** [kata-containers/tests#3448]
# Get your issue reviewed faster

Observed with d76404e087e3771414f4bd7a85275985d329ee43 while investigating https://github.com/kata-containers/kata-containers/pull/1760#issuecomment-827608257.

# Description of problem

Visible manifestation (in the above PR): The spell checking script incorrectly complains about a fragment like this:

```
        * [Kubernetes volumeMounts.subPaths](#kubernetes-volumemountssubpaths)

[...]

### Kubernetes `volumeMounts.subPaths`

Kubernetes `volumeMount.subPath` is not supported by Kata Containers at the
moment.
```

The error is 

```
INFO: Spell checking file 'docs/Limitations.md'
WARNING: Word 'subPaths': did you mean one of the following?: GOPATHs
WARNING: Incorrect word: 'volumeMounts'
ERROR: Spell check failed for file: 'docs/Limitations.md'
```

The root cause is that `kata-doc-to-script.sh` outputs the following;

```
% ../tests/.ci/kata-doc-to-script.sh -i docs/Limitations.md -
* [Overview](#overview)
* [Definition of a limitation](#definition-of-a-limitation)
* [Scope](#scope)
* [Contributing](#contributing)
* [Pending items](#pending-items)
    * [Runtime commands](#runtime-commands)
        * [checkpoint and restore](#checkpoint-and-restore)
        * [events command](#events-command)
        * [update command](#update-command)
    * [Networking](#networking)
        * [Docker swarm and compose support](#docker-swarm-and-compose-support)
    * [Resource management](#resource-management)
        * [docker run and shared memory](#docker-run-and-shared-memory)
        * [docker run and sysctl](#docker-run-and-sysctl)
    * [Docker daemon features](#docker-daemon-features)
        * [SELinux support](#selinux-support)
* [Architectural limitations](#architectural-limitations)
    * [Networking limitations](#networking-limitations)
        * [Support for joining an existing VM network](#support-for-joining-an-existing-vm-network)
        * [docker --net=host](#docker---nethost)
        * [docker run --link](#docker-run---link)
    * [Storage limitations](#storage-limitations)
        * [Kubernetes volumeMounts.subPaths](#kubernetes-volumemountssubpaths)
    * [Host resource sharing](#host-resource-sharing)
        * [docker run --privileged](#docker-run---privileged)
* [Miscellaneous](#miscellaneous)
    * [Docker --security-opt option partially supported](#docker---security-opt-option-partially-supported)
* [Appendices](#appendices)
    * [The constraints challenge](#the-constraints-challenge)
```

There are two issues in the output above:

1. The `volumeMounts.subPaths` text in the input was stripped of its back-ticks, instead of being stripped itself.
2. The text below the `---` was entirely stripped. So most of the document is actually not spell-checked at all.

# Expected result

The script should remove any text between backticks, but not remove an entire section of the document.

# Actual result

See above.

# Further information

(replace this text with any extra information you think might be useful)

**Comment by c3d** [comment]
@jodh-intel Could you please confirm that it is unintentional to remove anything but the table of contents?

**Comment by c3d** [comment]
Investigation showed that the problem is with the `sed` pattern being used https://github.com/kata-containers/tests/blob/main/.ci/kata-doc-to-script.sh#L162 because that pattern matches if there is only the `block_open` marker and no `block_close` marker.

**Comment by GabyCT** [comment]
@c3d can we close this issue? I saw that a PR has been merged related with this issue but I am not sure
