### ISSUE TITLE
Only uninstall kubernetes / restart docker when running a baremetal CI.

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3516]
https://github.com/kata-containers/tests/pull/3493 fixed the issues we had with the ARM CI, but the changes done were done for any environment.

Let's restrict those changes a little bit and only run those on baremetal CIs.

**Comment by c3d** [comment]
@fidencio I don't fully understand the rationale. Why would things be different or better in a VM? The changes in #3493 restart the docker daemon. Presumably, a same VM can be used for multiple tests and we'd see the same problem, no?
