### ISSUE TITLE
ci: make containerd fails when kuberentes is installed

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#352]
This issue was found when the PR #313  was run with the rest of tests. In ubuntu CI tests we run kuberentes( centos and fedora dont  do kuerbentes testing). I found that only after install the package 
of kuberentes in ubuntu the test

make cri-containerd fails.

The integration test fail trying to stop a pod.

```
E0529 17:17:39.871251  122119 remote_runtime.go:115] StopPodSandbox "3d75f5e7249d01a781fcb74f8ab31358744eda4488ef824dea3488fd041aa3ff" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "3d75f5e7249d01a781fcb74f8ab31358744eda4488ef824dea3488fd041aa3ff": running [/sbin/iptables -t nat -D POSTROUTING -s fe80::7c33:a2ff:fe60:d8b6/64 -j CNI-9e4f1858ef363c8f1e10386c -m comment --comment name: "containerd-net" id: "3d75f5e7249d01a781fcb74f8ab31358744eda4488ef824dea3488fd041aa3ff" --wait]: exit status 2: iptables v1.6.0: invalid mask `64' specified
Try `iptables -h' or 'iptables --help' for more information.
```

Note that the test only fail if kuberentes was installed, kata runtime is used as default runtime.

**Comment by jcvenegas** [comment]
The test fails if:
- kuberentes installed from packages
- Kata  runtime is using  `macvtap` internetworking model

If kuberentes is not installed mavtap networking model works well.

**Comment by chavafg** [comment]
@jcvenegas is this still happening anymore ? I think we can close this.
