### ISSUE TITLE
Update tracing test for dynamic agent tracing

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#3548]
https://github.com/kata-containers/tests/blob/main/tracing/tracing-test.sh will need to be updated for dynamic tracing.

Related: https://github.com/kata-containers/kata-containers/issues/419

**Comment by GabyCT** [comment]
Closing this issue as we're removing this in https://github.com/kata-containers/kata-containers/pull/2986
see https://github.com/kata-containers/kata-containers/issues/419
