### ISSUE TITLE
Local CRIO_K8S test failing in `make kubernetes` with `kubeadm` not found

### ISSUE THREAD

**Issue by c3d** [kata-containers/tests#3554]
# Description of problem

Running @alicefr's [local CI setup](https://github.com/alicefr/kata-local-ci-setup) on Ubuntu, I get:

```
May 20 12:11:31 kata-ubuntu-18.04 crio[27850]: time="2021-05-20 12:11:31.886…48"
May 20 12:11:32 kata-ubuntu-18.04 crio[27850]: time="2021-05-20 12:11:32.654…43"
May 21 04:40:46 kata-ubuntu-18.04 crio[27850]: time="2021-05-21 04:40:46.806…52"
May 21 04:44:23 kata-ubuntu-18.04 systemd[1]: crio.service: Current command …ed.
Hint: Some lines were ellipsized, use -l to show in full.
Init cluster using /var/run/crio/crio.sock
sudo: kubeadm: command not found
Failed at 119: sudo -E kubeadm init --config "${kubeadm_config_file}"
Failed at 78: ./init.sh
sudo: kubeadm: command not found
Failed at 27: sudo -E kubeadm reset -f --cri-socket="${cri_runtime_socket}"
Makefile:112: recipe for target 'kubernetes' failed
make: *** [kubernetes] Error 1
Failed at 49: sudo -E PATH="$PATH" bash -c "make kubernetes"
```

# Expected result

`kubeadm` should have worked.

# Actual result

`kubeadm` not found. I suspect `kubeadm` should have been installed earlier. My personal network is extremely flaky, so it's possible that the install failed.  I notably had GPG errors during a previous run:

```
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
E: The repository 'http://apt.kubernetes.io kubernetes-xenial-unstable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

# More information

Initial installation had failed with:

```
Package 'docker-ce' is not installed, so not removed
E: Unable to locate package kubeadm
E: Unable to locate package kubelet
E: Unable to locate package kubectl
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Unable to locate package docker-ce-cli
Reading package lists... Done
```

Shouldn't we verify if installation completed successfully?

**Comment by fidencio** [comment]
Hmm. That's weird and I tend to think the issue should be reported there rather than here, even if the outcome may be a patch here.

Regardless of where it should be reported, what's exactly the script running? Can you get the full log and comapre with the full log coming from the CI?  That would be the best way to spot the difference that may be causing this issue.

**Comment by alicefr** [comment]
I also supposed that you use 18.04 or have you upgrade the ubuntu version?

**Comment by Jakob-Naucke** [comment]
@c3d is this still an issue?

**Comment by GabyCT** [comment]
Closing this issue, in case that it is still a problem please re-open it
