### ISSUE TITLE
Crio doesn't restart correctly 

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#3563]
# Description of problem
If you want to run a second time the `jenkins_job_build.sh` crio is not started correctly because the configuration for the runtime have been duplicated. See https://github.com/kata-containers/tests/blob/main/.ci/configure_crio_for_kata.sh#L18.

Run a second time the script  `jenkins_job_build.sh` and check `/etc/crio/crio.conf.d/99-runtimes`
```
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_root = "/run/vc"
runtime_type = "vm"
privileged_without_host_devices = true

[crio.runtime.runtimes.runc]
runtime_path = "/usr/local/bin/crio-runc"
runtime_type = "oci"
runtime_root = "/run/runc"
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_root = "/run/vc"
runtime_type = "vm"
privileged_without_host_devices = true

[crio.runtime.runtimes.runc]
runtime_path = "/usr/local/bin/crio-runc"
runtime_type = "oci"
runtime_root = "/run/runc"

```

fyi @fidencio

**Comment by fidencio** [comment]
I'm submitting a fix for this upstream.
