### ISSUE TITLE
virtiofs-dax fio metrics: Add memory monitoring 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#3569]
**Which feature do you think can be improved?**

The #3484  adds a test to compare virtiofs with DAX enabled and not enabled, the fio results are one way to compare both configurations but enabling DAX could affect memory usage.  The test should collect memory usage and other stats  for both: qemu and virtiofsd.  

- It should store what is the maximal memory usage of a pod. 
- It may add a chart of memory usage over the time ( helpful to visualize if at some point memory is freed). 

**How can it be improved?**

Collect stats via `kata-monitor` (instead of grep and find binaries , at some point the it could help migrate the test to make it work with a multi node cluster.)

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by GabyCT** [comment]
@jcvenegas is this issue still relevant?
