### ISSUE TITLE
centos 8 CI is failing due to the "8.4" release / rebuild

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3588]
Seems that we're dealing with yet another breakage session of CentOS due to a minor release, as seen here: http://jenkins.katacontainers.io/job/kata-containers-2.0-centos-PR/1147/console
```
15:51:02 Error: 
15:51:02  Problem 1: cannot install the best update candidate for package authselect-compat-1.1-2.el8.x86_64
15:51:02   - nothing provides authselect(x86-64) = 1.2.2-2.el8 needed by authselect-compat-1.2.2-2.el8.x86_64
15:51:02  Problem 2: cannot install the best update candidate for package python3-pip-9.0.3-16.el8.noarch
15:51:02   - nothing provides platform-python-pip = 9.0.3-19.el8 needed by python3-pip-9.0.3-19.el8.noarch
15:51:02  Problem 3: package python3-pip-9.0.3-16.el8.noarch requires platform-python-pip = 9.0.3-16.el8, but none of the providers can be installed
15:51:02   - cannot install both platform-python-pip-9.0.3-18.el8.noarch and platform-python-pip-9.0.3-16.el8.noarch
15:51:02   - problem with installed package python3-pip-9.0.3-16.el8.noarch
15:51:02   - cannot install the best update candidate for package platform-python-pip-9.0.3-16.el8.noarch
15:51:02   - nothing provides platform-python-pip = 9.0.3-19.el8 needed by python3-pip-9.0.3-19.el8.noarch
15:51:02  Problem 4: package authselect-compat-1.1-2.el8.x86_64 requires authselect(x86-64) = 1.1-2.el8, but none of the providers can be installed
15:51:02   - cannot install both authselect-1.2.1-2.el8.x86_64 and authselect-1.1-2.el8.x86_64
15:51:02   - problem with installed package authselect-compat-1.1-2.el8.x86_64
15:51:02   - cannot install the best update candidate for package authselect-1.1-2.el8.x86_64
15:51:02   - nothing provides authselect(x86-64) = 1.2.2-2.el8 needed by authselect-compat-1.2.2-2.el8.x86_64
15:51:02  Problem 5: package authselect-compat-1.1-2.el8.x86_64 requires authselect(x86-64) = 1.1-2.el8, but none of the providers can be installed
15:51:02   - package authselect-1.1-2.el8.x86_64 requires authselect-libs(x86-64) = 1.1-2.el8, but none of the providers can be installed
15:51:02   - package fprintd-pam-1.90.9-2.el8.x86_64 requires authconfig, but none of the providers can be installed
15:51:02   - cannot install both authselect-libs-1.2.1-2.el8.x86_64 and authselect-libs-1.1-2.el8.x86_64
15:51:02   - cannot install the best update candidate for package fprintd-pam-1.90.0-0.20191121gitf022902.el8.x86_64
15:51:02   - cannot install the best update candidate for package authselect-libs-1.1-2.el8.x86_64
15:51:02   - nothing provides authselect(x86-64) = 1.2.2-2.el8 needed by authselect-compat-1.2.2-2.el8.x86_64
15:51:02 (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
15:51:02 Failed at 44: sudo -E dnf -y update
```

The easiest way to solve this would be updating the image on Azure to use an image based on 8.4.
@GabyCT, is there such image on Azure or not yet?

**Comment by GabyCT** [comment]
@fidencio in azure images the latest image of centOS is 8.3

**Comment by fidencio** [comment]
> @fidencio in azure images the latest image of centOS is 8.3

Would be possible to try to change it to using https://azuremarketplace.microsoft.com/en-us/marketplace/apps/procomputers.centos-8-stream?tab=overview ?

Theoretically CentOS Stream should break less than the CentOS 8 one, as Stream is supposed to be a "rolling" one.

**Comment by fidencio** [comment]
> > @fidencio in azure images the latest image of centOS is 8.3
> 
> Would be possible to try to change it to using https://azuremarketplace.microsoft.com/en-us/marketplace/apps/procomputers.centos-8-stream?tab=overview ?
> 
> Theoretically CentOS Stream should break less than the CentOS 8 one, as Stream is supposed to be a "rolling" one.

By the way, doesn't have to be that one specifically, any CentOS 8 Stream would do. :-)

**Comment by GabyCT** [comment]
@fidencio it seems is working with 8.3 as I updated http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-centos-PR/636/console

**Comment by fidencio** [comment]
@GabyCT, which was the version in use? 8.2?

**Comment by GabyCT** [comment]
> @fidencio it seems is working with 8.3 as I updated http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-centos-PR/636/console

^8.3 @fidencio

**Comment by fidencio** [comment]
Okay, cool.
I think we'll have similar problems in the future, if that happens we should consider moving to CentOS 8 Stream / RHEL.

I'll close this one, thanks @GabyCT for updating the image.
