### ISSUE TITLE
add test to ensure qemu is not running if container start fails

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#360]
qemu and kata-proxy processes should not be up after running next command

```
docker run --runtime=kata-runtime -ti busybox does-not-exist
```

see https://github.com/kata-containers/runtime/pull/351
see https://github.com/kata-containers/runtime/pull/351#issuecomment-393536771

**Comment by jodh-intel** [comment]
Can we also check to ensure the proxy is also not running?

**Comment by devimc** [comment]
@jodh-intel done :smile:
