### ISSUE TITLE
kubernetes-e2e: e2e tests are running with runc instead of kata

### ISSUE THREAD

**Issue by MatthieuSarter** [kata-containers/tests#3639]
# Description of problem

When running the kubernetes-e2e test, all the pods are using runc.

# Expected result

k8s system pods and sonobuoy pods should be running with runc and e2e tests pods should use kata.

# Further information

Reproduced on Ubuntu 16.04 ppc64le and Fedora 32 x86-64.
Issue is likely related to a TLS certificate error seen in the kata webhook pod output :

```
[root@largo containers]# head pod-annotate-webhook-6c69b6d9d7-7dm8t_default_pod-annotate-webhook-142a37ab8adbec34e896e2707a2c72d22137ef7276eb5f684b7b322ec69f67ea.lo
2021-06-22T10:22:24.34202598+02:00 stderr F 2021/06/22 08:22:24 [WARN] no metrics recorder active
2021-06-22T10:22:24.34203763+02:00 stderr F 2021/06/22 08:22:24 [WARN] no tracer active
2021-06-22T10:22:24.342796763+02:00 stderr F 2021/06/22 08:22:24 [INFO] Listening on :8080
2021-06-22T10:22:27.902011401+02:00 stderr F 2021/06/22 08:22:27 http: TLS handshake error from 10.244.0.1:23875: remote error: tls: bad certificate
2021-06-22T10:22:27.911453985+02:00 stderr F 2021/06/22 08:22:27 http: TLS handshake error from 10.244.0.1:12515: remote error: tls: bad certificate
2021-06-22T10:22:41.689126478+02:00 stderr F 2021/06/22 08:22:41 http: TLS handshake error from 10.244.0.1:62256: remote error: tls: bad certificate
2021-06-22T10:22:50.185572852+02:00 stderr F 2021/06/22 08:22:50 http: TLS handshake error from 10.244.0.1:16111: remote error: tls: bad certificate
2021-06-22T10:23:04.119569956+02:00 stderr F 2021/06/22 08:23:04 http: TLS handshake error from 10.244.0.1:65059: remote error: tls: bad certificate
2021-06-22T10:23:04.124541647+02:00 stderr F 2021/06/22 08:23:04 http: TLS handshake error from 10.244.0.1:53511: remote error: tls: bad certificate
2021-06-22T10:24:06.776421376+02:00 stderr F 2021/06/22 08:24:06 http: TLS handshake error from 10.244.0.1:61828: remote error: tls: bad certificate
```

**Comment by fidencio** [comment]
@wainersm, this was seen downstream AFAIR.  Do you remember what was done to work this around / fix the issue?

**Comment by wainersm** [comment]
Unfortunately I don't remember @fidencio .

I have been using the webhook on OpenShift CI for a while now without problems. @MatthieuSarter could you please give us more details about your usage? Did you make any changes to the webhook?

Apart from that, one immediate improvement to `kubernetes-e2e` would be to check if the webhook is working properly after its installation. This way it won't silently let us run the tests with runc. I can work on that as I make such as checking on OpenShift CI, so I got some code.

**Comment by MatthieuSarter** [comment]
> @MatthieuSarter could you please give us more details about your usage? Did you make any changes to the webhook?

I'm working on a Power system to run Kata CI. I tried to run the CRI_CONTAINERD_K8S_MINIMAL job on an Ubuntu 16.04 ppc64le system, and I noticed while it was running that all the container were running with runc.

Here are the env variables that are set on my system before calling ci_entry_point.sh:
```
  export BAREMETAL=true
  export DEBUG=true
  export SHIMV2_TEST="true"
  export KATA_DEV_MODE="true"
  export TEST_INITRD="yes"
  export AGENT_INIT="yes"
  export LIBC="gnu"

```

I then tried on a Fedora 32 x86-64 VM to see if the issue was specific to ppc64le, and I got the same issue.

On the pcc64le system I used a kata-webhook image that I built myself, it required some change in the Dockerfile (I had to move the ../vendor directory the same directory as the Dockerfile and add a `go mod init` command before the `go build`), but I did not change the Go code, the create-certs.sh script or the deployment YAML files.

On the x86-64 system, I used the default image, from DockerHub.

**Comment by wainersm** [comment]
@MatthieuSarter got it, thanks for the detailed information on your usage.

Today I was able to reproduce the problem on Kata CI. See https://github.com/kata-containers/tests/pull/3647#issuecomment-867653398

Interesting on OpenShift CI I have the webhook (apparently) working. For example, scroll down to the end of the logs [in here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-kata-containers-kata-containers-main-e2e-tests/1407957212520779776/artifacts/e2e-tests/kata-containers-e2e-pre/build-log.txt). And I am using the default image from DockerHub too, the only difference seems to be that I use CRI-O instead containerd.

Anyway, that TLS error occurred while ago on our downstream CI. I will look for more information and let you posted.

**Comment by wainersm** [comment]
FYI, On my local system I downgraded sonobouy and kubernetes to the previous used versions, respectively, 0.18.5 and 1.18.9-00; as a result the webhook started to work again.

**Comment by MatthieuSarter** [comment]
Thanks for the idea @wainersm , I tried this on my system, but I only downgraded kubernetes (older versions of sonobuoy have not been ported to ppc), and it's enough to avoid the TLS issue, and I can see that the sonobuoy e2e pod gets mutated to kata, which confirms the webhook is processing request (but the sonobuoy pods should not be mutated, I will open an issue about this, I think there is a missing return there : https://github.com/kata-containers/tests/blob/505c4adb0ad54600a3acc23f4fefbe80eebad95d/kata-webhook/main.go#L61 ).
