### ISSUE TITLE
ARM CI failing randomly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#3644]
ARM CI is failing constantly with the following error

```
bash integration/containerd/cri/integration-tests.sh
INFO: Stop crio service
INFO: Stop containerd service
Job for containerd.service canceled.
ERROR: containerd log :
-------------------------------------
cat: /tmp/test-cri-containerd.KAxJ/containerd.log: No such file or directory
Makefile:138: recipe for target 'cri-containerd' failed
make: *** [cri-containerd] Error 1
Failed at 28: sudo -E PATH="$PATH" bash -c "make cri-containerd"
Build step 'Execute shell' marked build as failure
```
/cc @jongwu @bergwolf @liubin

**Comment by jongwu** [comment]
Thanks @GabyCT -,  I have noticed this issue. it results from "Start request repeated too quickly" issue. let me try to workaround it.

**Comment by GabyCT** [comment]
@jongwu any updates with this issue? I see that ARM CI is still failing constantly 
11:48:39 Running hypervisor stability test
11:48:41 Ending hypervisor stability test
11:48:42 INFO: Containerd checks
11:48:43 bash integration/containerd/cri/integration-tests.sh
11:48:43 INFO: Stop crio service
11:48:43 INFO: Stop containerd service
11:48:43 Job for containerd.service canceled.
11:48:43 ERROR: containerd log :
11:48:43 ------------------------------

**Comment by jongwu** [comment]
thanks @GabyCT -, I try to fix it at [this](https://github.com/kata-containers/tests/pull/3651),  I see you have got it.

**Comment by jongwu** [comment]
> Thanks @GabyCT -, I have noticed this issue. it results from "Start request repeated too quickly" issue. let me try to workaround it.

The root cause of this issue is related with the conflict of the services which can stop containerd service and containerd service itself when they may stop containerd service at the same time.
