### ISSUE TITLE
CI check for guest kernel is fragile against configuration changes

### ISSUE THREAD

**Issue by dgibson** [kata-containers/tests#3754]
# Description of problem

To speed things up, instead of building a guest kernel on every run, the CI caches guest kernels.  The logic used to determine if it can use a cached kernel is simply:
```
    if [ "$cached_kernel_version" == "$current_kernel_version" ] && [ "$kernel_arch" == "x86_64" ]; then
```

Which means it will only rebuild if the kernel version changes.  That won't detect changes in the kernel configuration, which is generated from `tools/packaging/kernel` in the kata-containers repository.

That means that any change to that config submitted, will not be tested properly by the CI.

**Comment by jodh-intel** [comment]
> That won't detect changes in the kernel configuration

@dgibson - I was about to say that changes would be detected, but it looks like we broke that check :cry: In the old packaging repo we have:

- https://github.com/kata-containers/packaging/blob/master/.ci/test.sh#L39..L56

... But that CI check doesn't exist in:

- https://github.com/kata-containers/kata-containers/tree/main/ci

/cc @GabyCT, @jcvenegas.

**Comment by dgibson** [comment]
Ah.. so I did miss the fact that there's a "kernel config version" that's folded into the `$current_kernel_version`.  Requiring a manual increment on that seems awkward and error-prone compared to just diffing the configs themselves, though.

**Comment by dgibson** [comment]
Requiring a manual increment of the config version *is* error-prone, but it's usable.  So closing this issue.
