### ISSUE TITLE
install_kata_kernel.sh is overly complex

### ISSUE THREAD

**Issue by dgibson** [kata-containers/tests#3758]
# Description of problem

`.ci/install_kata_kernel.sh` is used to download or build a kernel for use by Kata created guests in the CI.  At the moment it has quite a lot of extraneous logic which makes it harder than necessary to read and update.

**Comment by c3d** [comment]
Hi @dgibson. I think that many of us felt that pain. Do you think that we can subdivide that into more actionable sub-items? Can we create a "project" like we did for things like tracing?

**Comment by dgibson** [comment]
Well, the PR I sent for this is already broken up into a number of individual patches.  I'd rather focus on actually doing rather than writing a lot about the problems.
