### ISSUE TITLE
Vagrant fedora machine does not come up

### ISSUE THREAD

**Issue by dgibson** [kata-containers/tests#3760]
# Description of problem

With the draft pull request I was able to bring up a Fedora based VM for running CI tests using `vagrant up fedora`.  However with the merged version of the vagrant patches, attempting to bring up the Fedora VM no longer works (the Ubuntu based one seems to get further).

# Expected result

```
$ vagrant up fedora
$ vagrant ssh fedora
```

Can then use the fedora VM.

# Actual result

```
$ vagrant up fedora
[ . . . ]
$ vagrant ssh fedora
==> fedora: Running action triggers before ssh ...
==> fedora: Running trigger...
==> fedora: Domain is not created. Please run `vagrant up` first.
```

# Further information

Full transcript to follow.

**Comment by dgibson** [comment]
[vagrant-fedora-failure.txt](https://github.com/kata-containers/tests/files/6884662/vagrant-fedora-failure.txt)

**Comment by wainersm** [comment]
Hi @Jakob-Naucke ! The commit  https://github.com/kata-containers/tests/commit/26cef9d550dbee1ced48acbcaafaf594cc653b18 broke the vagrant stuff for Fedora. Is there a variable or some other mean of not force Podman with Fedora?

**Comment by Jakob-Naucke** [comment]
I don't think that was the underlying issue at the time this was created, but I'm happy to help :slightly_smiling_face:
So the behaviour of `kata-containers/tools/osbuilder/rootfs-builder/rootfs.sh` is: When `$USE_DOCKER` or `$USE_PODMAN` is set, try to build guest with that container engine. If neither is set, try to use the host `debootstrap`/`dnf`.
Before https://github.com/kata-containers/tests/commit/26cef9d550dbee1ced48acbcaafaf594cc653b18, the behaviour of `tests/.ci/install_kata_image.sh` was to always `$USE_DOCKER`.
After the merge of that, the behaviour is to `$USE_DOCKER` except on Fedora-likes, where `$USE_PODMAN` is set.

So,
> Is there a variable or some other mean of not force Podman with Fedora?

you want to use neither or use Docker instead (like it was before)? I'm curious what's happening with Podman that breaks it.

**Comment by wainersm** [comment]
> So,
> 
> > Is there a variable or some other mean of not force Podman with Fedora?
> 
> you want to use neither or use Docker instead (like it was before)? I'm curious what's happening with Podman that breaks it.

I revert the patch and it started to work; that made me think it was related with Podman. I wanted to double-check that, so I need a way of setting `USE_DOCKER=yes` and this really be honored even if in Fedora.

Btw, that's the error that I am getting:
```
[install_kata_image.sh:42] INFO: Building image with AGENT_INIT=no
Creating rootfs for ubuntu
/home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/rootfs.sh -o 2.2.0-rc0-f3539d2fb7668aa557fead555a5fff6854f723eb-dirty -r /home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/ubuntu_rootfs ubuntu
INFO: rootfs_lib.sh file found. Loading content
INFO: Detecting agent rust version
INFO: Get rust version from /home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/../../../versions.yaml
Required rust version: 1.47.0
INFO: Detecting musl version
INFO: Get musl version from /home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/../../../versions.yaml
Required musl version: 1.1.23
/home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/ubuntu /home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder
/home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder
STEP 1: FROM docker.io/ubuntu:20.04
Getting image source signatures
Copying blob 16ec32c2132b done  
Copying config 1318b700e4 done  
Writing manifest to image destination
Storing signatures
STEP 2: RUN apt-get update && apt-get --no-install-recommends install -y     apt-utils     autoconf     automake     binutils     build-essential     ca-certificates     chrony     coreutils     curl     debianutils     debootstrap     g++     gcc     git     libc6-dev     libstdc++-8-dev     m4     make     musl     musl-dev     musl-tools     protobuf-compiler     sed     systemd     tar     vim     wget
2021-08-30T21:13:01.000430303Z: sd-bus call: Transport endpoint is not connected
error running container: error creating container for [/bin/sh -c apt-get update && apt-get --no-install-recommends install -y     apt-utils     autoconf     automake     binutils     build-essential     ca-certificates     chrony     coreutils     curl     debianutils     debootstrap     g++     gcc     git     libc6-dev     libstdc++-8-dev     m4     make     musl     musl-dev     musl-tools     protobuf-compiler     sed     systemd     tar     vim     wget]: : exit status 1
Error: error building at STEP "RUN apt-get update && apt-get --no-install-recommends install -y     apt-utils     autoconf     automake     binutils     build-essential     ca-certificates     chrony     coreutils     curl     debianutils     debootstrap     g++     gcc     git     libc6-dev     libstdc++-8-dev     m4     make     musl     musl-dev     musl-tools     protobuf-compiler     sed     systemd     tar     vim     wget": error while running runtime: exit status 1
make: *** [Makefile:93: /home/vagrant/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done] Error 125
[install_kata_image.sh:50] ERROR: sudo -E USE_DOCKER= DISTRO=ubuntu make -e image
[install_kata.sh:22] ERROR: .ci/install_kata_image.sh 

```

**Comment by wainersm** [comment]
@Jakob-Naucke IIUC since 26cef9d550dbee1ced48a docker is not installed on Fedora? Is it true? If so, we have another problem... docker is used to build the static-qemu.

**Comment by Jakob-Naucke** [comment]
> I revert the patch and it started to work; that made me think it was related with Podman. I wanted to double-check that, so I need a way of setting `USE_DOCKER=yes` and this really be honored even if in Fedora.

That is understandable and deserves a fix. Let me get back to you. However, I would appreciate it if it could be made to work with Podman, since you cannot really get Docker on Fedora-likes on the IBM architectures.

> `sd-bus call: Transport endpoint is not connected`

That definitely rings a bell, but its appearance was... irregular. I think at the time this happened to me, I rebooted the instance and it went away (I know that's very unsatisfactory, it's all I can gather from my notes now, which are about a month old).

> since [26cef9d](https://github.com/kata-containers/tests/commit/26cef9d550dbee1ced48acbcaafaf594cc653b18) docker is not installed on Fedora? Is it true? If so, we have another problem... docker is used to build the static-qemu.

It's true that I intended to no longer install Docker on Fedora. However, static-qemu can be built with Podman too: https://github.com/kata-containers/kata-containers/pull/2068

**Comment by marcel-apf** [comment]
@Jakob-Naucke just fire-up a Fedora machine and run the .ci/setup.sh script (after making the necessary tweaks)
It will just fail to run.
I think this kind of test should be a routine when adding new features, meaning that if it works only in CI it does not really help us since we don't have it in our machines.

**Comment by Jakob-Naucke** [comment]
@marcel-apf yes, I can reproduce this now, and I'm looking into it. However, I am definitely sure I had it working on a dev machine. Anyway, here's #3902.

**Comment by Jakob-Naucke** [comment]
This happens when runc is installed -- it works with crun, which is installed as a dependency by Fedora. My changes **install** runc rather than removing it, let me see why I did that.

**Comment by marcel-apf** [comment]
> @marcel-apf yes, I can reproduce this now, and I'm looking into it. However, I am definitely sure I had it working on a dev machine. Anyway, here's #3902.

@Jakob-Naucke thanks for the fix! Acked it.
Please cc me when you find a fix for the podman/fedora scenario.

**Comment by wainersm** [comment]
Fedora 32 onward defaults to cgroups v2 and some tools don't like it (old versions of Docker, for example). The image on CI is tweaked to use cgroups v1 instead, that's why @Jakob-Naucke 's pull requests passed but on a vanilla image (i.e. cgroups v2) it fails.

On the Vagrantfile that I maintain, the VM switch back to cgroups v1 (that needs reboot). However it executes the setup script before the reboot (i.e. still cgroups v2) and, for some unknown reason to me,  Podman has failed to build the osbuilder image.

@Jakob-Naucke I am finding a way to stick with Podman on the Fedora with Vagrant, regardless I like your https://github.com/kata-containers/tests/pull/3902 because it gives flexibility to users.
