### ISSUE TITLE
stable-2.1 | CI is failing after bumping containerd

### ISSUE THREAD

**Issue by snir911** [kata-containers/tests#3763]
This is a description of the CI failure which blocks the [containerd bumping on kata-containers/stable-2.1](https://github.com/kata-containers/kata-containers/pull/2222) (and as a result blocking backporting (e.g. https://github.com/kata-containers/kata-containers/pull/2226) and release efforts)

# Description of problem

After bumping containerd to v3.1.10 (https://github.com/kata-containers/kata-containers/pull/2222), trying to adapt tests on stable-2.1 (#3744) makes the **jenkins-ci-ubuntu-20-04** job to fail

# Expected result

all tests on #3744 should pass

# Actual result

**jenkins-ci-ubuntu-20-04** on https://github.com/kata-containers/tests/pull/3744 (which #depends-on [containerd bumping](https://github.com/kata-containers/kata-containers/pull/2222)) is [failing](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu20.04-PR/361/) with:
```
14:21:40     failed to remove container: rpc error: code = Unknown desc = failed to set removing state for container "a62d6b93cd87513b6c51a31e25298c6bbee21bacd41f4be7f162633dd9feb6da": container is still running, to stop first
14:21:40     Unexpected error:
14:21:40         <*status.statusError | 0xc00030a5f0>: {
14:21:40             Code: 2,
14:21:40             Message: "failed to set removing state for container \"a62d6b93cd87513b6c51a31e25298c6bbee21bacd41f4be7f162633dd9feb6da\": container is still running, to stop first",
14:21:40             Details: nil,
14:21:40             XXX_NoUnkeyedLiteral: {},
14:21:40             XXX_unrecognized: nil,
14:21:40             XXX_sizecache: 0,
14:21:40         }
14:21:40         rpc error: code = Unknown desc = failed to set removing state for container "a62d6b93cd87513b6c51a31e25298c6bbee21bacd41f4be7f162633dd9feb6da": container is still running, to stop first
14:21:40     occurred
```

# Further information

in #3744

**Comment by c3d** [comment]
@snir911 It looks like the PRs were merged. Did you get the CI to pass? If so, can we close this, or is there still a problem?

**Comment by snir911** [comment]
@c3d CI is still failing, bumping containerd in now included in https://github.com/kata-containers/kata-containers/pull/2226
