### ISSUE TITLE
ss command core dumps in one particular CI job

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#3774]
For reasons unknown the `ss(1)` command core dumps when running in the `jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal` job. For example, from that job's CI log (part of https://github.com/kata-containers/kata-containers/pull/1809):

```
17:20:06 + ss -Hp --vsock
17:20:06 tracing/test-agent-shutdown.sh: line 556: 13682 Segmentation fault      (core dumped) agent_addr=$(get_agent_vsock_address || true)
17:20:06 + true
17:20:06 + info 'agent-ctl log file'
```

I cannot reproduce this locally, so the shutdown test added on https://github.com/kata-containers/kata-containers/pull/1809 is going to have to be a NOP on the 18.04 containerd k8s job for now.

**Comment by GabyCT** [comment]
Closing this issue as we do not longer support that CI
