### ISSUE TITLE
Also run the firecracker tests using the jailer

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#3802]
The current tests we have for firecracker (https://github.com/kata-containers/ci/tree/master/jenkins/jobs/kata-containers-2.0-firecracker-ubuntu-PR) are running using the default kata-container configuration, which has the jailer binary commented out.

However, we've hit issues recently that could've been avoided (or we could've noticed earlier) if the we ran the tests using the jailer (please, refer to: https://github.com/kata-containers/kata-containers/issues/2387).

When thinking about the tests we can either have a second CI, a clone of the first CI, but running the tests with the jailer ... or we can do a double pass in the very same CI, just changing the kata-containers configuration file to uncomment the jailer line.

In any case, we can take advantage of https://github.com/kata-containers/tests/blob/main/.ci/set_kata_config.sh in order to enable the jailer.

**Comment by devimc** [comment]
according to this:  https://github.com/kata-containers/kata-containers/blob/e07a9fea793834804cae95ffa178dc88102a6f90/src/runtime/cli/config/configuration-fc.toml.in#L33-L35

```
# This is disabled by default as additional setup is required
# for this feature today.
#jailer_path = "@FCJAILERPATH@"
```

what kind of additional setup is required? I dunno :man_shrugging:

**Comment by fidencio** [comment]
> according to this: https://github.com/kata-containers/kata-containers/blob/e07a9fea793834804cae95ffa178dc88102a6f90/src/runtime/cli/config/configuration-fc.toml.in#L33-L35
> 
> ```
> # This is disabled by default as additional setup is required
> # for this feature today.
> #jailer_path = "@FCJAILERPATH@"
> ```
> 
> what kind of additional setup is required? I dunno man_shrugging

Let's figure it out in a few minutes. :-)
