### ISSUE TITLE
Create an "arch" script that is cleverer than arch(1)

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#382]
`arch(1)` (or `uname -m`) are useful but certain parts of the system require the golang `GOARCH` value instead:

https://golang.org/doc/install/source#environment

Create a script (`kata-arch.sh` ?) in this repo that other repos can call that:

- does not require `golang` to be installed.
- calls `arch(1)` and maps the output values like `x86_64` or `aarch64` to their `GOARCH` equivalents (`amd64`, `arm64`).

This shouldn't be a huge maintenance burden, particularly if there is only a single centralised utility to handle the mapping.

Related:

- https://github.com/kata-containers/documentation/issues/140
- https://github.com/kata-containers/ci/issues/35
- https://github.com/kata-containers/documentation/issues/128

/cc @grahamwhaley, @Pennyzct, @nitkon, @chavafg.

**Comment by jodh-intel** [comment]
@nitkon - regarding https://github.com/kata-containers/documentation/issues/140#issuecomment-395057299, maybe we could have options like:

- Intel:
  ```
  $ kata-arch.sh [--default]
  x86_64
  $ kata-arch.sh --kernel
  x86_64
  $ kata-arch.sh --golang
  amd64
  ```
- PPC64el:
  ```
  $ kata-arch.sh [--default]
  ppc64le
  $ kata-arch.sh --kernel
  powerpc
  $ kata-arch.sh --golang
  ppc64le
  ```

**Comment by nitkon** [comment]
@jodh-intel : Yes looks good.

**Comment by Pennyzct** [comment]
Lgtm👍
Following the format in arm arch:
$ kata-arch.sh [--default]
arm64
$ kata-arch.sh --kernel
arm64
$ kata-arch.sh --golang
arm64
