### ISSUE TITLE
metrics: Ubuntu based metrics probably don't disable auto updates

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#387]
I think I noticed during a metrics run last week that our Ubuntu based metrics tests (which I think means in particular anything that is constructed through a Dockerfile such as https://github.com/kata-containers/tests/blob/master/metrics/storage/blogbench_dockerfile/Dockerfile#L8, have not disabled the Ubuntu auto updater package. This has two potential effects:
 - if we do any apt actions in the container then that can fail due to a resource clash for the apt lock
 - if we are running metrics (which we no doubt are...), then the auto update is likely in the background consuming resource and time - that will inject noise into our results.

There are a number of ways to disable this - I am currently using:
```
apt remove -y unattended-upgrades
```

for the metrics VMs.
Can we have a scan of the code base to identify any tests that could be suffering from this, maybe verify that this is a real concern, and then apply the package remove to ensure we do not run into this.

**Comment by grahamwhaley** [comment]
@GabyCT - can you have a look at this please. I had a look at the memory-in-container test, and that is Alpine, so I suspect safe from this. I know the blogbench test may suffer though - not sure if there are others.

**Comment by GabyCT** [comment]
@grahamwhaley , I will review this :)
