### ISSUE TITLE
ci: vfio: dependencies resolving is failing not on main

### ISSUE THREAD

**Issue by snir911** [kata-containers/tests#3889]
# Description of problem

When you add a depends-on not on the main branch, vfio ci will fail to fetch the correct branch and apply the depended patch

# Expected result

all dependencies will be resolved correctly

# Actual result

depended are merged wrongly with main branch and messes the code

# Further information

For example, i received the following error when depends-on was applied on stable-2.1
`ci/jenkins_job_build.sh: line 165: .ci/ci_job_flags.sh: No such file or directory`

**Comment by GabyCT** [comment]
@snir911 I believe that the failure on `vfio` CI was due to a lack of backporting as it was fixed

**Comment by GabyCT** [comment]
This was fixed on https://github.com/kata-containers/tests/commit/e0e6dd94f39c8d60587530f2c96f2009725de6a2
