### ISSUE TITLE
Storing and pushing the custom stress image fails on Ubutnu

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/tests#3899]
When running the K8s tests with crio, the deafult container engine used is docker on Ubuntu(or non fedora likes). Starting the registry container [here](https://github.com/kata-containers/tests/blob/435563e2dba252d9af217185f58dc52f77e9e75e/integration/kubernetes/init.sh#L119) fails because containerd service is stopped above. 
```
Store custom stress image in registry
b5a329a9d86c964db436323f0b16332a3cd9317aee1861a21335a7d4a347d63b
docker: Error response from daemon: connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: tim
eout": unavailable.
[init.sh:128] ERROR: sudo -E docker run -d -p 5000:5000 --name kata-registry docker.io/ibmcom/registry:2.6.2.5
[run_kubernetes_tests.sh:62] ERROR: ./init.sh
[preflight] Running pre-flight checks
```
I encountered this on Ubuntu 20.04(ppc64le). Didn't have an x86 ubuntu system to check for the same.

**Comment by wainersm** [comment]
@Amulyam24 FYI, I ran the k8s tests with crio locally on Fedora, I don't see that error so it is likely a ubuntu-only (docker actually) problem.

Instead I get the following error message (which don't drive the run to fail, though):
```
Error: failed to evict container: "": failed to find container "kata-registry" in state: no container with name or ID kata-registry found: no such container
```

btw, you may want to use [this](https://github.com/kata-containers/tests/#using-vagrant-to-test-your-code-changes) to reproduce the job locally; that will help me to develop further that feature :)

**Comment by Amulyam24** [comment]
> @Amulyam24 FYI, I ran the k8s tests with crio locally on Fedora, I don't see that error so it is likely a ubuntu-only (docker actually) problem.
> 

Hi @wainersm. Yes, the tests run fine with crio on Fedora since they use podman by default.
> Instead I get the following error message (which don't drive the run to fail, though):
> 
> ```
> Error: failed to evict container: "": failed to find container "kata-registry" in state: no container with name or ID kata-registry found: no such container
> ```
> 
I didn't come across this error but I've been coming across the not proper cleaning up of kata-registry container which doesn't cause the CI to fail but might pose as a blocker to the stability tests with containerd jobs.
> btw, you may want to use [this](https://github.com/kata-containers/tests/#using-vagrant-to-test-your-code-changes) to reproduce the job locally; that will help me to develop further that feature :)

Sure, I've been trying to reproduce [this error](https://github.com/kata-containers/tests/pull/3900#issuecomment-909915800) locally. Using Vagrant should help me better. Thanks :)
