### ISSUE TITLE
ci: Improve the vfio-jenkins job

### ISSUE THREAD

**Issue by marcel-apf** [kata-containers/tests#3907]
There is no need to compile the QEMU in order to run the vfio VM, use the regular distro qemu-kvm.
The CI will run faster.

**Comment by devimc** [comment]
really? but how we will know that the version of QEMU that we are shipping through snap or kata deploy supports VFIO ? :thinking: 

cc @jcvenegas @fidencio @GabyCT

**Comment by devimc** [comment]
ignore my last comment, `vfio VM` is the VM that runs on the host, not the kata container, sorry
