### ISSUE TITLE
Random failures in ARM at k8s quota test

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#3932]
I have seen some failures at ARM CI with the following issue
```
10:57:16 not ok 1 Pod quota
10:58:53 # (in test file k8s-pod-quota.bats, line 31)
10:58:53 #   `kubectl wait --for=condition=Available --timeout=$timeout \' failed
10:58:53 # [bats-exec-test:23] INFO: k8s configured to use runtimeclass
10:58:53 # namespace/test-quota-ns created
10:58:53 # resourcequota/pod-quota created
10:58:53 #     pods: "2"
10:58:53 #     pods: "2"
10:58:53 # deployment.apps/deploymenttest created
10:58:53 # error: timed out waiting for the condition on deployments/deploymenttest
10:58:53 # deployment.apps "deploymenttest" deleted
10:58:53 # namespace "test-quota-ns" deleted
10:58:53 # resourcequota "pod-quota" deleted
10:58:53 [run_kubernetes_tests.sh:65] ERROR: bats k8s-pod-quota.bats
```
see http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/1271/
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/1272/
/cc @wainersm @jongwu

**Comment by wainersm** [comment]
@GabyCT let's revert one of my changes for now.

@jongwu The changes on the test that I am reverting may spot issues on ARM, or it can be that the quota values are too narrow for the workload on arm. Either way I don't have hardware at the moment to check it. So if you would have a look (and perhaps test it) I will appreciate it.

**Comment by jongwu** [comment]
Hello @wainersm -, I see that change will request cpu, however, cpu hotplug is not supported on Arm. I think that maybe the root cause of the failure.

**Comment by wainersm** [comment]
> Hello @wainersm -, I see that change will request cpu, however, cpu hotplug is not supported on Arm. I think that maybe the root cause of the failure.

@egernst ^

Thanks @jongwu !

An alternative for re-introduce the test is to skip that scenario on ARM. I will add it to my TODO list.
