### ISSUE TITLE
checkcommits: should not inspect the subject line of revert commit

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#3934]
**Which feature do you think can be improved?**

The checkcommits (cmd/checkcommits/checkcommits.go) program can be improved such as commits originated from `git revert` should be accepted without following the commit's subject rules.

For example, I just faced the following problem when I tried to revert a commit to the tests repo:
1. I did `git revert 3622e70b6fd160573b1127ba1fe3bc1fb2198ddc`
2. The subject line (auto-created by git) is *Revert "integration/kubernetes: Add cpu/memory constraints in resource quota"*
3. I edited the commit to include the *Fixes* and *Signed-off-by* tags, then git push
4. The *static-checks* job first complained about the lack of subsystem in the subject line
```
ERROR: Commit 1d80dcd: Failed to find subsystem in subject: "Revert "integration/kubernetes: Add cpu/memory constraints in resource quota""  
```
5. I changed the subject line to *k8s: Revert "integration/kubernetes: Add cpu/memory constraints in resource quota"*
6. git push. Now the static-checks complains about the subject being too long
7. I changed the subject line again, to *k8s: Revert "Add cpu/memory constraints in resource quota"*
8. git push. Now it is all fine.

**How can it be improved?**

IMHO the checkcommits should not inspect the line with pattern `^Revert ".*"`. In other words, it should be allowed commits with subject line auto-created by `git revert`.

**Comment by wainersm** [comment]
@GabyCT what do you think?

**Comment by fidencio** [comment]
fwiw, +1 for the proposal.

**Comment by wainersm** [comment]
@fidencio btw, changes on the process such as that should pass through the board revision?

**Comment by fidencio** [comment]
> @fidencio btw, changes on the process such as that should pass through the board revision?

/cc @kata-containers/architecture-committee for input

It should only go to the architecture committee meeting if there's some disagreement that only could be solved there.  Otherwise, business as usual. :-)

**Comment by egernst** [comment]
This proposal seems fine to me.

**Comment by GabyCT** [comment]
thank you @wainersm , I like the idea :)

**Comment by jodh-intel** [comment]
Agreed - good idea! I'll create a PR...
