### ISSUE TITLE
"vagrant up fedora" does not work on Ubuntu 20.04 host

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#3942]
The `vagrant up fedora` command fails on Ubuntu 20.04 with the following error:
```
Vagrant attempted to execute the capability 'reboot'
on the detect guest OS 'fedora', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```
@Jakob-Naucke  reported the issue here: https://github.com/kata-containers/tests/pull/3923#issuecomment-912672427

Currently it is required to configure the Fedora guest with cgroups v1 and that requires a reboot. Vagrant on Ubuntu host seems unable to reboot guests (whether Fedora or Ubuntu guests doesn't matter, it still fails).

`vagrant up ubuntu` on Ubuntu host works fine as it doesn't require reboot.

Possible solutions:

1. (mitigation actually) Mentions in https://github.com/kata-containers/tests/blob/main/README.md#using-vagrant-to-test-your-code-changes that `vagrant up fedora` on Ubuntu host is not supported.
2. Setup an account on [Vagrant cloud](https://app.vagrantup.com) to store a version of the Fedora's box with cgroups v1 enabled, therefore we just fetch the image and no reboot is needed.
3. Work to get the CI scripts running on Fedora with cgroups v2. That would be the best solution IMHO.

**Comment by cpmeadors** [comment]
Removing need-reveiw and assigning to @wainersm
