### ISSUE TITLE
ci failure related to tracing/test-agent-shutdown.sh

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#3978]
Cargo command is not found and there is an additional permissions error in 2 tests. I think it is related to https://github.com/kata-containers/tests/commit/ca718a600954323cfe95624913e880f2c59543d9 which was recently merged. @Jakob-Naucke 

jenkins-ci-pmem-ubuntu-18-04:
```
+ local cargo=/home/jenkins/.cargo
+ '[' -d /home/jenkins/.cargo ']'
+ sudo chown -R jenkins: /home/jenkins/.cargo /tmp/jenkins/workspace/kata-containers-2.0-pmem-ubuntu-20.04-PR/go/src/github.com/kata-containers/kata-containers
+ cargo --version
tracing/test-agent-shutdown.sh: line 774: cargo: command not found
+ /tmp/jenkins/workspace/kata-containers-2.0-pmem-ubuntu-20.04-PR/go/src/github.com/kata-containers/tests/tracing/../.ci/install_rust.sh
Install rust 1.54.0
info: downloading installer
error: could not write settings file: '/home/jenkins/.rustup/settings.toml': Permission denied (os error 13)
[install_rust.sh:25] ERROR: sh -s -- -y --default-toolchain 1.54.0
```

jenkins-ci-ubuntu-20-04:
```
+ local cargo=/home/jenkins/.cargo
+ '[' -d /home/jenkins/.cargo ']'
+ sudo chown -R jenkins: /home/jenkins/.cargo /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-PR/go/src/github.com/kata-containers/kata-containers
+ cargo --version
tracing/test-agent-shutdown.sh: line 774: cargo: command not found
+ /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-PR/go/src/github.com/kata-containers/tests/tracing/../.ci/install_rust.sh
Install rust 1.54.0
info: downloading installer
error: could not write settings file: '/home/jenkins/.rustup/settings.toml': Permission denied (os error 13)
[install_rust.sh:25] ERROR: sh -s -- -y --default-toolchain 1.54.0
```

**Comment by cmaf** [comment]
see https://github.com/kata-containers/kata-containers/pull/2620

**Comment by cmaf** [comment]
@GabyCT should we revert this commit until it can be further debugged?

**Comment by GabyCT** [comment]
@Jakob-Naucke could you please take a look?

**Comment by GabyCT** [comment]
@cmaf yes a revert can be done or if @Jakob-Naucke has the solution that can help too

**Comment by GabyCT** [comment]
the issue is also seen on metrics
```
14:31:11 Fails: 0, Passes 2
14:31:11 Move results
14:31:11 tracing/test-agent-shutdown.sh: line 774: cargo: command not found
14:31:13 Install rust 1.54.0
```

**Comment by GabyCT** [comment]
@cmaf regarding to that test why we need to run it on those CIs? (pmem, metrics,  vfio)

**Comment by cmaf** [comment]
@GabyCT it should run before the tracing test to make sure the agent shut down properly (see https://github.com/kata-containers/tests/pull/3495), however, the tracing test does not test agent tracing yet, only runtime. We **could** disable the test instead of reverting the commit. I actually don't know why those CIs were chosen since the tracing test currently runs with **jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal**.  @jodh-intel might be able to answer. 

Somewhat related, the tracing tests, once expanded, might need their own job. Otherwise we can add them to tests with the relevant architectures.

**Comment by cmaf** [comment]
@GabyCT I'm leaning towards reverting the commit since in https://github.com/kata-containers/tests/pull/3813 there seem to be some open PRs related to the agent shutdown test in the comments (https://github.com/kata-containers/kata-containers/pull/2399)

**Comment by GabyCT** [comment]
> @GabyCT I'm leaning towards reverting the commit since in #3813 there seem to be some open PRs related to the agent shutdown test in the comments ([kata-containers/kata-containers#2399](https://github.com/kata-containers/kata-containers/pull/2399))

thanks @cmaf , I open the issue https://github.com/kata-containers/tests/issues/3980 /cc @jodh-intel
