### ISSUE TITLE
tracing/test-agent-shutdown.sh  running on multiple CIs

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#3980]
@jodh-intel any idea why that test is running on multiple CIs like `pmem` `vfio` `metrics` etc. This is related to issue 
https://github.com/kata-containers/tests/issues/3978

**Comment by GabyCT** [comment]
According to @cmaf the test should run only in one  jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal

**Comment by cmaf** [comment]
@jodh-intel @GabyCT, yeah if it is supposed to only run prior to the existing tracing test, then it should run there, unless there are plans to move the tracing test to these CIs.

**Comment by GabyCT** [comment]
@cmaf no we do not want to run that test on `metrics` `pmem` at least could you make that change

**Comment by cmaf** [comment]
@GabyCT understood, do you want me to change that now or wait for @jodh-intel to comment?

**Comment by GabyCT** [comment]
lets wait to @jodh-intel answer thanks

**Comment by cmaf** [comment]
Ok. I see a comment in the test related to why it's not in  jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal:
```
        # For reasons unknown the ss(1) command core dumps when running in the
        # "jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal" job:
        #
        #  17:20:06 + ss -Hp --vsock
        #  17:20:06 tracing/test-agent-shutdown.sh: line 556: 13682 Segmentation fault      (core dumped) agent_addr=$(get_agent_vsock_address || true)
        #
        # This is not reproducible locally
```
https://github.com/kata-containers/tests/blob/main/tracing/test-agent-shutdown.sh#L746-752

**Comment by GabyCT** [comment]
so @cmaf where the test is running? or should run?

**Comment by GabyCT** [comment]
@cmaf if you see here https://github.com/kata-containers/tests/blob/478b4ce16ff18ab91354b2879924fe51b646a14c/tracing/test-agent-shutdown.sh#L763
the test should not run on `metrics` but is running

**Comment by GabyCT** [comment]
```
+ '[' ubuntu = ubuntu ']'
+ grep -q LTS
+ '[' CRI_CONTAINERD_K8S = CRI_CONTAINERD_K8S_MINIMAL ']'
+ '[' false = true ']'
+ local cargo=/home/jenkins/.cargo
+ '[' -d /home/jenkins/.cargo ']'
+ sudo chown -R jenkins: /home/jenkins/.cargo /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-PR/go/src/github.com/kata-containers/kata-containers
+ cargo --version
tracing/test-agent-shutdown.sh: line 774: cargo: command not found
+ /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-PR/go/src/github.com/kata-containers/tests/tracing/../.ci/install_rust.sh
Install rust 1.54.0
info: downloading installer
error: could not write settings file: '/home/jenkins/.rustup/settings.toml': Permission denied (os error 13)
[install_rust.sh:25] ERROR: sh -s -- -y --default-toolchain 1.54.0
++ handle_error 774
++ local exit_code=1
++ local line_number=774
+++ basename tracing/test-agent-shutdown.sh
```
this is an example of an Ubuntu CI job where the test should not run but is running

**Comment by jodh-intel** [comment]
Hi @GabyCT - agreed, that test shouldn't be running on the metrics CI's. @cmaf is correct - we run the shutdown test before the tracing tests. Due to the requirements for the shutdown test, it does an `exit 0` if the environment isn't correct. And it looks like it should do that for metrics tests:

- https://github.com/kata-containers/tests/blob/main/tracing/test-agent-shutdown.sh#L763

**Comment by GabyCT** [comment]
@jodh-intel it is also running on pmem, vfio and a bunch of CIs that are currently failing
http://jenkins.katacontainers.io/job/kata-containers-2.0-pmem-ubuntu-20.04-PR/139/console
