### ISSUE TITLE
Debug test-agent-shutdown.sh which fails in multiple CI jobs

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#3981]
The following error is seen in `jenkins-ci-pmem-ubuntu-18-04`,  `jenkins-ci-ubuntu-18-04-initrd`, `jenkins-metrics-ubuntu-20-04`, `jenkins-ci-ARM-ubuntu-18-04` :
```
+ echo -e '[test-agent-shutdown.sh:1196] ERROR: empty log file: '\''/tmp/jenkins/workspace/kata-containers-2.0-pmem-ubuntu-20.04-PR/go/src/github.com/kata-containers/tests/kata-agent.log'\'''
[test-agent-shutdown.sh:1196] ERROR: empty log file: '/tmp/jenkins/workspace/kata-containers-2.0-pmem-ubuntu-20.04-PR/go/src/github.com/kata-containers/tests/kata-agent.log'
```

There is also a segmentation fault seen in `jenkins-ci-pmem-ubuntu-18-04`, `jenkins-ci-ubuntu-18-04-initrd`, (but not in `jenkins-metrics-ubuntu-20-04`, `jenkins-ci-ARM-ubuntu-18-04`):
```
+ echo -e '[test-agent-shutdown.sh:588] INFO: VSOCK details'
[test-agent-shutdown.sh:588] INFO: VSOCK details
+ ss -Hp --vsock
tracing/test-agent-shutdown.sh: line 556: 16908 Segmentation fault      (core dumped) exit 1
```

Seen in https://github.com/kata-containers/kata-containers/pull/2675

@jodh-intel

**Comment by fidencio** [comment]
I just hit this on http://jenkins.katacontainers.io/job/kata-containers-2.0-pmem-ubuntu-20.04-PR/138/

**Comment by cmaf** [comment]
`test-agent-shutdown.sh` had been running in jobs it should not have been and was moved to `CRI_CONTAINERD_K8S_MINIMAL` in order to group it with `tracing-test.sh` (https://github.com/kata-containers/kata-containers/pull/2684). However, it has been explicitly disabled for `CRI_CONTAINERD_K8S_MINIMAL` due to a segmentation fault that is not locally reproducible. (See [test-agent.shutdown.sh#L746-L761](https://github.com/kata-containers/tests/blob/main/tracing/test-agent-shutdown.sh#L746-L761), related issue https://github.com/kata-containers/tests/issues/3774.) This is the same one seen above. 

The current tracing test does **not** include agent tracing yet, so this problem does not affect the current `tracing-test.sh`, but it does mean that other PRs that depend on it can't be tested (https://github.com/kata-containers/tests/pull/3985). 

cc @jodh-intel @Jakob-Naucke @chavafg

**Comment by cmaf** [comment]
In local testing on x86_64 Ubuntu 20.04 I am reproducing the error in https://github.com/kata-containers/tests/issues/3878

**Comment by cmaf** [comment]
This will likely be moved to `jenkins-ci-ubuntu-20-04`  or something similar, see https://github.com/kata-containers/tests/issues/4195 and https://github.com/kata-containers/tests/pull/4196; closing.
