### ISSUE TITLE
CI: add basic testing for kata-monitor

### ISSUE THREAD

**Issue by fgiudici** [kata-containers/tests#3983]
**Which feature do you think can be improved?**
We currently miss CI tests for the kata-monitor binary

**How can it be improved?**
We could start adding few basics checks for kata-monitor in our CI, to catch regressions early in the PRs.
An environment with just a container engine and kata would be enough. 
We could start pods via crictl, run the kata-monitor binary and scrape its endpoints checking the output matches the expected values.
We have also to identify the CI job where we can add the kata-monitor tests.

**Comment by fgiudici** [comment]
I already prepared a simple script that would start a couple of containers and check that kata-monitor correctly picks them up and exports the metrics in its own endpoints.
Looking for the best suited place to add those few and lightweight tests. Any advice? :-)

**Comment by wainersm** [comment]
Hi @fgiudici , thanks for opening this!

Based on your description and how I see the organization of the tests repository, I think that test should live under the `tests/functional` directory. @GabyCT @devimc any idea?

Regarding the CI jobs, does the kata-monitor contain code paths dependent of the CRI? If it is CRI agnostic then it could be ran on `CRI_CONTAINERD` as that job runs most of the tests suites.

**Comment by fgiudici** [comment]
> Hi @fgiudici , thanks for opening this!
> 
> Based on your description and how I see the organization of the tests repository, I think that test should live under the `tests/functional` directory. @GabyCT @devimc any idea?
> 
> Regarding the CI jobs, does the kata-monitor contain code paths dependent of the CRI? If it is CRI agnostic then it could be ran on `CRI_CONTAINERD` as that job runs most of the tests suites.

Hey, thanks @wainersm... yeah, kata-monitor is container engine agnostic (as long the container engine is CRI compliant). So testing with containerd would be perfect :-)

**Comment by fidencio** [comment]
> Regarding the CI jobs, does the kata-monitor contain code paths dependent of the CRI? If it is CRI agnostic then it could be ran on `CRI_CONTAINERD` as that job runs most of the tests suites.

I am slightly afraid that if it only runs on `CRI_CONTAINERD` we may not have someone from CRI-O side to help maintaining it.

While I'd like to see tests about kata-monitor, I'd like to have an agreement that this should be maintained by both CRI-O & containerd folks.  Thus, maybe, run those on both CRI-O and CONTAINERD CIs, to ensure we don't break integration with one or another.

**Comment by fgiudici** [comment]
> While I'd like to see tests about kata-monitor, I'd like to have an agreement that this should be maintained by both CRI-O & containerd folks. Thus, maybe, run those on both CRI-O and CONTAINERD CIs, to ensure we don't break integration with one or another.

Yeah, that would be perfect. Also I would like to note that the tests I have in mind are quick and lightweight: start 2 pods (a kata one and a vanilla one), scrape the endpoints of kata-monitor to check it has detected the kata one, get the metrics, stop the pods, check kata-monitor detects it. These few tests run in less than a minute on my local env.

**Comment by wainersm** [comment]
> > Regarding the CI jobs, does the kata-monitor contain code paths dependent of the CRI? If it is CRI agnostic then it could be ran on `CRI_CONTAINERD` as that job runs most of the tests suites.
> 
> I am slightly afraid that if it only runs on `CRI_CONTAINERD` we may not have someone from CRI-O side to help maintaining it.
> 
> While I'd like to see tests about kata-monitor, I'd like to have an agreement that this should be maintained by both CRI-O & containerd folks. Thus, maybe, run those on both CRI-O and CONTAINERD CIs, to ensure we don't break integration with one or another.

Just to make clear, by:

CRI_CONTAINERD I meant to http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-PR
And CRIO_K8S I meant to http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR

I'm fine to run on both jobs. The new CI proposal assume jobs have maintainers and, in my mind, the maintainer can pick up whatever test suite to run he/she likes :)
