### ISSUE TITLE
Backport ci: fix deps resolving

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/tests#4021]
#3913 needs a backport, but doesn't have it yet. Its lack on `stable` has a nastier side effect besides the mentioned problems with `$USE_PODMAN` yet: `source`ing `.ci/lib.sh` early leads to a clone of `kata-containers/kata-containers` that does **not** respect `stable`, cf. #4018 (yes, yes, I know it was me who introduced it).

**Comment by fidencio** [comment]
Closing as the fix got merged already.
