### ISSUE TITLE
cri-o integration test "ctr logging [tty=true]" fails randomly

### ISSUE THREAD

**Issue by littlejawa** [kata-containers/tests#4069]
When running our cri-o integration tests, we see failures on this specific test.
We have added it to the "skip" list for now, but we need to understand what is causing this (apparently random) issue.

**Comment by Jakob-Naucke** [comment]
@littlejawa can you provide an example failure?

**Comment by littlejawa** [comment]
> @littlejawa can you provide an example failure?

Hi @Jakob-Naucke,
Unfortunately not. I've seen it happen from time to time in the CI, but I did not save the logs, and the failing builds are gone now.

What I can tell you though is that the failure was due to the test not being able to find a specific string in the logs.
Apparently, most of the time, it does find it. But from time to time, it is not there. And it this is not related to the PR being tested - it happened one time, then fixed itself in the next run from the same PR.

I can't say better unfortunately, I've not been able to find when this would happen, so I just commented it out.
