### ISSUE TITLE
kata-webhook: need a rebuild of quay.io/kata-containers/kata-webhook-example

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#4080]
The PR https://github.com/kata-containers/tests/pull/3647 changes the webhook server application so that it can handle the `admissionregistration.k8s.io/v1` API requests. In order to get that PR merged I made a build of the app image and pushed to `quay.io/wainersm/kata-webhook-api-v1:latest`. After the PR gets merged we should provide a rebuild of the original image (`quay.io/kata-containers/kata-webhook-example`).

**Comment by fidencio** [comment]
@wainersm, are you part of the group that can upload a new image there?  If not, what's your quay.io username so we can add you there for now? 

Later on we must have this process automated, as we currently do for the kata-deploy images.

**Comment by wainersm** [comment]
> @wainersm, are you part of the group that can upload a new image there? If not, what's your quay.io username so we can add you there for now?
> 

My username on quay.io is `wainersm`

> Later on we must have this process automated, as we currently do for the kata-deploy images.

I agree. I opened a issue about it -> https://github.com/kata-containers/tests/issues/4135

**Comment by fidencio** [comment]
> > @wainersm, are you part of the group that can upload a new image there? If not, what's your quay.io username so we can add you there for now?
> 
> My username on quay.io is `wainersm`

Added.

> 
> > Later on we must have this process automated, as we currently do for the kata-deploy images.
> 
> I agree. I opened a issue about it -> #4135

Thanks.

I've noticed that @littlejawa has built the webhook image recently.  Of course, if it's still not working for you, go ahead and do a new build.

**Comment by wainersm** [comment]
Thanks @fidencio I was able to build and update the image on quay.io.

**Comment by littlejawa** [comment]
> I've noticed that @littlejawa has built the webhook image recently. Of course, if it's still not working for you, go ahead and do a new build.

FWIW: My update did not include Wainer's work, so it was certainly better to have his image instead.
