### ISSUE TITLE
ci: the ci_crio_entry_point.sh script fails

### ISSUE THREAD

**Issue by littlejawa** [kata-containers/tests#4103]
This script was added recently (from #4058). The goal was to modify the corresponding jenkins job to fetch and execute that script rather than have the script embedded into the jenkins job.

The problem occurs when we run this script: when the kubernetes e2e test tries to cleanup, it fails, because it tried to stop the containerd service (when we're using crio).

The script is very similar to what jenkins runs, the difference may be in the environment variables definition order and default values, and what is visible from the variables exported by jenkins. I will investigate it.

**Comment by fidencio** [comment]
@littlejawa, as you mentioned you'll investigate it, I'm assigning the issue to you.  Thanks, Julien.
