### ISSUE TITLE
cpu tests fail on Clear Linux

### ISSUE THREAD

**Issue by DnPlas** [kata-containers/tests#415]
When testing Kata Containers in Clear Linux, a set of CPU tests fail with the following output:

[Fail] Update number of CPUs Update CPU period and quota [It] should have 2 CPUs
/tmp/gopath/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:278

[Fail] Update number of CPUs Update CPU period and quota [It] should have 3 CPUs
/tmp/gopath/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:278

[Fail] Update number of CPUs Update CPU period and quota [It] should have 1 CPUs
/tmp/gopath/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:278

[Fail] CPUs and CPU set updating cpus and cpuset of a running container [It] should have the right number of vCPUs
/tmp/gopath/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:432

We are using the latest Kata release (1.0.0), kernel version 14.14.22 and the image is in [1].

[1] https://github.com/kata-containers/agent/releases/download/1.0.0/kata-containers.tar.gz

**Comment by chavafg** [comment]
Hi @DnPlas, can you run the `kata-collect-data.sh` script and upload the output here?

/cc @devimc

**Comment by chavafg** [comment]
also, can you please provide the commit/version of the tests you are using?

**Comment by DnPlas** [comment]
@chavafg sure, I'm attaching the output of kata-collect-data.sh
[kata-collect-data.log](https://github.com/kata-containers/tests/files/2103248/kata-collect-data.log). I'm on the master branch.

**Comment by chavafg** [comment]
Thanks, as you are running with release 1.0.0, can you please checkout to `v1.0.0` in the `tests` repo and try to rerun them?

**Comment by DnPlas** [comment]
We ran all tests on v1.0.0, none fails, meaning there's no issue. Thanks for the follow up.
