### ISSUE TITLE
CI: test akin to OpenShift Sandboxed Containers

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#4163]
**Which feature do you think can be improved?**

*Context*

I maintain a [job running on OpenShift CI](https://prow.ci.openshift.org/?job=periodic-ci-kata-containers-kata-containers-main-e2e-tests) used to test the integration of latest Kata Containers (**main** branch) with latest GA'ed version of OpenShift (4.9 at the time of this writing).
On that job it is used the default Kata runtime configuration (the configuration.toml file), and the QEMU and Kernel built by Kata Containers CI scripts.

*The Problem*

Kata Containers is bundled into the Red Hat [OpenShift Sandboxed Containers](https://docs.openshift.com/container-platform/4.9/sandboxed_containers/understanding-sandboxed-containers.html) (OSC) and it should use the Red Hat CoreOS (RHCOS) kernel and QEMU from Red Hat Advanced Virtualization (AV). 

The job aforementioned has two limitations:
  1) it doesn't use the host's kernel and QEMU. Often those are older than what is tested on Kata CI, therefore, regressions may be introduced and we will notice too late;
  2) the runtime configuration is slightly different from the defaults (e.g. `sandbox_cgroup_only` is set to `true`) and none job on Kata CI does test that exact configuration. As a result, again, regressions can be noticed later (e.g. https://github.com/kata-containers/kata-containers/issues/2868)

**How can it be improved?**

Have another job configured to test the stack as close as possible to what is shipped with OSC. That involves changes to the build and runtime configurations to use kernel and QEMU from RHCOS.

**Comment by fidencio** [comment]
@wainersm, I'd be totally in for having a different job testing latest kata-containers with the Red Hat bits, and we even discussed this in the past.

The main problem is how the community (as in, folks outside of Red Hat network) will be able to reproduce and debug the issue in case something goes wrong.  This could be solved by a simple agreement that Red Hatters will commit to debugging, reporting, and providing as much info as possible so the community can work on the issue upstream.

**Comment by Jakob-Naucke** [comment]
> The main problem is how the community (...) will be able to reproduce and debug the issue in case something goes wrong.

Either way, we will have logs, right? (Not that that always makes debugging easy. But in some cases, you can tell the required fix fairly easily.)

**Comment by snir911** [comment]
If it would make it easier maybe it could be just plain k8s+crio configured similarly to Openshift and centos based, IMO it should be close enough. Other option could be to leverage okd.io for such job in addition to how-to-reproduce document IDK how helpful/applicable is it

**Comment by wainersm** [comment]
Hi @fidencio ,

> @wainersm, I'd be totally in for having a different job testing latest kata-containers with the Red Hat bits, and we even discussed this in the past.
> 
> The main problem is how the community (as in, folks outside of Red Hat network) will be able to reproduce and debug the issue in case something goes wrong. This could be solved by a simple agreement that Red Hatters will commit to debugging, reporting, and providing as much info as possible so the community can work on the issue upstream.

I've been hesitated to turn that job on OpenShift CI as required for pull requests because (among other reasons) the community may find difficult to access a cluster to reproduce and debug issues as you mentioned. Although one can have access to OpenShift for free on https://www.redhat.com/en/technologies/cloud-computing/openshift

When I open any issue found by the tests on those jobs (e.g. https://github.com/kata-containers/kata-containers/issues/2601 and https://github.com/kata-containers/kata-containers/issues/2464) I always try to provide as much information as possible so that the community can find the issue without the necessity to access OpenShift. In other cases I even provide reproducers which can be ran with Kubernetes on community distros. Anyway, I'd like to re-enforce that we (the @kata-containers/redhat team) agreed that issues found on those jobs should be reported with useful/quality information and debugged by ourselves; although we always expect to solve found issues in cooperation with the community.

Other than that, I plan to open an issue for us to discuss the possibility of adding a new CI job to test the `sandboxed_cgroups_only=true` on a community distro like Centos or Fedora, since that some bugs which hurt us (Red Hat) recently could have been discovered by having a simple job on Kata CI to test that configuration.

Thanks for the comments Fidencio!
