### ISSUE TITLE
Kubernetes installation fails on Debian

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/tests#4168]
```
Install Kubernetes components
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Hit:1 http://debian-archive.trafficmanager.net/debian buster InRelease
Get:2 http://debian-archive.trafficmanager.net/debian-security buster/updates InRelease [65.4 kB]
Hit:3 http://debian-archive.trafficmanager.net/debian buster-updates InRelease
Hit:4 http://debian-archive.trafficmanager.net/debian buster-backports InRelease
Hit:6 https://download.docker.com/linux/debian jessie InRelease
Get:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease [9401 B]
Get:7 https://packages.cloud.google.com/apt kubernetes-xenial-unstable/main amd64 Packages [50.9 kB]
Reading package lists...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Release file for http://debian-archive.trafficmanager.net/debian-security/dists/buster/updates/InRelease is expired (invalid since 7h 54min 8s). Updates for this repository will not be applied.
[install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
```

e.g. http://jenkins.katacontainers.io/job/kata-containers-2.0-debian-PR/2434/console, which only shows up much later bco #4167

**Comment by Jakob-Naucke** [comment]
`http://security.debian.org/debian-security buster/updates InRelease` etc. still work for me -- is this an Azure issue?

**Comment by zhsj** [comment]
> `http://security.debian.org/debian-security buster/updates InRelease` etc. still work for me -- is this an Azure issue?

It's an Azure issue.

debian-archive.trafficmanager.net seems to have multiple backends. When I access it from my network, I'm hitting mirror-backend-southeastasia-0.azure.prod/backend(X-Backend header in http response), I see the file(http://debian-archive.trafficmanager.net/debian-security/dists/buster/updates/InRelease) is valid.

This mirror seems to be manged by Azure.

**Comment by Jakob-Naucke** [comment]
@zhsj thank you for checking -- I should have recorded proof, but I saw earlier today the `Valid-Until` ended on the 8th. This seems to be resolved regardless.

**Comment by Jakob-Naucke** [comment]
it is
