### ISSUE TITLE
kubeadm init fails on ppc64le with v1.22.0

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/tests#4175]
From the kubelet logs, it always considers docker as the runtime even when clearly configured to use CRIO/Containerd.
It is definitely strange since if this is a bug, then it should fail on the other architectures as well, which doesn't happen. 

After multiple trials and reaching a dead end with no possible reason found yet, the init only works when k8s version is upgraded to v1.22.2, would it make sense to upgrade the k8s version only on ppc64le(via versions.yaml) for now for the sake of having a stable CI? 

cc @Jakob-Naucke @GabyCT @fidencio

**Comment by Jakob-Naucke** [comment]
I think that would be acceptable. Just one thing: If upgrade to 1.22.2 works across all architectures without any hiccups whatsoever, I think we should do that instead. @fidencio how painful are these k8s upgrades usually?

**Comment by Amulyam24** [comment]
Issue irrelevant, k8ss init works with v1.22.0 on ppc64le now.
