### ISSUE TITLE
s390x | test_watch_entries failure

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#4183]
```
thread 'watcher::tests::test_watch_entries' panicked at 'assertion failed: `(left == right)`
  left: `"original"`,
 right: `"updated"`', src/watcher.rs:732:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test watcher::tests::test_watch_entries ... FAILED
```

cc @Jakob-Naucke @egernst

**Comment by fidencio** [comment]
And this happened on http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/981

**Comment by Jakob-Naucke** [comment]
Duplicate of https://github.com/kata-containers/kata-containers/issues/2946, closing

**Comment by fidencio** [comment]
> Duplicate of [kata-containers/kata-containers#2946](https://github.com/kata-containers/kata-containers/issues/2946), closing

Perfect, thanks!  I was looking for s390x specific reports and missed #2946
