### ISSUE TITLE
Tracing test no longer running

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#4195]
Since the tracing test was previously run in the CRI_CONTAINERD_K8S_MINIMAL (jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal) and it was disabled, we have the following options:
1. Move the tracing test to CRI_CONTAINERD_K8S (jenkins-ci-ubuntu-20-04)
2. Repurpose/rename CRI_CONTAINERD_K8S_MINIMAL for tracing test (and future tests) and add myself as an owner (See [403](https://github.com/kata-containers/ci/issues/403))

I think 2 is probably best since CRI_CONTAINERD_K8S does a lot already. For now I need to test 1 for agent-shutdown-test debugging.

cc @jodh-intel @GabyCT

**Comment by cmaf** [comment]
Also CRI_CONTAINERD_K8S might be appropriate, see https://github.com/kata-containers/tests/issues/3990#issuecomment-923791326

@Jakob-Naucke

**Comment by Jakob-Naucke** [comment]
@cmaf I still think we should include it in `CRI_CONTAINERD_K8S` so that it is run e.g. on s390x. If the resulting tests duration is unacceptable to you, I would still be against putting it into `CRI_CONTAINERD_K8S_MINIMAL` because the name becomes confusing then (a name like `CRI_CONTAINERD_K8S_LOAD_BALANCING_B` would be more accurate then, even though probably not appropriate :)).

**Comment by GabyCT** [comment]
@cmaf @Jakob-Naucke I prefer that the tracing job does not run on  CRI_CONTAINERD_K8S (jenkins-ci-ubuntu-20-04) we do not want to increase the time on one of the CI jobs that is running a lot of testing

**Comment by Jakob-Naucke** [comment]
@GabyCT if you insist, we can use this to load balance a little. However, don't you think the job should be renamed then? `CRI_CONTAINERD_K8S_MINIMAL` wouldn't really be appropriate any more IMO.

**Comment by GabyCT** [comment]
rename the `CRI_CONTAINERD_K8S_MINIMAL`? yes that can be done

**Comment by GabyCT** [comment]
also if you want to run these tests on your environment @Jakob-Naucke you can make it just say that if it is s390x then it runs these tests

**Comment by Jakob-Naucke** [comment]
@GabyCT yeah, I guess that wouldn't be a huge deal, we already do the same for static and unit checks. Thanks!

**Comment by GabyCT** [comment]
@cmaf so which is the combination that is working with this test? we have `CRIO_K8S`, `CLOUD-HYPERVISOR-K8S-CRIO` and `CRIO_K8S_MINIMACRIO_K8S_MINIMAL`

**Comment by GabyCT** [comment]
in case that you want to create a job for this you can but please add a baseline and put how will be the mantainer on http://jenkins.katacontainers.io/view/Daily%20baseline/

**Comment by cmaf** [comment]
@GabyCT I tested it on CRI_CONTAINERD_K8S ([see here](https://github.com/kata-containers/tests/pull/4196/files#diff-7b436cb5923ba7f66ccf2e140b342330400dcb1d6776d03444564dc34c5379f1L40`))

**Comment by GabyCT** [comment]
ok it that only works with containerd as I can see you can use the current job that you have is easier
