### ISSUE TITLE
Equalize the golang versions throughout the project

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#4263]
This issue is a spin off of a https://github.com/kata-containers/tests/pull/4249#issuecomment-987068837 I wrote to [workflows: Bump golang to 1.17 #4249](https://github.com/kata-containers/tests/pull/4249).

Throughout the tests and kata-containers repositories we are referencing different versions of Golang. IMHO we should remove inconsistencies and have a more clear policy for golang support versions.

Some inconsistencies I've noted:

 * on `kata-containers/versions.yaml` the golang `version` is still set to `1.11`
 * the `tests/.ci/install_go.sh` pick up `newest-version` from `kata-containers/versions.yaml` (i.e. currently `1.17.3`), meaning the integration/functional tests on Jenkins are testing on the newest version. Shouldn't it be on the oldest?
 * `kata-containers/src/runtime/go.mod` is set to `1.14`
 * the https://github.com/kata-containers/tests/pull/4249 updates the github workflows to run the linter and unit tests on `1.16` and `1.17`(same versions already used on kata-containers) 
 * the `tools/packaging/kata-monitor/Dockerfile` to build the kata-monitor image uses `golang:1.15-alpine`. Maybe it is okay the kata-monitor appliance be built on 1.15?
 * the `tests/kata-webhook/go.mod` is set to `1.16`

Cc @fidencio @kata-containers/architecture-committee

**Comment by GabyCT** [comment]
Closing this issue as it seems solved
