### ISSUE TITLE
Should kata-containers-2.0-tests-ubuntu-ARM-PR allow only sequencial builds?

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#4276]
The CI job [kata-containers-2.0-tests-ubuntu-ARM-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/) is currently configured to allow concurrent builds. I am concerned that this can result on random errors because the job run on bare-metal, therefore concurrent access to shared resources might drive to race conditions.

Let me give an example. I recently submitted a pull request #4260 which touches only files under `.ci/openshift-ci` and so that should not make any test to fail. However the [job 16](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/1624) fails in what seems to be a race condition error:
```
11:39:30 bash -f integration/kubernetes/run_kubernetes_tests.sh
11:39:30 ~/workspace/kata-containers-2.0-tests-ubuntu-ARM-PR/go/src/github.com/kata-containers/tests/integration/kubernetes ~/workspace/kata-containers-2.0-tests-ubuntu-ARM-PR/go/src/github.com/kata-containers/tests
11:39:30 Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
11:39:31 [init.sh:79] ERROR: iptables -X
11:39:31 [run_kubernetes_tests.sh:68] ERROR: ./init.sh
```
It happens that `tests/integration/kubernetes/init.sh` has some instructions to save the iptables configuration before Kubernetes is started, then iptables is restored after the tests had ran. Two concurrent builds can drive to race condition. Maybe unlikely to happens and that error actually means that a previous build left iptables locked by mistake?

Anyway, I think we should evaluate whether or not that job should allow for concurrent builds.

**Comment by wainersm** [comment]
Hi @jongwu, @justin-he, as the owners of the job. What's your taken on that?

**Comment by Jakob-Naucke** [comment]
I, for one, don't allow concurrent builds on s390x. We run tests that affect and depend on root-owned system directories.

**Comment by jongwu** [comment]
I think it's the same situation on arm. running test concurrently is not stable, thus we need lots of bug fix and refactor. So I'm not sure we can do that now.

**Comment by Jakob-Naucke** [comment]
> I think it's the same situation on arm. running test concurrently is not stable, thus we need lots of bug fix and refactor. So I'm not sure we can do that now.

You're not sure we can do _what_ now? We can change the ARM jobs to prohibiting concurrent builds, can't we?

**Comment by jongwu** [comment]
@Jakob-Naucke -, no, I think

**Comment by Jakob-Naucke** [comment]
> @Jakob-Naucke -, no, I think

@jongwu huh?

**Comment by jongwu** [comment]
> huh

I have not investigated about how to run test on arm concurrently.  At the first glance, I consider it not easy to do.

**Comment by Jakob-Naucke** [comment]
@jongwu Maybe there is a misunderstanding here. As far as I understand:
- The jobs we run are **not** guaranteed to work when executed concurrently.
- The ARM CI is configured to **allow** for concurrent execution of jobs.

Therefore, shouldn't we simply reconfigure ARM to **not** allow the concurrent execution of jobs (i.e. only allow sequential)?

However, it's possible that this is enabled to allow load balancing across the 3 ARM nodes that we have, which is a feature we would want to keep (would be a shame if two were unused). Not sure how Jenkins works there. If it does work that way, we should ideally allow parallel execution across those nodes, but not within one node.

**Comment by jongwu** [comment]
> @jongwu Maybe there is a misunderstanding here. As far as I understand:
> 
> * The jobs we run are **not** guaranteed to work when executed concurrently.
> * The ARM CI is configured to **allow** for concurrent execution of jobs.
> 
> Therefore, shouldn't we simply reconfigure ARM to **not** allow the concurrent execution of jobs (i.e. only allow sequential)?
> 
OK, arm ci should not allow running concurrently on one node.

> However, it's possible that this is enabled to allow load balancing across the 3 ARM nodes that we have, which is a feature we would want to keep (would be a shame if two were unused). Not sure how Jenkins works there. If it does work that way, we should ideally allow parallel execution across those nodes, but not within one node.

yeah, we have 3 arm nodes and they can run parallelly.

**Comment by jongwu** [comment]
So, What we need is that disable parallelly running ci on one node and let the ci run parallelly on different nodes as it does for now. @Jakob-Naucke @wainersm

**Comment by Jakob-Naucke** [comment]
Right. Should we use something like https://plugins.jenkins.io/throttle-concurrents/? I guess we could also build this ourselves, but making that non-fragile is probably kind of painful.

**Comment by jongwu** [comment]
Hello @Jakob-Naucke -, should it work that disable concurrent build in jenkins configuration? If it is, why should we need a plugin?

**Comment by jongwu** [comment]
I try to disable the "concurrent build" in jenkins configuration and I can't deploy jenkins test on different ci nodes, so we should enable this tag.
When this tag is enabled, we the new jenkins job will hang on if the number of jenkins jobs are more than jenkins ci nodes. That is what we want and need no change for it. Am I right? @wainersm  @Jakob-Naucke

**Comment by Jakob-Naucke** [comment]
> When this tag is enabled, we the new jenkins job will hang on if the number of jenkins jobs are more than jenkins ci nodes. That is what we want and need no change for it.

If it works like that, then I think we're good. (Although I do now wonder how one would configure concurrent jobs on one node if they wanted to.) @wainersm any other objections? Otherwise we can close.
