### ISSUE TITLE
Use authentication when checking GitHub URLs in static check script

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#4304]
The `check_url()` function in the static check script (https://github.com/kata-containers/tests/blob/main/.ci/static-checks.sh#L530) uses `curl(1)`. This normally works fine, but since that function gets called for every URL in every changed document, if a PR contains too many document changes, we can hit the GitHub rate limiter.

By default (for unauthenticated access), Github allows 60 http requests / hour.

If we switch to authenticated access (using `curl -u"${GITHUB_USER}:${GITHUB_TOKEN}" ...`) that limit goes up to 5000 / hour.

Examples of where we've hit the HTTP 429 issue:

- https://github.com/kata-containers/kata-containers/pull/2023#issuecomment-862283865
- https://github.com/kata-containers/kata-containers/pull/3330#issuecomment-1000280515

**Comment by wainersm** [comment]
Hi @jodh-intel ,

I hope to have an intern working with me soon, then I am looking for "good-first-issue" for him/her. This issue seems a good candidate. Is it still valid?
