### ISSUE TITLE
ci: ci is failing to clone repos

### ISSUE THREAD

**Issue by snir911** [kata-containers/tests#4307]
# Description of problem

The following errors are received:
on ubuntu:
`error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.`
on fedora likes:
`error: RPC failed; curl 56 OpenSSL SSL_read: Connection reset by peer, errno 104`

# Expected result

cloning the repos is completed

# Actual result

failing to clone repos

# Further information
https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

**Comment by snir911** [comment]
It seems to be github's issue:
https://github.community/t/read-timeouts-and-errors-from-github-urls/219615

**Comment by GabyCT** [comment]
@snir911 can we close this issue or this is still happening?
