### ISSUE TITLE
Only run URL checks in github workflow

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#4311]
Not sure how many of the Jenkins CI jobs are doing it right now, but apparently they fall into the category of static tests and should be done **ONCE** in github workflow, instead of repeating the same tests in different Jenkins jobs.

Example of URL checks in Jenkins jobs:

http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/1238/console

http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/3008/console

**Comment by jodh-intel** [comment]
Nice catch @bergwolf - that would explain the http 429 errors we see sometimes due to the GitHub rate limiter for unauthenticated GETs: #4304.

**Comment by snir911** [comment]
Should we make the arm job non-required till this fixed? lately this issue is encountered very often

**Comment by jodh-intel** [comment]
@snir911 - wfm!

**Comment by wainersm** [comment]
@bergwolf all non-x86_64 jobs on Jenkins will have the static-check executed: https://github.com/kata-containers/tests/blob/main/.ci/jenkins_job_build.sh#L132

@jodh-intel are there any arch-specific static-checks? Maybe on non-x86_64 we should only run the unit tests...

**Comment by snir911** [comment]
@wainersm FWIW i saw the following options exist for static-checks.sh:
```
--no-arch) handle_funcs="arch-agnostic" ;;
--only-arch) handle_funcs="arch-specific" ;;
```

**Comment by GabyCT** [comment]
Closing this issue as it seems solved
