### ISSUE TITLE
Set user agent in static checker's URL check

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#4401]
As shown below, some websites require a user agent to be set. The static checker's URL check ([`check_url()`](https://github.com/kata-containers/tests/blob/main/.ci/static-checks.sh#L532) function) doesn't do this as it's using `curl` without specifying a UA, so we need to consider if there is a workaround or whether we should set a UA (and if so, which one).

- https://github.com/kata-containers/kata-containers/pull/3558#issuecomment-1022121194

Related: #4304.

**Comment by bookinabox** [comment]
I will take a look at this.

Are there any websites besides AMD known to cause issues?

Looking into amd.com, it seems be to hosted off Akamai, which from what I can glean has some settings the website user can set up to filter specific user-agents.

For example, trying to spoof with this user agent I arbitrarily got as one of the first results online

`curl -sIL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" https://www.amd.com`

fails with 403, but something that is clearly not a complete user agent like

`curl -sIL -A "Chromium/" https://www.amd.com`

return 200 just fine. I'm not quite sure what phrases might trigger the blacklist, but I will play around more. I don't think there's a way around spoofing the agent, so its probably best to find some very generic user-agent that works (like Windows/Chrome) to minimize any sites being picky.
