### ISSUE TITLE
error while building cloud hypervisor on VFIO CI

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#4494]
We got a failure on the VFIO CI with the following
```
14:00:28 14ef1744d7660dc15ae9e1d781fbcd8c8c06876b1e4d776e8b055d73034cd112
14:00:42 Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
14:00:42 Error: statfs /var/run/docker.sock: no such file or directory
14:00:42 make[1]: Leaving directory '/home/jenkins/workspace/workspace/kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline/go/src/github.com/kata-containers/kata-containers'
14:00:42 make[1]: *** [tools/packaging/kata-deploy/local-build/Makefile:30: cloud-hypervisor-tarball-build] Error 125
14:00:42 make: *** [tools/packaging/kata-deploy/local-build/Makefile:33: cloud-hypervisor-tarball] Error 2
```
This seems to be related with https://github.com/kata-containers/tests/commit/e05447a9d2ab997c7861d517b4bfc4a759e2f692

**Comment by fidencio** [comment]
This puzzles me immensely, I must say.

If we look at the logs we can see:
```
20:37:45 ++ GOROOT=/usr/local/go
20:37:45 ++ export KUBERNETES=no
20:37:45 ++ KUBERNETES=no
20:37:45 ++ export ghprbPullId
20:37:45 ++ export ghprbTargetBranch
```

But if we look at https://github.com/kata-containers/tests/commit/3b0547f42266a3a5df22ae20a82a4332af34b9ab, we can see:
```
    export GOROOT="/usr/local/go"
    export KUBERNETES="no"
    export USE_DOCKER="true"
    export ghprbPullId
    export ghprbTargetBranch
```

I sincerely am not sure why the baseline does **not** execute that bit.
Could it be some cached artefact being kept and used on the host machine?

**Comment by GabyCT** [comment]
well the same machine is being used for PRs and baseline

**Comment by devimc** [comment]
I have removed manually `/home/jenkins/workspace/workspace/kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline` and restarted the job http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline/166/console

**Comment by fidencio** [comment]
And it passed the point where it was failing and is now using docker instead of podman.

I still don't understand why it happened, but I am glad it seems to be solved.

**Comment by fidencio** [comment]
@GabyCT, I am closing this one as it's passed (http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline/166/console).

**Comment by devimc** [comment]
now it's passing, please feel free to close it :smiley:
