### ISSUE TITLE
Add a log simplification script

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#451]
Sometimes, you want to be able to compare two component logs files. say two `runtime.log` files extracted from the system log [1].

Write a simple script to simplify a log file to make it easier to diff without your brain melting.

---

[1] - https://github.com/kata-containers/tests/tree/master/cmd/log-parser

**Comment by grahamwhaley** [comment]
+1 for sure. I've been thinking similarly having stared at logs for a couple of days.
Something that will show you the 'lifecycle of a single container' in a more human readable form than the raw-ish logs would be great for me right now.

**Comment by jodh-intel** [comment]
The script I've added on #452 is pretty crude but surprisingly useful. I'm not sure if it'll suit your scenario but  I agree that we need a way to portray the lifecycle from the logs in a more meaningful way.
