### ISSUE TITLE
`priority=1` is constantly being added to the repo file

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#4535]
When setup AlibabaCloud(based CentOS:8) node, I found after the CI job runs, the package repo file is constantly appending `priority=1`:

```bash
$ tail -10 /etc/yum.repos.d/AliYun.repo 

priority=1
priority=1
priority=1
priority=1
priority=1
priority=1
priority=1
priority=1
priority=1
```

The source:

https://github.com/kata-containers/tests/blob/f3d17866e411f1246898bd7e6c7e649ff64a67a8/.ci/setup_env_centos.sh#L40

CentOS may have the same issue maybe.

To fix it, can only append when the last line is not `priority=1`.

/cc @GabyCT

**Comment by fidencio** [comment]
@liubin, I guess the main reason it's never been exposed on CentOS CIs is because there's not baremetal running CentOS (AFAICT).  Nice catch!

**Comment by liubin** [comment]
Note: this line has the same issue.

```
echo "skip_missing_names_on_install=0" | sudo tee -a /etc/yum.conf
```
