### ISSUE TITLE
kata-log-parser fails because of missing PID

### ISSUE THREAD

**Issue by littlejawa** [kata-containers/tests#4632]
When using logs from the containerd-shim-v2, kata-log-parser fails because some of the logs have no PID.
While kata-log-parser is used in our CI's teardown script, this makes it useless, as it actually fails on every run.

We would need to make kata-log-parser more tolerant over the log format.

**Comment by wainersm** [comment]
Hi @littlejawa always bothered me the fact that kata-log-parser runs on the teardown and it doesn't fail the job. I suspect it is because the tool is used, in CI, as a mere log collector, i.e., the intention is not really to test the tool. This should be changed IMO.
