### ISSUE TITLE
tracing test fails on ARM ci job

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#4684]
The tracing test fails on ARM due to problems with the tmux session. There is no problem with the agent shutdown test which also uses tmux sessions. I suspect the problem is either improper shutdown of the kata trace forwarder tmux session at the end of the agent shutdown test prior to the tracing test (which should be fixed in https://github.com/kata-containers/tests/issues/4678), or an error with capturing the output of the tmux session. 

```
10:43:53 [tracing-test.sh:259] INFO: Creating trace forwarder tmux session
10:43:53 + tmux new-session -d -s kata-trace-forwarder-session 'kata-trace-forwarder -l trace'
10:43:53 + tmux capture-pane -pt kata-trace-forwarder-session
10:43:53 + grep '"source":"kata-trace-forwarder"'
10:43:53 server exited unexpectedly
10:43:53 + die 'trace forwarder not running in kata-trace-forwarder-session'
10:43:53 + local 'msg=trace forwarder not running in kata-trace-forwarder-session'
10:43:53 ++ basename tracing/tracing-test.sh
```

Since the test was originally intended for the 'jenkins-ci-ubuntu-20-04' job, and priority right now for the tracing test is to enable agent tracing in the test and expand hypervisor usage in testing, let's limit both the agent shutdown test and the tracing test to x86_64.

Note: @Jakob-Naucke this change will also disable these tests on s390x. While the tracing test alone may be stable on that ci job, with agent tracing enabled in the test it should not be run without the agent shutdown test first, which is unstable for the s390x job.

**Comment by Jakob-Naucke** [comment]
a very late /cc @BbolroC
