### ISSUE TITLE
ci: jenkins CI set-up on aarch64

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#472]
We have been working on setting up jenkins CI on aarch64 for a while. There exists several issues, and we will declare and discuss here.
@jodh-intel @jongwu @weichen81
The community are considering to transfer to zuul, dropping jenkins, but probably we may be dedicated to build jenkins firstly, and mirror the set-up procedure in zuul.😁

**Comment by Pennyzct** [comment]
Can we reopen this? the whole set-up issue hasn't been solved yet😭 @jodh-intel @chavafg

**Comment by grahamwhaley** [comment]
Sure, if that is what you need, then np... pressing button now...

**Comment by Pennyzct** [comment]
can we re-reopen this? it's still on going.😅

**Comment by grahamwhaley** [comment]
Sure - it keeps closing as you are marking it as 'Fixed' in your commits that are merging ;-)
You may want to open new Issues for your branches until this is finally done then...

**Comment by Pennyzct** [comment]
thanks. @grahamwhaley . I will open new issues for small tasks and refer them here.😁
