### ISSUE TITLE
CI: distro installs: use more chronic

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#479]
A whole bunch of our apt installs etc. in the CI scripts are filtered via [chronic](https://joeyh.name/code/moreutils/) so they are silent unless they fail - but we only seem to have that on the first half of the script, and its use sort of stops around:
https://github.com/kata-containers/tests/blob/master/.ci/setup_env_ubuntu.sh#L44

Add more `chronic`s as necessary to calm the log output down...

**Comment by grahamwhaley** [comment]
@chavafg - just to check - is there any reason we don't do this at present, or has it just been oversight as we've added things to the scripts maybe?

**Comment by jodh-intel** [comment]
+1 for less apt output :)

**Comment by chavafg** [comment]
Found some more places where we can add chronic.
