### ISSUE TITLE
add cmd/check-markdown/kata-check-markdown to .gitignore

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#4790]
After running `./.ci/static-checks.sh --docs` there will be a file named `cmd/check-markdown/kata-check-markdown` remained.

**Comment by jodh-intel** [comment]
@wainersm - are you still looking at this? If not, could I possibly hijack it and give it to one of our outreach students?

**Comment by jodh-intel** [comment]
@Toreseen - if you do this, you'll need to:

```bash
$ git clone https://github.com/kata-containers/tests
$ git remote add Toreseen-github https://github.com/Toreseen/tests
$ git checkout -b update-gitignore
```

Then,

- Browse to https://github.com/kata-containers/tests and click "fork".
- Run the command @liubin has specified above.
- Check that the output of `git status` shows `cmd/check-markdown/kata-check-markdown`.
- Modify the top-level `.gitignore` to add `cmd/check-markdown/kata-check-markdown`.
- Re-run `git status` and ensure that `cmd/check-markdown/kata-check-markdown` is no longer shown.

Then,

```bash
$ git commit -as
$ git push -f Toreseen-github
```
