### ISSUE TITLE
socat repo, used in the tracing tests has been down for some time

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#4847]
Let's switch to a GitHub mirror of that repo, such as: https://github.com/3ndG4me/socat

This is affecting the Ubuntu CI: http://ci.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-PR/

**Comment by cmaf** [comment]
The mirror version doesn't support VSOCK, so we are going to temporarily disable the tracing test and agent shutdown test instead.
```
+ die 'Exiting as need version of socat with VSOCK support'
+ local 'msg=Exiting as need version of socat with VSOCK support'
+ '[' -z '' ']'
+ '[' -z true ']'
+ echo 'ERROR: Exiting as need version of socat with VSOCK support'
ERROR: Exiting as need version of socat with VSOCK support
+ local error_location
```
