### ISSUE TITLE
ci: rootfs image during the tests is not the same one released as part of the static binaries

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#4850]
When installing the kata image as part of our CI scripts, unless `osbuilder_distro` is specified, we'd end up using an ubuntu image, see: https://github.com/kata-containers/tests/blob/2b549f992e7f0c076b75b7164b9b93c8a995f410/.ci/install_kata_image.sh#L44

And we do not specify `osbuilder_distro` when calling the script, see: https://github.com/kata-containers/tests/blob/2b549f992e7f0c076b75b7164b9b93c8a995f410/.ci/install_kata.sh#L34

This leads to testing using a rootfs image, but then doing a release with an image that was not tested as part of our CI.

**Comment by stevenhorsman** [comment]
The unifying of the base images used in test and release would be great and ties in with the work in https://github.com/kata-containers/tests/issues/4893
