### ISSUE TITLE
'Check Subsystem' fails for merge commits

### ISSUE THREAD

**Issue by GeorginaKin** [kata-containers/tests#4929]
Currently the 'Commit Message Check' for a PR fails when there is a merge commit included - this is because the merge commit has no subsystem type in the commit message which causes failure.
You can see an example of this [here](https://github.com/kata-containers/tests/runs/7324203259?check_suite_focus=true) in the latest PR I opened to merge main into the CCv0 branch:

**Comment by bookinabox** [comment]
^Those were just testing on a personal repo. I'm just adding an or  "Merge " for the subsystem check. If there was a better way that this was done in the main repo, lmk bc I couldn't find it.

**Comment by GeorginaKin** [comment]
Closing as #4932 has been merged and the issue has been fixed - tested with the new merge issue: #4955
