### ISSUE TITLE
Nydus test not working properly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#4947]
It seems that the test nydus is not working properly in several CI's
```
20:19:56 Running nydus integration tests
20:19:58 Image is up to date for sha256:dcac4621b8636ac822ab7737648a272fcf378b8df6d315816036f00d5536d1e2
20:19:59 Pod 41f67b9745ecad1b64868d2045a5f35c9701fa42d3fcbbd26060c2ae954f67fc created
20:20:03 Container 00ee670e18c7ce45a1acc30062498d2333ef378bb2d8a1be944737bca25bc5a4 created
20:20:03 time="2022-07-16T01:20:03Z" level=fatal msg="starting the container \"00ee670e18c7ce45a1acc30062498d2333ef378bb2d8a1be944737bca25bc5a4\": rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: ENOENT: No such file or directory: unknown"
20:20:03 [nydus_tests.sh:153] ERROR: sudo -E crictl start 00ee670e18c7ce45a1acc30062498d2333ef378bb2d8a1be944737bca25bc5a4
```
see http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-CONTAINERD-main-baseline/324/console
/cc @liubin

**Comment by liubin** [comment]
Is it better to disable it temporally to not block any PRs?

I read some logs and verified recent changes, but I can't get the reason cause it failed.
I'm planning to verify it locally.

**Comment by stevenhorsman** [comment]
Hey, I've been looking into this problem a bit as I originally noticed it effecting the CC tests on Friday. I don't think there have been any nydus related patches merged and did a diff of the console log for before and after this error happened. The only thing I spotted that was different is the host kernel has changed: `Kernel = "5.13.0-1031-azure"` -> `Kernel = "5.15.0-1014-azure"`. This might be unrelated, but wanted to mention it in case it helped!

**Comment by GabyCT** [comment]
@liubin here it is https://github.com/kata-containers/tests/pull/4949 and thanks @stevenhorsman for the info

**Comment by liubin** [comment]
It can work locally.
I will keep on debugging it.

**Comment by liubin** [comment]
Found these errors:
`dest stat error. /run/kata-containers/48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99/rootfs/etc/resolv.conf`

> Jul 20 03:34:01 ubuntu20-586200 kata[47942]: time="2022-07-20T03:34:01.179525793Z" level=debug msg="reading guest console" console-protocol=unix name=containerd-shim-v2 pid=47942 sandbox=ff996ca8ff841413e861ccf82a4bc97dcbd9dc0c7fa6a7e5fe7653b1b11690d4 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"dest stat error. /run/kata-containers/48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99/rootfs/etc/resolv.conf: ENOENT\",\"level\":\"INFO\",\"ts\":\"2022-07-20T03:34:01.163240551Z\",\"name\":\"kata-agent\",\"eid\":\"48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99\",\"version\":\"0.1.0\",\"action\":\"child process log\",\"pid\":\"59\",\"cid\":\"48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99\",\"subsystem\":\"container\",\"module\":\"rustjail\",\"source\":\"agent\"}"
Jul 20 03:34:01 ubuntu20-586200 kata[47942]: time="2022-07-20T03:34:01.181129631Z" level=debug msg="reading guest console" console-protocol=unix name=containerd-shim-v2 pid=47942 sandbox=ff996ca8ff841413e861ccf82a4bc97dcbd9dc0c7fa6a7e5fe7653b1b11690d4 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"mount error: ENOENT\",\"level\":\"INFO\",\"ts\":\"2022-07-20T03:34:01.167134178Z\",\"version\":\"0.1.0\",\"source\":\"agent\",\"pid\":\"59\",\"eid\":\"48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99\",\"action\":\"child process log\",\"cid\":\"48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99\",\"subsystem\":\"container\",\"module\":\"rustjail\",\"name\":\"kata-agent\"}"
Jul 20 03:34:01 ubuntu20-586200 kata[47942]: time="2022-07-20T03:34:01.182543664Z" level=debug msg="reading guest console" console-protocol=unix name=containerd-shim-v2 pid=47942 sandbox=ff996ca8ff841413e861ccf82a4bc97dcbd9dc0c7fa6a7e5fe7653b1b11690d4 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"temporary parent process exit:child exit: ENOENT: No such file or directory\",\"level\":\"INFO\",\"ts\":\"2022-07-20T03:34:01.168493047Z\",\"cid\":\"48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99\",\"version\":\"0.1.0\",\"name\":\"kata-agent\",\"eid\":\"48c6784d791350064df091d0d51249233d7d47814b49c8ef97a21198296a0d99\",\"module\":\"rustjail\",\"subsystem\":\"container\",\"action\":\"child process log\",\"source\":\"agent\",\"pid\":\"59\"}"
