### ISSUE TITLE
CI network stability

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#507]
Saw at http://jenkins.katacontainers.io/job/kata-containers-agent-fedora-27-PR/77/console and it seems to be network issue after googling a bit of the error `OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104`.

```
[kata-containers-agent-fedora-27-PR] $ /bin/bash /tmp/jenkins8220582811189955888.sh
Cloning into 'tests'...
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

I remember seeing transient network issues before but it looks quite stable recently. Let's keep track of transient network issues here and see if it comes back often.

**Comment by devimc** [comment]
I haven't seen more network issues, can we close this?
cc @chavafg

**Comment by chavafg** [comment]
lets close, haven't seen them either.
