### ISSUE TITLE
CI: `codecov/patch` check issue

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#508]
Not sure if this is the right place to raise this but I want to raise an issue w.r.t. `codecov/patch` check in out PR CI check list, after digging through a failure in kata-containers/runtime/pull/458.

The codecov failure on that PR (`codecov/patch — 39.13% of diff hit (target 64.16%)`) looks bogus since clearly the patch is already properly tested with UT.

Looking at https://codecov.io/gh/kata-containers/runtime/commit/b821a5df4c1adb154613b80f981ba16684ed8b80, the change in kata_agent.go is clearly covered by UT in kata_agent_test.go but the patch diff coverage for kata_agent.so is reported as `0%`.

This looks to be an issue on codecov.io side. I would suggest we either remove codecov/patch, or always ignore it during reviewing.

@egernst @sboeuf @jodh-intel @grahamwhaley @WeiZhang555 @gnawux WDYT?

**Comment by sboeuf** [comment]
@bergwolf I agree I've seen many `codecov/patch` weird behavior compared to `codecov/project` which was always properly reporting the coverage as expected.
Unless someone thinks `codecov/patch` is needed for a good reason, I think keeping `codecov/project` only will be enough.

**Comment by sboeuf** [comment]
@kata-containers/tests any opinion on this ?

**Comment by jodh-intel** [comment]
+1 to removing patch.
