### ISSUE TITLE
metrics: Iperf3 bandwidth, jitter, multiqueue and bidirectional tests

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#509]
This test measures bandwidth,  jitter, multiqueue and bidirectional bandwidth using iperf3

**Comment by grahamwhaley** [comment]
If we are considering pulling this in from the https://github.com/clearcontainers/tests/blob/master/metrics/network/network-metrics-iperf3.sh type tests, then I really want us to do a deep analysis on the data we get for stability and repeatability.
Previously those tests showed a huge amount of noise and variation (on my platforms at least), which can lead to misleading results.

The core issue I think is that these tests, when run on a single machine, basically end up as a pure S/W stack CPU bound test, so anything perturbing the CPU impacts the numbers greatly.

**Comment by GabyCT** [comment]
@grahamwhaley these tests are not going to be part of the CI.

**Comment by grahamwhaley** [comment]
OK. We still need to have a very firm grip on the results they produce though - we don't want folks running them and taking the first numbers they produce without an idea of the 'quality' of the expected results.
