### ISSUE TITLE
ARM failure unit CI

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#5119]
Most of the time the ARM unit CI is failing with
11:09:56 test util::tests::test_interruptable_io_copier_shutdown ... ok
11:09:57 test util::tests::test_interruptable_io_copier_reader ... ok
11:10:01 test watcher::tests::verify_container_cleanup_watching ... ok
11:10:03 
11:10:03 failures:
11:10:03 
11:10:03 failures:
11:10:03     watcher::tests::create_tmpfs
11:10:03 
11:10:03 test result: FAILED. 110 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 10.44s

**Comment by jongwu** [comment]
Thanks @GabyCT -, It seems the environment of CI machine is not clean. There are lots of mount entries. After some cleanup work, the CI can pass again.

**Comment by GabyCT** [comment]
Thanks @jongwu
