### ISSUE TITLE
go get github.com/containerd/containerd failed

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#5249]
http://jenkins.katacontainers.io/job/kata-containers-dragonball-tests-ubuntu-20.04-PR/167/console

> 15:00:09 + go get github.com/containerd/containerd
15:00:09 # github.com/containerd/containerd/pkg/cap
15:00:21 ../../containerd/containerd/pkg/cap/cap_linux.go:83:15: undefined: strings.Cut
15:00:21 # github.com/containerd/containerd/images
15:00:23 ../../containerd/containerd/images/mediatypes.go:105:24: undefined: strings.Cut
15:00:23 ++ err_report

**Comment by liubin** [comment]
due to this containerd's patch https://github.com/containerd/containerd/commit/eaedadbed01219f6d074e739574f40ad7d72b126

**Comment by fidencio** [comment]
@liubin, in general we should get away of the `go get` approach, and simply use a `git clone` instead.

The problem on updating golang is that it'll require a whole lot of work in the CI side as well, which was already started by @bergwolf.  See; https://github.com/kata-containers/kata-containers/pull/5511

I think the best way to proceed is working together on Tao's PR.  WDYT?

**Comment by liubin** [comment]
yes, as @bergwolf  has done in https://github.com/kata-containers/tests/pull/5224.

This issue comes out recently, and if not fixed asap, it will break other PRs, so I think we can do a temporary fix to let the CI pass.

**Comment by fidencio** [comment]
I agree 100% with the temporary fix, I just think it'll require more work on the tests side in order to have it passing.
