### ISSUE TITLE
ci: install-kata-kernel.sh are likely pending forever

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#525]
when I run .ci/install-kata-kernel.sh, it were pending forever at command line `make -s ARCH=${kernel_arch} oldconfig > /dev/null`. 
Removing redirection, the pending comes from prompting new options which weren't listed in config file.
`Cortex-A55: 1024718: Update of DBM/AP bits without break before make might result in incorrect update (ARM64_ERRATUM_1024718) [Y/n/?] (NEW)`
Maybe we could add` yes` command to repeatedly "press enter", which will result in using the defaults value for the `make oldconfig` command.
`yes "" | make -s ARCH=${kernel_arch} oldconfig > /dev/null`
Hi~@jcvenegas. if I'm right, could you add it to #https://github.com/kata-containers/packaging/pull/79. After all, this script will reuse your pull request eventually.

**Comment by jcvenegas** [comment]
@Pennyzct so redirecting to `/dev/null` was hiding that the config had missing configs to be defined. I would prefer to remove the `/dev/null` redirection and let the user decide if want that new config or not.

After the config process finish the user should save that new config and use it in the future or sent a PR with those new additions.

**Comment by jcvenegas** [comment]
So if you are getting those new question from the config could you decide if should go or not and send a PR to update the config. This will help new users use a good default defined from us.

**Comment by Pennyzct** [comment]
@weichen81
