### ISSUE TITLE
CC: add e2e tests for IBM SE on CI

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/tests#5256]
**Which feature do you think can be improved?**

Similar to #4977, we would like to establish e2e tests for IBM secure execution (SE) to verify the functionality for TEE-enabled CC. 

We are currently waiting for a public test machine (SE-enabled) on IBM cloud. In the mean time, as an initial step, we would like to set up a CI job without SE, but with an encrypted image of a test pod on the current Jenkins slaves for s390x. 
When the machine is available (hopefully in December, 2022), we will extend the tests to embrace SE.

**How can it be improved?**

1. Declare `CC_SE_CRI_CONTAINERD_K8S` for `CI_JOB` at  https://github.com/kata-containers/tests/blob/CCv0/.ci/ci_job_flags.sh#L108
2. Add a condition `CC_CRI_CONTAINERD_K8S_SE_QEMU` below 
https://github.com/kata-containers/tests/blob/CCv0/.ci/run.sh#L77
3. Add a test call to `make`  target `cc-se-containerd`
https://github.com/kata-containers/tests/blob/CCv0/.ci/run.sh#L77
4. Place a test script at `functional/se` like https://github.com/kata-containers/tests/tree/CCv0/functional/sev
5. Check if any modification is needed at building a rootfs image
https://github.com/kata-containers/tests/blob/CCv0/.ci/install_kata_image.sh#L51
6. Check if a special kernel for SE is needed
https://github.com/kata-containers/tests/blob/CCv0/.ci/install_kata_kernel.sh#L66
7. Add additional condition for SE for configuration placement under https://github.com/kata-containers/tests/blob/CCv0/.ci/install_runtime.sh#L134

I would like to hear any feedback from you: @stevenhorsman and @hbrueckner

**Comment by fidencio** [comment]
> As mentioned above I don't think we want to use these. The TDX CC tests are probably a better model to use, but I don' think they are ready quite yet.

I second that.

**Comment by BbolroC** [comment]
> https://github.com/kata-containers/tests/blob/005e1c7322c8fbe50b13e7606c2c819c7a72fedf/.ci/run.sh#L81
> 
> to call the `cc-kubernetes` test targets - the sev tests don't match the structure, or test cases of the rest of our CC testing, so I'd want us to invest in doing the SE tests correctly and build on the current tests cases, and just change the preparation if nescessary.

yeah, it does make sense to use the `cc-kubernetes` target. It looks simpler, but going in a right direction. Thanks. 

> `if we'd need to try and build it in when the rootfs is created.` 

As far as I understood from what Jakob showed me, creating a secure image is the last step after the rootfs including required files is created.  Anyhow, as I mentioned, the initial goal is to get the `cc-kubernetes` target running and the test passed with an encrypted pod image (without SE). I think you could give me more helpful comments after I finish the 1st test round and open up a PR.

Thank you. :wink:

**Comment by hbrueckner** [comment]
> > `if we'd need to try and build it in when the rootfs is created.`
> 
> As far as I understood from what Jakob showed me, creating a secure image is the last step after the rootfs including required files is created. Anyhow, as I mentioned, the initial goal is to get the `cc-kubernetes` target running and the test passed with an encrypted pod image (without SE). I think you could give me more helpful comments after I finish the 1st test round and open up a PR.

Agree with @BbolroC . The SE image creation should be the last step, running after picking up any additional content related to tests + any "personalization" of the image, e.g., offline kbc secrets. Let's build up this SE image creation after @BbolroC finished the work w/o SE.
