### ISSUE TITLE
CI failed to build agent-ctl

### ISSUE THREAD

**Issue by liubin** [kata-containers/tests#5376]
> 17:14:12     --> /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-tests-PR-qemu-devmapper/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/cgroups/fs/mod.rs:1028:5
17:14:12      |
17:14:12 1026 | fn new_cgroup(h: Box<dyn cgroups::Hierarchy>, path: &str) -> Cgroup {
17:14:12      |                                                              ------ expected `Cgroup` because of return type
17:14:12 1027 |     let valid_path = path.trim_start_matches('/').to_string();
17:14:12 1028 |     cgroups::Cgroup::new(h, valid_path.as_str())
17:14:12      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Cgroup`, found enum `Result`
17:14:12      |
17:14:12      = note: expected struct `Cgroup`
17:14:12                   found enum `Result<Cgroup, cgroups_rs::error::Error>`
17:14:12

**Comment by liubin** [comment]
`src/tools/kata-ctl` and `agent-ctl` use `cargo install` to build and install the binaries, but `cargo install` will default use the latest version of the dependencies, and there is a broken upgrade in cgroups v0.2.12.

Next, I'm planning to upgrade croups-rs in a separate PR, then you can rebase the main branch and continue your work.

Is it ok to you @yaoyinnan @dcantah?

**Comment by yaoyinnan** [comment]
> `src/tools/kata-ctl` and `agent-ctl` use `cargo install` to build and install the binaries, but `cargo install` will default use the latest version of the dependencies, and there is a broken upgrade in cgroups v0.2.12.
> 
> Next, I'm planning to upgrade croups-rs in a separate PR, then you can rebase the main branch and continue your work.
> 
> Is it ok to you @yaoyinnan @dcantah?

Thanks, I will rebase after the upgrade croups-rs.

**Comment by liubin** [comment]
Closed by https://github.com/kata-containers/kata-containers/pull/6035
