### ISSUE TITLE
incrementing kata_config_version for kernel config option changes

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#5419]
Is or was there a check that ensures kata_config_version is updated when kernel config options are added or removed in tools/packaging? I noticed that there were a few patches that were merged that did **not** increment the version.

**Comment by amshinde** [comment]
@cmaf We used to have this check which I can find in the older repos: 
https://github.com/kata-containers/packaging/blob/17f37e029c2fe20f7d514e6e3a01cfb9a2523aaa/.ci/test.sh#L43
But I cannot see that check anymore in our current repos.  Will try to check for the git history tomorrow to see when we dropped this check. 
Its necessary that we bring this check back to make sure we test for the latest kernel config changes in our CI. Without this check enforced, I think the CI may end up testing with an older kernel. 
cc @GabyCT

**Comment by cmaf** [comment]
Thanks @amshinde, tentatively assigning this to you
