### ISSUE TITLE
kata-containers repo checks out 'kata_default_branch' and overwrites existing branch

### ISSUE THREAD

**Issue by ryansavino** [kata-containers/tests#5431]
# Description of problem

In the scripts, if kata-containers repo exists, a checkout of the 'kata_default_branch' is performed when it should not be. This overwrites the branch under test where existing work needs to be verified.

# Expected result

The working branch should be used and tested.

# Actual result

'kata_default_branch' is checked out instead.

**Comment by stevenhorsman** [comment]
Closed with #5432 merging
