### ISSUE TITLE
Kubernetes install failing due to broken apt key link

### ISSUE THREAD

**Issue by ryansavino** [kata-containers/tests#5494]
# Description of problem

The k8s install fails and reports an issue downloading the apt key.

# Expected result

Successful k8s install.

# Actual result

Tests log of k8s install failing:

```
09:09:03 INFO: Install Kubernetes
09:09:03 Install Kubernetes components
09:09:03 Warning: apt-key output should not be parsed (stdout is not a terminal)
09:09:03 gpg: no valid OpenPGP data found.
```

**Comment by GabyCT** [comment]
Closing this as the CI is running
