### ISSUE TITLE
CC | KBS Resource URI scheme test update for CI

### ISSUE THREAD

**Issue by Xynnn007** [kata-containers/tests#5521]
**Which feature do you think can be improved?**

[This PR](https://github.com/kata-containers/kata-containers/pull/6404#issuecomment-1465825400) brings [KBS Resource URI](https://github.com/confidential-containers/documentation/issues/85) and [the unified image format](https://github.com/confidential-containers/attestation-agent/issues/113) together with ttrpc.

KBS URI and the unified image format will cause the current test images fail to decrypt. We need to remake test images using the new key provider (although it is under reviewing, it can work to make test images) https://github.com/confidential-containers/attestation-agent/pull/143

cc @stevenhorsman

**Comment by stevenhorsman** [comment]
So I think one of the challenges we have here is which container registry to pick: 
- Currently most of our images are in quay.io, but we've found in the past at least that it doesn't work probably with encrypted images
- The old encrypted images the `ssh-demo` (for offline_fs_kbc and eaa_kbc tests) are on dockerhub, but due to pull rate limits, this causes issues when being run on enterprise infrastructure

**Comment by fitzthum** [comment]
Ok let's make a list of images that we need (and then their location in the CI). we should try to generate these images ASAP so we are ready to switch to new version of the AA.

**Encrypted Image**
- unencrypted ssh image
- encrypted ssh image

I think all the encrypted image tests use the same image, which is made from [this](https://github.com/confidential-containers/documentation/tree/main/demos/ssh-demo).

for the SEV tests we use images that have their decryption keys and private key for ssh connection stored as labels, which is kind of handy (although docker can't read the labels of the encrypted images). we should consider doing this again for our generic image.

**Signed Image**
signed images @stevenhorsman might have more details here.

**Enclave-CC**
@mythi does enclave-cc need any other images for testing?

**Peer Pods**
@stevenhorsman again, does peer pods use any other images for testing?

**Comment by stevenhorsman** [comment]
Thanks for kicking this conversation off Tobin

**Encrypted image**
So the encrypted one we use is the ssh-demo as you've said, which we've pulled from docker for the 'offline_fs_kbc` tests as quay didn't work properly with encryption, but it sounds like ghcr.io might resolve that. I'm not wedded to it, being the encrypted image, but being able to ssh-into it to get it is working is kinda handy, but if we have another, better test case for checking the encrypted image I'm not against that.
As you know (but for the benefit of others), it is encrypted using the key in https://github.com/confidential-containers/documentation/blob/main/demos/ssh-demo/aa-offline_fs_kbc-keys.json which we pull in directly in our tests, but modifying it to add the key in the fixtures directory directly shouldn't be an issue if we need to use something different
It is worth noting that the current image is multi-arch as we use it for testing both x86 and s390x

**Signed images**
We have a bunch of images here in https://quay.io/repository/kata-containers/confidential-containers?tab=tags 

I'll try and explain what they are and what other resources we need that are linked to them:
- `quay.io/kata-containers/confidential-containers:unsigned` is just an unsigned image that is nginx. The reason it is there is to ensure that is that in our policy we state that `quay.io/kata-containers/confidential-containers` should always be signed, so when pulling this we check it fails
- `quay.io/kata-containers/confidential-containers:signed` is the signed version of nginx, signed with the public bit of the gpg key used base64 encoded in https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/offline-fs-kbc/x86_64/aa-offline_fs_kbc-resources.json and the signature claim of this is in the tar https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/quay_verification/x86_64/signatures.tar
- `quay.io/kata-containers/confidential-containers:other_signed` is a signed busybox image. It was signed with a random pgp key that I threw away, but the signature claim file is included in  https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/quay_verification/x86_64/signatures.tar. The purpose of it to check that an image signed with a different gpg key is rejected.

- `quay.io/kata-containers/confidential-containers:unsigned-s390x`, `quay.io/kata-containers/confidential-containers:signed-s390x` and `quay.io/kata-containers/confidential-containers:other_signed-s390x` are the s390x equivalents of the above 3 images that @BbolroC created. If we can instead switch to multi-arch images (I'm not sure what that means in terms if signing as I guess they'd have different signature claim files for the different arches - I guess we could use the same gpg public keys and stuff them in the same signature tar to make it a little cleaner though?

`quay.io/kata-containers/confidential-containers:cosign-signed` is an image that @Xynnn007 created so is co-sign signed with the public bit of the gpg key used base64 encoded in https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json
- `quay.io/kata-containers/confidential-containers:cosign-signed-key2` is another image that @Xynnn007 co-signed, with a gpg key pair that was thrown away - similar to the approach in `quay.io/kata-containers/confidential-containers:other_signed` 
- `quay.io/kata-containers/confidential-containers:cosign-signed-s390x` is the s390x version that I think @BbolroC created again.

The key take aways are that for the signed images we need to keep hold of the public gpg key and signature claim files (for red hat simple signing) and add them into our fixtures. We also need to update the policy.json files if we move to a new container registry

**Authenticated images**
https://quay.io/repository/kata-containers/confidential-containers-auth?tab=tags contains some images that are in an registry that is not public to test the authenticated registry pull.
It consists of `quay.io/kata-containers/confidential-containers-auth:test` which is a mutli-arch image pointing to the s390x and amd64 versions and I think I just pushed nginx there again.

**Peer pods**
The good news here is that we don't have any specific peer pod tests images at the moment - the plan would be to re-use the Kata-CC/CoCo ones as we extend the test cases to add encrypted image/signature checking support

One thing that would be worth noting as the test images get produces would be to document the process of how we did them (and maybe script it?) so it's easier to re-create them in future as I know when I was helping Choi create the s390x versions I had to look back at randomly disconnected docs I'd made to find the steps I took.

I hope this helps, but let me know if there are things I've glossed over, or don't understood.

**Comment by fitzthum** [comment]
Ok, thanks for the overview @stevenhorsman. That is very useful.

Let me attempt to list what adaptations we will need to make for the new KBS URI for each of these categories. 

For the encrypted images, the resource id is stored in the image annotation, so we will need to re-encrypt the images. We could potentially use the same unencrypted image. We should add the labels so that we don't break the SEV stuff. For the `offline_fs_kbc` we will need to update the json resource file that goes inside the image so that the keys have the proper IDs. We'll probably also need to update the keys themselves while we're at it. For SEV, we will need to update the tests to populate the KBS DB with keys that have the correct ID. I don't think any code changes are required, but we'll see. I'm not sure how the keys are provisioned to the EAA KBC, but something will probably need to be updated there.

For the signed images, we should be able to use the same images (moved to ghcr). We will need to update all the stuff mentioned above to use the proper IDs for all the resources. We will also need to update the policy files to match the new registry. Multiarch signed images seem like a good idea, but I think that is technically orthogonal to the image format changes.

Authenticated registries are basically the same thing. We just need to update the resource ID for the `offline_fs_kbc`.

So there are some moving pieces here, but I think we can get it sorted out. I can start creating some of these resources next week and lineup the test changes.

**Comment by mythi** [comment]
> **Enclave-CC**
> @mythi does enclave-cc need any other images for testing?

`enclave-cc` images are currently not very well coordinated/organized:

The initial POCs used `docker.io/huaijin20191223/scratch-base:v1.8` which is a minimal image with just a hello world binary installed. This image is still being used for kind tests w/ SGX simulation.

For the CNCF workshop/demo I used that same image and encrypted it using sample keyprovider and pushed to `docker.io/mylinen/hello-world-encrypted:samplekbc2`. This is also used by our SIM CI.

The real HW CI uses the same base but encrypts using `verdictd` and for testing we use it `eaa_kbc` from `docker.io/eqmcc/helloworld_enc`. This also comes with cosign signing.

I'm trying to find the `Dockerfile` and C code for this hello-world image. :-) While it would be nice to continue using this very trivial image, I feel some more meaningful workload would be better. I've not tried any of the existing Kata images. We have done some testing using `redis` which could be something to consider to replace that hello-world image...

**Comment by stevenhorsman** [comment]
Sorry something I forgot is that EAA does have their own versions of some of the test images at the moment that I think @arronwy created.

**Comment by Xynnn007** [comment]
> I'm trying to find the Dockerfile and C code for this hello-world image. :-) While it would be nice to continue using this very trivial image, I feel some more meaningful workload would be better. I've not tried any of the existing Kata images. We have done some testing using redis which could be something to consider to replace that hello-world image...

Hi @mythi I've set-up a local verdictd on the test ci machine. If the code and dockerfile are found please share with me, I can make a image and test this.

**Comment by stevenhorsman** [comment]
> Ok, the signature images should be available [here](https://github.com/orgs/confidential-containers/packages)
> 
> I made a couple adjustments to the names. First, rather than call the image itself confidential-containers, now all the containers are in the `confidential-containers` org and the images are called `test-container` and `test-container-s390x`. I separated the `s390x` stuff into a different image rather than using the labels. The labels are mostly the same, but I changed `other_signed` to `signed-wrong-key`. Hopefully the new names are a little more organized, but maybe I made it worse. I will be making a change to the tests shortly to use these new images (without the resource uri changes for now) to make sure everything works. That PR will have a full listing of all the name changes.

Thanks - the org change and signed-wrong-key tag change makes a lot more sense - so thanks for taking the opportunity to improve it!

**Comment by mythi** [comment]
> > I'm trying to find the Dockerfile and C code for this hello-world image. :-) While it would be nice to continue using this very trivial image, I feel some more meaningful workload would be better. I've not tried any of the existing Kata images. We have done some testing using redis which could be something to consider to replace that hello-world image...
> 
> Hi @mythi I've set-up a local verdictd fitting with the new encrypted image format on the test ci machine. If the code and dockerfile are found please share with me, I can make a image and test this.

They were lost but I created something equivalent from scratch: https://github.com/confidential-containers/enclave-cc/pull/137
