### ISSUE TITLE
Add `mshv` tests

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#5528]
In order to test `mshv` ideally we'd need to:
* [x] Have a Linux machine added to our CI were we can run tests for `mshv`
   * If this can be achieve using GitHub actions, better, as this becomes the starting point for me to have more and more tests switched to using GitHub actions (see: https://github.com/kata-containers/ci/issues/529).
* [x] "Mirror" at least one specific CI job to be used for `mshv`
   * I'd suggest something that runs k8s tests, ctr tests, and maybe even one with devmapper
   * It could be interesting to have this testing different VMMs, but we can start with only one, whichever is the MSFT's choice

We may need to expand this list at some point, but this is mostly a place-holder for now.

**Comment by jepio** [comment]
Just a minor clarification - this will be a Linux machine.

**Comment by fidencio** [comment]
> Related question @fidencio: do we currently have tests that build utilize a non-ubuntu kata container VM rootfs/initrd image? I know that we test eg. fedora as the host, but afaik that still uses the (default) ubuntu output of osbuilder for the guest VM.

Not yet, but I was about to open that issue and mention what we need to do as part of the review for the CBL Mariner addition. :-).

**Comment by sprt** [comment]
Fixed in https://github.com/kata-containers/kata-containers/pull/6839
