### ISSUE TITLE
kata-manager: add option to install from release binaries

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#559]
Running "[`kata-manager.sh`](https://github.com/kata-containers/tests/tree/master/cmd/kata-manager) ` install-packages`" will (indirectly) install the packages from OBS.

Since we continue to experience problems with OBS, it would be useful to have an option to install the packages from the [release binaries](https://github.com/kata-containers/runtime/releases/tag/1.1.0) as suggested by @chavafg on https://github.com/kata-containers/osbuilder/pull/143#issuecomment-410065602.

**Comment by GabyCT** [comment]
Closing this issue as we are not using OBS installation in the CI
