### ISSUE TITLE
Testing Disk IO performance

### ISSUE THREAD

**Issue by chandrabvv** [kata-containers/tests#560]
How can we turn off caching of disk in memory to test the disk IO performance? We can turn off caching In KVM virtual machine by setting the "cache=none" in config file of virtual machine, but i am not able to find such option in Kata containers. In case of Docker containers, simply setting directio in the application will do the job but not in the case of Kata container because it is a light weight VM and processes running inside it will not be visible to host kernel.

**Comment by grahamwhaley** [comment]
Hi @chandrabvv ,
 Indeed, as you have pointed out, Kata presents a more complex challenge when trying to manipulate disk caching, as you have caches both inside the guest VM and outside on the host. And, afaik, when you perform actions inside the VM (such as disabling, bypassing or flushing the caches), they do not propagate out to the host.

When you mention `cache=none` - are you specifically referring to the 9pfs cache mode here? I suspect you are. Sadly it seems there is no configuration item in the Kata config file to add/adjust the 9p mount commandline - not beyond setting the 'msize'. Checking into what our current settings are though:

- [here](https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L55) are the default 9p options used by Kata, and afaict, we do not set a `cache=` option.
- Looking at the [kernel 9p docs](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/9p.txt#n71) it looks like the default is for no caches to be used with 9p

So, I suspect currently we are operating in `cache=none` mode for 9p. I have tried to check this by looking at the output of `mount` inside a running Kata container - and no `cache` elements appear - but, be aware, iirc, `mount` may not show all the options 9p has set (for instance, iirc it does not show the `2000L` mode we are using).

Ultimately then, I think:
- you should be aware that there are a number of layers of caching, both inside the VM and on the host
- if you wish to modify the 9p settings, or the `QEMU` invocation line, I think:
    - the easiest approach will be for you to build a local Kata from source
    - and if you make some generic modifications, such as adding the ability to add items to the 9p mount options into the Kata toml configuration file - then we would *love* to have some PRs to review and add that to the codebase ;-)

**Comment by chandrabvv** [comment]
Hi @grahamwhaley ,
Thanks for prompt and detailed reply. I am not much aware of 9pfs caching. My query was about file caching in linux , irrespective of file system. User can specifically set in its application about choice of file caching (yes or no) by using O_DIRECT in open() system call. This option is available in KVM vm config file as "cache = none", [https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_tuning_and_optimization_guide/sect-virtualization_tuning_optimization_guide-blockio-caching](details). So, I was just asking that, is there any such option in the config file of Kata containers. According to reply, it seems that it is currently not available. And irrespective of file system, what is the default caching policy for containers (light weight VM) in Kata technology?

**Comment by grahamwhaley** [comment]
Hi @chandrabvv Looking at that link to virt-manage docs (thanks!), I think this is going to quickly get complex ;-).
I think that specific link is referring to disk image and block mounts, probably into QEMU. For Kata, we have a number of methods/routes we use to map host side files and images into the guest. Off the top of my head, the most common ones are:
- 9p (over virtio) - our default for mapping the workload image into the guest
- blkdevice (when using a docker graph driver that supports this feature, such as devicemapper)
- NVDIMM/DAX - we use to map in the VM rootfs image (note, that is *not* the container workload, and not visible from within the container).

I believe how the cache mode is set and what it is currently set to by default for Kata will potentially be different for each of those cases.
For your case, presuming you are running some diskIO benchmarks inside the container, you will need to understand, depending on your setup, either how 9p/virtio is configured and works, or if you are using devicemapper on the host and thus have a blockdevice mapped through qemu to the guest container, how that block device is being handled by qemu.

I believe at present kata is not specifying a cache mode for either 9p or block devices. In that case, we will be using the default as set by QEMU and the host kernel/KVM. There is a hint on [this page](https://doc.opensuse.org/documentation/leap/virtualization/html/book.virt/cha.cachemodes.html#cachemodes.descr) that the default mode may be different for different types of mount.

If you wish to see which QEMU command line is being used to run your kata container, a quick method is to do something like:
```bash
term1$ docker run -ti --rm --runtime=kata-runtime busybox sh
# and then in another terminal
term2$ ps -ef | fgrep qemu
```

There you will see a (rather long) qemu invocation line, and from that, and maybe using the `mount` command inside your container, you can figure out which mount point your IO benchmarks will actually run on/exercise, and thus how that is actually mounted to the host via QEMU.

Be wary of trying to directly tie virt-manager docs up to how Kata works. Kata does not use virt-manager or libvirt, but uses a lot of the same technology. How we mount host side files and images can be quite different from what you may have experienced with virt-manager though.

Yes, I think we could do with some more comprehensive documentation for Kata on what the options are and how we mount/map files from the host into the guest and back again.

/cc @amshinde here for any input on the block device side.

@chandrabvv - I will be quite interested in what you find - and maybe we can collaborate on writing up some documentation here for others in the future?

@kata-containers/runtime folks and all - please dive in and correct any misconceptions I have here! ;-)

**Comment by chandrabvv** [comment]
@grahamwhaley 
Thanks for detailed explanation. I will share my findings with you.

**Comment by grahamwhaley** [comment]
@chandrabvv Hi. As it happens, I've had to take up some storage IO testing here as well.
I'm nearly ready to submit a PR that enables some testing using [fio](https://github.com/axboe/fio).
I also had a think and look into the buffercache enablement on both the host and guest side. I have a small patch that disables the buffer cache on the host (actually, it sets the QEMU QMP option of `cache=none` on the block mount, thus making QEMU access the host side devices in O_DIRECT mode, and thus bypassing the host side buffercaches). I'll PR that soon as an RFC so we can all discuss if that is the right thing to do or not.

**Comment by grahamwhaley** [comment]
Actually, I may as well post the tiny patch here, so you could try it if you wanted. Note, I don't think this is the real solution - I think we'd want it to be configurable from the Kata toml config file and then passed down to [govmm](https://github.com/intel/govmm), but this small hack enables testing the theory:

```patch
diff --git a/vendor/github.com/intel/govmm/qemu/qmp.go b/vendor/github.com/intel/govmm/qemu/qmp.go
index 32a59ef..92fbd20 100644
--- a/vendor/github.com/intel/govmm/qemu/qmp.go
+++ b/vendor/github.com/intel/govmm/qemu/qmp.go
@@ -640,6 +640,10 @@ func (q *QMP) ExecuteBlockdevAdd(ctx context.Context, device, blockdevID string)
                        "driver":   "file",
                        "filename": device,
                },
+               "cache": map[string]interface{}{
+                       "direct":   true,
+                       //"writeback": false,
+               },
        }

        if q.version.Major > 2 || (q.version.Major == 2 && q.version.Minor >= 9) {
```

The reason the `writeback` is commented out there is, afaict it was deprecated maybe in QEMU v2.9, and if you pass it in now QMP errors out.
