### ISSUE TITLE
metrics: drop the 3s sleeps on `docker stop`s

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#564]
Over on #476 we introduced serialisation and an extra sleep when shutting down multiple containers as it was showing up a lockup condition. Check that lockup has gone, and revert!

To check the problem has gone, recommendation is:
- run the metrics PR script under a VM
- run the mega death soak test, and see what happens when it tries to remove 110 nginx's

**Comment by grahamwhaley** [comment]
Also related, #563

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
