### ISSUE TITLE
spot and fix failed test suites under docker integration test on aarch64

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#567]
For now, not all test suites under docker integration test could be passed successfully on aarch64. 
We will track and fix those above tests in this issue, just as we discussed in #514 .
@jodh-intel @devimc @weichen81

**Comment by Pennyzct** [comment]
Hi~ @GabyCT  Could you reopen this?
This issue was created to track all the tests which are not passing on Arm right now. We thought that creating issue for each non-working test will keep too many flying issues, which we discussed in #514. 
Is there a do-not-close flag for this kind of issue, just like the do-not-merge flag?

**Comment by jodh-intel** [comment]
@Pennyzct - reopened.
