### ISSUE TITLE
iperf3 issue with ftruncate

### ISSUE THREAD

**Issue by chandrabvv** [kata-containers/tests#570]
Clear container had issue with ftruncate and is not able to run iperf3. https://github.com/intel/cc-oci-runtime/issues/152
Is this issue resolved in Kata containers? I am still not able to tun iperf3 using docker image http://networkstatic.net/measuring-network-bandwidth-using-iperf-and-docker/

**Comment by devimc** [comment]
a workaround would be to use `devicemapper` as  storage driver https://docs.docker.com/storage/storagedriver/device-mapper-driver/

**Comment by grahamwhaley** [comment]
Hi @chandrabvv The issue still exists afaik - it is to do with referencing unlinked files, and handling by 9pfs.
As @devimc says, if you use devicemapper and kata's block device mount mode for the workload, then the issue does not manifest as that will not use 9p.
Alternatively, we have a workaround in our `iperf3` tests that moves the TMPDIR to a RAM based filesystem. You can see the current fix at: https://github.com/kata-containers/tests/blob/master/metrics/network/network-metrics-iperf3.sh#L41

**Comment by chandrabvv** [comment]
@grahamwhaley @devimc 
Thanks for clarification.

**Comment by GabyCT** [comment]
Closing this issue as a solution was provided of how to run iperf3
