### ISSUE TITLE
Makefile: sort the contents....

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#581]
We try to maintain, where possible, files and lists in alphabetical order - but we seem to have a few things in our [Makefile](https://github.com/kata-containers/tests/blob/master/Makefile#L11) that break those rules (a cri one I think for instance).

Let's sort the file and lists ... **BUT** ... there is a risk here. In the past we have had some test run ordering issues whereby tests would randomly fail if they were ordered a certain way.
Thus, we can at least open a PR for this and see what happens. The tests should be inter-dependant, and we presently have no hard requirement to run any specific tests before others.

**Comment by jodh-intel** [comment]
+1. We just need to make sure we don't bork the default (1st) rule in doing this.
