### ISSUE TITLE
Reference 'how to hand run the tests' in this repo

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#584]
As mentioned over on https://github.com/kata-containers/community/pull/46#discussion_r204467611, we should have some link-backs between this repo where the tests live, and the contrib/community docs where we discuss how developers should/can run the tests by hand before they submit PRs.

I suspect the current best place for a link is around the [developer-mode section](https://github.com/kata-containers/tests#developer-mode).

**Comment by egernst** [comment]
This done?

**Comment by jodh-intel** [comment]
Doesn't appear to be done yet.

Now that https://github.com/kata-containers/tests/pull/920 has landed, we can add https://github.com/kata-containers/tests#run-the-kata-containers-tests to the dev guide.

**Comment by egernst** [comment]
You suggest we add a section which points to https://github.com/kata-containers/tests#run-the-kata-containers-tests , right @jodh-intel ?

**Comment by jodh-intel** [comment]
My original comment was about `static-checks.sh` specifically so maybe we should check with @grahamwhaley if my comment above aligns with his views :)
