### ISSUE TITLE
ExistDockerContainer must use container ID not container name

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#598]
`ExistDockerContainer` checks if the kata components (proxy, agent, qemu) are still running, the functions used to check this, are `HypervisorRunning` , `ProxyRunning` and `ShimRunning` https://github.com/kata-containers/tests/blob/master/integration/docker/docker.go#L210-L219, these functions need the container ID to check the commandline of all the running processes at `/proc` https://github.com/kata-containers/tests/blob/master/process.go#L55-L85 ,
the problem is that `ExistDockerContainer` is using the container name not the container ID, hence `ExistDockerContainer` always returns `false`. 

**Note: container's name can't be used since it's not present in the process command line**

**Comment by grahamwhaley** [comment]
np with this change, CID would seem the natural choice.
afaik, both CID and name are unique to a container in Docker I think - so, is there something that prompted the change - maybe we can accept either CID or name?
Just looking for a few more details really :-)

**Comment by devimc** [comment]
issue updated
