### ISSUE TITLE
ci: lib.sh: should `KATA_RUNTIME` default to `kata-runtime`?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#600]
I happened to be browsing the code, when I saw this in `.ci/lib.sh`:

https://github.com/kata-containers/tests/blob/master/.ci/lib.sh#L10
```
export KATA_RUNTIME=${KATA_RUNTIME:-cc}
```

I suspect that is wrong, and a hangover from early kata integration effort, for a couple of reasons:
- `cc` implies maybe **C**lear **C**ontainers
- but `cc` is actually the C compiler??

@chavafg @jodh-intel - wdyt - that should probably default to `kata-runtime`, yes?

**Comment by jodh-intel** [comment]
agreed.

**Comment by chavafg** [comment]
yes, that needs to be `kata-runtime`
