### ISSUE TITLE
metrics: genreport: high level list of feature improvements

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#601]
The metrics genreport scripts added on #597 have a lot of scope for improvement. This Issue is the high level place to collect potential improvements, that can then be worked upon in sub-Issues.

- [ ] Add an index/ToC the generated report
- [ ] Memory density
    - [ ] Improve text on PSS page
    - [ ] Explain 'n' is number of containers on system scaling page
    - [ ] Density/footprint changes as we increase vCPUs or VM memory allocation
    - [ x ] Add 2-results diff compare to footprint statistics - but see #709 
- [ ] Boot speed page
    - [ ] Scaling graph on if/how times are affected by number of already running containers.
- [ ] Network page
suggestions include:
    - [ ] [network cpu](https://github.com/kata-containers/tests/blob/master/metrics/network/cpu_statistics_iperf.sh)
    - [ ] [ab/nginx](https://github.com/clearcontainers/tests/blob/master/metrics/network/network-nginx-ab-benchmark.sh)
    - [ ] container-to-container measurements
    - [ ] container-to-host and reverse measurement
- [ x ] Disk I/O page
- [ ] Add grabdata ability to capture 'runc-in-a-VM' footprint data, as that is a useful compare against kata-VM footprint
- [ ] Summary page has a strange `The following object is masked from ’package:ggpubr’` warning when doing a kata/runc compare - should be an easy 'suppress' fix.

**Comment by GabyCT** [comment]
@grahamwhaley is this issue still open or the issues where fixed? thanks

**Comment by grahamwhaley** [comment]
I think we can close it - nobody is actively adding to the metrics report code.
