### ISSUE TITLE
Can we check that stdout/stderr produce correct output

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#62]
Relating to https://github.com/kata-containers/agent/issues/125 and https://github.com/kata-containers/agent/issues/124 - can we add a test that checks that what we get over stdout and stderr are in fact correct and whole.
@jodh-intel has suggested https://github.com/jamesodhunt/utfout (oh, look, it is written by @jodh-intel ;-) ) might be a good tool to use for this.
Other simpler thoughts from me are to:
- just check we get the right size we expect to start with
- we could do an md5sum compare to what we expect

/cc @chavafg

**Comment by jodh-intel** [comment]
... cough... in my defense, I should point out that I needed a tool to test *exactly* this sort of scenario with Upstart [*]. Upstart is rather clever so I couldn't use a shell to do this. I then realised there was an opportunity to create a useful generic tool that can do silly things like:

```
# Write continuous stream of nul bytes to stderr, 1 every second
$ utfout -b 1s -e '' -r -1

# Write "foo" 100 times direct to the terminal, pausing for 1/10 of a second between each write
$ utfout -b 1ds -t foo -r 99

# Display all braille characters to stderr
$ utfout "\{\u2800..\u28FF}\n"

# Write "foo bar" with 100 nul bytes between them to stdout
$ utfout "foo" "" -r 99 " bar"

```

More examples in the man page :)

---
[*] - http://ifdeflinux.blogspot.co.uk/2012/09/out-output-utility.html

**Comment by chavafg** [comment]
We have a minimal test for this [1], but we need to enhance it as with big output is where the problems are seen. 

[1] https://github.com/kata-containers/tests/blob/master/integration/docker/run_test.go#L282

**Comment by egernst** [comment]
@chavafg @grahamwhaley this is quite stale.  Should this be closed?

**Comment by grahamwhaley** [comment]
Yeah, sure, I'll close. I've not witnessed it for a while, or at least not kata being any worse than runc under k8s at least ;-)
