### ISSUE TITLE
checkcommits should allow fixes : 

### ISSUE THREAD

**Issue by ydjainopensource** [kata-containers/tests#68]
Currently checkcommits does not allow for whitespace after `Fixes` and before  `: `

It should allow this syntax too.
 
> Fixes : #< PR-number >

**Comment by grahamwhaley** [comment]
For reference, I suspect the defacto definition of what is accepted is probably what github will accept/spot:
https://help.github.com/articles/closing-issues-using-keywords/

But, to me, that page doesn't really talk about whitespace, or ':' use. Ho hum.
