### ISSUE TITLE
Run minimal CI setup on osx

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#688]
We have configured Travis for the proxy and shim repos to run on osx. Since those repos leverage *this* repos `.ci/*` scripts, we should perform a minimal CI run on osx simply to check changes such as #683. The reason being, changes like #683 have to be merged but cannot actually be tested until the next proxy or shim PR is raised!

I think we'd need to do something like for minimal osx support:

- Update `.travis.yml` to add:
  ```
  os:
    - linux
    - linux-ppc64le
    - osx
  ```
  Note the `linux-ppc64le` also added for similar reasons to osx.
- Create `.ci/setup_env_osx.sh`
- `.ci/setup.sh`:
  - Add a call to `.ci/setup_env_osx.sh`.
  - Change the code to exit immediately after querying the docker version from the versions database
    (https://github.com/kata-containers/tests/blob/master/.ci/setup.sh#L38).

/cc @chavafg, @grahamwhaley, @raravena80, @nitkon.

**Comment by grahamwhaley** [comment]
I think this sounds not too hard and will gain us some extra tests.
@jodh-intel can you give a very simple high level list of what extra things this will test ?

**Comment by jodh-intel** [comment]
It's just testing a very small subset of the CI scripts in this repo that the other (osx-enabled) repos use.

**Comment by chavafg** [comment]
Agree to add some checks. 
Not sure about creating `.ci/setup_env_osx.sh` if we are going to stop after getting the docker version. It would make sense only if we want to build the packages.
Also `manage_ctr_mgr.sh` does not have support for osx currently.
I can add the travis changes, but for the `.ci/setup_env_osx.sh`, we'll need someone that has `osx`, any volunteer?

**Comment by jodh-intel** [comment]
@chavafg - yeah, you're probably right about not needing `.ci/setup_env_osx.sh` ... unless @raravena80, or @marcov or someone else with a Mac wants to take a look...? :)

**Comment by raravena80** [comment]
I can take a look.  However, can we make it so that it doesn't block the overall tests?

**Comment by chavafg** [comment]
opened #692 to add the osx and ppc job.

**Comment by raravena80** [comment]
on the same note, do we have a list of packages that get setup with centos, ubuntu, etc?  Or just a best effort approach by looking at `setup_env_ubuntu.sh`, `setup_env_centos.sh`, etc

**Comment by chavafg** [comment]
Best way is taking a look at `setup_env_*.sh` files, I think we don't have a dependency list.

**Comment by chavafg** [comment]
this is already done. ppc and osx jobs are in place.
