### ISSUE TITLE
Run Posix compliance tests for 9p

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#693]
It would be good to have a list of what posix tests fail for 9p.
@chavafg @GabyCT @jcvenegas @devimc @grahamwhaley We talked about this in the past. Did we run these ?

**Comment by amshinde** [comment]
cc @egernst

**Comment by jcvenegas** [comment]
@devimc added some test long time ago, not sure what is the exact place we have them.

**Comment by amshinde** [comment]
@devimc @jcvenegas I would be good to have a list of Posix calls that fail for 9p documented.
We had a request recently to check which of these do not work with 9p:

fstat,stat
ftruncate
fallocate(FALLOC_FL_KEEP_SIZE)
ioctl(FS_IOC_FIEMAP)
fallocate(FALLOC_FL_KEEP_SIZE | FALLOC_FL_PUNCH_HOLE)
open(),close(),create(),fsync()
closedir(),readdir(),mkdir,opendir
syscall(SYS_renameat2)
preadv,pwritev

**Comment by devimc** [comment]
yes I added those tests long time ago ... :smile: 

https://github.com/clearcontainers/tests/tree/master/conformance/posixfs

**Comment by jcvenegas** [comment]
long time ago in a galaxy far far away (Clear Contaienrs)

**Comment by amshinde** [comment]
@jcvenegas haha :) 
Any volunteers for running tests and documenting them?

**Comment by grahamwhaley** [comment]
I think I was the last person to probably run any POSIX tests on Kata. I used them when doing the NFS/VSOCK evaluation, and also ran them on 9p at that point for comparison:
https://github.com/kata-containers/runtime/issues/279#issuecomment-394371299
Note, I updated the version of the pjdfstest I used as iirc there had been relevant updates since the version in the CC scripts (the CC scripts are pulling from sourceforge, I used the version from github which seemed more maintained). I posted the Dockerfile you can use over on that thread.

From my notes when doing the NFS/VSOCK work, I found on 9p pjdfstests that we were:
- Vanilla VM (virsh QEMU iirc) 9p had 6 failures
- Kata 9p had 88 failures

So, that also merits some investigation, if we have a different number of failures under Kata than 9p does under a more vanilla QEMU/9p setup.

I can re-run these tests, but I don't know if I'll get to that this week - a short week for me, and I have a couple of other things to wrap up first.

**Comment by amshinde** [comment]
@grahamwhaley So you were seeing more failures with Kata, I assume this was under qemu-lite?

**Comment by grahamwhaley** [comment]
@amshinde I don't think I have the details to hand, so cannot say for sure I'm afraid. It could have been - afraid we'll have to re-try it to find out for sure.

**Comment by GabyCT** [comment]
@amshinde , I ran the tests and here it is the summary
```
Test Summary Report
-------------------
./tests/chmod/12.t          (Wstat: 0 Tests: 14 Failed: 6)
  Failed tests:  3-4, 7-8, 11-12
./tests/link/00.t           (Wstat: 0 Tests: 202 Failed: 10)
  Failed tests:  135-136, 142-143, 149-150, 156-157, 163-164
./tests/mkdir/00.t          (Wstat: 0 Tests: 36 Failed: 2)
  Failed tests:  33-34
./tests/mkfifo/00.t         (Wstat: 0 Tests: 36 Failed: 2)
  Failed tests:  33-34
./tests/mknod/00.t          (Wstat: 0 Tests: 36 Failed: 2)
  Failed tests:  33-34
./tests/mknod/11.t          (Wstat: 0 Tests: 28 Failed: 4)
  Failed tests:  12-13, 25-26
./tests/open/00.t           (Wstat: 0 Tests: 47 Failed: 2)
  Failed tests:  33-34
Files=232, Tests=8789, 704 wallclock secs ( 1.69 usr  1.17 sys + 21.37 cusr 276.72 csys = 300.95 CPU)
Result: FAIL
```

This is the setup that I am using:
```
# `kata-env`

Output of "`/usr/local/bin/kata-runtime kata-env`":
```toml
[Meta]
  Version = "1.0.18"

[Runtime]
  Debug = true
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.3.0"
    Commit = "d00742f43f3fb1177e74d864e47a1bae697c2d73"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = true
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.3.0_agent_042c3ebd71c.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67-13"
  Parameters = "agent.log=debug"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.3.0-6ddb006ad3f709cab018af9dc0bf9e756c3ce2cd"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = true

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.3.0-5fbf1f0919ce0bb1f2b7e85692cdf3058023926f"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = true

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.15.0-1023-azure"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz"

[Netmon]
  Version = "kata-netmon version 1.3.0"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = true
  Enable = false
```

**Comment by GabyCT** [comment]
Closing this issue as this https://github.com/kata-containers/tests/commit/cd19c78cf84b784a35f42544651d69a8e11b4cd8 is already merged
