### ISSUE TITLE
Update soak test for netmon

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#727]
`integration/stability/soak_parallel_rm.sh` needs to take account of the new network monitor process when https://github.com/kata-containers/runtime/pull/534 lands.

**Comment by GabyCT** [comment]
@jodh-intel, if I understand correctly at `soak_parallel_rm.sh` we need to check that this process is not running `/usr/libexec/kata-containers/kata-netmon`. One question if a run a container like `docker run -d busybox sh -c "sleep 10"`, I can do not see this process, is there a way to test that `kata-netmon` is running, thanks.
