### ISSUE TITLE
write test to exercise netmon

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#728]
When https://github.com/kata-containers/runtime/pull/534 lands, we'll need a test in this repo to exercise it.

**Comment by GabyCT** [comment]
@sboeuf any suggestions of what kind of test we should write to exercise netmon? thanks

**Comment by sboeuf** [comment]
@GabyCT the idea behind `kata-netmon` is to be able to support use cases such as `docker connect` and `docker disconnect`, by detecting that a new interface is being added to the container namespace, and by hotplugging it to our existing VM.
Here is a nice example from @bergwolf https://github.com/kata-containers/tests/pull/743, that you can use as a reference.
