### ISSUE TITLE
tests: Add test to verify container entropy.

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#734]
After https://github.com/kata-containers/runtime/pull/676  is merged the containers entropy increase lets add a new tests to verify the entropy level.

**Comment by jcvenegas** [comment]
Adding more details about testing:
We can create a go program and run it in a container. The program will generate a random number.
This is the way we found the issue ( go uses /dev/random to get a random number so our it used to hang for ever due to the low entropy the kata container had).

Another way to do it 
1. On the host the the entropy level, `cat /proc/sys/kernel/random/entropy_avail`
2. Create a container and get the same inside of the container. 
3. Compare the level between the host and guest this should be similar.

**Comment by GabyCT** [comment]
After discussing with @jcvenegas , the test should always look that the entropy level inside the container is more than 1000
