### ISSUE TITLE
metrics test failed on missing perf command

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#763]
Saw at http://jenkins.katacontainers.io/job/kata-metrics-agent-ubuntu-16-04-PR/43/console

```
00:32:45 ERROR: command perf not available
00:32:45 ~/workspace/workspace/kata-metrics-agent-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
00:32:45 ~/workspace/workspace/kata-metrics-agent-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/cmd/checkmetrics ~/workspace/workspace/kata-metrics-agent-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
00:32:45 go build -ldflags "-X main.sysBaseFile=" -o checkmetrics
00:32:50 install -D checkmetrics /usr/bin/checkmetrics
00:32:50 ~/workspace/workspace/kata-metrics-agent-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg="Failed Maxval (6.982500 < 7.522450) for [boot-times]"
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg="Check for [boot-times] failed [Failed]"
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg=" with [[*F* boot-times 95.0% 113.1% 105.0% 10.0% 108.7% 116.0% 6.8% 1.8% 20]]"
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg="Failed Maxval (48825.000000 < 51082.070000) for [memory-footprint-ksm]"
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg="Check for [memory-footprint-ksm] failed [Failed]"
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg=" with [[*F* memory-footprint-ksm 95.0% 109.9% 105.0% 10.0% 109.9% 109.9% 0.0% 0.0% 1]]"
00:32:50 time="2018-09-21T00:32:50Z" level=warning msg="Overall we failed"
```

**Comment by grahamwhaley** [comment]
Ack. It has an issue over at https://github.com/kata-containers/ci/issues/43, as it is actually more of a CI VM config error than a metrics/tests error.
It also does not stop the metrics actually completing, as it only stops one test running (network perf), that we are not currently using as a pass/fail trigger.
But, thanks for raising. Let's see if I can get to update this next week (it is as simple as locating the correct ubuntu package or install method, adding it into https://github.com/kata-containers/ci/tree/master/VMs/metrics/ubuntu16.04 and rebuilding the VM base image on the metrics build slave...)

**Comment by GabyCT** [comment]
This is still present http://jenkins.katacontainers.io/job/kata-metrics-tests-ubuntu-16-04-PR/77/.

**Comment by grahamwhaley** [comment]
It is - it has 'come back' when I moved back to bare metal deployment for the slaves.
I opened a CI issue for this to note we need to add perf into the ansible scripts over at https://github.com/kata-containers/ci/issues/81

**Comment by GabyCT** [comment]
@grahamwhaley , I just open this PR https://github.com/kata-containers/ci/pull/83, please take a look (I am new using Ansible :) )

**Comment by GabyCT** [comment]
Closing this issue as `perf` command was added
