### ISSUE TITLE
kata-manager should be able to install Kata on non-development systems

### ISSUE THREAD

**Issue by marcov** [kata-containers/tests#828]
kata-manager is introduced in the [install documentation](https://github.com/kata-containers/documentation/blob/master/install/README.md) as an easy way to install kata for new users.
 
At the moment, there are some prerequisites needed to get kata-manager working:
- have git and the golang installed
- have a copy of `kata-doc-to-script.sh` available in `${GOPATH}/src/${test_repo}/.ci/`

It's unlikely that new users have their system setup in this way, so we need to update kata-manager to allow it to run on a standard/non-dev environment.

**Comment by jodh-intel** [comment]
Related:

- https://github.com/kata-containers/documentation/pull/279
- https://github.com/kata-containers/documentation/issues/278

**Comment by jodh-intel** [comment]
Not sure why github didn't auto-close this as it's fixed by #829.
