### ISSUE TITLE
Add docker test for ipvlan

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#861]
Once https://github.com/kata-containers/runtime/pull/852 lands, we need to test ipvlan plugin for docker.
To test with ipvlan plugin in l2 mode:
```
$ docker network  create  -d ipvlan \
   --subnet=10.54.10.0/24 \
     -o ipvlan_mode=l2 \
     ipvlan2

$ docker run --rm -itd --runtime=kata-runtime --network ipvlan2  --ip=10.54.10.2 --name ipvlan2_1 --rm --runtime=runc debian

$ docker run --rm -itd --runtime=kata-runtime --network ipvlan2  --ip=10.54.10.3 --name ipvlan2_2 --rm --runtime=runc debian
```
Make sure container `ipvlan2_1` can ping `ipvlan2_2`

Once the agent PR lands which fixes ipvlan in l3 mode (https://github.com/kata-containers/agent/pull/404), , we need to test with ipvlan l3 mode:
```
$ docker network  create  -d ipvlan \
   --subnet=10.54.20.0/24 \
     -o ipvlan_mode=l3 \
     ipvlan3

$ docker run --rm -itd --runtime=kata-runtime --network ipvlan3  --ip=10.54.20.2 --name ipvlan3_1 --rm --runtime=runc debian

$ docker run --rm -itd --runtime=kata-runtime --network ipvlan3  --ip=10.54.20.3 --name ipvlan3_2 --rm --runtime=runc debian
```

As before, we need to check that the containers can ping each other.

**Comment by GabyCT** [comment]
@amshinde , I am trying to create the network of ipvlan (like you did in the example), however, I am getting the following error
`Error response from daemon: plugin "ipvlan" not found`
The version of the `kata-agent` that I am using is the following
`kata-agent version 1.3.0-0f411fd1887d833b9af04624bb66e2757ae25ea3`

Do I need to setup something else? thanks

**Comment by amshinde** [comment]
@GabyCT Forgot to add this, ipvlan is still marked as experimental for docker. There is a PR open to not have this as a experimental feature as it is mature enough, but has not been merged yet.

To use the ipvlan driver, you need to update docker as:
```
vi /etc/docker/daemon.json
{
   "experimental": true
}
```

After the config file is update, a you need to do `systemctl daemon-reload` followed by `systemctl restart docker`.
You should then be able to use the ipvlan driver.
