### ISSUE TITLE
ci: scripts: install_kata: allow a version of kata to be specified for install

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#864]
Sometimes it would be very useful to install all the components of a specific version of kata.
The CI `.ci/install_*` scripts, invoked from `.ci/install_kata.sh` has most of the functionality, but has no way to specify and pass on a version to all the components.

Add such a feature.

**Comment by jodh-intel** [comment]
Related to this, we should do the same for [`kata-manager`](https://github.com/kata-containers/tests/tree/master/cmd/kata-manager).

If we [fork the documentation](https://github.com/kata-containers/documentation/issues/246) when we create [stable branches](https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md), it would be relatively easy to get `kata-manager` to point at the appropriate repo branch and execute the version-specific instructions with a new `--version $version` option for example.
