### ISSUE TITLE
metrics: scaling test: elasticsearch faling to launch

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#866]
A little while ago (a week or two), elasticsearch stopped running in the scaling footprint test from the [report generator data grab](https://github.com/kata-containers/tests/blob/master/metrics/report/grabdata.sh#L118).
It is likely the versioning of elasticsearch changed on the hub, and/or maybe 'latest' is no longer available.
Needs a bit of debug, and fix by pinning a version or finding an alternative 'large footprint' test.

**Comment by jodh-intel** [comment]
Might need to add it to `versions.yaml` like we did for `xurls`:  #855.
