### ISSUE TITLE
configuring docker to use runc in jenkins_job_build.sh will fail in case docker is not already installed.

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#878]
In `jenkins_job_build.sh`, we assume that docker is already installed when calling `manage_ctr_mgr.sh" docker configure -r runc -f` on :
https://github.com/kata-containers/tests/blob/master/.ci/jenkins_job_build.sh#L77 

The assumption is true for the VMs that we launch on vexxhost, but it is not the same for baremetal nodes. 

On the `setup.sh` we install docker in case it is not installed, so maybe we should configure docker to use `runc` after installing it in `setup.sh` instead of doing it in the `jenkins_job_build.sh` script.

**Comment by grahamwhaley** [comment]
Let me have a try at that and see if it flies - I think the general idea and reflow is sound.
