### ISSUE TITLE
Memory Hotplug is not available on arm64 

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#879]
# Description of problem
Looking into the implementation of new feature: memory hotplug, [runtime/#400](https://github.com/kata-containers/runtime/pull/786), it uses the (`qemu) device_add pc-dimm,id=dimm1,memdev=mem1` to limit memory on runtime. However, this feature is not availble for arm64 for now. 

# Actual result
`Nov 01 10:53:19 entos-thunderx2-desktop kata-runtime[184060]: time="2018-11-01T10:53:19.183208764+08:00" level=info msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"'pc-dimm' is not a valid device model name\"}}" arch=arm64 command=create container=aee45652f4df987389e82774b94a2da9fd702356e37559761a7dedc7bb60ff79 name=kata-runtime pid=184060 source=virtcontainers subsystem=qmp`

This will lead to a large portion of [mem_test.go](https://github.com/kata-containers/tests/blob/master/integration/docker/mem_test.go) failed. I will configure the filter configuration to skip these tests asap.
@weichen81

**Comment by Pennyzct** [comment]
That also means that `-m` option for memory limit in docker commands is not workable on arm64 when runtime is kata-runtime.

**Comment by jodh-intel** [comment]
> That also means that `-m` option for memory limit in docker commands is not workable on arm64 when runtime is kata-runtime.

It would probably be worth capturing that in:

- https://github.com/kata-containers/documentation/blob/master/Limitations.md
