### ISSUE TITLE
CI: Ignore vendor/ directories when running go test

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#88]
`go list` in golang 1.9 is clever and prunes vendor packages by default:

```
$ (GOROOT=/usr/local/go/go1.9/go PATH=$GOROOT/bin:$PATH go list ./...)
github.com/kata-containers/proxy
```

However, we're using golang 1.8 with Travis and the behaviour is different:

```
$ (GOROOT=/usr/local/go/go1.8.1/go PATH=$GOROOT/bin:$PATH go list ./...)
github.com/kata-containers/proxy
github.com/kata-containers/proxy/vendor/github.com/davecgh/go-spew/spew
github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux
github.com/kata-containers/proxy/vendor/github.com/pmezard/go-difflib/difflib
github.com/kata-containers/proxy/vendor/github.com/sirupsen/logrus
github.com/kata-containers/proxy/vendor/github.com/sirupsen/logrus/hooks/syslog
github.com/kata-containers/proxy/vendor/github.com/stretchr/testify/assert
github.com/kata-containers/proxy/vendor/golang.org/x/crypto/ssh
github.com/kata-containers/proxy/vendor/golang.org/x/crypto/ssh/terminal
github.com/kata-containers/proxy/vendor/golang.org/x/sys/unix
github.com/kata-containers/proxy/vendor/golang.org/x/sys/windows
```

This behaviour is causing `.ci/go-test.sh` to try to run tests on vendor packages, which we don't want.

We could update all the `.travis.yml` files to only use versions of go >= 1.9 but we specify go 1.8 as our minimum version. Hence, simply filter vendor packages out of `go list` before running `go test`.

**Comment by grahamwhaley** [comment]
Let's co-ordinate and make a decision when to move and what to. @jcvenegas was asking before what version of golang we used on the metrics-ci, possibly for the same or a related reason. Currently it is v1.8.3 - am happy to move to v1.9.x if that is where we need to be and set as our baseline minimum version.

**Comment by jodh-intel** [comment]
Hi @grahamwhaley - I've raised https://github.com/kata-containers/kata-containers/issues/15 to discuss the general issue here.
