### ISSUE TITLE
ci: install_kata_image/update_agent does not change name of .img file

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#881]
Not a big problem generally, as it happens in one-shot CI slaves, but, if the [install_kata_image.sh](https://github.com/kata-containers/tests/blob/master/.ci/install_kata_image.sh) finds it needs to update the agent image, it does so by injecting a new agent into the 'kata-containers.img' - but, if that .img file is a link to a fully qualified osbuilder image (such as in my example `/kata-containers-2018-10-26-10:33:49.086322915+0100-osbuilder-b9b9410-agent-e395ac6`, then the agent in that file gets updated, but the name of the file does not.
Normally not an issue, but, this name appears in the output of `kata-env`, and thus in things such as possibly CI logs and the metrics reportgen report - which is very misleading, as it heavily hints that the agent in use is one version, whereas in fact it has been updated and is a different version (which threw me, when doing some build version metrics comparisons).

It's not clear to me there is an easy fix here. My local solution is likely to force a full image/agent build/install when I request a specific version of kata to be built.

**Comment by jodh-intel** [comment]
I think if the script detects that `kata-containers.img` is a link, it should copy it to a unique name, inject the new agent and then recreate the `kata-containers.img` link, all with copious amounts of log output to show what is going on.

**Comment by chavafg** [comment]
`install_kata_image.sh` no longer injects the new agent inside an already created image. It now downloads it from our jenkins cache or builds it from sources. Closing this one.
