### ISSUE TITLE
Add jenkins_job_build.sh script

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#90]
`jenkins_job_build.sh` script should be called in the Jenkins Jobs for all repos. This will minimize duplicated code in the jenkins job configuration

**Comment by grahamwhaley** [comment]
Is that not the case today @chavafg - I thought it was, so am curious ;-)

**Comment by chavafg** [comment]
@grahamwhaley It is the case for CC, but not for Kata-Containers CI right now.
