### ISSUE TITLE
Docker cp test case always failed even running by manually related with device busy issue

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/tests#915]
Here is the test log and kata environment log:

[kata-env.txt](https://github.com/kata-containers/tests/files/2599639/kata-env.txt)
[docker_cp_failed_log.txt](https://github.com/kata-containers/tests/files/2599642/docker_cp_failed_log.txt)

@chavafg 
docker cp will failed by running the test script.
And i double check it by running it step by step in the test script by manually and it still failed.
could you please help to check if such issue will find in your test or it is a real issue/
Thanks
Zhiming

**Comment by chavafg** [comment]
Hi @zhiminghufighting, 

I wasn't able to reproduce the failure, can you please run `sudo -E PATH=$PATH /usr/local/bin/kata-collect-data.sh` and paste the output here?

It would also be helpful if you can check for docker errors running `sudo journalctl -u docker`.

**Comment by devimc** [comment]
`docker cp` tests are working properly, closing..
