### ISSUE TITLE
Document how to run the tests

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#919]
There is no documentation on how to run our tests.

**Comment by grahamwhaley** [comment]
We have a couple of 'fragments', but nothing comprehensive or really aimed at human use cases, so I'm looking forward to this ;-)
See these for ref:
How to set up Jenkins to run the CI test scripts:
https://github.com/kata-containers/ci/blob/master/Jenkins_setup.md#job-build-script

How to run the basic tests by hand before submitting a PR:
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#before-submitting-a-pr
