### ISSUE TITLE
metrics: mem-in-container: may need to nap before measure

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#931]
As found over on https://github.com/kata-containers/runtime/issues/933, now we hotplug memory into the container, that takes a short time to appear to the system.
Therefore, in the 'memory in container' test, we may want to add a short nap/delay before we take the measure. Cmd is [here](https://github.com/kata-containers/tests/blob/master/metrics/density/memory_usage_inside_container.sh#L21)

**Comment by clarecch** [comment]
Hi @grahamwhaley , in fact, it takes just a little time for kernel to hotplug a dimm physically. While it takes more time for kernel to manage the hotplug memory logically, which includes creating page tables for memory and put all free pages into buddy system, when you echo `online` to new memory block in sysfs.

Reference https://elixir.bootlin.com/linux/v4.10/source/Documentation/memory-hotplug.txt#L56
