### ISSUE TITLE
Create a test that asserts OCI calls

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#941]
Docker 18.09 has broken the expected runtime behaviour (see https://github.com/kata-containers/runtime/issues/926).

To make it simpler and safer for us to update [the version of Docker we test with](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L154), we could create a new test that does the following:

- Clear the journald journal logs.
- Enable full debug.
- Create a container.
- Extract the debug logs for the runtime from the journal:
  ```
  $ sudo journalctl -q -o cat -a -t kata-runtime > ./runtime.log
  ```
- Extract lines matching `arguments=`:
  ```
  $ grep -o "arguments=[^ ]*" runtime.log --color|cut -d= -f2-|tr -d '"'|tr -d "\\\\"
  create
  state
  start
  state
  kill
  state
  kill
  delete
  ```

As shown, that will list all the runtime CLI calls as defined by the [OCI runtime lifecycle](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md).

We can then validate that list of calls against what we expect. For reference see the following, which shows the incorrect calls from containerd:

- https://github.com/moby/moby/issues/38233#issuecomment-440687251
- https://github.com/moby/moby/issues/38233#issuecomment-440725686

**Comment by GabyCT** [comment]
@jodh-intel , I have a question regarding this test. Should we run this test in a different jenkins job? and should it run in every PR? My concern is because we will erase at the beginning the logs. thanks

**Comment by GabyCT** [comment]
@jodh-intel another question, after running the container (with the logs enabled), I see that for arguments, I have a list of 
```
state
delete
kill
state
create
...
```
Do I need to compare those arguments with the list of https://github.com/opencontainers/runtime-spec/blob/master/runtime.md (create, start, kill, delete)? What I mean is that I need to check that all those four arguments (create, start, kill, delete) exist in the arguments from the log (while a container runs)? thanks
